! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

  MODULE INCIDENTS
    USE GLOBAL_DATA
    IMPLICIT NONE
! --- Incident codes
    INTEGER, PARAMETER :: INC_NOT = 0
    INTEGER, PARAMETER :: INC_SLOW = 1
    INTEGER, PARAMETER :: INC_BLOCK = 2

    INTEGER              :: NUMBER_OF_INCIDENTS = 0
    INTEGER, ALLOCATABLE :: INCIDENT_CODE(:,:)
    INTEGER, ALLOCATABLE :: INCIDENT_LINK(:)
    INTEGER, ALLOCATABLE :: INCIDENT_BEGIN_POINT(:)
    INTEGER, ALLOCATABLE :: INCIDENT_BEGIN_TIME(:)
    INTEGER, ALLOCATABLE :: INCIDENT_END_POINT(:)
    INTEGER, ALLOCATABLE :: INCIDENT_END_TIME(:)
    INTEGER, ALLOCATABLE :: INCIDENT_RBNF(:)
    INTEGER, ALLOCATABLE :: INCIDENT_WARN_POINT(:)

    CONTAINS

! ==================================================================================================
    SUBROUTINE ALLOCATE_INCIDENT_ARRAYS
    IF(ALLOCATED(INCIDENT_LINK)) RETURN
    ALLOCATE(INCIDENT_LINK(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_CODE(NUMBER_OF_INCIDENTS, N_FREEWAY_LANES))
    ALLOCATE(INCIDENT_BEGIN_POINT(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_END_POINT(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_BEGIN_TIME(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_END_TIME(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_RBNF(NUMBER_OF_INCIDENTS))
    ALLOCATE(INCIDENT_WARN_POINT(NUMBER_OF_INCIDENTS))
    INCIDENT_CODE = 0
    INCIDENT_LINK = 0
    INCIDENT_BEGIN_POINT = 0
    INCIDENT_BEGIN_TIME = 0
    INCIDENT_END_POINT = 0
    INCIDENT_END_TIME = 0
    INCIDENT_RBNF = 0
    INCIDENT_WARN_POINT = 0
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE DEALLOCATE_INCIDENT_ARRAYS
    IF(ALLOCATED(INCIDENT_LINK))        DEALLOCATE(INCIDENT_LINK)
    IF(ALLOCATED(INCIDENT_CODE))        DEALLOCATE(INCIDENT_CODE)
    IF(ALLOCATED(INCIDENT_BEGIN_POINT)) DEALLOCATE(INCIDENT_BEGIN_POINT)
    IF(ALLOCATED(INCIDENT_END_POINT))   DEALLOCATE(INCIDENT_END_POINT)
    IF(ALLOCATED(INCIDENT_BEGIN_TIME))  DEALLOCATE(INCIDENT_BEGIN_TIME)
    IF(ALLOCATED(INCIDENT_END_TIME))    DEALLOCATE(INCIDENT_END_TIME)
    IF(ALLOCATED(INCIDENT_RBNF))        DEALLOCATE(INCIDENT_RBNF)
    IF(ALLOCATED(INCIDENT_WARN_POINT))  DEALLOCATE(INCIDENT_WARN_POINT)
    END SUBROUTINE
      
! ==================================================================================================
    SUBROUTINE SAVE_INCIDENTS(FILE1)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1
    INTEGER :: I
! ----------------------------------------------------------------------

! --- Save static data.

    WRITE(FILE1) NUMBER_OF_INCIDENTS
    DO I = 1, NUMBER_OF_INCIDENTS
      WRITE(FILE1) INCIDENT_LINK(I)
      WRITE(FILE1) INCIDENT_CODE(I, 1:N_FREEWAY_LANES)
      WRITE(FILE1) INCIDENT_BEGIN_POINT(I)
      WRITE(FILE1) INCIDENT_END_POINT(I)
      WRITE(FILE1) INCIDENT_BEGIN_TIME(I)
      WRITE(FILE1) INCIDENT_END_TIME(I)
      WRITE(FILE1) INCIDENT_BEGIN_TIME(I)
      WRITE(FILE1) INCIDENT_WARN_POINT(I)
    ENDDO
    RETURN
    END SUBROUTINE
            
! ==================================================================================================
    SUBROUTINE RESTORE_INCIDENTS(FILE1)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1
    INTEGER :: I
! ----------------------------------------------------------------------

! --- Restore data.

    READ(FILE1) NUMBER_OF_INCIDENTS
    IF(NUMBER_OF_INCIDENTS .NE. 0) THEN
      IF(.NOT. ALLOCATED(INCIDENT_LINK)) THEN
        ALLOCATE(INCIDENT_LINK(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_CODE(NUMBER_OF_INCIDENTS, N_FREEWAY_LANES))
        ALLOCATE(INCIDENT_BEGIN_POINT(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_END_POINT(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_BEGIN_TIME(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_END_TIME(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_RBNF(NUMBER_OF_INCIDENTS))
        ALLOCATE(INCIDENT_WARN_POINT(NUMBER_OF_INCIDENTS))
      ENDIF
      DO I = 1, NUMBER_OF_INCIDENTS
        READ(FILE1) INCIDENT_LINK(I)
        READ(FILE1) INCIDENT_CODE(I, 1:N_FREEWAY_LANES)
        READ(FILE1) INCIDENT_BEGIN_POINT(I)
        READ(FILE1) INCIDENT_END_POINT(I)
        READ(FILE1) INCIDENT_BEGIN_TIME(I)
        READ(FILE1) INCIDENT_END_TIME(I)
        READ(FILE1) INCIDENT_BEGIN_TIME(I)
        READ(FILE1) INCIDENT_WARN_POINT(I)
      ENDDO
    ENDIF
    RETURN
    END SUBROUTINE

  END MODULE

     
