! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

  MODULE TIME_PERIOD_MOES
 
  REAL, ALLOCATABLE :: SIGNALPHASES_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: SIGNALPHASES_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: SIGNALPHASES_MOEUNITS(:)
  INTEGER N_SIGNALPHASES_MOES
 
  REAL, ALLOCATABLE :: FREEWAY_DETECTOR_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: FREEWAY_DETECTOR_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: FREEWAY_DETECTOR_MOEUNITS(:)
  INTEGER N_FREEWAY_DETECTOR_MOES
 
  REAL, ALLOCATABLE :: STREET_DETECTOR_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: STREET_DETECTOR_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: STREET_DETECTOR_MOEUNITS(:)
  INTEGER N_STREET_DETECTOR_MOES
 
  REAL, ALLOCATABLE :: DATASTATION_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: DATASTATION_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: DATASTATION_MOEUNITS(:)
  INTEGER N_DATASTATION_MOES
 
  REAL, ALLOCATABLE :: ENTRYLINK_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: ENTRYLINK_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: ENTRYLINK_MOEUNITS(:)
  INTEGER N_ENTRYLINK_MOES
 
  REAL, ALLOCATABLE :: LINK_FREEWAY_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: LINK_FREEWAY_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: LINK_FREEWAY_MOEUNITS(:)
  INTEGER N_LINK_FREEWAY_MOES
 
  REAL, ALLOCATABLE :: LINK_STREET_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: LINK_STREET_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: LINK_STREET_MOEUNITS(:)
  INTEGER N_LINK_STREET_MOES
 
  REAL, ALLOCATABLE :: LANE_FREEWAY_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: LANE_FREEWAY_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: LANE_FREEWAY_MOEUNITS(:)
  INTEGER N_LANE_FREEWAY_MOES
 
  REAL, ALLOCATABLE :: LANE_STREET_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: LANE_STREET_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: LANE_STREET_MOEUNITS(:)
  INTEGER N_LANE_STREET_MOES
 
  REAL, ALLOCATABLE :: NETWORK_FREEWAY_MOE(:,:)
  CHARACTER*80, ALLOCATABLE :: NETWORK_FREEWAY_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: NETWORK_FREEWAY_MOEUNITS(:)
  INTEGER N_NETWORK_FREEWAY_MOES
 
  REAL, ALLOCATABLE :: VTYPE_LINK_FREEWAY_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: VTYPE_LINK_FREEWAY_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: VTYPE_LINK_FREEWAY_MOEUNITS(:)
  INTEGER N_VTYPE_LINK_FREEWAY_MOES
 
  REAL, ALLOCATABLE :: VTYPE_LINK_STREET_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: VTYPE_LINK_STREET_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: VTYPE_LINK_STREET_MOEUNITS(:)
  INTEGER N_VTYPE_LINK_STREET_MOES
 
  REAL, ALLOCATABLE :: BUSROUTE_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: BUSROUTE_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: BUSROUTE_MOEUNITS(:)
  INTEGER N_BUSROUTE_MOES
 
  REAL, ALLOCATABLE :: BUSSTATION_MOE(:,:,:)
  CHARACTER*80, ALLOCATABLE :: BUSSTATION_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: BUSSTATION_MOEUNITS(:)
  INTEGER N_BUSSTATION_MOES
 
  REAL, ALLOCATABLE :: NETWORK_STREET_MOE(:,:)
  CHARACTER*80, ALLOCATABLE :: NETWORK_STREET_MOELABEL(:)
  CHARACTER*80, ALLOCATABLE :: NETWORK_STREET_MOEUNITS(:)
  INTEGER N_NETWORK_STREET_MOES
  
  CONTAINS
  
  SUBROUTINE DEALLOCATE_TIME_PERIOD_MOES_ARRAYS
  IF(ALLOCATED(FREEWAY_DETECTOR_MOE)) DEALLOCATE(FREEWAY_DETECTOR_MOE)
  IF(ALLOCATED(FREEWAY_DETECTOR_MOELABEL)) DEALLOCATE(FREEWAY_DETECTOR_MOELABEL)
  IF(ALLOCATED(FREEWAY_DETECTOR_MOEUNITS)) DEALLOCATE(FREEWAY_DETECTOR_MOEUNITS)
  IF(ALLOCATED(STREET_DETECTOR_MOE)) DEALLOCATE(STREET_DETECTOR_MOE)
  IF(ALLOCATED(STREET_DETECTOR_MOELABEL)) DEALLOCATE(STREET_DETECTOR_MOELABEL)
  IF(ALLOCATED(STREET_DETECTOR_MOEUNITS)) DEALLOCATE(STREET_DETECTOR_MOEUNITS)
  IF(ALLOCATED(DATASTATION_MOE)) DEALLOCATE(DATASTATION_MOE)
  IF(ALLOCATED(DATASTATION_MOELABEL)) DEALLOCATE(DATASTATION_MOELABEL)
  IF(ALLOCATED(DATASTATION_MOEUNITS)) DEALLOCATE(DATASTATION_MOEUNITS)
  IF(ALLOCATED(ENTRYLINK_MOE)) DEALLOCATE(ENTRYLINK_MOE)
  IF(ALLOCATED(ENTRYLINK_MOELABEL)) DEALLOCATE(ENTRYLINK_MOELABEL)
  IF(ALLOCATED(ENTRYLINK_MOEUNITS)) DEALLOCATE(ENTRYLINK_MOEUNITS)
  IF(ALLOCATED(LINK_FREEWAY_MOE)) DEALLOCATE(LINK_FREEWAY_MOE)
  IF(ALLOCATED(LINK_FREEWAY_MOELABEL)) DEALLOCATE(LINK_FREEWAY_MOELABEL)
  IF(ALLOCATED(LINK_FREEWAY_MOEUNITS)) DEALLOCATE(LINK_FREEWAY_MOEUNITS)
  IF(ALLOCATED(LINK_STREET_MOE)) DEALLOCATE(LINK_STREET_MOE)
  IF(ALLOCATED(LINK_STREET_MOELABEL)) DEALLOCATE(LINK_STREET_MOELABEL)
  IF(ALLOCATED(LINK_STREET_MOEUNITS)) DEALLOCATE(LINK_STREET_MOEUNITS)
  IF(ALLOCATED(LANE_FREEWAY_MOE)) DEALLOCATE(LANE_FREEWAY_MOE)
  IF(ALLOCATED(LANE_FREEWAY_MOELABEL)) DEALLOCATE(LANE_FREEWAY_MOELABEL)
  IF(ALLOCATED(LANE_FREEWAY_MOEUNITS)) DEALLOCATE(LANE_FREEWAY_MOEUNITS)
  IF(ALLOCATED(LANE_STREET_MOE)) DEALLOCATE(LANE_STREET_MOE)
  IF(ALLOCATED(LANE_STREET_MOELABEL)) DEALLOCATE(LANE_STREET_MOELABEL)
  IF(ALLOCATED(LANE_STREET_MOEUNITS)) DEALLOCATE(LANE_STREET_MOEUNITS)
  IF(ALLOCATED(NETWORK_FREEWAY_MOE)) DEALLOCATE(NETWORK_FREEWAY_MOE)
  IF(ALLOCATED(NETWORK_FREEWAY_MOELABEL)) DEALLOCATE(NETWORK_FREEWAY_MOELABEL)
  IF(ALLOCATED(NETWORK_FREEWAY_MOEUNITS)) DEALLOCATE(NETWORK_FREEWAY_MOEUNITS)
  IF(ALLOCATED(VTYPE_LINK_FREEWAY_MOE)) DEALLOCATE(VTYPE_LINK_FREEWAY_MOE)
  IF(ALLOCATED(VTYPE_LINK_FREEWAY_MOELABEL)) DEALLOCATE(VTYPE_LINK_FREEWAY_MOELABEL)
  IF(ALLOCATED(VTYPE_LINK_FREEWAY_MOEUNITS)) DEALLOCATE(VTYPE_LINK_FREEWAY_MOEUNITS)
  IF(ALLOCATED(VTYPE_LINK_STREET_MOE)) DEALLOCATE(VTYPE_LINK_STREET_MOE)
  IF(ALLOCATED(VTYPE_LINK_STREET_MOELABEL)) DEALLOCATE(VTYPE_LINK_STREET_MOELABEL)
  IF(ALLOCATED(VTYPE_LINK_STREET_MOEUNITS)) DEALLOCATE(VTYPE_LINK_STREET_MOEUNITS)
  IF(ALLOCATED(BUSROUTE_MOE)) DEALLOCATE(BUSROUTE_MOE)
  IF(ALLOCATED(BUSROUTE_MOELABEL)) DEALLOCATE(BUSROUTE_MOELABEL)
  IF(ALLOCATED(BUSROUTE_MOEUNITS)) DEALLOCATE(BUSROUTE_MOEUNITS)
  IF(ALLOCATED(BUSSTATION_MOE)) DEALLOCATE(BUSSTATION_MOE)
  IF(ALLOCATED(BUSSTATION_MOELABEL)) DEALLOCATE(BUSSTATION_MOELABEL)
  IF(ALLOCATED(BUSSTATION_MOEUNITS)) DEALLOCATE(BUSSTATION_MOEUNITS)
  IF(ALLOCATED(NETWORK_STREET_MOE)) DEALLOCATE(NETWORK_STREET_MOE)
  IF(ALLOCATED(NETWORK_STREET_MOELABEL)) DEALLOCATE(NETWORK_STREET_MOELABEL)
  IF(ALLOCATED(NETWORK_STREET_MOEUNITS)) DEALLOCATE(NETWORK_STREET_MOEUNITS)
  END SUBROUTINE
 
  END MODULE

! ==========================================================================================================
  SUBROUTINE STORE_ALL_MOES
  USE TIME_PERIOD_MOES
  USE TEXT
  USE SIMPARAMS
  USE FREEWAY_LINKS
  USE STREET_LINKS
  IMPLICIT NONE
  INCLUDE 'MOEFUNCTIONS.FI'
  INTEGER :: GETCLASSMOES
  CHARACTER*80 CMOE, UNIT
  CHARACTER*80 CMOES(200), UNITS(200)
  INTEGER :: NMOES, STATUS, TEMP, ISIZE, IARRAY(4), K, ITP, NOBJ
  INTEGER :: IOBJ, NMOE, ILEN, IRET
  REAL :: RMOE
! ----------------------------------------------------------------------
 
! --- Count the number of time periods used.

  DO K = 1, 19
    IF(TPSECONDS(K) .GT. 0) ITP = K
  ENDDO
 
! --- Get the number of characters in the moelist.
 
  TEMP = GETMOELISTLENGTH(ISIZE)

! --- Define the entrylink MOEs.

  NOBJ = 0
  TEMP = GETNUMMOEOBJECTS('ENTRYLINK', IARRAY, NOBJ)
  TEMP = GETCLASSMOES(ISIZE, 'ENTRYLINK', NMOES, CMOES, UNITS)
  N_ENTRYLINK_MOES = NMOES
  DO IOBJ = 1, NOBJ
    TEMP = GETNUMMOEOBJECTS('ENTRYLINK', IARRAY, IOBJ)

! --- Allocate arrays for entrylink MOEs.
              
    IF(.NOT. ALLOCATED(ENTRYLINK_MOE)) THEN
      ALLOCATE(ENTRYLINK_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(ENTRYLINK_MOELABEL(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(ENTRYLINK_MOEUNITS(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
    ENDIF
    DO NMOE = 1, NMOES
      ILEN = LEN_TRIM(CMOES(NMOE))
      CMOE = CMOES(NMOE)(2:ILEN-1)
      IRET = GETENTRYLINKMOEDATA(CMOE, IARRAY, 2, RMOE)
      IF(TIME_PERIOD .EQ. 1) ENTRYLINK_MOELABEL(NMOE) = CMOE
      ENTRYLINK_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
      ILEN = LEN_TRIM(UNITS(NMOE))
      UNIT = UNITS(NMOE)(2:ILEN-1)
      IF(TIME_PERIOD .EQ. 1) ENTRYLINK_MOEUNITS(NMOE) = UNIT
    ENDDO
  ENDDO
  
  IF(N_FREEWAY_LINKS .GT. 0) THEN
    
  ! --- Define the detector MOEs.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('DATASTATION', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'DATASTATION', NMOES, CMOES, UNITS)
    N_DATASTATION_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('DATASTATION', IARRAY, IOBJ)
 
  ! --- Allocate arrays for datastation MOEs.
               
      IF(.NOT. ALLOCATED(DATASTATION_MOE)) THEN
        ALLOCATE(DATASTATION_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(DATASTATION_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(DATASTATION_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETDATASTATIONMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) DATASTATION_MOELABEL(NMOE) = CMOE
        DATASTATION_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) DATASTATION_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
 
  ! --- Define the freeway detector MOEs.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('FREEWAY_DETECTOR', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'FREEWAY_DETECTOR', NMOES, CMOES, UNITS)
    N_FREEWAY_DETECTOR_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('FREEWAY_DETECTOR', IARRAY, IOBJ)
 
  ! --- Allocate arrays for freeway detector MOEs.
               
      IF(.NOT. ALLOCATED(FREEWAY_DETECTOR_MOE)) THEN
        ALLOCATE(FREEWAY_DETECTOR_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(FREEWAY_DETECTOR_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(FREEWAY_DETECTOR_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETFREEWAYDETECTORMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) FREEWAY_DETECTOR_MOELABEL(NMOE) = CMOE
        FREEWAY_DETECTOR_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) FREEWAY_DETECTOR_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the freeway link MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LINK_FREEWAY', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'LINK_FREEWAY', NMOES, CMOES, UNITS)
    N_LINK_FREEWAY_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('LINK_FREEWAY', IARRAY, IOBJ)

  ! --- Allocate arrays for freeway link MOEs.
              
      IF(.NOT. ALLOCATED(LINK_FREEWAY_MOE)) THEN
        ALLOCATE(LINK_FREEWAY_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LINK_FREEWAY_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LINK_FREEWAY_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETFREEWAYLINKMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) LINK_FREEWAY_MOELABEL(NMOE) = CMOE
        LINK_FREEWAY_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) LINK_FREEWAY_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the freeway lane MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LANE_FREEWAY', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'LANE_FREEWAY', NMOES, CMOES, UNITS)
    N_LANE_FREEWAY_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('LANE_FREEWAY', IARRAY, IOBJ)

  ! --- Allocate arrays for freeway lane MOEs.
              
      IF(.NOT. ALLOCATED(LANE_FREEWAY_MOE)) THEN
        ALLOCATE(LANE_FREEWAY_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LANE_FREEWAY_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LANE_FREEWAY_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETFREEWAYLANEMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) LANE_FREEWAY_MOELABEL(NMOE) = CMOE
        LANE_FREEWAY_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) LANE_FREEWAY_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the Freeway network MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('NETWORK_FREEWAY', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'NETWORK_FREEWAY', NMOES, CMOES, UNITS)
    N_NETWORK_FREEWAY_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('NETWORK_FREEWAY', IARRAY, IOBJ)

  ! --- Allocate arrays for network MOEs.
              
      IF(.NOT. ALLOCATED(NETWORK_FREEWAY_MOE)) THEN
        ALLOCATE(NETWORK_FREEWAY_MOE(NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(NETWORK_FREEWAY_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(NETWORK_FREEWAY_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETNETWORKFREEWAYMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) NETWORK_FREEWAY_MOELABEL(NMOE) = CMOE
        NETWORK_FREEWAY_MOE(NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) NETWORK_FREEWAY_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the vehicle type freeway link MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_FREEWAY', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'VEHICLETYPE_LINK_FREEWAY', NMOES, CMOES, UNITS)
    N_VTYPE_LINK_FREEWAY_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_FREEWAY', IARRAY,IOBJ)

  ! --- Allocate arrays for the vehicle type freeway link MOEs.
              
      IF(.NOT. ALLOCATED(VTYPE_LINK_FREEWAY_MOE)) THEN
        ALLOCATE(VTYPE_LINK_FREEWAY_MOE(NOBJ, NMOES, ITP),STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(VTYPE_LINK_FREEWAY_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(VTYPE_LINK_FREEWAY_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETVEHICLETYPEFREEWAYLINKMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) VTYPE_LINK_FREEWAY_MOELABEL(NMOE) = CMOE
        VTYPE_LINK_FREEWAY_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) VTYPE_LINK_FREEWAY_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
  ENDIF
     
  IF(N_STREET_LINKS .GT. 0) THEN
    
  ! --- Define the street detector MOEs.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('STREET_DETECTOR', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'STREET_DETECTOR', NMOES, CMOES, UNITS)
    N_STREET_DETECTOR_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('STREET_DETECTOR', IARRAY, IOBJ)
 
  ! --- Allocate arrays for street detector MOEs.
               
      IF(.NOT. ALLOCATED(STREET_DETECTOR_MOE)) THEN
        ALLOCATE(STREET_DETECTOR_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(STREET_DETECTOR_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(STREET_DETECTOR_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETSTREETDETECTORMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) STREET_DETECTOR_MOELABEL(NMOE) = CMOE
        STREET_DETECTOR_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) STREET_DETECTOR_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the street link MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LINK_STREET', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'LINK_STREET', NMOES, CMOES, UNITS)
    N_LINK_STREET_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('LINK_STREET', IARRAY, IOBJ)

  ! --- Allocate arrays for street link MOEs.
              
      IF(.NOT. ALLOCATED(LINK_STREET_MOE)) THEN
        ALLOCATE(LINK_STREET_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LINK_STREET_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LINK_STREET_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETSTREETLINKMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) LINK_STREET_MOELABEL(NMOE) = CMOE
        LINK_STREET_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) LINK_STREET_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the street lane MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LANE_STREET', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'LANE_STREET', NMOES, CMOES, UNITS)
    N_LANE_STREET_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('LANE_STREET', IARRAY, IOBJ)

  ! --- Allocate arrays for street lane MOEs.
              
      IF(.NOT. ALLOCATED(LANE_STREET_MOE)) THEN
        ALLOCATE(LANE_STREET_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LANE_STREET_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(LANE_STREET_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETSTREETLANEMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) LANE_STREET_MOELABEL(NMOE) = CMOE
        LANE_STREET_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) LANE_STREET_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the Street network MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('NETWORK_STREET', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'NETWORK_STREET', NMOES, CMOES, UNITS)
    N_NETWORK_STREET_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('NETWORK_STREET', IARRAY, IOBJ)

  ! --- Allocate arrays for network MOEs.
              
      IF(.NOT. ALLOCATED(NETWORK_STREET_MOE)) THEN
        ALLOCATE(NETWORK_STREET_MOE(NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(NETWORK_STREET_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(NETWORK_STREET_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETNETWORKSTREETMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) NETWORK_STREET_MOELABEL(NMOE) = CMOE
        NETWORK_STREET_MOE(NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) NETWORK_STREET_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
     
  ! --- Define the vehicle type street link MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_STREET', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'VEHICLETYPE_LINK_STREET', NMOES,CMOES, UNITS)
    N_VTYPE_LINK_STREET_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_STREET', IARRAY, IOBJ)

  ! --- Allocate arrays for the vehicle type street link MOEs.
              
      IF(.NOT. ALLOCATED(VTYPE_LINK_STREET_MOE)) THEN
        ALLOCATE(VTYPE_LINK_STREET_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(VTYPE_LINK_STREET_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(VTYPE_LINK_STREET_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETVEHICLETYPESTREETLINKMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) VTYPE_LINK_STREET_MOELABEL(NMOE) = CMOE
        VTYPE_LINK_STREET_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) VTYPE_LINK_STREET_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO

! --- Define the actuated signal phase MOEs.

    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('SIGNALPHASES', IARRAY, NOBJ)
    TEMP = GETCLASSMOES(ISIZE, 'SIGNALPHASES', NMOES, CMOES, UNITS)
    N_SIGNALPHASES_MOES = NMOES
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('SIGNALPHASES', IARRAY, IOBJ)

  ! --- Allocate arrays for link MOEs.
              
      IF(.NOT. ALLOCATED(SIGNALPHASES_MOE)) THEN
        ALLOCATE(SIGNALPHASES_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(SIGNALPHASES_MOELABEL(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
        ALLOCATE(SIGNALPHASES_MOEUNITS(NMOES), STAT=STATUS)
        IF(STATUS .NE. 0) GOTO 10
      ENDIF
      DO NMOE = 1, NMOES
        ILEN = LEN_TRIM(CMOES(NMOE))
        CMOE = CMOES(NMOE)(2:ILEN-1)
        IRET = GETSIGNALPHASESMOEDATA(CMOE, IARRAY, 2, RMOE)
        IF(TIME_PERIOD .EQ. 1) SIGNALPHASES_MOELABEL(NMOE) = CMOE
        SIGNALPHASES_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
        ILEN = LEN_TRIM(UNITS(NMOE))
        UNIT = UNITS(NMOE)(2:ILEN-1)
        IF(TIME_PERIOD .EQ. 1) SIGNALPHASES_MOEUNITS(NMOE) = UNIT
      ENDDO
    ENDDO
   ENDIF
     
! --- Define the bus route MOEs.

  NOBJ = 0
  TEMP = GETNUMMOEOBJECTS('BUSROUTE', IARRAY, NOBJ)
  TEMP = GETCLASSMOES(ISIZE, 'BUSROUTE', NMOES, CMOES, UNITS)
  N_BUSROUTE_MOES = NMOES
  DO IOBJ = 1, NOBJ
    TEMP = GETNUMMOEOBJECTS('BUSROUTE', IARRAY, IOBJ)

! --- Allocate arrays for bus route MOEs.
              
    IF(.NOT. ALLOCATED(BUSROUTE_MOE)) THEN
      ALLOCATE(BUSROUTE_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(BUSROUTE_MOELABEL(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(BUSROUTE_MOEUNITS(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
    ENDIF
    DO NMOE = 1, NMOES
      ILEN = LEN_TRIM(CMOES(NMOE))
      CMOE = CMOES(NMOE)(2:ILEN-1)
      IRET = GETBUSROUTEMOEDATA(CMOE, IARRAY, 2, RMOE)
      IF(TIME_PERIOD .EQ. 1) BUSROUTE_MOELABEL(NMOE) = CMOE
      BUSROUTE_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
      ILEN = LEN_TRIM(UNITS(NMOE))
      UNIT = UNITS(NMOE)(2:ILEN-1)
      IF(TIME_PERIOD .EQ. 1) BUSROUTE_MOEUNITS(NMOE) = UNIT
    ENDDO
  ENDDO
     
! --- Define the bus station MOEs.

  NOBJ = 0
  TEMP = GETNUMMOEOBJECTS('BUSSTATION', IARRAY, NOBJ)
  TEMP = GETCLASSMOES(ISIZE, 'BUSSTATION', NMOES, CMOES, UNITS)
  N_BUSSTATION_MOES = NMOES
  DO IOBJ = 1, NOBJ
    TEMP = GETNUMMOEOBJECTS('BUSSTATION', IARRAY, IOBJ)

! --- Allocate arrays for bus route MOEs.
              
    IF(.NOT. ALLOCATED(BUSSTATION_MOE)) THEN
      ALLOCATE(BUSSTATION_MOE(NOBJ, NMOES, ITP), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(BUSSTATION_MOELABEL(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
      ALLOCATE(BUSSTATION_MOEUNITS(NMOES), STAT=STATUS)
      IF(STATUS .NE. 0) GOTO 10
    ENDIF
    DO NMOE = 1, NMOES
      ILEN = LEN_TRIM(CMOES(NMOE))
      CMOE = CMOES(NMOE)(2:ILEN-1)
      IRET = GETBUSSTATIONMOEDATA(CMOE, IARRAY, 2, RMOE)
      IF(TIME_PERIOD .EQ. 1) BUSSTATION_MOELABEL(NMOE) = CMOE
      BUSSTATION_MOE(IOBJ, NMOE, TIME_PERIOD) = RMOE
      ILEN = LEN_TRIM(UNITS(NMOE))
      UNIT = UNITS(NMOE)(2:ILEN-1)
      IF(TIME_PERIOD .EQ. 1) BUSSTATION_MOEUNITS(NMOE) = UNIT
    ENDDO
  ENDDO

  RETURN
10 WRITE(*,*) 'ALLOCATION ERROR IN STORE_ALL_MOES'
  ERROR_FLAG = 1
  END
      
! ==========================================================================================================
  SUBROUTINE WRITE_ALL_MOES
  USE TIME_PERIOD_MOES
  USE TEXT
  USE SIMPARAMS
  USE SEEDS
  USE FREEWAY_LINKS
  USE STREET_LINKS
  IMPLICIT NONE
  INCLUDE 'IOFILES.INC'
  INCLUDE 'MOEFUNCTIONS.FI'
  INTEGER MOEFLEN
  COMMON /MOES[DLLEXPORT]/ MOEFOLDER, MOEFLEN
  CHARACTER*512 MOEFOLDER
  CHARACTER*50000 STRING
  INTEGER :: ARGS(4), TEMP, I, K, NM, ITP, IDOT, JLEN, J, NOBJ, IMOE, IOBJ, ITPC
  CHARACTER(512) :: RUN_NAME, PATH, INPUTNAME, FILENAME
  CHARACTER(5) :: CNUM
  INTEGER :: IOUNIT = 1, NAMELEN, PATHLEN, KLEN
! ----------------------------------------------------------------------

! --- Count the number of time periods used.

  DO K = 1, 19
    IF(TPSECONDS(K) .GT. 0) ITP = K
  ENDDO

! --- Open a CSV file for MOEs.

  I = INDEX(LINFNAME, '\', BACK = .TRUE.)
  NAMELEN = LINFLEN - I - 4
  INPUTNAME(1:NAMELEN) = LINFNAME(I+1:LINFLEN)
  
  PATHLEN = MOEFLEN
  IF(MOEFLEN .NE. 0) THEN
    PATH(1:MOEFLEN) = MOEFOLDER(1:MOEFLEN)
  ELSE
    PATHLEN = INDEX(LINFNAME, '\', BACK = .TRUE.) - 1
    PATH(1:PATHLEN) = LINFNAME(1:PATHLEN)
  ENDIF
  
  IF(RUN_NUMBER .EQ. 0) THEN
    FILENAME = PATH(1:PATHLEN) // '\' // INPUTNAME(1:NAMELEN) // '_MOES.CSV'
    I = PATHLEN + NAMELEN + 10
    OPEN(IOUNIT, FILE = FILENAME(1:I), ACTION='WRITE', ERR=10, IOMSG=ETEXT)
  ELSE
    RUN_NAME(1:PATHLEN+NAMELEN+1) = PATH(1:PATHLEN) // '\' // INPUTNAME(1:NAMELEN)
    IDOT = PATHLEN + NAMELEN + 2
    IF(RUN_NUMBER .GT. 999) THEN
      WRITE(CNUM, 1) RUN_NUMBER
      RUN_NAME(IDOT:IDOT+4) = CNUM(1:5)
      FILENAME = RUN_NAME(1:IDOT+4) // '_MOES.CSV'
      OPEN(1, FILE = FILENAME(1:IDOT+13), ACTION='WRITE', ERR=10, IOMSG=ETEXT)
    ELSEIF(RUN_NUMBER .GT. 99) THEN
      WRITE(CNUM, 2) RUN_NUMBER
      RUN_NAME(IDOT:IDOT+3) = CNUM(1:4)
      FILENAME = RUN_NAME(1:IDOT+3) // '_MOES.CSV'
      OPEN(1, FILE = FILENAME(1:IDOT+12), ACTION='WRITE', ERR=10, IOMSG=ETEXT)
    ELSEIF(RUN_NUMBER .GT. 9) THEN
      WRITE(CNUM, 3) RUN_NUMBER
      RUN_NAME(IDOT:IDOT+2) = CNUM(1:3)
      FILENAME = RUN_NAME(1:IDOT+2) // '_MOES.CSV'
      OPEN(IOUNIT, FILE = FILENAME(1:IDOT+11), ACTION='WRITE', ERR=10, IOMSG=ETEXT)
    ELSE
      WRITE(CNUM, 4) RUN_NUMBER
      RUN_NAME(IDOT:IDOT+1) = CNUM(1:2)
      FILENAME = RUN_NAME(1:IDOT+1) // '_MOES.CSV'
      OPEN(IOUNIT, FILE = FILENAME(1:IDOT+10), ACTION='WRITE', ERR=10, IOMSG=ETEXT)
    ENDIF
  ENDIF
  WRITE(IOUNIT, 5) 'Random Number Seeds', ISEED1, ISEED2, ISEED3
1 FORMAT('#', I4)  
2 FORMAT('#', I3)  
3 FORMAT('#', I2)  
4 FORMAT('#', I1)  
5 FORMAT(A, ',', I8, ',', I8, ',', I8)

 
  NOBJ = 0
  TEMP = GETNUMMOEOBJECTS('ENTRYLINK', ARGS, NOBJ)
  IF(NOBJ .GT. 0) THEN
    STRING = ''
    WRITE(STRING(1:20), '(A)') 'Entry Link MOEs,,,'
    I = 18
    DO NM = 1, N_ENTRYLINK_MOES
      JLEN = LEN_TRIM(ENTRYLINK_MOELABEL(NM))
      KLEN = LEN_TRIM(ENTRYLINK_MOEUNITS(NM))
      J = I + JLEN + KLEN + 2
      WRITE(STRING(I:J), '(4A)') ENTRYLINK_MOELABEL(NM)(1:JLEN), ' (', ENTRYLINK_MOEUNITS(NM)(1:KLEN), ')'
      DO K = 1, ITP
        WRITE(STRING(J+K:J+K), '(A)') ','
      ENDDO
      I = J + K
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
    WRITE(STRING(1:20), '(A)') 'Upstream,Downstream,'
    I = 21
    DO NM = 1, N_ENTRYLINK_MOES
      DO K = 1, ITP
        WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
        I = I + 5
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
    STRING = ''
    I = 1
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('ENTRYLINK', ARGS, IOBJ)
      WRITE(STRING(1:8), '(I8)') ARGS(1)
      WRITE(STRING(9:9), '(A)') ','
      WRITE(STRING(10:17), '(I8)') ARGS(2)
      WRITE(STRING(18:18), '(A)') ','
      I = 19
      DO IMOE = 1, N_ENTRYLINK_MOES
        DO ITPC = 1, ITP
          WRITE(STRING(I:I+9), '(G10.2)') ENTRYLINK_MOE(IOBJ, IMOE, ITPC)
          WRITE(STRING(I+10:I+10), '(A)') ','
          I = I + 11
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
    ENDDO
  ENDIF
    
  IF(N_FREEWAY_LINKS .GT. 0) THEN
    
  ! --- Write the freeway link MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LINK_FREEWAY', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:19), '(A)') 'Freeway Link MOEs,,'
      I = 20
      DO NM = 1, N_LINK_FREEWAY_MOES
        JLEN = LEN_TRIM(LINK_FREEWAY_MOELABEL(NM))
        KLEN = LEN_TRIM(LINK_FREEWAY_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') LINK_FREEWAY_MOELABEL(NM)(1:JLEN), ' (', LINK_FREEWAY_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:20), '(A)') 'Upstream,Downstream,'
      I = 21
      DO NM = 1, N_LINK_FREEWAY_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('LINK_FREEWAY', ARGS, IOBJ)
        WRITE(STRING(1:4), '(I4)') ARGS(1)
        WRITE(STRING(5:5), '(A)') ','
        WRITE(STRING(6:9), '(I4)') ARGS(2)
        WRITE(STRING(10:10), '(A)') ','
        I = 11
        DO IMOE = 1, N_LINK_FREEWAY_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') LINK_FREEWAY_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the lane MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LANE_FREEWAY', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:20), '(A)') 'Freeway Lane MOEs,,,'
      I = 21
      DO NM = 1, N_LANE_FREEWAY_MOES
        JLEN = LEN_TRIM(LANE_FREEWAY_MOELABEL(NM))
        KLEN = LEN_TRIM(LANE_FREEWAY_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') LANE_FREEWAY_MOELABEL(NM)(1:JLEN), ' (', LANE_FREEWAY_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-1)
      STRING = ''
      WRITE(STRING(1:25), '(A)') 'Upstream,Downstream,Lane,'
      I = 26
      DO NM = 1, N_LANE_FREEWAY_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('LANE_FREEWAY', ARGS, IOBJ)
        WRITE(STRING(1:4), '(I4)') ARGS(1)
        WRITE(STRING(5:5), '(A)') ','
        WRITE(STRING(6:9), '(I4)') ARGS(2)
        WRITE(STRING(10:10), '(A)') ','
        WRITE(STRING(11:12), '(I2)') ARGS(3)
        WRITE(STRING(13:13), '(A)') ','
        I = 14
        DO IMOE = 1, N_LANE_FREEWAY_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') LANE_FREEWAY_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the freeway detector MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('FREEWAY_DETECTOR', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:23), '(A)') 'Freeway Detector MOEs,,'
      I = 24
      DO NM = 1, N_FREEWAY_DETECTOR_MOES
        JLEN = LEN_TRIM(FREEWAY_DETECTOR_MOELABEL(NM))
        KLEN = LEN_TRIM(FREEWAY_DETECTOR_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') FREEWAY_DETECTOR_MOELABEL(NM)(1:JLEN), ' (', FREEWAY_DETECTOR_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:20), '(A)') 'Upstream,Downstream,'
      I = 21
      DO NM = 1, N_FREEWAY_DETECTOR_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('FREEWAY_DETECTOR', ARGS, IOBJ)
        WRITE(STRING(1:4), '(I4)') ARGS(1)
        WRITE(STRING(5:5), '(A)') ','
        WRITE(STRING(6:9), '(I4)') ARGS(2)
        WRITE(STRING(10:10), '(A)') ','
        I = 11
        DO IMOE = 1, N_FREEWAY_DETECTOR_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') FREEWAY_DETECTOR_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the freeway vehicletypelink MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_FREEWAY', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:32), '(A)') 'Freeway Vehicletype Link MOEs,,,'
      I = 33
      DO NM = 1, N_VTYPE_LINK_FREEWAY_MOES
        JLEN = LEN_TRIM(VTYPE_LINK_FREEWAY_MOELABEL(NM))
        KLEN = LEN_TRIM(VTYPE_LINK_FREEWAY_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') VTYPE_LINK_FREEWAY_MOELABEL(NM)(1:JLEN), ' (', VTYPE_LINK_FREEWAY_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:25), '(A)') 'Upstream,Downstream,Type,'
      I = 26
      DO NM = 1, N_VTYPE_LINK_FREEWAY_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_FREEWAY', ARGS,IOBJ)
        IF(.NOT. TYPE_IS_USED(ARGS(3))) CYCLE
        WRITE(STRING(1:4), '(I4)') ARGS(1)
        WRITE(STRING(5:5), '(A)') ','
        WRITE(STRING(6:9), '(I4)') ARGS(2)
        WRITE(STRING(10:10), '(A)') ','
        WRITE(STRING(11:14), '(I4)') ARGS(3)
        WRITE(STRING(15:15), '(A)') ','
        I = 16
        DO IMOE = 1, N_VTYPE_LINK_FREEWAY_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') VTYPE_LINK_FREEWAY_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the data station MOEs to the CSV file.
      
    IF(ALLOCATED(DATASTATION_MOE)) THEN
      STRING = ''
      WRITE(STRING(1:18), '(A)') 'Data Station MOEs,'
      I = 19
      DO NM = 1, N_DATASTATION_MOES
        JLEN = LEN_TRIM(DATASTATION_MOELABEL(NM))
        KLEN = LEN_TRIM(DATASTATION_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') DATASTATION_MOELABEL(NM)(1:JLEN), ' (', DATASTATION_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-1)
      STRING = ''
      WRITE(STRING(1:15), '(A)') 'Station Number,'
      I = 16
      DO NM = 1, N_DATASTATION_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      NOBJ = 0
      TEMP = GETNUMMOEOBJECTS('DATASTATION', ARGS, NOBJ)
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('DATASTATION', ARGS, IOBJ)
        WRITE(STRING(1:4), '(I4)') ARGS(1)
        WRITE(STRING(5:5), '(A)') ','
        I = 6
        DO IMOE = 1, N_DATASTATION_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') DATASTATION_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
        STRING = ''
      ENDDO
    ENDIF
 
  ! --- Write the Freeway network MOEs to the CSV file.
 
    STRING = ''
    WRITE(STRING(1:21), '(A)') 'Freeway Network MOEs,'
    I = 22
    DO NM = 1, N_NETWORK_FREEWAY_MOES
      JLEN = LEN_TRIM(NETWORK_FREEWAY_MOELABEL(NM))
      KLEN = LEN_TRIM(NETWORK_FREEWAY_MOEUNITS(NM))
      J = I + JLEN + KLEN + 2
      WRITE(STRING(I:J), '(4A)') NETWORK_FREEWAY_MOELABEL(NM)(1:JLEN), ' (', NETWORK_FREEWAY_MOEUNITS(NM)(1:KLEN), ')'
      DO K = 1, ITP
        WRITE(STRING(J+K:J+K), '(A)') ','
      ENDDO
      I = J + K
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I)
    STRING = ''
    WRITE(STRING(1:26), '(A)') ','
    I = 2
    DO NM = 1, N_NETWORK_FREEWAY_MOES
      DO K = 1, ITP
        WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
        I = I + 5
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
    STRING = ''
    WRITE(STRING(1:1), '(A)') ','
    I = 2
    DO IMOE = 1, N_NETWORK_FREEWAY_MOES
      DO ITPC = 1, ITP
        WRITE(STRING(I:I+8), '(F9.2)') NETWORK_FREEWAY_MOE(IMOE, ITPC)
        WRITE(STRING(I+9:I+9), '(A)') ','
        I = I + 10
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
  ENDIF       
  
  IF(N_STREET_LINKS .GT. 0) THEN
 
  ! --- Write the street link MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LINK_STREET', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:18), '(A)') 'Street Link MOEs,,'
      I = 19
      DO NM = 1, N_LINK_STREET_MOES
        JLEN = LEN_TRIM(LINK_STREET_MOELABEL(NM))
        KLEN = LEN_TRIM(LINK_STREET_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') LINK_STREET_MOELABEL(NM)(1:JLEN), ' (', LINK_STREET_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:20), '(A)') 'Upstream,Downstream,'
      I = 21
      DO NM = 1, N_LINK_STREET_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('LINK_STREET', ARGS, IOBJ)
        WRITE(STRING(1:8), '(I8)') ARGS(1)
        WRITE(STRING(9:9), '(A)') ','
        WRITE(STRING(10:17), '(I8)') ARGS(2)
        WRITE(STRING(18:18), '(A)') ','
        I = 19
        DO IMOE = 1, N_LINK_STREET_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+9), '(G10.2)') LINK_STREET_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+10:I+10), '(A)') ','
            I = I + 11
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF

  ! --- Write the street lane MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('LANE_STREET', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:19), '(A)') 'Street Lane MOEs,,,'
      I = 20
      DO NM = 1, N_LANE_STREET_MOES
        JLEN = LEN_TRIM(LANE_STREET_MOELABEL(NM))
        KLEN = LEN_TRIM(LANE_STREET_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') LANE_STREET_MOELABEL(NM)(1:JLEN), ' (', LANE_STREET_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-1)
      STRING = ''
      WRITE(STRING(1:25), '(A)') 'Upstream,Downstream,Lane,'
      I = 26
      DO NM = 1, N_LANE_STREET_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('LANE_STREET', ARGS, IOBJ)
        WRITE(STRING(1:8), '(I8)') ARGS(1)
        WRITE(STRING(9:9), '(A)') ','
        WRITE(STRING(10:17), '(I8)') ARGS(2)
        WRITE(STRING(18:18), '(A)') ','
        WRITE(STRING(19:20), '(I2)') ARGS(3)
        WRITE(STRING(21:21), '(A)') ','
        I = 22
        DO IMOE = 1, N_LANE_STREET_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+9), '(G10.2)') LANE_STREET_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+10:I+10), '(A)') ','
            I = I + 11
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the street detector MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('STREET_DETECTOR', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:22), '(A)') 'Street Detector MOEs,,'
      I = 23
      DO NM = 1, N_STREET_DETECTOR_MOES
        JLEN = LEN_TRIM(STREET_DETECTOR_MOELABEL(NM))
        KLEN = LEN_TRIM(STREET_DETECTOR_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') STREET_DETECTOR_MOELABEL(NM)(1:JLEN), ' (', STREET_DETECTOR_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:20), '(A)') 'Upstream,Downstream,'
      I = 21
      DO NM = 1, N_STREET_DETECTOR_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('STREET_DETECTOR', ARGS, IOBJ)
        WRITE(STRING(1:8), '(I8)') ARGS(1)
        WRITE(STRING(9:9), '(A)') ','
        WRITE(STRING(10:17), '(I8)') ARGS(2)
        WRITE(STRING(18:18), '(A)') ','
        I = 19
        DO IMOE = 1, N_STREET_DETECTOR_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') STREET_DETECTOR_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the actuated signal phase MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('SIGNALPHASES', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:28), '(A)') 'Actuated Signal Phase MOEs,,'
      I = 29
      DO NM = 1, N_SIGNALPHASES_MOES
        JLEN = LEN_TRIM(SIGNALPHASES_MOELABEL(NM))
        KLEN = LEN_TRIM(SIGNALPHASES_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') SIGNALPHASES_MOELABEL(NM)(1:JLEN), ' (', SIGNALPHASES_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:20), '(A)') 'Node,Phase,'
      I = 21
      DO NM = 1, N_SIGNALPHASES_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('SIGNALPHASES', ARGS, IOBJ)
        WRITE(STRING(1:8), '(I8)') ARGS(1)
        WRITE(STRING(9:9), '(A)') ','
        WRITE(STRING(10:17), '(I8)') ARGS(2)
        WRITE(STRING(18:18), '(A)') ','
        I = 19
        DO IMOE = 1, N_SIGNALPHASES_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') SIGNALPHASES_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
    
  ! --- Write the street vehicletypelink MOEs to the CSV file.
 
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_STREET', ARGS, NOBJ)
    IF(NOBJ .GT. 0) THEN
      STRING = ''
      WRITE(STRING(1:31), '(A)') 'Street Vehicletype Link MOEs,,,'
      I = 32
      DO NM = 1, N_VTYPE_LINK_STREET_MOES
        JLEN = LEN_TRIM(VTYPE_LINK_STREET_MOELABEL(NM))
        KLEN = LEN_TRIM(VTYPE_LINK_STREET_MOEUNITS(NM))
        J = I + JLEN + KLEN + 2
        WRITE(STRING(I:J), '(4A)') VTYPE_LINK_STREET_MOELABEL(NM)(1:JLEN), ' (', VTYPE_LINK_STREET_MOEUNITS(NM)(1:KLEN), ')'
        DO K = 1, ITP
          WRITE(STRING(J+K:J+K), '(A)') ','
        ENDDO
        I = J + K
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      WRITE(STRING(1:25), '(A)') 'Upstream,Downstream,Type,'
      I = 26
      DO NM = 1, N_VTYPE_LINK_STREET_MOES
        DO K = 1, ITP
          WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
          I = I + 5
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
      I = 1
      DO IOBJ = 1, NOBJ
        TEMP = GETNUMMOEOBJECTS('VEHICLETYPE_LINK_STREET', ARGS, IOBJ)
        IF(.NOT. TYPE_IS_USED(ARGS(3))) CYCLE
        WRITE(STRING(1:8), '(I8)') ARGS(1)
        WRITE(STRING(9:9), '(A)') ','
        WRITE(STRING(10:17), '(I8)') ARGS(2)
        WRITE(STRING(18:18), '(A)') ','
        WRITE(STRING(19:27), '(I8)') ARGS(3)
        WRITE(STRING(28:28), '(A)') ','
        I = 29
        DO IMOE = 1, N_VTYPE_LINK_STREET_MOES
          DO ITPC = 1, ITP
            WRITE(STRING(I:I+8), '(F9.2)') VTYPE_LINK_STREET_MOE(IOBJ, IMOE, ITPC)
            WRITE(STRING(I+9:I+9), '(A)') ','
            I = I + 10
          ENDDO
        ENDDO
        WRITE(IOUNIT, '(A)') STRING(1:I-2)
      ENDDO
    ENDIF
 
  ! --- Write the Street network MOEs to the CSV file.
 
    STRING = ''
    WRITE(STRING(1:20), '(A)') 'Street Network MOEs,'
    I = 21
    DO NM = 1, N_NETWORK_STREET_MOES
      JLEN = LEN_TRIM(NETWORK_STREET_MOELABEL(NM))
      KLEN = LEN_TRIM(NETWORK_STREET_MOEUNITS(NM))
      J = I + JLEN + KLEN + 2
      WRITE(STRING(I:J), '(4A)') NETWORK_STREET_MOELABEL(NM)(1:JLEN), ' (', NETWORK_STREET_MOEUNITS(NM)(1:KLEN), ')'
      DO K = 1, ITP
        WRITE(STRING(J+K:J+K), '(A)') ','
      ENDDO
      I = J + K
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I)
    STRING = ''
    WRITE(STRING(1:26), '(A)') ','
    I = 2
    DO NM = 1, N_NETWORK_STREET_MOES
      DO K = 1, ITP
        WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
        I = I + 5
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
    STRING = ''
    WRITE(STRING(1:1), '(A)') ','
    I = 2
    DO IMOE = 1, N_NETWORK_STREET_MOES
      DO ITPC = 1, ITP
        WRITE(STRING(I:I+8), '(F9.2)') NETWORK_STREET_MOE(IMOE, ITPC)
        WRITE(STRING(I+9:I+9), '(A)') ','
        I = I + 10
      ENDDO
    ENDDO
     
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
  ENDIF
 
! --- Write the bus route MOEs to the CSV file.
      
  IF(ALLOCATED(BUSROUTE_MOE)) THEN
    STRING = ''
    WRITE(STRING(1:15), '(A)') 'Bus Route MOEs,'
    I = 16
    DO NM = 1, N_BUSROUTE_MOES
      JLEN = LEN_TRIM(BUSROUTE_MOELABEL(NM))
      KLEN = LEN_TRIM(BUSROUTE_MOEUNITS(NM))
      J = I + JLEN + KLEN + 2
      WRITE(STRING(I:J), '(4A)') BUSROUTE_MOELABEL(NM)(1:JLEN), ' (', BUSROUTE_MOEUNITS(NM)(1:KLEN), ')'
      DO K = 1, ITP
        WRITE(STRING(J+K:J+K), '(A)') ','
      ENDDO
      I = J + K
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-1)
    WRITE(STRING(1:1), '(A)') ','
    I = 2
    DO NM = 1, N_BUSROUTE_MOES
      DO K = 1, ITP
        WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
        I = I + 5
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-1)
    STRING = ','
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('BUSROUTE', ARGS, NOBJ)
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('BUSROUTE', ARGS, IOBJ)
      WRITE(STRING(1:4), '(I4)') ARGS(1)
      WRITE(STRING(5:5), '(A)') ','
      I = 6
      DO IMOE = 1, N_BUSROUTE_MOES
        DO ITPC = 1, ITP
          WRITE(STRING(I:I+8), '(F9.2)') BUSROUTE_MOE(IOBJ, IMOE, ITPC)
          WRITE(STRING(I+9:I+9), '(A)') ','
          I = I + 10
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-1)
    ENDDO
  ENDIF
 
! --- Write the bus station MOEs to the CSV file.
     
  IF(ALLOCATED(BUSSTATION_MOE)) THEN
    STRING = ''
    WRITE(STRING(1:17), '(A)') 'Bus Station MOEs,'
    I = 18
    DO NM = 1, N_BUSSTATION_MOES
      JLEN = LEN_TRIM(BUSSTATION_MOELABEL(NM))
      KLEN = LEN_TRIM(BUSSTATION_MOEUNITS(NM))
      J = I + JLEN + KLEN + 2
      WRITE(STRING(I:J), '(4A)') BUSSTATION_MOELABEL(NM)(1:JLEN), ' (', BUSSTATION_MOEUNITS(NM)(1:KLEN), ')'
      DO K = 1, ITP
        WRITE(STRING(J+K:J+K), '(A)') ','
      ENDDO
      I = J + K
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-1)
    STRING = ''
    WRITE(STRING(1:15), '(A)') 'Station Number,'
    I = 16
    DO NM = 1, N_BUSSTATION_MOES
      DO K = 1, ITP
        WRITE(STRING(I:I+4), '(A,I2,A)') 'TP',K,','
        I = I + 5
      ENDDO
    ENDDO
    WRITE(IOUNIT, '(A)') STRING(1:I-2)
    STRING = ''
    I = 1
    NOBJ = 0
    TEMP = GETNUMMOEOBJECTS('BUSSTATION', ARGS, NOBJ)
    DO IOBJ = 1, NOBJ
      TEMP = GETNUMMOEOBJECTS('BUSSTATION', ARGS, IOBJ)
      WRITE(STRING(1:4), '(I4)') ARGS(1)
      WRITE(STRING(5:5), '(A)') ','
      I = 6
      DO IMOE = 1, N_BUSSTATION_MOES
        DO ITPC = 1, ITP
          WRITE(STRING(I:I+8), '(F9.2)') BUSSTATION_MOE(IOBJ, IMOE, ITPC)
          WRITE(STRING(I+9:I+9), '(A)') ','
          I = I + 10
        ENDDO
      ENDDO
      WRITE(IOUNIT, '(A)') STRING(1:I-2)
      STRING = ''
    ENDDO
  ENDIF
  CLOSE(1)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_ALL_MOES'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  ERROR_FLAG = 1
  RETURN
  END
!
! ==========================================================================================================
! Function: GETCLASSMOES( int ISIZE, char CLASSNAME, int NMOES, char CMOES )
!
!
! Description: Gets all of the MOEs pertaining to a specific class
!
!
! Arguments:  ISIZE     - [in] size of the MOE list
!             CLASSNAME - [in] name of the MOE class
!             NMOES     - [out] number of MOEs in the class
!             CMOES    - [out] array of MOE character strings
!
! Returns: int = 0 - success
! Returns: int = 1 - CLASS name was not recognized or object was not found
! ==========================================================================================================
  INTEGER FUNCTION GETCLASSMOES(ISIZE, CLASSNAME, NMOES, CMOES, UNITS)
  IMPLICIT NONE
  INTEGER :: ISIZE, NMOES
  CHARACTER*(*) CLASSNAME
  CHARACTER*80 CMOES(200)
  CHARACTER*80 UNITS(200)
  CHARACTER*1500 STRING
  CHARACTER*(ISIZE) CBUF
  INTEGER :: ILEN, IC, I1, I2, KC, NC, IEND, KEND
  INCLUDE 'MOELIST.FI'
! ----------------------------------------------------------------------
 
! --- Parse the moelist to define the MOEs within a class.
       
  GETCLASSMOES = 0      
  ILEN = LEN_TRIM(CLASSNAME)
  NMOES = 0
  DO IC = 1, ISIZE - 20
    IF(CBUF(IC:IC+10) .EQ. 'CLASS name=') THEN
      I1 = IC + 12
      I2 = I1 + ILEN - 1
      IF(CBUF(I1:I2) .EQ. CLASSNAME) THEN
        DO KC = I2+1, ISIZE - 20
          IF(CBUF(KC:KC+4) .EQ. 'name=') THEN
            NC = SCAN(CBUF(KC+6:ISIZE), '"')
            I1 = KC + 5
            I2 = I1 + NC
            NMOES = NMOES + 1
            CMOES(NMOES) = CBUF(I1:I2)
          ENDIF
          IF(CBUF(KC:KC+5) .EQ. 'units=') THEN
            NC = SCAN(CBUF(KC+7:ISIZE), '"')
            I1 = KC + 6
            I2 = I1 + NC
            UNITS(NMOES) = CBUF(I1:I2)
          ENDIF
          IF(CBUF(KC:KC+10) .EQ. 'CLASS name=') GOTO 1
        ENDDO
      ENDIF
    ENDIF
  ENDDO
  GETCLASSMOES = 1
1 CONTINUE
  END
