  MODULE CORWIN_DATA
    INTEGER SIM_LINKSTATEVALID
    INTEGER SIM_ADDVEHICLE
    INTEGER SIM_LINKCOMPLETE
    INTEGER SIM_ADDRAMPMETER
    INTEGER SIM_ADDINCIDENT
    INTEGER SIM_LINKTIDVALID
  END MODULE
  SUBROUTINE SENDMSG(I, J)
  INTEGER, INTENT(IN) :: I, J
  RETURN
  END
  SUBROUTINE SETTIDDATA
  RETURN
  END
  SUBROUTINE OUTPUTSTRING(I, J, K)
  INTEGER, INTENT(IN) :: I, J, K
  RETURN
  END
