! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

! ==========================================================================================================
  SUBROUTINE CHECK_INPUTS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs.
! ----------------------------------------------------------------------
  USE FREEWAY_LINKS
  USE STREET_LINKS
  USE SIMPARAMS                 
  IMPLICIT NONE
! ----------------------------------------------------------------------
  IF(TIME_PERIOD .EQ. 1) THEN
    CALL CHECK_NETWORK_INPUTS
    IF(N_FREEWAY_LINKS .GT. 0) THEN
      CALL CHECK_FREEWAY_NETWORK_INPUTS
      CALL CHECK_FREEWAYLINKS
      CALL CHECK_EXIT_PERCENTAGES
      CALL CHECK_RAMPMETERS
      CALL CHECK_FREEWAYDETECTORS
      CALL CHECK_FREEWAY_INCIDENTS
    ENDIF
    IF(N_STREET_LINKS .GT. 0) THEN
      CALL CHECK_STREET_NETWORK_INPUTS
      CALL CHECK_STREETLINKS
      CALL CHECK_TURN_PERCENTAGES
      CALL CHECK_AC_SIGNALS
      CALL CHECK_FTC_SIGNALS
      CALL CHECK_PARKING_ZONES
      !CALL CHECK_NODES
      CALL CHECK_STREETDETECTORS
      CALL CHECK_BUSSTATIONS
      !CALL CHECK_INTERSECTION_DATA
    ENDIF
    CALL CHECK_ENTRYNODES
    CALL CHECK_BUSROUTES
    CALL CHECK_NODE_COORDINATES
  ELSE
    IF(N_FREEWAY_LINKS .GT. 0) THEN
      CALL CHECK_EXIT_PERCENTAGES
      CALL CHECK_RAMPMETERS
    ENDIF
    IF(N_STREET_LINKS .GT. 0) THEN
      CALL CHECK_TURN_PERCENTAGES
      CALL CHECK_AC_SIGNALS
      CALL CHECK_FTC_SIGNALS
      CALL CHECK_PARKING_ZONES
    ENDIF
  ENDIF
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_NETWORK_INPUTS
! ----------------------------------------------------------------------
! --- Check the validity of all network inputs.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I
! ----------------------------------------------------------------------
  DO I = 1, 19
    IF(TPSECONDS(I) .GT. 9999) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'INVALID DURATION FOR TIME PERIOD ', I
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(TIMESTEP .LT. 0.01 .OR. TIMESTEP .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F6.3)') 'INVALID TIME STEP = ', TIMESTEP
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF

  IF(TIME_INTERVAL .LT. 1 .OR. TIME_INTERVAL .GT. 200) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, I4)') 'INVALID TIME INTERVAL = ', TIME_INTERVAL
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF

  IF(TRANSITION_CODE .LT. 0 .OR. TRANSITION_CODE .GT. 3) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, I1)') 'INVALID PRE-TIMED SIGNAL TRANSITION METHOD = ', TRANSITION_CODE
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF

  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_FREEWAY_NETWORK_INPUTS
! ----------------------------------------------------------------------
! --- Check the validity of all freeway network inputs.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE CAR_FOLLOWING
  USE DRIVERS
  USE GLOBAL_DATA
  IMPLICIT NONE
  INTEGER :: I
! ----------------------------------------------------------------------
  IF(LAG_ACCEL .LT. 0.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.1)') 'INVALID LAG TO ACCELERATE = ', LAG_ACCEL
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  IF(LAG_DECEL .LT. 0.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.1)') 'INVALID LAG TO DECELERATE = ', LAG_DECEL
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  DO I = 1, 4
    IF(CFRICT(I) .LT. 0.0 .OR. CFRICT(I) .GT. 1.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID COEFFICIENT OF FRICTION'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, 'VALUE = ', CFRICT(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(DEFAULT_HOV_PCT .LT. 0.0 .OR. DEFAULT_HOV_PCT .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID DEFAULT HOV PCT = ', DEFAULT_HOV_PCT
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  DO I = 1, 10
    IF(FZFOLL(I) .LT. 0.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID FREEWAY CAR FOLLOWING SENSITIVITY FACTOR' 
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, 'VALUE = ', FZFOLL(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(FFSPEED_ADJ(I, I_FREEWAY) .LT. 0.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID FREEWAY FREEFLOW SPEED FACTOR'  
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, 'VALUE = ', FFSPEED_ADJ(I, I_FREEWAY) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(FREEWAY_PCT_COOP .LT. 0.0 .OR. FREEWAY_PCT_COOP .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID FREEWAY COOPERATION PERCENTAGE = ', FREEWAY_PCT_COOP
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  IF(LC_TIME_FREEWAY .LT. 0.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID FREEWAY LANE CHANGE INTERVAL = ', LC_TIME_FREEWAY
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  IF(DLC_MULT .LT. 0.0 .OR. DLC_MULT .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID FREEWAY DISCRETIONARY LANE CHANGE MULTIPLIER = ', DLC_MULT
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_STREET_NETWORK_INPUTS
! ----------------------------------------------------------------------
! --- Check the validity of all street network inputs.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE CAR_FOLLOWING
  USE DRIVERS
  USE BUS_STATION_DATA
  USE GLOBAL_DATA
  USE DISTRIBUTIONS
  USE PEDS
  USE EVENTS
  IMPLICIT NONE
  INTEGER :: I, J
! ----------------------------------------------------------------------
  DO I = 1, 10
    IF(ACCEPTABLE_GAP(I) .LT. 1.5 .OR. ACCEPTABLE_GAP(I) .GT. 7.5) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, F10.1)') 'INVALID ACCEPTABLE GAP'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', ACCEPTABLE_GAP(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(ACCEPTABLE_LTG(I) .LT. 1.0 .OR. ACCEPTABLE_LTG(I) .GT. 10.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID ACCEPTABLE LT GAP'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', ACCEPTABLE_LTG(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(ACCEPTABLE_RTG(I) .LT. 1.0 .OR. ACCEPTABLE_RTG(I) .GT. 10.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID ACCEPTABLE RT GAP'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', ACCEPTABLE_RTG(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(ADDITIONAL_GAP(I) .LT. 1.0 .OR. ADDITIONAL_GAP(I) .GT. 7.5) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID ADDITIONAL GAP' 
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', ADDITIONAL_GAP(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(AMBER_DECEL(I) .GT. -2.0 .OR. AMBER_DECEL(I) .LT. -30.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID AMBER RESPONSE'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', AMBER_DECEL(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 6
    DO J = 1, 10
      IF(DWELL_MULTIPLIER(I, J) .LT. 0.0 .OR. DWELL_MULTIPLIER(I, J) .GT. 10.0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A)') 'INVALID DWELL MULTIPLIER' 
        CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', DWELL_MULTIPLIER(I, J) 
      CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDDO
  ENDDO
  
  DO I = 1, 10
    IF(SZFOLL(I) .LT. 0.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID STREET CAR FOLLOWING SENSITIVITY FACTOR' 
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', SZFOLL(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(FFSPEED_ADJ(I, 2) .LT. 0.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID STREET FREEFLOW SPEED FACTOR'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', FFSPEED_ADJ(I, 2) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(LC_TIME_STREET .LT. 0.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID STREET LANE CHANGE INTERVAL = ', LC_TIME_STREET
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  DO I = 1, N_STREET_LANES
    IF(LT_JUMPER_PROB(I) .LT. 0.0 .OR. LT_JUMPER_PROB(I) .GT. 1.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID LT JUMPER PROBABILITY'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', LT_JUMPER_PROB(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 3
    IF(LT_LAGGER_PROB(I) .LT. 0.0 .OR. LT_LAGGER_PROB(I) .GT. 1.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID LT LAGGER PROBABILITY' 
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', LT_LAGGER_PROB(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  !IF(LT_SPEED .LT. 0 .OR. LT_SPEED .GT. 44) THEN
  !  CALL NEW_ERROR
  !  WRITE(MSGTEXT, '(A, I4)') 'INVALID LT SPEED = ', LT_SPEED
  !  CALL SENDTEXTMSG(M_ERROR)
  !ENDIF
  
  !IF(RT_SPEED .LT. 0 .OR. RT_SPEED .GT. 26) THEN
  !  CALL NEW_ERROR
  !  WRITE(MSGTEXT, '(A, I4)') 'INVALID RT SPEED = ', RT_SPEED
  !  CALL SENDTEXTMSG(M_ERROR)
  !ENDIF
  
  DO I = 1, 4
    IF(SPILLBACK_PROB(I) .LT. 0.0 .OR. SPILLBACK_PROB(I) .GT. 1.0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID SPILLBACK PROBABILITY' 
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', SPILLBACK_PROB(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(STREET_PCT_COOP .LT. 0.0 .OR. STREET_PCT_COOP .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID STREET COOPERATION PERCENTAGE = ', STREET_PCT_COOP
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  IF(DRIVER_FAMPCT .LT. 0.0 .OR. DRIVER_FAMPCT .GT. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, F10.2)') 'INVALID DRIVER FAMILIARITY PERCENTAGE = ', DRIVER_FAMPCT
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  DO I = 1, 10
    IF(PDELAY_WEAK(I) .LT. 0 .OR. PDELAY_WEAK(I) .GT. 50) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID WEAK PEDESTRIAN DELAY'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', PDELAY_WEAK(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 10
    IF(PDELAY_STRONG(I) .LT. 0 .OR. PDELAY_STRONG(I) .GT. 50) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID STRONG PEDESTRIAN DELAY'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, ' VALUE = ', PDELAY_STRONG(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  DO I = 1, 3
    IF(PED_DURATION(I) .LT. 0 .OR. PED_DURATION(I) .GT. 50) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A)') 'INVALID PEDESTRIAN DURATION'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, 'VALUE = ', PED_DURATION(I) 
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  
  IF(SUM(QFACTOR) .NE. 1.0) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A)') 'QUEUE DISCHARGE FACTORS DO NOT TOTAL 1.0'
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  
  IF(SUM(STE_MULT) .NE. 10) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A)') 'INVALID SHORT TERM EVENT DISTRIBUTION'
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_ENTRYNODES
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for entry nodes.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE FREEWAY_LINKS
  USE STREET_LINKS
  USE FLOWDATA_MOD
  USE ENTRYNODE_DATA
  USE NODE_TABLE
  IMPLICIT NONE
  INTEGER :: I, IUP, IDOWN, IL, NLANES, J
  REAL :: DSUM
! ----------------------------------------------------------------------
  IF(TYPEDIST .LT. 0 .OR. TYPEDIST .GT. 2) THEN
    CALL NEW_ERROR
    WRITE(MSGTEXT, '(A, I1)') 'INVALID VEHICLE ENTRY HEADWAY OPTION = ' , TYPEDIST
    CALL SENDTEXTMSG(M_ERROR)
  ELSEIF(TYPEDIST .EQ. 2) THEN
    IF(ERLANGA .LT. 0 .OR. ERLANGA .GT. 9) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I1)') 'INVALID ERLANG PARAMETER = ' , ERLANGA
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDIF

  DO I = 1, NUMBER_OF_ENTRYNODES
    IUP = ENTRYLINK(I)%UP
    IDOWN = ENTRYLINK(I)%DOWN
    
    IF(NODE_TYPE(IUP) .NE. NT_EXTERN .OR. NODE_TYPE(IDOWN) .NE. NT_INTERN) THEN
      IF(ENTRYLINK(I)%CARDTYPE .NE. 51) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I4)') 'INVALID ENTRY LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ELSE
      
      CALL FIND_FREEWAY_LINK(IUP, IDOWN, IL)
      IF(IL .NE. 0) THEN
        NLANES = FNUMLANES(IL)
      ELSE
        CALL FIND_STREET_LINK(IUP, IDOWN, IL)
        IF(IL .NE. 0) NLANES = SNUMLANES(IL)
      ENDIF
      IF(IL .EQ. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I4)') 'ENTRY LINK NOT FOUND FOR NODE ', IUP
        CALL SENDTEXTMSG(M_ERROR)
      ELSE
        
        DO J = 1, ENTRYLINK(I)%INDEX
          IF(ENTRYLINK(I)%FLOW(J) .LT. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I4)') 'NEGATIVE FLOWRATE AT NODE ', IUP
            CALL SENDTEXTMSG(M_ERROR)
            EXIT
          ENDIF
        ENDDO
        
        IF(TRUCK_PCT(IUP) .LT. 0.0 .OR. TRUCK_PCT(IUP) .GT. 1.0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I4)') 'INVALID TRUCK PERCENTAGE AT NODE ', IUP
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, F5.1)') '  TRUCK PERCENTAGE = ', TRUCK_PCT(IUP) * 100
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        
        IF(CARPOOL_PCT(IUP) .LT. 0.0 .OR. CARPOOL_PCT(IUP) .GT. 1.0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I4)') 'INVALID CARPOOL PERCENTAGE AT NODE ', IUP
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, F5.1)') '  CARPOOL PERCENTAGE = ', CARPOOL_PCT(IUP) * 100
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        
        IF(HOV_VIOLATOR_PCT(IUP) .LT. 0.0 .OR. HOV_VIOLATOR_PCT(IUP) .GT. 1.0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I4)') 'INVALID HOV VIOLATOR PERCENTAGE AT NODE ', IUP
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, F5.1)') '  HOV VIOLATOR PERCENTAGE = ', HOV_VIOLATOR_PCT(IUP) * 100
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        
        DSUM = SUM(LANE_PCT(IUP, 1:NLANES))
        IF(ABS(DSUM - 1.0 .GT. .000001)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I4)') 'INVALID LANE DISTRIBUTION AT ENTRY NODE ', IUP
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, <NLANES>F8.2)') ' ENTRIES ARE ', (LANE_PCT(IUP, J), J = 1, NLANES)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_FREEWAYLINKS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for freeway links.
! ----------------------------------------------------------------------
  USE FREEWAY_LINKS
  USE DATASTATIONS
  USE SIMPARAMS
  USE TEXT
  USE GLOBAL_DATA
  USE NODE_TABLE
  USE DRIVERS
  IMPLICIT NONE
  INTEGER :: IL, IUP, IDOWN, IAUX, BARR, K, ISPEED, USN, DSN, W1, W2, TRAVEL
  LOGICAL :: L1, L2, SHORTLINKS, FOUND
! ----------------------------------------------------------------------
  DO IL = 1, N_FREEWAY_LINKS
    IUP = FUSN(IL)
    IDOWN = FDSN(IL)
    
    IF(NODE_TYPE(IUP) .NE. NT_INTERN .AND. NODE_TYPE(IDOWN) .NE. NT_INTERN) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I4)') 'INVALID LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(NODE_TYPE(IUP) .EQ. NT_EXTERN .OR. NODE_TYPE(IDOWN) .EQ. NT_EXTERN) THEN
      IF(FLENGTH(IL) .NE. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'LENGTH SPECIFIED FOR ENTRY OR EXIT LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      IF(DATASTATION_ID(IL) .NE. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'DATASTATION LOCATION SPECIFIED FOR ENTRY OR EXIT LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I6)') '  DATASTATION LOCATION = ', DATASTATION(DATASTATION_ID(IL))%LOCATION
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ELSE
      IF(NODE_TYPE(IUP) .NE. NT_INTERN .AND. LINKTYPE(IL) .NE. 0 .AND. FTHRU_LINK(IL) .NE. 0) THEN
        IF(LINKTYPE(FTHRU_LINK(IL)) .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A)') 'INTERFACE RAMP LINK CONNECTS TO FREEWAY MAINLINE'
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, 2I5)') '  DUMMY NODE MUST BE INSERTED ON LINK', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      IF(FLENGTH(IL) .EQ. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'LENGTH NOT SPECIFIED FOR INTERNAL LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ELSEIF(FLENGTH(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE LENGTH SPECIFIED FOR INTERNAL LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, F10.1)') '  LENGTH = ', FLENGTH(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF    
    ENDIF

    IF(LINKTYPE(IL) .LT. 0 .OR. LINKTYPE(IL) .GT. 2) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'INVALID FREEWAY LINK TYPE CODE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I2)') '  LINK TYPE CODE = ', LINKTYPE(IL)
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF

    IF(NODE_TYPE(IUP) .NE. NT_EXTERN .AND. NODE_TYPE(IDOWN) .NE. NT_EXTERN) THEN
      IF(MAINLINE_RECEIVING_LANE(IL) .LT. 1 .OR. MAINLINE_RECEIVING_LANE(IL) .GT. 20) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LANE RECEIVING TRAFFIC FROM LANE 1 ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I2)') '  LANE RECEIVING TRAFFIC FROM LANE 1 = ', MAINLINE_RECEIVING_LANE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF

      IF(LINKTYPE(IL) .EQ. 0) THEN
        IF(FNUMLANES(IL) .LT. 1 .OR. FNUMLANES(IL) .GT. 10) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID NUMBER OF THRU LANES ON MAINLINE LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I2)') '  NUMBER OF LANES = ', FNUMLANES(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ELSE
        IF(FNUMLANES(IL) .LT. 1 .OR. FNUMLANES(IL) .GT. 5) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID NUMBER OF THRU LANES ON RAMP LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I2)') '  NUMBER OF LANES = ', FNUMLANES(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(AUX_LANE_ID(IL, 1) .NE. 0) THEN
        IF(NODE_TYPE(IUP) .NE. NT_INTERN .OR. NODE_TYPE(IDOWN) .NE. NT_INTERN) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'AUXILIARY LANES NOT ALLOWED ON INTERFACE LINKS ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        
        IF(AUX_LANE_ID(IL, 1) .NE. 11 .AND. AUX_LANE_ID(IL, 1) .NE. 16) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'AUXILIARY LANES INCORRECTLY NUMBERED ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A)') '  FIRST LEFT AUXILIARY LANE MUST BE 11 AND FIRST RIGHT AUXILIARY LANE MUST BE 16'
          CALL SENDTEXTMSG(M_ERROR)
        ELSE
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_CODE(IL, IAUX) .LT. 1 .OR. AUX_LANE_CODE(IL, IAUX) .GT. 3) THEN
              CALL NEW_ERROR
              WRITE(MSGTEXT, '(A, 2I5)') 'AUXILIARY LANE HAS INCORRECT LANE TYPE CODE ON LINK', IUP, IDOWN
              CALL SENDTEXTMSG(M_ERROR)
              WRITE(MSGTEXT, '(A, I2, A, I1)') '  LANE ID = ', AUX_LANE_ID(IL, IAUX), ' CODE = ', AUX_LANE_CODE(IL, IAUX) 
              CALL SENDTEXTMSG(M_ERROR)
            ELSEIF(AUX_LANE_CODE(IL, IAUX) .EQ. AUX_FULL) THEN
              IF(AUX_LANE_LENGTH(IL, IAUX) .NE. FLENGTH(IL)) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'FULL AUXILIARY LANE HAS INCORRECT LENGTH ON LINK', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I2, A, I5)') '  LANE ID = ', AUX_LANE_ID(IL, IAUX), ' LENGTH = ', AUX_LANE_LENGTH(IL, IAUX) 
                CALL SENDTEXTMSG(M_ERROR)
              ENDIF
            ELSE
              IF(AUX_LANE_LENGTH(IL, IAUX) .GT. FLENGTH(IL)) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'AUXILIARY LANE LENGTH EXCEEDS LINK LENGTH ON LINK', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I2, A, I5)') '  LANE ID = ', AUX_LANE_ID(IL, IAUX), ' LENGTH = ', AUX_LANE_LENGTH(IL, IAUX) 
                CALL SENDTEXTMSG(M_ERROR)
              ENDIF
            ENDIF
          ENDDO
        ENDIF
      ENDIF
        
      ISPEED = NINT(FFREEFLOWSPEED(IL) * FEET2MILES)
      IF(ISPEED .LT. 1 .OR. ISPEED .GT. 75) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE FREEFLOW SPEED ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I3)') '  FREEFLOW SPEED = ', ISPEED
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(FGRADE(IL) .LT. -9 .OR. FGRADE(IL) .GT. 10) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE GRADE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  GRADE = ', FGRADE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(TILT(IL) .LT. 0 .OR. TILT(IL) .GT. 12) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE SUPERELEVATION ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  SUPERELEVATION = ', TILT(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(PAVEMENT(IL) .LT. 0 .OR. PAVEMENT(IL) .GT. 4) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE PAVEMENT CODE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  PAVEMENT CODE = ', PAVEMENT(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
        
      IF(FSTARTUP_TIME(IL) .LT. 0 .OR. FSTARTUP_TIME(IL) .GT. 6.0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE MEAN QUEUE DISCHARGE HEADWAY ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, F5.1)') '  MEAN QUEUE DISCHARGE HEADWAY = ', FSTARTUP_TIME(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF

      IF(BARRIER(IL, 1) .NE. 0) THEN
        L1 = .FALSE.     !RIGHT LANE
        L2 = .FALSE.     !LEFT LANE
        BARR = BARRIER(IL, 1)
        IF(BARR .GE. 1 .AND. BARR .LE. FNUMLANES(IL) - 1) THEN
          L1 = .TRUE.
          L2 = .TRUE.
        ELSEIF(BARR .EQ. FNUMLANES(IL)) THEN
          L1 = .TRUE.
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 11) L2 = .TRUE.
          ENDDO
        ELSEIF(BARR .EQ. 16) THEN
          L2 = .TRUE.
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 16) L1 = .TRUE.
          ENDDO
        ELSEIF(BARR .GE. 11 .AND. BARR .LE. 15) THEN
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_ID(IL, IAUX) .EQ. BARR) L1 = .TRUE.
            IF(AUX_LANE_ID(IL, IAUX) .EQ. BARR + 1) L2 = .TRUE.
          ENDDO
        ELSEIF(BARR .GE. 16) THEN
          IF(BARR .EQ. 16) L2 = .TRUE.
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_ID(IL, IAUX) .EQ. BARR) L1 = .TRUE.
            IF(AUX_LANE_ID(IL, IAUX) .EQ. BARR - 1) L2 = .TRUE.
          ENDDO
        ENDIF
        IF(.NOT. (L1 .AND. L2)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'BARRIER BETWEEN NON-EXISTANT LANES ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I1)') '  LANE ID = ', BARR
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(NHOV_LANES(IL) .GT. 0) THEN
        IF(NHOV_LANES(IL) .GT. 3) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'MORE THAN 3 HOV LANES ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I1)') '  NUMBER = ', NHOV_LANES(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_SIDE(IL) .LT. 0 .OR. HOV_SIDE(IL) .GT. 1) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LOCATION CODE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I1)') '  CODE = ', HOV_SIDE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_TYPE(IL) .LT. 0 .OR. HOV_TYPE(IL) .GT. 1) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID TYPE OF HOV FACILITY ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I1)') '  TYPE CODE = ', HOV_TYPE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        !IF(HOV_CODE(IL) .LT. 0 .OR. HOV_CODE(IL) .GT. 4) THEN
        !  CALL NEW_ERROR
        !  WRITE(MSGTEXT, '(A, 2I5)') 'INVALID HOV USAGE CODE ON LINK ', IUP, IDOWN
        !  CALL SENDTEXTMSG(M_ERROR)
        !  WRITE(MSGTEXT, '(A, I1)') '  LANE USE CODE = ', HOV_CODE(IL)
        !  CALL SENDTEXTMSG(M_ERROR)
        !ENDIF
        IF(HOV_BEGIN(IL) .LT. 0 .OR. HOV_BEGIN(IL) .GE. FLENGTH(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID HOV BEGINNING LOCATION ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5)') '  BEGINNING LOCATION = ', HOV_BEGIN(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_END(IL) .LT. 0 .OR. HOV_END(IL) .GT. FLENGTH(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID HOV END LOCATION ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5)') '  END LOCATION = ', HOV_END(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_END(IL) .LT. HOV_BEGIN(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID HOV BEGINNING OR END LOCATION ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5, A, I5)') '  BEGINNING LOCATION = ', HOV_BEGIN(IL), '  END LOCATION = ', HOV_END(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_PCT(IL) .LT. 0 .OR. HOV_PCT(IL) .GT. 1.0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID PERCENTAGE FOR USING HOV LANE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I3)') '  PERCENTAGE = ', HOV_PCT(IL) * 100
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(TRUCK_CODE(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE TRUCK BIAS/RESTRICTION CODE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I5)') '  CODE = ', TRUCK_CODE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ELSEIF(TRUCK_CODE(IL) .GT. 4) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID TRUCK BIAS/RESTRICTION CODE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I5)') '  CODE = ', TRUCK_CODE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(TRUCK_LANE(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE TRUCK LANE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I5)') '  LANE = ', TRUCK_LANE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ELSEIF(TRUCK_LANE(IL) .GT. FNUMLANES(IL)) THEN
        FOUND = .FALSE.
        DO IAUX = 1, N_AUXLANES
          IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
          IF(AUX_LANE_ID(IL, IAUX) .EQ. TRUCK_LANE(IL)) THEN
            FOUND = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT. FOUND) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID TRUCK LANE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5)') '  LANE = ', TRUCK_LANE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(TRUCK_DIR(IL) .LT. 0 .OR. TRUCK_DIR(IL) .GT. 1) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID TRUCK BIAS DIRECTION ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I5)') '  DIRECTION = ', TRUCK_DIR(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
          
      IF(OFFRAMP_LINK(IL) .EQ. 0) THEN
        IF(OFFRAMP_WARN_DISTANCE(IL) .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'OFFRAMP WARNING DISTANCE SPECIFIED BUT NO OFF-RAMP ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(OFFRAMP_SENDING_LANE(IL) .NE. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'OFFRAMP ALIGNMENT LANE SPECIFIED BUT NO OFF-RAMP ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I2)') '  ALIGNMENT LANE ', OFFRAMP_SENDING_LANE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_OFFRAMP_WARN_DISTANCE(IL) .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'HOV OFFRAMP WARNING DISTANCE SPECIFIED BUT NO OFF-RAMP ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ELSE
        IF(OFFRAMP_WARN_DISTANCE(IL) .LT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE OFFRAMP WARNING DISTANCE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  OFFRAMP WARNING DISTANCE = ', OFFRAMP_WARN_DISTANCE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_OFFRAMP_WARN_DISTANCE(IL) .LT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE HOV OFFRAMP WARNING DISTANCE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  HOV OFFRAMP WARNING DISTANCE = ', HOV_OFFRAMP_WARN_DISTANCE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(HOV_OFFRAMP_WARN_DISTANCE(IL) .LT. OFFRAMP_WARN_DISTANCE(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'HOV OFFRAMP WARNING DISTANCE IS LESS THAN WARNING DISTANCE FOR ALL VEHICLES ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  HOV OFFRAMP WARNING DISTANCE = ', HOV_OFFRAMP_WARN_DISTANCE(IL)
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  OFFRAMP WARNING DISTANCE = ', OFFRAMP_WARN_DISTANCE(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(OFFRAMP_SENDING_LANE(IL) .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'OFF-RAMP LANE ALIGNMENT NOT SPECIFIED ON LINK', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(DATASTATION_ID(IL) .NE. 0) THEN
        IF(DATASTATION(DATASTATION_ID(IL))%LOCATION .LT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE DATASTATION LOCATION ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  DATASTATION LOCATION = ', DATASTATION(DATASTATION_ID(IL))%LOCATION
          CALL SENDTEXTMSG(M_ERROR)
        ELSEIF(DATASTATION(DATASTATION_ID(IL))%LOCATION .GT. FLENGTH(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'DATASTATION LOCATION BEYOND END OF LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I6)') '  DATASTATION LOCATION = ', DATASTATION(DATASTATION_ID(IL))%LOCATION
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(ETL_WARN(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE EXCLUSIVE TRUCK LANE WARNING DISTANCE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I6)') '  EXCLUSIVE TRUCK LANE WARNING DISTANCE = ', ETL_WARN(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(ANTICIP_WARNING_SPEED(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE ANTICIPATORY LANE CHANGE SPEED ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I6)') '  ANTICIPATORY LANE CHANGE SPEED = ', ANTICIP_WARNING_SPEED(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(ANTICIP_WARNING_DISTANCE(IL) .LT. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE ANTICIPATORY LANE CHANGE DISTANCE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I6)') '  ANTICIPATORY LANE CHANGE DISTANCE = ', ANTICIP_WARNING_DISTANCE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(FCFMULT(IL) .LT. 0.01 .OR. FCFMULT(IL) .GT. 10.0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID CAR FOLLOWING MULTIPLIER ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, F5.2)') '  CAR FOLLOWING MULTIPLIER = ', FCFMULT(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDIF 
  ENDDO
  
  SHORTLINKS = .FALSE.
  DO IL = 1, N_FREEWAY_LINKS
    IF(FTHRU_LINK(IL) .NE. 0) THEN
      IF(NODE_TYPE(FDSN(FTHRU_LINK(IL))) .NE. NT_EXTERN) THEN
        TRAVEL = FFREEFLOWSPEED(IL) * FFSPEED_ADJ(10, I_FREEWAY) * TIMESTEP
        IF(TRAVEL .GT. FLENGTH(FTHRU_LINK(IL))) THEN
          SHORTLINKS = .TRUE.
          MSGTEXT = ''
          CALL SENDTEXTMSG(M_ERROR)
          USN = FUSN(FTHRU_LINK(IL))
          DSN = FDSN(FTHRU_LINK(IL))
          IF(USN .GT. 999) THEN
            W1 = 4
          ELSEIF(USN .GT. 99) THEN
            W1 = 3
          ELSEIF(USN .GT. 9) THEN
            W1 = 2
          ELSE
            W1 = 1
          ENDIF
          IF(DSN .GT. 999) THEN
            W2 = 4
          ELSEIF(DSN .GT. 99) THEN
            W2 = 3
          ELSEIF(DSN .GT. 9) THEN
            W2 = 2
          ELSE
            W2 = 1
          ENDIF
          WRITE(MSGTEXT, '(A)') '*** WARNING ***'
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A,I<W1>,A,I<W2>)') '  LINK MAY BE TOO SHORT: ', USN, '->', DSN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A,I5)') '  LINK LENGTH: ', FLENGTH(FTHRU_LINK(IL))
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A,I5)') '  MAXIMUM DISTANCE TRAVELED IN ONE TIME STEP: ', TRAVEL
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
  ENDDO
  IF(SHORTLINKS) THEN
    MSGTEXT = ''
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'ALL LINKS NEED TO BE AT LEAST AS LONG AS A VEHICLE CAN TRAVEL IN ONE TIME STEP'
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'WHEN APPROACHING THE LINK.'
    CALL SENDTEXTMSG(M_ERROR)
    MSGTEXT = ''
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'SHORT LINKS CAN CAUSE UNPREDICTABLE RESULTS INCLUDING FATAL ERRORS.'
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_FREEWAYDETECTORS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for freeway detectors.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE FREEWAY_DETECTORS
  USE FREEWAY_LINKS
  IMPLICIT NONE
  INTEGER :: I, IL, IUP, IDOWN
! ----------------------------------------------------------------------
  DO I = 1, N_FREEWAY_DETECTORS
    IL = FDETECTOR(I)%LINK
    IUP = FUSN(IL)
    IDOWN = FDSN(IL)
    IF(FDETECTOR(I)%LANE1 .GT. N_FREEWAY_LANES) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'DETECTOR LOCATED IN ILLEGAL LANE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I2)') '  LANE = ', FDETECTOR(I)%LANE1
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    IF(FDETECTOR(I)%LOCATION .LT. 0 .OR. FDETECTOR(I)%LOCATION .GT. FLENGTH(IL)) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LOCATION FOR DETECTOR ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, F5.1)') '  LOCATION = ', FDETECTOR(I)%LOCATION
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    !IF(FDETECTOR(I)%ZONE_LENGTH .LT. 0 .OR. FDETECTOR(I)%ZONE_LENGTH .GT. 50) THEN
    !  CALL NEW_ERROR
    !  WRITE(MSGTEXT, '(A, 2I5)') 'INVALID DETECTOR LENGTH ON LINK ', IUP, IDOWN
    !  CALL SENDTEXTMSG(M_ERROR)
    !  WRITE(MSGTEXT, '(A, F8.2)') '  DETECTOR LENGTH = ', FDETECTOR(I)%ZONE_LENGTH
    !  CALL SENDTEXTMSG(M_ERROR)
    !ENDIF
    IF(FDETECTOR(I)%TYPE_CODE .NE. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'UNSUPPORTED DETECTOR TYPE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1)') '  DETECTOR TYPE = ', FDETECTOR(I)%TYPE_CODE
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  RETURN
  END
  
! ==========================================================================================================
  SUBROUTINE CHECK_RAMPMETERS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for rampmeters.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE RAMP_METERS
  USE FREEWAY_DETECTORS
  USE NODE_TABLE
  IMPLICIT NONE
  INTEGER :: I, J, IDET
! ----------------------------------------------------------------------
  DO I = 1, NUMBER_OF_RAMPMETERS
    IF(RAMPMETERS(I)%DSN .LT. 0 .OR. NODE_TYPE(RAMPMETERS(I)%DSN) .NE. NT_INTERN) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'RAMPMETER IS NOT ALLOWED AT NODE ',  RAMPMETERS(I)%DSN
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(RAMPMETERS(I)%CONTROL .LT. 0 .OR. RAMPMETERS(I)%CONTROL .GT. 3) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'INVALID CONTROL TYPE FOR RAMPMETER AT NODE ',  RAMPMETERS(I)%DSN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4, A, I4)') '  CONTROL TYPE = ', RAMPMETERS(I)%CONTROL
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(RAMPMETERS(I)%ONSET .LT. 0 .OR. RAMPMETERS(I)%ONSET .GT. 6999) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'INVALID ONSET TIME FOR RAMPMETER AT NODE ',  RAMPMETERS(I)%DSN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') '  ONSET TIME = ', RAMPMETERS(I)%ONSET
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(RAMPMETERS(I)%CONTROL .EQ. 3) THEN
      IF(RAMPMETERS(I)%SPEED(1) .EQ. 0) THEN  
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I4)') 'INVALID SPEED DISTRIBUTION FOR RAMPMETER AT NODE ',  RAMPMETERS(I)%DSN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', 1, 'VALUE = ', 0
        CALL SENDTEXTMSG(M_ERROR)
      ELSE
        DO J = 1, 5
          IF(RAMPMETERS(I)%SPEED(J) .GT. RAMPMETERS(I)%SPEED(J+1)) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I4)') 'INVALID SPEED DISTRIBUTION FOR RAMPMETER AT NODE ',  RAMPMETERS(I)%DSN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1, A, F10.1)') '  ENTRY = ', I, 'VALUE = ', RAMPMETERS(I)%SPEED(J)
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDDO
      ENDIF
    ENDIF
    
    DO J = 1, 10
      IF(RAMPMETERS(I)%DETECTOR(J) .NE. 0) THEN
        IDET = RAMPMETERS(I)%DETECTOR(J)
        IF(FDETECTOR(IDET)%LINK .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I4)') 'DETECTOR NOT FOUND FOR RAMPMETER AT NODE ',  RAMPMETERS(I)%DSN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDDO
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_FREEWAY_INCIDENTS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for freeway incidents.
! ----------------------------------------------------------------------
  USE INCIDENTS
  USE FREEWAY_LINKS
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I, IL, ILN, IAUX
  LOGICAL :: FOUND
! ----------------------------------------------------------------------
  DO I = 1, NUMBER_OF_INCIDENTS
    IL = INCIDENT_LINK(I)
    DO ILN = 1, N_FREEWAY_LANES
      IF(INCIDENT_CODE(I, ILN) .LT. 0 .OR. INCIDENT_CODE(I, ILN) .GT. 2) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I4)') 'INVALID INCIDENT CODE FOR INCIDENT NUMBER ', I
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1, A, I1)') '  LANE = ', ILN, ' CODE = ', INCIDENT_CODE(I, ILN)
        CALL SENDTEXTMSG(M_ERROR)
      ELSEIF(INCIDENT_CODE(I, ILN) .GT. 0) THEN
        IF(ILN .GT. FNUMLANES(IL)) THEN
          FOUND = .FALSE.
          DO IAUX = 1, N_AUXLANES
            IF(AUX_LANE_ID(IL, IAUX) .EQ. 0) EXIT
            IF(AUX_LANE_ID(IL, IAUX) .EQ. ILN) THEN
              FOUND = .TRUE.
              EXIT
            ENDIF
          ENDDO
          IF(.NOT. FOUND) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I4)') 'INVALID LANE SPECIFIED FOR INCIDENT NUMBER ', I
            CALL SENDTEXTMSG(M_ERROR)
#ifdef TSIS_COMPATIBLE
            IF(ILN .EQ. 11) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 6
            ELSEIF(ILN .EQ. 12) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 7
            ELSEIF(ILN .EQ. 13) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 8
            ELSEIF(ILN .EQ. 16) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 9
            ELSEIF(ILN .EQ. 17) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 10
            ELSEIF(ILN .EQ. 18) THEN
              WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', 11
            ENDIF
            CALL SENDTEXTMSG(M_ERROR)
#else
            WRITE(MSGTEXT, '(A, I4)') ' LANE NUMBER = ', ILN
            CALL SENDTEXTMSG(M_ERROR)
#endif      
          ENDIF
        ENDIF
      ENDIF
    ENDDO
    IF(INCIDENT_BEGIN_POINT(I) .LT. 0 .OR. INCIDENT_BEGIN_POINT(I) .GT. FLENGTH(IL)) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'INVALID BEGINNING LOCATION FOR INCIDENT NUMBER ', I
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') ' BEGINNING LOCATION = ', INCIDENT_BEGIN_POINT(I)
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    IF(INCIDENT_END_POINT(I) - INCIDENT_BEGIN_POINT(I) .LE. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I4)') 'INVALID LENGTH FOR INCIDENT NUMBER ', I
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') ' LENGTH = ', INCIDENT_END_POINT(I) - INCIDENT_BEGIN_POINT(I)
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_NODES
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for street nodes.
! ----------------------------------------------------------------------
  USE STREET_NODES
  USE NODE_TABLE
  USE GLOBAL_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I
! ----------------------------------------------------------------------
  DO I = 1, MAX_NODE_NUMBER
    IF(IS_USED(I) .AND. NETCODE(I) .EQ. I_STREET) THEN
      IF(NACT(I) + NFTC(I) .EQ. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I4)') 'CONTROL NOT SPECIFIED FOR NODE ', I
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDIF
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_STREETLINKS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for street links.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE STREET_LINKS
  USE GLOBAL_DATA
  USE NODE_TABLE
  USE DRIVERS
  IMPLICIT NONE
  INTEGER :: IL, IUP, IDOWN, I, J, ICHAN, ILN, ISPEED, TOTAL, W1, W2, USN, DSN, TRAVEL
  REAL :: LMAX
  LOGICAL :: SHORTLINKS
! ----------------------------------------------------------------------
  DO IL = 1, N_STREET_LINKS
    IUP = SUSN(IL)
    IDOWN = SDSN(IL)
    
    IF(NODE_TYPE(IUP) .NE. NT_INTERN .AND. NODE_TYPE(IDOWN) .NE. NT_INTERN) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I4)') 'INVALID LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(NODE_TYPE(IUP) .EQ. NT_EXTERN .OR. NODE_TYPE(IDOWN) .EQ. NT_EXTERN) THEN
      IF(SLENGTH(IL) .NE. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'LENGTH SPECIFIED FOR ENTRY OR EXIT LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ELSE
      
      IF(SLENGTH(IL) .LT. 1) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I8)') 'INVALID LENGTH SPECIFIED FOR INTERNAL LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I15)') '  LENGTH = ', SLENGTH(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(NUMBER_LEFTPOCKETS(IL) .GT. 0) THEN
        DO ILN = LAST_FULL_LANE(IL) + 1, TOTAL_LANES(IL)
          IF(LANE_LENGTH(IL, ILN) .LT. 20 .OR. LANE_LENGTH(IL, ILN) .GT. SLENGTH(IL)) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LENGTH OF LEFT POCKET LANES ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, F5.2)') '  LENGTH = ', LANE_LENGTH(IL, ILN)
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDDO   
        LMAX = LANE_LENGTH(IL, LAST_FULL_LANE(IL) + 1)
        DO ILN = LAST_FULL_LANE(IL) + 1, TOTAL_LANES(IL)
          IF(LANE_LENGTH(IL, ILN) .GT. LMAX) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'UNREALISTIC LENGTH OF LEFT POCKET LANES ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A)') '  OUTER POCKET LANE IS LONGER THAN AN INNER POCKET LANE'
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
          LMAX = LANE_LENGTH(IL, ILN)
        ENDDO
        IF(LEFT_LINK(IL) .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'LEFT POCKET LANES EXIST, BUT NO LEFT TURN RECEIVING LINK ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(NUMBER_RIGHTPOCKETS(IL) .GT. 0) THEN
        DO ILN = 1, NUMBER_RIGHTPOCKETS(IL)
          IF(LANE_LENGTH(IL, ILN) .LT. 20 .OR. LANE_LENGTH(IL, ILN) .GT. SLENGTH(IL)) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LENGTH OF RIGHT POCKET LANES ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, F10.2)') '  LANE LENGTH = ', LANE_LENGTH(IL, ILN)
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I6)') '  LINK LENGTH = ', SLENGTH(IL)
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDDO
        LMAX = LANE_LENGTH(IL, NUMBER_RIGHTPOCKETS(IL))
        DO ILN = NUMBER_RIGHTPOCKETS(IL) - 1, 1, -1
          IF(LANE_LENGTH(IL, ILN) .GT. LMAX) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'UNREALISTIC LENGTH OF RIGHT POCKET LANES ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A)') '  OUTER POCKET LANE IS LONGER THAN AN INNER POCKET LANE'
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
          LMAX = LANE_LENGTH(IL, ILN)
        ENDDO
        IF(RIGHT_LINK(IL) .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'RIGHT POCKET LANES EXIST, BUT NO RIGHT TURN RECEIVING LINK ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(SGRADE(IL) .LT. -9 .OR. SGRADE(IL) .GT. 9) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE GRADE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  GRADE = ', SGRADE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(LINKTYPE_CODE(IL) .LT. 1 .OR. LINKTYPE_CODE(IL) .GT. 4) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID DISTRIBUTION CODE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  VALUE = ', LINKTYPE_CODE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      ISPEED = NINT(SFREEFLOWSPEED(IL) * FEET2MILES)
      IF(ISPEED .LT. 1 .OR. ISPEED .GT. 65) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'UNACCEPTABLE FREEFLOW SPEED ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I3)') '  FREEFLOW SPEED = ', ISPEED
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      DO I = 1, TOTAL_LANES(IL)
        IF(CHANNELIZATION(IL, I) .GT. 11) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID CHANNELIZATION CODE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I1, A, I3)') '  LANE = ', I, ' CODE = ', CHANNELIZATION(IL, I)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDDO
      
!Check for required receiving links and illogical channelization.
      
      DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
        ICHAN = CHANNELIZATION(IL, I)
        
        IF(ICHAN .EQ. 1) THEN
          IF(LEFT_LINK(IL) .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR LEFT TURN LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
            !All lanes to the left must be left only
            DO J = I, SNUMLANES(IL)
              IF(CHANNELIZATION(IL, J) .NE. 1) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'ILLOGICAL CHANNELIZATION FOR LEFT TURN LANE ON LINK ', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
                CALL SENDTEXTMSG(M_ERROR)
                EXIT
              ENDIF
            ENDDO
          ENDIF
          
        ELSEIF(ICHAN .EQ. 8) THEN
          IF(STHRU_LINK(IL) .EQ. 0 .AND. LEFT_LINK(IL) .EQ. 0 .AND. LEFT_DIAG_LINK(IL) .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR THRU+LEFT+DIAGONAL TURN LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
            !Lanes to the left must not allow thru
            DO J = I, SNUMLANES(IL)
              IF(CHANNELIZATION(IL, J) .EQ. 11) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'ILLOGICAL CHANNELIZATION FOR THRU+LEFT+DIAGONAL TURN LANE ON LINK ', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
                CALL SENDTEXTMSG(M_ERROR)
                EXIT
              ENDIF
            ENDDO
          ENDIF
          
        ELSEIF(ICHAN .EQ. 4) THEN
          IF(RIGHT_LINK(IL) .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR RIGHT TURN LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
            !All lanes to the right must be right only
            DO J = I, 1, -1
              IF(CHANNELIZATION(IL, J) .NE. 4) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'ILLOGICAL CHANNELIZATION FOR RIGHT TURN LANE ON LINK ', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
                CALL SENDTEXTMSG(M_ERROR)
                EXIT
              ENDIF
            ENDDO
          ENDIF
          
        ELSEIF(ICHAN .EQ. 7) THEN
          IF(STHRU_LINK(IL) .EQ. 0 .AND. RIGHT_LINK(IL) .EQ. 0 .AND. RIGHT_DIAG_LINK(IL) .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR THRU+RIGHT+DIAGONAL TURN LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
            !Lanes to the right must not allow thru
            DO J = I, 1, -1
              IF(CHANNELIZATION(IL, J) .EQ. 11) THEN
                CALL NEW_ERROR
                WRITE(MSGTEXT, '(A, 2I5)') 'ILLOGICAL CHANNELIZATION FOR RIGHT TURN LANE ON LINK ', IUP, IDOWN
                CALL SENDTEXTMSG(M_ERROR)
                WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
                CALL SENDTEXTMSG(M_ERROR)
                EXIT
              ENDIF
            ENDDO
          ENDIF
          
        ELSEIF(ICHAN .EQ. 10) THEN
          IF(LEFT_DIAG_LINK(IL) .EQ. 0 .AND. RIGHT_DIAG_LINK(IL) .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR DIAGONAL LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
          
        ELSEIF(ICHAN .EQ. 11) THEN
          IF(STHRU_LINK(IL) .EQ. 0 .AND. NODE_TYPE(SDSN(IL)) .EQ. NT_INTERN) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO RECEIVING LINK FOR THRU LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  LANE = ', I
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF
      ENDDO
      
!Check that no more than one lane is channelized as 9.      
      
      ILN = 0
      DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
        IF(CHANNELIZATION(IL, I) .EQ. 9) ILN = ILN + 1
      ENDDO
      IF(ILN .GT. 1) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'MORE THAN ONE LANE CHANNELIZED WITH CODE 9 ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF

      IF(QDISCHARGE_HDWY(IL) .LT. 1.4 .OR. QDISCHARGE_HDWY(IL) .GT. 9.9) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID MEAN QUEUE DISCHARGE HEADWAY ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, F5.1)') '  VALUE = ', QDISCHARGE_HDWY(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(PED_CODE(IL) .LT. 0 .OR. PED_CODE(IL) .GT. 3) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'INVALID PEDESTRIAN CODE ON LINK ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I1)') '  VALUE = ', PED_CODE(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(STHRU_LINK(IL) .NE. 0) THEN
        IF(NODE_TYPE(SDSN(STHRU_LINK(IL))) .NE. NT_EXTERN) THEN
          IF(SALIGNMENT_LANE(IL) .LT. 0 .OR. SALIGNMENT_LANE(IL) .GT. LAST_FULL_LANE(IL)) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'INVALID ALIGNMENT LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  VALUE = ', SALIGNMENT_LANE(IL)
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF      
          IF(STHRU_ALIGNMENT_LANE(IL) .LT. 0 .OR. STHRU_ALIGNMENT_LANE(IL) .GT. LAST_FULL_LANE(STHRU_LINK(IL))) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'INVALID THRU ALIGNMENT LANE ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I1)') '  VALUE = ', STHRU_ALIGNMENT_LANE(IL)
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF
      ENDIF
      
      IF(LEFT_LINK(IL) .EQ. 0) THEN
        TOTAL = COND_LEFTPCT(IL, 1) + COND_THRUPCT(IL, 1) + COND_RIGHTPCT(IL, 1) + COND_LDIAGPCT(IL, 1) + COND_RDIAGPCT(IL, 1)
        IF(TOTAL .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO LEFT RECEIVER FOR SPECIFIED CONDITIONAL TURN PERCENTAGE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(STHRU_LINK(IL) .EQ. 0) THEN
        TOTAL = COND_LEFTPCT(IL, 2) + COND_THRUPCT(IL, 2) + COND_RIGHTPCT(IL, 2) + COND_LDIAGPCT(IL, 2) + COND_RDIAGPCT(IL, 2)
        IF(TOTAL .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO THRU RECEIVER FOR SPECIFIED CONDITIONAL TURN PERCENTAGE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(RIGHT_LINK(IL) .EQ. 0) THEN
        TOTAL = COND_LEFTPCT(IL, 3) + COND_THRUPCT(IL, 3) + COND_RIGHTPCT(IL, 3) + COND_LDIAGPCT(IL, 3) + COND_RDIAGPCT(IL, 3)
        IF(TOTAL .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO RIGHT RECEIVER FOR SPECIFIED CONDITIONAL TURN PERCENTAGE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(LEFT_DIAG_LINK(IL) .EQ. 0) THEN
        TOTAL = COND_LEFTPCT(IL, 4) + COND_THRUPCT(IL, 4) + COND_RIGHTPCT(IL, 4) + COND_LDIAGPCT(IL, 4) + COND_RDIAGPCT(IL, 4)
        IF(TOTAL .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO LEFT DIAGONAL RECEIVER FOR SPECIFIED CONDITIONAL TURN PERCENTAGE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(RIGHT_DIAG_LINK(IL) .EQ. 0) THEN
        TOTAL = COND_LEFTPCT(IL, 5) + COND_THRUPCT(IL, 5) + COND_RIGHTPCT(IL, 5) + COND_LDIAGPCT(IL, 5) + COND_RDIAGPCT(IL, 5)
        IF(TOTAL .GT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO RIGHT DIAGONAL RECEIVER FOR SPECIFIED CONDITIONAL TURN PERCENTAGE ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      
      IF(STE_FREQ(IL) .NE. 0) THEN
        IF(STE_DURATION(IL) .LE. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID MEAN DURATION OF SHORT TERM EVENTS ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, 2I5)') '  MEAN DURATION ', STE_DURATION(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        IF(STE_FREQ(IL) .LT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'INVALID MEAN FREQUENCY OF SHORT TERM EVENTS ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, 2I5)') '  MEAN FREQUENCY ', STE_FREQ(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ELSEIF(STE_FREQ(IL) .GT. 3600 / STE_DURATION(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'OVERLAPPING SHORT TERM EVENTS ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5, A, I5)') '  MEAN DURATION = ', STE_DURATION(IL), ' MEAN FREQUENCY = ', STE_FREQ(IL)
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I5)') '  FOR THE SPECIFIED MEAN DURATION THE MEAN FREQUENCY SHOULD NOT EXCEED ', &
                                       3600 / STE_DURATION(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
    
    IF(NODE_TYPE(SDSN(IL)) .NE. NT_EXTERN) THEN
      IF(LEFT_PERCENT(IL) + STHRU_PERCENT(IL) + RIGHT_PERCENT(IL) + LDIAG_PERCENT(IL) + RDIAG_PERCENT(IL) .EQ. 0) THEN
        IF(ROUNDABOUT_ID(IL) .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO TURN PERCENTAGES ENTERED FOR LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
  ENDDO
  
  SHORTLINKS = .FALSE.
  DO IL = 1, N_STREET_LINKS
    IF(STHRU_LINK(IL) .NE. 0) THEN
      IF(NODE_TYPE(SDSN(STHRU_LINK(IL))) .NE. NT_EXTERN) THEN
        IF(SIGNAL_CODE(IL) .NE. S_STOP) THEN
          TRAVEL = SFREEFLOWSPEED(IL) * FFSPEED_ADJ(10, I_STREET) * TIMESTEP
          IF(TRAVEL .GT. SLENGTH(STHRU_LINK(IL))) THEN
            SHORTLINKS = .TRUE.
            MSGTEXT = ''
            CALL SENDTEXTMSG(M_ERROR)
            USN = SUSN(STHRU_LINK(IL))
            DSN = SDSN(STHRU_LINK(IL))
            IF(USN .GT. 9999) THEN
              W1 = 5
            ELSEIF(USN .GT. 999) THEN
              W1 = 4
            ELSEIF(USN .GT. 99) THEN
              W1 = 3
            ELSEIF(USN .GT. 9) THEN
              W1 = 2
            ELSE
              W1 = 1
            ENDIF
            IF(DSN .GT. 9999) THEN
              W2 = 5
            ELSEIF(DSN .GT. 999) THEN
              W2 = 4
            ELSEIF(DSN .GT. 99) THEN
              W2 = 3
            ELSEIF(DSN .GT. 9) THEN
              W2 = 2
            ELSE
              W2 = 1
            ENDIF
            WRITE(MSGTEXT, '(A)') '*** WARNING ***'
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A,I<W1>,A,I<W2>)') '  LINK MAY BE TOO SHORT: ', USN, '->', DSN
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A,I5)') '  LINK LENGTH: ', SLENGTH(STHRU_LINK(IL))
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A,I5)') '  MAXIMUM DISTANCE TRAVELED IN ONE TIME STEP: ', TRAVEL
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF
      ENDIF
    ENDIF
  ENDDO
  IF(SHORTLINKS) THEN
    MSGTEXT = ''
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'ALL LINKS NEED TO BE AT LEAST AS LONG AS A VEHICLE CAN TRAVEL IN ONE TIME STEP'
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'WHEN APPROACHING THE LINK.'
    CALL SENDTEXTMSG(M_ERROR)
    MSGTEXT = ''
    CALL SENDTEXTMSG(M_ERROR)
    WRITE(MSGTEXT, '(A)') 'SHORT LINKS CAN CAUSE UNPREDICTABLE RESULTS INCLUDING FATAL ERRORS.'
    CALL SENDTEXTMSG(M_ERROR)
  ENDIF
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_EXIT_PERCENTAGES
! ----------------------------------------------------------------------
! --- Check the validity of all exit percentage inputs for freeway links.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE FREEWAY_LINKS
  USE NODE_TABLE
  IMPLICIT NONE
  INTEGER :: IL, IUP, IDOWN
! ----------------------------------------------------------------------
  DO IL = 1, N_FREEWAY_LINKS
    IUP = FUSN(IL)
    IDOWN = FDSN(IL)
    IF(NODE_TYPE(IUP) .EQ. NT_EXTERN .OR. NODE_TYPE(IDOWN) .EQ. NT_EXTERN) CYCLE
    IF(OFFRAMP_LINK(IL) .EQ. 0) THEN
      IF(FTHRU_PERCENT(IL) .LT. 100) THEN 
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'EXIT PERCENTAGE SPECIFIED ON LINK WITH NO OFF-RAMP ', IUP, IDOWN
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ELSEIF(FTHRU_PERCENT(IL) .LT. 0 .OR. FTHRU_PERCENT(IL) .GT. 100) THEN 
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'INVALID EXIT PERCENTAGE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') '  EXIT PERCENTAGE  = ', 100 - FTHRU_PERCENT(IL)
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_TURN_PERCENTAGES
! ----------------------------------------------------------------------
! --- Check the validity of all turn percentage inputs for street links.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE STREET_LINKS
  USE NODE_TABLE
  IMPLICIT NONE
  INTEGER :: IL, IUP, IDOWN, I, ICHAN, ILN
! ----------------------------------------------------------------------
  DO IL = 1, N_STREET_LINKS
    IUP = SUSN(IL)
    IDOWN = SDSN(IL)
    IF(NODE_TYPE(IUP) .EQ. NT_EXTERN .OR. NODE_TYPE(IDOWN) .EQ. NT_EXTERN) CYCLE
    
    !TOTAL = LEFT_PERCENT(IL) + STHRU_PERCENT(IL) + RIGHT_PERCENT(IL) + DIAG_PERCENT(IL)
    !IF(TOTAL .NE. 100) THEN
    !  CALL NEW_ERROR
    !  WRITE(MSGTEXT, '(A, 2I5)') 'TURN PERCENTAGES DO NOT EQUAL 100% ON LINK ', IUP, IDOWN
    !  CALL SENDTEXTMSG(M_ERROR)
    !  WRITE(MSGTEXT, '(A, I4)') '  LEFT TURN PERCENTAGE  = ', LEFT_PERCENT(IL)
    !  CALL SENDTEXTMSG(M_ERROR)
    !  WRITE(MSGTEXT, '(A, I4)') '  THRU TURN PERCENTAGE  = ', STHRU_PERCENT(IL)
    !  CALL SENDTEXTMSG(M_ERROR)
    !  WRITE(MSGTEXT, '(A, I4)') '  RIGHT TURN PERCENTAGE = ', RIGHT_PERCENT(IL)
    !  CALL SENDTEXTMSG(M_ERROR)
    !  WRITE(MSGTEXT, '(A, I4)') '  DIAG TURN PERCENTAGE  = ', DIAG_PERCENT(IL)
    !  CALL SENDTEXTMSG(M_ERROR)
    !ENDIF

!Check that at least one lane is available for each specified turn movement.
      
    IF(LEFT_PERCENT(IL) .NE. 0) THEN
      IF(NUMBER_LEFTPOCKETS(IL) .EQ. 0) THEN
        ILN = 0
        IF(LEFT_LINK(IL) .NE. 0) THEN
          DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
            ICHAN = CHANNELIZATION(IL, I)
            IF(ICHAN .EQ. 0 .OR. ICHAN .EQ. 1 .OR. ICHAN .EQ. 8 .OR. ICHAN .EQ. 9) THEN
              ILN = ILN + 1
              EXIT
            ENDIF
          ENDDO
          IF(ILN .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO LANE CHANNELIZED FOR SPECIFIED LEFT TURNS ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF
      ENDIF
    ENDIF
      
    IF(STHRU_PERCENT(IL) .NE. 0 .AND. NODE_TYPE(SDSN(IL)) .EQ. NT_INTERN) THEN
      ILN = 0
      IF(STHRU_LINK(IL) .NE. 0) THEN
        DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
          ICHAN = CHANNELIZATION(IL, I)
          IF(ICHAN .EQ. 0 .OR. ICHAN .EQ. 11 .OR. ICHAN .EQ. 7 .OR. ICHAN .EQ. 8 .OR. ICHAN .EQ. 9) THEN
            ILN = ILN + 1
            EXIT
          ENDIF
        ENDDO
        IF(ILN .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO LANE CHANNELIZED FOR SPECIFIED THRU MOVEMENT ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
      
    IF(RIGHT_PERCENT(IL) .NE. 0) THEN
      IF(NUMBER_RIGHTPOCKETS(IL) .EQ. 0) THEN
        ILN = 0
        IF(RIGHT_LINK(IL) .NE. 0) THEN
          DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
            ICHAN = CHANNELIZATION(IL, I)
            IF(ICHAN .EQ. 0 .OR. ICHAN .EQ. 4 .OR. ICHAN .EQ. 7 .OR. ICHAN .EQ. 9) THEN
              ILN = ILN + 1
              EXIT
            ENDIF
          ENDDO
          IF(ILN .EQ. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, 2I5)') 'NO LANE CHANNELIZED FOR SPECIFIED RIGHT TURNS ON LINK ', IUP, IDOWN
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF
      ENDIF
    ENDIF
      
    IF(LDIAG_PERCENT(IL) .NE. 0) THEN
      ILN = 0
      IF(LEFT_DIAG_LINK(IL) .NE. 0) THEN
        DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
          ICHAN = CHANNELIZATION(IL, I)
          IF(ICHAN .EQ. 0 .OR. ICHAN .EQ. 10 .OR. ICHAN .EQ. 8 .OR. ICHAN .EQ. 9) THEN
            ILN = ILN + 1
            EXIT
          ENDIF
        ENDDO
        IF(ILN .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO LANE CHANNELIZED FOR SPECIFIED LEFT DIAGONAL MOVEMENT ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF
    
    IF(RDIAG_PERCENT(IL) .NE. 0) THEN
      ILN = 0
      IF(RIGHT_DIAG_LINK(IL) .NE. 0) THEN
        DO I = FIRST_FULL_LANE(IL), LAST_FULL_LANE(IL)
          ICHAN = CHANNELIZATION(IL, I)
          IF(ICHAN .EQ. 0 .OR. ICHAN .EQ. 10 .OR. ICHAN .EQ. 7 .OR. ICHAN .EQ. 9) THEN
            ILN = ILN + 1
            EXIT
          ENDIF
        ENDDO
        IF(ILN .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'NO LANE CHANNELIZED FOR SPECIFIED RIGHT DIAGONAL MOVEMENT ON LINK ', IUP, IDOWN
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
    ENDIF

  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_STREETDETECTORS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for street detectors.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE STREET_DETECTORS
  USE STREET_LINKS
  IMPLICIT NONE
  INTEGER :: I, IL, IUP, IDOWN
  LOGICAL :: ERROR
! ----------------------------------------------------------------------
  DO I = 1, N_STREET_DETECTORS
    IL = SDETECTOR(I)%LINK
    IUP = SUSN(IL)
    IDOWN = SDSN(IL)
    ERROR = (SDETECTOR(I)%LANE1 .LT. 0 .OR. SDETECTOR(I)%LANE1 .GT. N_STREET_LANES) &
       .AND. SDETECTOR(I)%LANE1 .NE. 100 .AND. SDETECTOR(I)%LANE1 .NE. 200
    IF(ERROR) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'DETECTOR LOCATED IN ILLEGAL LANE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I3)') '  LANE = ', SDETECTOR(I)%LANE1
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    ERROR = (SDETECTOR(I)%LANE1 .LT. 0 .OR. SDETECTOR(I)%LANE1 .GT. N_STREET_LANES) &
       .AND. SDETECTOR(I)%LANE1 .NE. 100 .AND. SDETECTOR(I)%LANE1 .NE. 200
    IF(ERROR) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'DETECTOR LOCATED IN ILLEGAL LANE ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I3)') '  LANE = ', SDETECTOR(I)%LANE2
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    IF(SDETECTOR(I)%LOCATION .LT. 0 .OR. SDETECTOR(I)%LOCATION .GT. SLENGTH(IL)) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'INVALID LOCATION FOR DETECTOR ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I5)') '  LOCATION = ', SDETECTOR(I)%LOCATION
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    IF(SDETECTOR(I)%STATION_ID .LT. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'NEGATIVE DETECTOR STATION ID ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I1)') '  STATION ID= ', SDETECTOR(I)%STATION_ID
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    IF(SDETECTOR(I)%ZONE_LENGTH .LT. 0 .OR. SDETECTOR(I)%ZONE_LENGTH .GT. 99.9) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, 2I5)') 'INVALID DETECTOR LENGTH ON LINK ', IUP, IDOWN
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, F8.1, A)') '  DETECTOR LENGTH = ', SDETECTOR(I)%ZONE_LENGTH, ' FEET'
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, F8.1, A)') '  MAXIMUM ALLOWED DETECTOR LENGTH = ', 99.9, ' FEET'
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  RETURN
  END
  
! ==========================================================================================================
  SUBROUTINE CHECK_AC_SIGNALS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for AC signals.
! ----------------------------------------------------------------------
  USE ACTUATED_CONTROLLERS
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: IACT, PHASE
! ----------------------------------------------------------------------
  DO IACT = 1, NUMBER_OF_ACS
    DO PHASE = 1, 8
      IF(AC_SIGNALS(IACT)%GUI_DEFAULT_EXTENSION_TIMES(PHASE) .GT. 9.9) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I5)') 'INVALID EXTENSION TIME FOR THE ACTUATED SIGNAL AT NODE ', AC_SIGNALS(IACT)%NODE(1)
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I5, A, F5.1)') '  PHASE =  ', PHASE, ' , EXTENSION TIME = ', AC_SIGNALS(IACT)%GUI_DEFAULT_EXTENSION_TIMES(PHASE)
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A)') '  MAXIMUM EXTENSION TIME IS 9.9 SECONDS'
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDDO
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_FTC_SIGNALS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for FTC signals.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE TIMED_CONTROLLERS
  IMPLICIT NONE
  INTEGER :: ISIG, NODE, INT, IAP
! ----------------------------------------------------------------------
  DO ISIG = 1, NUMBER_OF_FTCS
    NODE = FTC_SIGNALS(ISIG)%NODE
    IF(SUM(FTC_SIGNALS(ISIG)%SIGNAL_CODE(1:5, 1:12)) .EQ. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'CONTROL CODES NOT SPECIFIED FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(FTC_SIGNALS(ISIG)%OFFSET .LT. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'NEGATIVE OFFSET FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') '  OFFSET = ', FTC_SIGNALS(ISIG)%OFFSET
      CALL SENDTEXTMSG(M_ERROR)
      
    ELSEIF(FTC_SIGNALS(ISIG)%OFFSET .GT. FTC_SIGNALS(ISIG)%CYCLE_LENGTH) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'OFFSET EXCEEDS CYCLE LENGTH FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4, A, I4)') '  OFFSET = ', FTC_SIGNALS(ISIG)%OFFSET,&
                                       '  CYCLE LENGTH = ', FTC_SIGNALS(ISIG)%CYCLE_LENGTH
      CALL SENDTEXTMSG(M_ERROR)
    ENDIF
    
    IF(FTC_SIGNALS(ISIG)%ACTIVE_INTERVALS .LT. 1) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'NO INTERVALS SPECIFIED FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
      CALL SENDTEXTMSG(M_ERROR)
      WRITE(MSGTEXT, '(A, I4)') '  OFFSET = ', FTC_SIGNALS(ISIG)%OFFSET
      CALL SENDTEXTMSG(M_ERROR)
    ELSEIF(FTC_SIGNALS(ISIG)%ACTIVE_INTERVALS .GT. 1) THEN
      DO INT = 1, FTC_SIGNALS(ISIG)%ACTIVE_INTERVALS
        IF(FTC_SIGNALS(ISIG)%DURATION(INT) .LT. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'NEGATIVE DURATION FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4, A, I4)') '  DURATION = ', FTC_SIGNALS(ISIG)%DURATION(INT), ' INTERVAL = ', INT
          CALL SENDTEXTMSG(M_ERROR)
        ELSEIF(FTC_SIGNALS(ISIG)%DURATION(INT) .GT. 120) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'DURATION EXCEEDS 120 SECONDS FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4, A, I4)') '  DURATION = ', FTC_SIGNALS(ISIG)%DURATION(INT), ' INTERVAL = ', INT
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
        DO IAP = 1, FTC_SIGNALS(ISIG)%APPROACHES
          IF(FTC_SIGNALS(ISIG)%SIGNAL_CODE(IAP, INT) .LT. 0 .OR. FTC_SIGNALS(ISIG)%SIGNAL_CODE(IAP, INT) .GT. 9) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I5)') 'INVALID CONTROL CODE FOR FIXED TIME CONTROL SIGNAL AT NODE ', NODE
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(6(A, I4))') '  CONTROL CODE = ', FTC_SIGNALS(ISIG)%SIGNAL_CODE(IAP, INT), &
                                             '  INTERVAL = ', INT, ' APPROACH NUMBER = ', IAP
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_BUSSTATIONS
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for bus stations.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE BUS_STATION_DATA
  USE STREET_LINKS
  USE VEHICLE_TYPES
  USE NODE_TABLE
  IMPLICIT NONE
  INTEGER :: I, IL, ITYP, BUSLEN
! ----------------------------------------------------------------------
  IF(ALLOCATED(BUS_STATION_LIST)) THEN
    BUSLEN = 0
    DO ITYP = 1, NTYPES
      IF(FLT_FREEWAY_BUS(ITYP) .NE. 0) THEN
        BUSLEN = MAX(BUSLEN, VTLENGTH(ITYP))
      ENDIF
    ENDDO
  
    DO I = 1, NUMBER_OF_BUSSTATIONS
      IF(BUS_STATION_LIST(I)%LINK .NE. 0) THEN
        IL = BUS_STATION_LIST(I)%LINK
      
        IF(NODE_TYPE(SUSN(IL)) .EQ. NT_EXTERN .OR. NODE_TYPE(SDSN(IL)) .EQ. NT_EXTERN) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5, A)') 'BUS STATION ', I, ' SPECIFIED ON ENTRY OR EXIT LINK'
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, 2I5)') '  LINK = ', SUSN(IL), SDSN(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      
        IF(BUS_STATION_LIST(I)%BLOCK_CODE .LT. 0 .OR. BUS_STATION_LIST(I)%BLOCK_CODE .GT. 1) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'INVALID BLOCK CODE FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  BLOCK CODE = ', BUS_STATION_LIST(I)%BLOCK_CODE
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      
        IF(BUS_STATION_LIST(I)%TYPE_CODE .LT. 1 .OR. BUS_STATION_LIST(I)%TYPE_CODE .GT. 6) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'INVALID TYPE FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  TYPE CODE = ', BUS_STATION_LIST(I)%TYPE_CODE
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      
        IF(BUS_STATION_LIST(I)%CAPACITY .LT. 1 .OR. BUS_STATION_LIST(I)%CAPACITY .GT. 6) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'INVALID CAPACITY FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  CAPACITY = ', BUS_STATION_LIST(I)%CAPACITY
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      
        IF(BUS_STATION_LIST(I)%LOCATION .LT. 0 .OR. BUS_STATION_LIST(I)%LOCATION .GT. SLENGTH(IL)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'INVALID LOCATION FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  DISTANCE FROM STOPBAR = ', SLENGTH(IL) - BUS_STATION_LIST(I)%LOCATION
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      
        IF(UP_INT_WIDTH(IL) .GT. 0.) THEN
          IF(BUS_STATION_LIST(I)%LOCATION - BUS_STATION_LIST(I)%CAPACITY * BUSLEN .LT. UP_INT_WIDTH(IL)) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I2, A)') 'BUS STATION ', I, ' EXTENDS INTO THE UPSTREAM INTERSECTION'
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I5)') '  FRONT LOCATION = ', BUS_STATION_LIST(I)%LOCATION
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I4)') '  REQUIRED LENGTH OF STATION = ', BUS_STATION_LIST(I)%CAPACITY * BUSLEN
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ELSE        
          IF(BUS_STATION_LIST(I)%LOCATION - BUS_STATION_LIST(I)%CAPACITY * BUSLEN .LT. 0) THEN
            CALL NEW_ERROR
            WRITE(MSGTEXT, '(A, I2, A)') 'BUS STATION ', I, ' EXTENDS BEYOND UPSTREAM NODE'
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I5)') '  FRONT LOCATION = ', BUS_STATION_LIST(I)%LOCATION
            CALL SENDTEXTMSG(M_ERROR)
            WRITE(MSGTEXT, '(A, I4)') '  REQUIRED LENGTH OF STATION = ', BUS_STATION_LIST(I)%CAPACITY * BUSLEN
            CALL SENDTEXTMSG(M_ERROR)
          ENDIF
        ENDIF

        IF(BUS_STATION_LIST(I)%DWELL .LT. 1 .OR. BUS_STATION_LIST(I)%DWELL .GT. 500) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I2, A)') 'INVALID MEAN DWELL TIME FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  MEAN DWELL TIME = ', BUS_STATION_LIST(I)%DWELL
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF

        IF(BUS_STATION_LIST(I)%BYPASS_PCT .LT. 0 .OR. BUS_STATION_LIST(I)%BYPASS_PCT .GT. 1.0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I2, A)') 'INVALID BYPASS PERCENTAGE FOR BUS STATION ', I
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  BYPASS PERCENTAGE = ', INT(BUS_STATION_LIST(I)%BYPASS_PCT * 100)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF

      ENDIF
    ENDDO
  ENDIF
  RETURN
  END
  
! ==========================================================================================================
  SUBROUTINE CHECK_PARKING_ZONES
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for parking zones.
! ----------------------------------------------------------------------
  USE PARKING
  USE STREET_LINKS
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I, IL, ILN
! ----------------------------------------------------------------------
  DO I = 1, NUMBER_OF_PARKING_ZONES
    IL = PARKING_ZONE_LINK(I)
    IF(PARK_LEFT_START(I) .NE. 0) THEN
      IF(PARK_LEFT_START(I) .LT. UP_INT_WIDTH(IL)) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'LEFT PARKING ZONE EXTENDS INTO UPSTREAM INTERSECTION ON LINK ', SUSN(IL), SDSN(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      IF(NUMBER_LEFTPOCKETS(IL) .GT. 0) THEN 
        ILN = LAST_FULL_LANE(IL) + 1
        IF(PARK_LEFT_START(I) + PARK_LEFT_LEN(I) .GT. SLENGTH(IL) - LANE_LENGTH(IL, ILN)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'LEFT PARKING ZONE EXTENDS INTO TURN POCKET ON LINK ', SUSN(IL), SDSN(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      IF(PARK_LEFT_START(I) + PARK_LEFT_LEN(I) .GT. SLENGTH(IL)) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'LEFT PARKING ZONE EXTENDS BEYOND END OF LINK ', SUSN(IL), SDSN(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDIF
    IF(PARK_RIGHT_START(I) .NE. 0) THEN
      IF(PARK_RIGHT_START(I) .LT. UP_INT_WIDTH(IL)) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'RIGHT PARKING ZONE EXTENDS INTO UPSTREAM INTERSECTION ON LINK ', SUSN(IL), SDSN(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      IF(NUMBER_RIGHTPOCKETS(IL) .GT. 0) THEN  
        ILN = NUMBER_RIGHTPOCKETS(IL)
        IF(PARK_RIGHT_START(I) + PARK_RIGHT_LEN(I) .GT. SLENGTH(IL) - LANE_LENGTH(IL, ILN)) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, 2I5)') 'RIGHT PARKING ZONE EXTENDS INTO TURN POCKET ON LINK ', SUSN(IL), SDSN(IL)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDIF
      IF(PARK_RIGHT_START(I) + PARK_RIGHT_LEN(I) .GT. SLENGTH(IL)) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, 2I5)') 'RIGHT PARKING ZONE EXTENDS BEYOND END OF LINK ', SUSN(IL), SDSN(IL)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDIF
  ENDDO
  RETURN
  END
  

! ==========================================================================================================
  SUBROUTINE CHECK_BUSROUTES
! ----------------------------------------------------------------------
! --- Check the validity of all inputs for bus routes.
! ----------------------------------------------------------------------
  USE SIMPARAMS
  USE TEXT
  USE BUS_ROUTE_DATA
  USE BUS_STATION_DATA
  USE FREEWAY_LINKS
  USE STREET_LINKS
  IMPLICIT NONE
  INTEGER :: IBR, J, NERR, IL, I1, I2, ISTAT
! ----------------------------------------------------------------------
  DO IBR = 1, NUMBER_OF_ROUTES   
    IF(BUSR_HDWY(IBR) .NE. 0 .AND. BUSR_NNODES(IBR) .EQ. 0) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'NODES NOT SPECIFIED FOR BUS ROUTE ', IBR
      CALL SENDTEXTMSG(M_ERROR)
    ELSEIF(BUSR_NNODES(IBR) .NE. 0) THEN
      
      IF(BUSR_HDWY(IBR) .LT. 1 .OR. BUSR_HDWY(IBR) .GT. 9999) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I5)') 'INVALID HEADWAY SPECIFIED FOR BUS ROUTE ', IBR
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I4)') '  HEADWAY = ', BUSR_HDWY(IBR)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      IF(BUSR_OFFSET(IBR) .LT. 0 .OR. BUSR_OFFSET(IBR) .GT. 9999) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I5)') 'INVALID OFFSET SPECIFIED FOR BUS ROUTE ', IBR
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I4)') '  HEADWAY = ', BUSR_OFFSET(IBR)
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
      
      DO J = 1, BUSR_NNODES(IBR)
        IF(BUSR_ROUTE_NODES(IBR, J) .LT. 0 .OR. BUSR_ROUTE_NODES(IBR, J) .GT. MAX_NODE_NUMBER+1000) THEN
          NERR = 1
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'INVALID NODE SPECIFIED FOR BUS ROUTE ', IBR
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, I4)') '  NODE = ', BUSR_ROUTE_NODES(IBR, J)
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDDO
    ENDIF
    
    NERR = 0
    IF(NERR .EQ. 0) THEN
      DO J = 1, BUSR_NNODES(IBR) - 1
        I1 = BUSR_ROUTE_NODES(IBR, J)
        I2 = BUSR_ROUTE_NODES(IBR, J+1)
        CALL FIND_FREEWAY_LINK(I1, I2, IL)
        IF(IL .EQ. 0) CALL FIND_STREET_LINK(I1, I2, IL)
        IF(IL .EQ. 0) THEN
          CALL NEW_ERROR
          WRITE(MSGTEXT, '(A, I5)') 'LINK NOT FOUND IN BUS ROUTE ', IBR
          CALL SENDTEXTMSG(M_ERROR)
          WRITE(MSGTEXT, '(A, 2I5)') '  LINK = ', I1, I2
          CALL SENDTEXTMSG(M_ERROR)
        ENDIF
      ENDDO
    ENDIF
    
    DO J = 1, 34
      IF(BUSR_STATIONLIST(IBR, J) .EQ. 0) EXIT
      ISTAT = BUSR_STATIONLIST(IBR, J) 
      IF(BUS_STATION_LIST(ISTAT)%LINK .EQ. 0) THEN
        CALL NEW_ERROR
        WRITE(MSGTEXT, '(A, I5)') 'UNDEFINED STATION REFERENCED IN BUS ROUTE ', IBR
        CALL SENDTEXTMSG(M_ERROR)
        WRITE(MSGTEXT, '(A, I4)') '  STATION = ', ISTAT
        CALL SENDTEXTMSG(M_ERROR)
      ENDIF
    ENDDO
  ENDDO
  RETURN
  END

! ==========================================================================================================
  SUBROUTINE CHECK_NODE_COORDINATES
! ----------------------------------------------------------------------
! --- Check that coordinates have been entered for all internal nodes.
! ----------------------------------------------------------------------
  USE NODE_TABLE
  USE SIMPARAMS
  USE GLOBAL_DATA
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I
! ----------------------------------------------------------------------
  DO I = 1, MAX_NODE_NUMBER
    IF(IS_USED(I) .AND. .NOT. IS_DEFINED(I)) THEN
      CALL NEW_ERROR
      WRITE(MSGTEXT, '(A, I5)') 'COORDINATES UNDEFINED FOR NODE ', I
      CALL SENDTEXTMSG(M_ERROR)
    !ELSEIF(IS_DEFINED(I) .AND. .NOT. IS_USED(I)) THEN
    !  CALL NEW_ERROR
    !  WRITE(MSGTEXT, '(A, I5)') 'COORDINATES SPECIFIED FOR UNUSED NODE ', I
    !  CALL SENDTEXTMSG(M_ERROR)
    ENDIF
  ENDDO
  RETURN
  END
  
! ==========================================================================================================
  SUBROUTINE NEW_ERROR
  USE TEXT
  USE SIMPARAMS
  IMPLICIT NONE
  INTEGER :: W
! ----------------------------------------------------------------------
  ERROR_COUNT = ERROR_COUNT + 1
  IF(ERROR_COUNT .LT. 10) THEN
    W = 1
  ELSEIF(ERROR_COUNT .LT. 100) THEN
    W = 2
  ELSE
    W = 3
  ENDIF
  MSGTEXT = ''
  CALL SENDTEXTMSG(M_INFO)
  WRITE(MSGTEXT, '(A, I<W>)') 'ERROR NUMBER: ', ERROR_COUNT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END
  

!! ==========================================================================================================
!  SUBROUTINE CHECK_INTERSECTION_DATA
!  USE TEXT
!  USE STREET_LINKS
!  USE NODE_TABLE
!  IMPLICIT NONE
!  INTEGER :: IL
!! ----------------------------------------------------------------------
!  DO IL = 1, N_STREET_LINKS
!    IF(NODE_TYPE(SUSN(IL)) .NE. NT_INTERN .OR. NODE_TYPE(SDSN(IL)) .NE. NT_INTERN) CYCLE
!    IF(RT_ARC_LENGTH(IL, 1, 1) .NE. 0) THEN
!      IF(RIGHT_LINK(IL) .NE. 0) THEN
!        IF(LANE_CENTER(IL, 1) .GE. UP_INT_WIDTH(RIGHT_LINK(IL))) THEN
!          WRITE(MSGTEXT, '(A,2I5)') 'RIGHT TURN DATA FOR LINK ', SUSN(IL), SDSN(IL)
!          CALL SENDTEXTMSG(M_ERROR)
!          !WRITE(MSGTEXT, '(A, F10.3)') '  LEFT TURN ARC LENGTH ', LT_ARC_LENGTH(IL, 1, 1) 
!          !CALL SENDTEXTMSG(M_ERROR)
!          !IF(LEFT_LINK(IL) .NE. 0) THEN
!          !  WRITE(MSGTEXT, '(A, F10.3)') '  CENTER OF LEFTMOST LANE ', LANE_CENTER(IL, TOTAL_LANES(IL)) 
!          !  CALL SENDTEXTMSG(M_ERROR)
!          !  WRITE(MSGTEXT, '(A, F10.3)') '  INTERSECTION WIDTH OF LEFT RECEIVING LINK', UP_INT_WIDTH(LEFT_LINK(IL)) 
!          !  CALL SENDTEXTMSG(M_ERROR)
!          !ENDIF
!          WRITE(MSGTEXT, '(A, F10.3)') '  CENTER OF LANE 1 ', LANE_CENTER(IL, 1) 
!          CALL SENDTEXTMSG(M_ERROR)
!          WRITE(MSGTEXT, '(A, F10.3)') '  INTERSECTION WIDTH OF RIGHT RECEIVING LINK', UP_INT_WIDTH(RIGHT_LINK(IL)) 
!          CALL SENDTEXTMSG(M_ERROR)
!          WRITE(MSGTEXT, '(A, F10.3)') '  RIGHT TURN ARC LENGTH ', RT_ARC_LENGTH(IL, 1, 1) 
!          CALL SENDTEXTMSG(M_ERROR)
!        ENDIF
!      ENDIF
!    ENDIF
!    !IF(RT_ARC_LENGTH(IL, 1, 1) .NE. 0) THEN
!      !IF(LANE_CENTER(IL, 1) .GE. UP_INT_WIDTH(IL)) THEN
!        !WRITE(MSGTEXT, '(A,2I5)') 'INTERSECTION DATA FOR LINK ', SUSN(IL), SDSN(IL)
!        !CALL SENDTEXTMSG(M_ERROR)
!        !WRITE(MSGTEXT, '(A, F10.3)') '  RIGHT TURN ARC LENGTH ', RT_ARC_LENGTH(IL, 1, 1) 
!        !CALL SENDTEXTMSG(M_ERROR)
!        !WRITE(MSGTEXT, '(A, I3)') '  CENTER OF LANE 1 ', LANE_CENTER(IL, 1) 
!        !CALL SENDTEXTMSG(M_ERROR)
!        !WRITE(MSGTEXT, '(A, F10.3)') '  INTERSECTION WIDTH ', UP_INT_WIDTH(IL) 
!        !CALL SENDTEXTMSG(M_ERROR)
!      !ENDIF
!    !ENDIF
!  ENDDO
!  RETURN
!  END
  
        
