! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

  MODULE CAR_FOLLOWING
    INTEGER :: FPCFSEP = 10
    INTEGER :: FIDMSEP = 10
    INTEGER :: SPCFSEP = 3
    INTEGER :: SIDMSEP = 3
    INTEGER, PARAMETER :: CFM_PITT = 1
    INTEGER, PARAMETER :: CFM_IDM = 2
    INTEGER, PARAMETER :: CFM_ACC = 3
    INTEGER, PARAMETER :: CFM_CACC = 4
    REAL :: FZFOLL(10) =(/1.25, 1.15, 1.05, 0.95, 0.85, 0.75, 0.65, 0.55, 0.45, 0.35/)
    REAL :: SZFOLL(10) =(/1.25, 1.15, 1.05, 0.95, 0.85, 0.75, 0.65, 0.55, 0.45, 0.35/)
    REAL :: FZFOLL_IDM(10) =(/1.25, 1.15, 1.05, 0.95, 0.85, 0.75, 0.65, 0.55, 0.45, 0.35/)
    REAL :: SZFOLL_IDM(10) =(/1.25, 1.15, 1.05, 0.95, 0.85, 0.75, 0.65, 0.55, 0.45, 0.35/)
    REAL :: ACC_TG = 1.4
    REAL :: ACC_AMAX = 2.0
    REAL :: ACC_DMAX = -3.0
    REAL :: ACC_K1 = 0.07
    REAL :: ACC_K2 = 0.23
    REAL :: CACC_TG = 1.4
    REAL :: CACC_AMAX = 2.0
    REAL :: CACC_DMAX = -3.0
    REAL :: CACC_K1 = 0.07
    REAL :: CACC_K2 = 0.23
    LOGICAL :: WRITE202 = .FALSE.
  END MODULE
  
  MODULE VEHICLE_PARAMETERS

! --- Turn codes.

    INTEGER, PARAMETER :: TC_NULL = -1
    INTEGER, PARAMETER :: TC_LEFT = 0
    INTEGER, PARAMETER :: TC_THRU = 1
    INTEGER, PARAMETER :: TC_RIGHT = 2
    INTEGER, PARAMETER :: TC_LDIAG = 3
    INTEGER, PARAMETER :: TC_RDIAG = 4

! --- Lane codes.

    INTEGER, PARAMETER :: LC_GOOD = 0
    INTEGER, PARAMETER :: LC_VACATE = 1
    INTEGER, PARAMETER :: LC_NULL = 2
    INTEGER, PARAMETER :: LC_ANTICIP = 3
    INTEGER, PARAMETER :: LC_INC_GOOD = 4
    INTEGER, PARAMETER :: LC_INC_VACATE = 5
    INTEGER, PARAMETER :: LC_AVOIDHOV = 6
    INTEGER, PARAMETER :: LC_EXCLUDED = 7
        
  END MODULE
      
  MODULE DRIVERS

! --- Indexed by network and driver type.

    REAL :: FFSPEED_ADJ(10, 2)
    DATA FFSPEED_ADJ /.88, .91, .94, .97, .99, 1.01, 1.03, 1.06, 1.09, 1.12,   &
                      .75, .81, .91, .94, .97, 1.00, 1.07, 1.11, 1.17, 1.27/

! --- Indexed by driver type.

    REAL :: ACCEPTABLE_GAP(10) = (/5.6, 5.0, 4.6, 4.2, 3.9, 3.7, 3.4, 3.0, 2.6, 2.0/)
    REAL :: ACCEPTABLE_LTG(10) = (/7.8, 6.6, 6.0, 5.4, 4.8, 4.5, 4.2, 3.9, 3.6, 2.7/)       
    REAL :: ACCEPTABLE_RTG(10) = (/10.0, 8.8, 8.0, 7.2, 6.4, 6.0, 5.6, 5.2, 4.8, 3.6/)
    REAL :: ACCEPTABLE_RABT_GAP(10) = (/5.1, 4.5, 4.1, 3.7, 3.4, 3.2, 2.9, 2.5, 2.1, 1.5/)
    INTEGER :: AMBER_DECEL(10) = (/-21, -18, -15, -12, -9, -7, -6, -5, -4, -4/)
  
! --- Indexed by number of lanes to cross.
    
    REAL :: ADDITIONAL_GAP(10) = (/1.2, 2.1, 2.6, 3.1, 3.5, 3.9, 4.2, 4.6, 4.9, 5.1/)
        
    CONTAINS
      
! ==================================================================================================
    SUBROUTINE SAVE_DRIVERS(FILE)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: I, J
! ----------------------------------------------------------------------

! --- Save static data.

    DO I = 1, 10
      WRITE(FILE) (FFSPEED_ADJ(I, J), J = 1, 2)
    ENDDO
    WRITE(FILE) ACCEPTABLE_LTG(1:10)
    WRITE(FILE) ACCEPTABLE_RTG(1:10)
    WRITE(FILE) ACCEPTABLE_GAP(1:10)
    WRITE(FILE) ADDITIONAL_GAP(1:10)
    WRITE(FILE) AMBER_DECEL(1:10)
    RETURN
    END SUBROUTINE
      
! ==================================================================================================
    SUBROUTINE RESTORE_DRIVERS(FILE)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: I, J
! ----------------------------------------------------------------------

! --- Restore data.

    DO I = 1, 10
      READ(FILE) (FFSPEED_ADJ(I, J), J = 1, 2)
    ENDDO
    READ(FILE) ACCEPTABLE_LTG(1:10)
    READ(FILE) ACCEPTABLE_RTG(1:10)
    READ(FILE) ACCEPTABLE_GAP(1:10)
    READ(FILE) ADDITIONAL_GAP(1:10)
    READ(FILE) AMBER_DECEL(1:10)
    RETURN
    END SUBROUTINE
        
  END MODULE

  MODULE FREEWAY_VEHICLES
    USE GLOBAL_DATA
    USE VEHICLE_PARAMETERS
    IMPLICIT NONE
    INTEGER :: MAX_VEHICLES_F
    INTEGER :: HIGHEST_INDEX_F
    INTEGER :: SORTED_LIST_LENGTH

! --- Vehicle arrays

    REAL,    ALLOCATABLE :: FACCELERATION(:)
    INTEGER, ALLOCATABLE :: FCROSS1(:,:)
    INTEGER, ALLOCATABLE :: FCROSS2(:,:)
    REAL,    ALLOCATABLE :: FDECEL(:)
    REAL,    ALLOCATABLE :: FDESIREDSPEED(:)
    REAL,    ALLOCATABLE :: FDISCH_TIMER(:)
    INTEGER, ALLOCATABLE :: FDRIVERTYPE(:)    
    INTEGER, ALLOCATABLE :: FENTRY_LINK(:)
    REAL,    ALLOCATABLE :: FENTRYTIME(:)
    INTEGER, ALLOCATABLE :: FEV_DIST(:)
    INTEGER, ALLOCATABLE :: FEV_OVRSPD(:)
    INTEGER, ALLOCATABLE :: FEV_RANGE(:)
    INTEGER, ALLOCATABLE :: FEV_RAND(:)
    REAL,    ALLOCATABLE :: FEV_WAIT_TIMER(:)
    INTEGER, ALLOCATABLE :: FEV_WATCH(:)
    INTEGER, ALLOCATABLE :: FFLEET(:)
    LOGICAL, ALLOCATABLE :: FGO_THRU_SIGNAL(:)
    REAL,    ALLOCATABLE :: FLAG_TIMER(:)
    INTEGER, ALLOCATABLE :: FLANE(:)
    INTEGER, ALLOCATABLE :: FLANECODES(:,:)
    INTEGER, ALLOCATABLE :: FLINK(:)
    INTEGER, ALLOCATABLE :: FFOLLOWER(:)
    INTEGER, ALLOCATABLE :: FID(:)
    INTEGER, ALLOCATABLE :: FLAST_DETID(:)
    REAL,    ALLOCATABLE :: FLC_TIMER(:)
    INTEGER, ALLOCATABLE :: FLEADER(:)
    REAL,    ALLOCATABLE :: FLOCATION(:)
    INTEGER, ALLOCATABLE :: FPATHID(:)
    INTEGER, ALLOCATABLE :: FPATHPOINT(:)
    INTEGER, ALLOCATABLE :: FPSAVE(:)
    INTEGER, ALLOCATABLE :: FPSEUDO_LEADER(:)
    REAL,    ALLOCATABLE :: FPREV_ACCEL(:)
    INTEGER, ALLOCATABLE :: FPREVLINK(:)
    INTEGER, ALLOCATABLE :: FPREVLANE(:)
    INTEGER, ALLOCATABLE :: FROUTEID(:)
    REAL,    ALLOCATABLE :: FSPEED(:)
    REAL,    ALLOCATABLE :: FSPEED_ADJ(:)
    INTEGER, ALLOCATABLE :: FTURNCODE(:)
    INTEGER, ALLOCATABLE :: FVLENGTH(:)        
    INTEGER, ALLOCATABLE :: FVTYPE(:)
    INTEGER, ALLOCATABLE :: FXCODE(:)
    LOGICAL, ALLOCATABLE :: FWILL_COOP_EV(:)
    LOGICAL, ALLOCATABLE :: FWILL_COOP_LC(:)
    LOGICAL, ALLOCATABLE :: FWILL_MOVE(:)
    LOGICAL, ALLOCATABLE :: FDIVERTED(:)
    INTEGER, ALLOCATABLE :: FCF_MODEL(:)

    INTEGER, ALLOCATABLE :: DESTINATION(:)
    REAL,    ALLOCATABLE :: DISTANCE_TO_SEGMENT_END(:)
    LOGICAL, ALLOCATABLE :: HOV_VIOLATOR(:)
    LOGICAL, ALLOCATABLE :: HOV_URGENT(:)
    INTEGER, ALLOCATABLE :: IMETER(:)
    INTEGER, ALLOCATABLE :: INCIDENT_NUM(:)
    INTEGER, ALLOCATABLE :: ISEGMENT(:)
    LOGICAL, ALLOCATABLE :: MUST_MERGE(:)
    LOGICAL, ALLOCATABLE :: WARNED_EXIT(:)
    INTEGER, ALLOCATABLE :: NEXT_OBJECT(:)
    REAL,    ALLOCATABLE :: REMAINING_DIST(:)
    INTEGER, ALLOCATABLE :: SORTED_LIST(:)
    INTEGER, ALLOCATABLE :: SORT_POSITION(:)
    INTEGER, ALLOCATABLE :: CURRENT_LIST(:)
    INTEGER, ALLOCATABLE :: SAVE_NEXT_STOP(:)
        
    
!DEC$ ATTRIBUTES DLLEXPORT :: HIGHEST_INDEX_F   
!DEC$ ATTRIBUTES DLLEXPORT :: FDRIVERTYPE   
!DEC$ ATTRIBUTES DLLEXPORT :: FID   
        
    CONTAINS
        
    SUBROUTINE FREEWAY_RANDOM(ISEED, RNDNUM)
    USE SIMPARAMS
    IMPLICIT NONE
    INTEGER, INTENT(INOUT) :: ISEED
    REAL, INTENT(OUT) :: RNDNUM
    INTEGER A, P, B15, B16, XHI, XALO, LEFTLO, FHI, K
! ----------------------------------------------------------------------
!     Define the constant values.

    DATA A   /      16807 /
    DATA B15 /      32768 /
    DATA B16 /      65536 /
    DATA P   / 2147483647 /
! ----------------------------------------------------------------------
    IF(STOCHASTIC) THEN
      XHI    = ISEED / B16
      XALO   = (ISEED - XHI*B16) * A
      LEFTLO = XALO / B16
      FHI    = XHI * A + LEFTLO
      K      = FHI / B15
      ISEED  = ( ((XALO-LEFTLO*B16) - P) + (FHI - K*B15)*B16 ) + K
      IF( ISEED .LT. 0 ) ISEED = ISEED + P
      RNDNUM = (2 * (ISEED / 256) + 1) / 16777216.0
    ELSE
      RNDNUM = 0.5
    ENDIF

    END SUBROUTINE       
        
    SUBROUTINE ALLOCATE_FREEWAY_INTERFACE_ARRAYS
    IF(ALLOCATED(FCROSS1)) RETURN
    ALLOCATE(FCROSS1(MAX_NODE_NUMBER, N_INTERFACE_LANES))
    ALLOCATE(FCROSS2(MAX_NODE_NUMBER, N_INTERFACE_LANES))
    FCROSS1 = 0
    FCROSS2 = 0
    END SUBROUTINE
    
    SUBROUTINE ALLOCATE_FREEWAY_VEHICLE_ARRAYS
    IF(ALLOCATED(FID)) RETURN
    MAX_VEHICLES_F = 1000
    ALLOCATE(FID(MAX_VEHICLES_F))
    FID = 0
        
    ALLOCATE(FLEADER(MAX_VEHICLES_F))
    FLEADER = 0
        
    ALLOCATE(FPSEUDO_LEADER(MAX_VEHICLES_F))
    FPSEUDO_LEADER = 0
        
    ALLOCATE(FFOLLOWER(MAX_VEHICLES_F))
    FFOLLOWER = 0
        
    ALLOCATE(FLINK(MAX_VEHICLES_F))
    FLINK = 0
        
    ALLOCATE(FLANE(MAX_VEHICLES_F))
    FLANE = 0
        
    ALLOCATE(FPREVLINK(MAX_VEHICLES_F))
    FPREVLINK = 0
        
    ALLOCATE(FPREVLANE(MAX_VEHICLES_F))
    FPREVLANE = 0
        
    ALLOCATE(FDRIVERTYPE(MAX_VEHICLES_F))
    FDRIVERTYPE = 0
        
    ALLOCATE(FVLENGTH(MAX_VEHICLES_F))        
    FVLENGTH = 0
        
    ALLOCATE(FFLEET(MAX_VEHICLES_F))
    FFLEET = 0
        
    ALLOCATE(FVTYPE(MAX_VEHICLES_F))
    FVTYPE = 0
        
    ALLOCATE(FLANECODES(MAX_VEHICLES_F, N_FREEWAY_LANES))
    FLANECODES = LC_NULL
        
    ALLOCATE(FPATHID(MAX_VEHICLES_F))
    FPATHID = 0
        
    ALLOCATE(FPSAVE(MAX_VEHICLES_F))
    FPSAVE = 0
        
    ALLOCATE(FROUTEID(MAX_VEHICLES_F))
    FROUTEID = 0
        
    ALLOCATE(FPATHPOINT(MAX_VEHICLES_F))
    FPATHPOINT = 0
        
    ALLOCATE(FTURNCODE(MAX_VEHICLES_F))
    FTURNCODE = TC_THRU
        
    ALLOCATE(FXCODE(MAX_VEHICLES_F))
    FXCODE = 0
        
    ALLOCATE(FLAST_DETID(MAX_VEHICLES_F))
    FLAST_DETID = 0
        
    ALLOCATE(FENTRY_LINK(MAX_VEHICLES_F))
    FENTRY_LINK = 0
        
    ALLOCATE(REMAINING_DIST(MAX_VEHICLES_F))
    REMAINING_DIST = 0
        
    ALLOCATE(FLC_TIMER(MAX_VEHICLES_F))
    FLC_TIMER = 0
        
    ALLOCATE(FLAG_TIMER(MAX_VEHICLES_F))
    FLAG_TIMER = 0
        
    ALLOCATE(FDESIREDSPEED(MAX_VEHICLES_F))
    FDESIREDSPEED = 0
        
    ALLOCATE(FSPEED(MAX_VEHICLES_F))
    FSPEED = 0
        
    ALLOCATE(FSPEED_ADJ(MAX_VEHICLES_F))
    FSPEED_ADJ = 0
        
    ALLOCATE(FACCELERATION(MAX_VEHICLES_F))
    FACCELERATION = 0.
        
    ALLOCATE(FPREV_ACCEL(MAX_VEHICLES_F))
    FPREV_ACCEL = 0
        
    ALLOCATE(FLOCATION(MAX_VEHICLES_F))
    FLOCATION = 0
        
    ALLOCATE(FENTRYTIME(MAX_VEHICLES_F))
    FENTRYTIME = 0

    ALLOCATE(FDISCH_TIMER(MAX_VEHICLES_F))
    FDISCH_TIMER = 0

    ALLOCATE(FGO_THRU_SIGNAL(MAX_VEHICLES_F))
    FGO_THRU_SIGNAL = .FALSE.

    ALLOCATE(FWILL_COOP_LC(MAX_VEHICLES_F))
    FWILL_COOP_LC = .FALSE.
        
    ALLOCATE(FEV_WAIT_TIMER(MAX_VEHICLES_F))
    FEV_WAIT_TIMER = 0.
        
    ALLOCATE(FEV_WATCH(MAX_VEHICLES_F))
    FEV_WATCH = 0
        
    ALLOCATE(FEV_RAND(MAX_VEHICLES_F))
    FEV_RAND = 0
        
    ALLOCATE(FEV_DIST(MAX_VEHICLES_F))
    FEV_DIST = .FALSE.
        
    ALLOCATE(FWILL_COOP_EV(MAX_VEHICLES_F))
    FWILL_COOP_EV = .FALSE.
        
    ALLOCATE(FWILL_MOVE(MAX_VEHICLES_F))
    FWILL_MOVE = .FALSE.

    ALLOCATE(FEV_OVRSPD(MAX_VEHICLES_F))
    FEV_OVRSPD = 0
        
    ALLOCATE(FEV_RANGE(MAX_VEHICLES_F))
    FEV_RANGE = .FALSE.
        

    ALLOCATE(DISTANCE_TO_SEGMENT_END(MAX_VEHICLES_F))
    DISTANCE_TO_SEGMENT_END = 0.
        
    ALLOCATE(SORTED_LIST(MAX_VEHICLES_F))
    SORTED_LIST = 0
        
    ALLOCATE(SORT_POSITION(MAX_VEHICLES_F))
    SORT_POSITION = 0
        
    ALLOCATE(CURRENT_LIST(MAX_VEHICLES_F))
    CURRENT_LIST = 0
        
    ALLOCATE(SAVE_NEXT_STOP(MAX_VEHICLES_F))
    SAVE_NEXT_STOP = 0
        
    ALLOCATE(MUST_MERGE(MAX_VEHICLES_F))
    MUST_MERGE = .FALSE.
        
    ALLOCATE(WARNED_EXIT(MAX_VEHICLES_F))
    WARNED_EXIT = .FALSE.
        
    ALLOCATE(HOV_VIOLATOR(MAX_VEHICLES_F))
    HOV_VIOLATOR = .FALSE.
        
    ALLOCATE(HOV_URGENT(MAX_VEHICLES_F))
    HOV_URGENT = .FALSE.
        
    ALLOCATE(FDIVERTED(MAX_VEHICLES_F))
    FDIVERTED = .FALSE.
        
    ALLOCATE(FCF_MODEL(MAX_VEHICLES_F))
    FCF_MODEL = 0
        
    ALLOCATE(FDECEL(MAX_VEHICLES_F))
    FDECEL = 20.
        
    ALLOCATE(ISEGMENT(MAX_VEHICLES_F))
    ISEGMENT = 0
        
    ALLOCATE(NEXT_OBJECT(MAX_VEHICLES_F))
    NEXT_OBJECT = 0
        
    ALLOCATE(DESTINATION(MAX_VEHICLES_F))
    DESTINATION = 0
        
    ALLOCATE(IMETER(MAX_VEHICLES_F))
    IMETER = 0
        
    ALLOCATE(INCIDENT_NUM(MAX_VEHICLES_F))
    INCIDENT_NUM = 0
        
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE DELETE_FREEWAY_VEHICLE(IV)
    INTEGER, INTENT(IN) :: IV
    INTEGER :: IPOS, I
! ----------------------------------------------------------------------

! --- Remove an unused vehicle from the vehicle arrays.

    IPOS = SORT_POSITION(IV) 

! --- Compress the sorted list.

    IF(IPOS .NE. 0) THEN
      SORTED_LIST(IPOS) = 0
      SORT_POSITION(IV) = 0
      DO I = IPOS, SORTED_LIST_LENGTH - 1
        SORTED_LIST(I) = SORTED_LIST(I+1)
        IF(SORTED_LIST(I) .NE. 0) SORT_POSITION(SORTED_LIST(I)) = I
      ENDDO
      SORTED_LIST(SORTED_LIST_LENGTH) = 0
      SORTED_LIST_LENGTH = SORTED_LIST_LENGTH - 1
    ENDIF
    IF(FLEADER(IV) .NE. 0) FFOLLOWER(FLEADER(IV)) = 0
    IF(FFOLLOWER(IV) .NE. 0) FLEADER(FFOLLOWER(IV)) = 0
    FID(IV) = 0
    FLEADER(IV) = 0
    FPSEUDO_LEADER(IV) = 0
    FFOLLOWER(IV) = 0
    FLINK(IV) = 0
    FLANE(IV) = 0
    FPREVLINK(IV) = 0
    FPREVLANE(IV) = 0
    FDRIVERTYPE(IV) = 0
    FVLENGTH(IV) = 0        
    FFLEET(IV) = 0
    FVTYPE(IV) = 0
    FLANECODES(IV, 1:N_FREEWAY_LANES) = LC_NULL
    FPATHID(IV) = 0
    FPSAVE(IV) = 0
    FROUTEID(IV) = 0
    FPATHPOINT(IV) = 0
    FTURNCODE(IV) = TC_THRU
    FXCODE(IV) = 0
    FLAST_DETID(IV) = 0
    FENTRY_LINK(IV) = 0
    REMAINING_DIST(IV) = 0.
    FLC_TIMER(IV) = 0.
    FLAG_TIMER(IV) = 0.
    FDESIREDSPEED(IV) = 0.
    FSPEED(IV) = 0.
    FSPEED_ADJ(IV) = 0.
    FACCELERATION(IV) = 0.
    FPREV_ACCEL(IV) = 0.
    FLOCATION(IV) = 0.
    FENTRYTIME(IV) = 0.
    FDISCH_TIMER(IV) = 0.
    FGO_THRU_SIGNAL(IV) = .FALSE.
    FWILL_COOP_LC(IV) = .FALSE.
    FEV_WAIT_TIMER(IV) = 0
    FEV_WATCH(IV) = 0.
    FEV_RAND(IV) = 0
    FEV_DIST(IV) = 0.
    FWILL_COOP_EV(IV) = .FALSE.
    FWILL_MOVE(IV) = .FALSE.
    FEV_OVRSPD(IV) = 0
    FEV_RANGE(IV) = 0.

    ISEGMENT(IV) = 0
    NEXT_OBJECT(IV) = 0
    DESTINATION(IV) = 0
    IMETER(IV) = 0
    INCIDENT_NUM(IV) = 0
    DISTANCE_TO_SEGMENT_END(IV) = 0.
    MUST_MERGE(IV) = .FALSE.
    WARNED_EXIT(IV) = .FALSE.
    HOV_VIOLATOR(IV) = .FALSE.
    HOV_URGENT(IV) = .FALSE.
    FDIVERTED(IV) = .FALSE.
    FCF_MODEL(IV) = 0
    FDECEL(IV) = 20.
    SAVE_NEXT_STOP(IV) = 0
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE REALLOCATE_FREEWAY_VEHICLE_ARRAYS
    USE ARRAY_FUNCTIONS
    INTEGER :: I1, I2
! ----------------------------------------------------------------------
    I1 = MAX_VEHICLES_F 
    I2 = MAX_VEHICLES_F + 1000
    MAX_VEHICLES_F = I2
        
    CALL REALLOCATE_INTEGER(FID, I1, I2) 
    CALL REALLOCATE_INTEGER(FLEADER, I1, I2) 
    CALL REALLOCATE_INTEGER(FPSEUDO_LEADER, I1, I2) 
    CALL REALLOCATE_INTEGER(FFOLLOWER, I1, I2) 
    CALL REALLOCATE_INTEGER(FLINK, I1, I2) 
    CALL REALLOCATE_INTEGER(FLANE, I1, I2) 
    CALL REALLOCATE_INTEGER(FPREVLINK, I1, I2) 
    CALL REALLOCATE_INTEGER(FPREVLANE, I1, I2) 
    CALL REALLOCATE_INTEGER(FDRIVERTYPE, I1, I2) 
    CALL REALLOCATE_INTEGER(FVLENGTH, I1, I2)         
    CALL REALLOCATE_INTEGER(FFLEET, I1, I2) 
    CALL REALLOCATE_INTEGER(FVTYPE, I1, I2) 
    CALL REALLOCATE_INTEGER_X(FLANECODES, I1, I2, N_FREEWAY_LANES) 
    CALL REALLOCATE_INTEGER(FPATHID, I1, I2) 
    CALL REALLOCATE_INTEGER(FPSAVE, I1, I2) 
    CALL REALLOCATE_INTEGER(FROUTEID, I1, I2) 
    CALL REALLOCATE_INTEGER(FPATHPOINT, I1, I2) 
    CALL REALLOCATE_INTEGER(FTURNCODE, I1, I2) 
    CALL REALLOCATE_INTEGER(FXCODE, I1, I2)
    CALL REALLOCATE_INTEGER(FLAST_DETID, I1, I2)
    CALL REALLOCATE_INTEGER(FENTRY_LINK, I1, I2)
    CALL REALLOCATE_REAL(REMAINING_DIST, I1, I2) 
    CALL REALLOCATE_REAL(FLC_TIMER, I1, I2)
    CALL REALLOCATE_REAL(FLAG_TIMER, I1, I2)
    CALL REALLOCATE_REAL(FDESIREDSPEED, I1, I2) 
    CALL REALLOCATE_REAL(FSPEED, I1, I2) 
    CALL REALLOCATE_REAL(FSPEED_ADJ, I1, I2) 
    CALL REALLOCATE_REAL(FACCELERATION, I1, I2) 
    CALL REALLOCATE_REAL(FPREV_ACCEL, I1, I2) 
    CALL REALLOCATE_REAL(FLOCATION, I1, I2) 
    CALL REALLOCATE_REAL(FENTRYTIME, I1, I2)
    CALL REALLOCATE_REAL(FDISCH_TIMER, I1, I2)
    CALL REALLOCATE_LOGICAL(FGO_THRU_SIGNAL, I1, I2)
    CALL REALLOCATE_LOGICAL(FWILL_COOP_LC, I1, I2)
    CALL REALLOCATE_REAL(FEV_WAIT_TIMER, I1, I2)
    CALL REALLOCATE_INTEGER(FEV_WATCH, I1, I2)
    CALL REALLOCATE_INTEGER(FEV_RAND, I1, I2)
    CALL REALLOCATE_INTEGER(FEV_DIST, I1, I2)
    CALL REALLOCATE_LOGICAL(FWILL_COOP_EV, I1, I2)
    CALL REALLOCATE_LOGICAL(FWILL_MOVE, I1, I2)
    CALL REALLOCATE_INTEGER(FEV_OVRSPD, I1, I2)
    CALL REALLOCATE_INTEGER(FEV_RANGE, I1, I2)

    CALL REALLOCATE_INTEGER(SORTED_LIST, I1, I2)
    CALL REALLOCATE_INTEGER(SORT_POSITION, I1, I2) 
    CALL REALLOCATE_INTEGER(CURRENT_LIST, I1, I2) 
    CALL REALLOCATE_INTEGER(SAVE_NEXT_STOP, I1, I2) 
    CALL REALLOCATE_INTEGER(ISEGMENT, I1, I2) 
    CALL REALLOCATE_INTEGER(NEXT_OBJECT, I1, I2) 
    CALL REALLOCATE_INTEGER(DESTINATION, I1, I2) 
    CALL REALLOCATE_INTEGER(IMETER, I1, I2) 
    CALL REALLOCATE_INTEGER(INCIDENT_NUM, I1, I2) 
    CALL REALLOCATE_REAL(DISTANCE_TO_SEGMENT_END, I1, I2) 
    CALL REALLOCATE_LOGICAL(MUST_MERGE, I1, I2)
    CALL REALLOCATE_LOGICAL(WARNED_EXIT, I1, I2)
    CALL REALLOCATE_LOGICAL(HOV_VIOLATOR, I1, I2)
    CALL REALLOCATE_LOGICAL(HOV_URGENT, I1, I2)
    CALL REALLOCATE_LOGICAL(FDIVERTED, I1, I2)
    CALL REALLOCATE_INTEGER(FCF_MODEL, I1, I2)
    CALL REALLOCATE_REAL(FDECEL, I1, I2)
    END SUBROUTINE
             
! ==================================================================================================
    SUBROUTINE DEALLOCATE_FREEWAY_VEHICLE_ARRAYS
    IF(ALLOCATED(FID)) DEALLOCATE(FID)
    IF(ALLOCATED(FLEADER)) DEALLOCATE(FLEADER)
    IF(ALLOCATED(FPSEUDO_LEADER)) DEALLOCATE(FPSEUDO_LEADER)
    IF(ALLOCATED(FFOLLOWER)) DEALLOCATE(FFOLLOWER)
    IF(ALLOCATED(FLINK)) DEALLOCATE(FLINK)
    IF(ALLOCATED(FLANE)) DEALLOCATE(FLANE)
    IF(ALLOCATED(FPREVLINK)) DEALLOCATE(FPREVLINK)
    IF(ALLOCATED(FPREVLANE)) DEALLOCATE(FPREVLANE)
    IF(ALLOCATED(FDRIVERTYPE)) DEALLOCATE(FDRIVERTYPE)
    IF(ALLOCATED(FVLENGTH)) DEALLOCATE(FVLENGTH)
    IF(ALLOCATED(FFLEET)) DEALLOCATE(FFLEET)
    IF(ALLOCATED(FVTYPE)) DEALLOCATE(FVTYPE)
    IF(ALLOCATED(FLANECODES)) DEALLOCATE(FLANECODES)
    IF(ALLOCATED(FPATHID)) DEALLOCATE(FPATHID)
    IF(ALLOCATED(FPSAVE)) DEALLOCATE(FPSAVE)
    IF(ALLOCATED(FROUTEID)) DEALLOCATE(FROUTEID)
    IF(ALLOCATED(FPATHPOINT)) DEALLOCATE(FPATHPOINT)
    IF(ALLOCATED(FTURNCODE)) DEALLOCATE(FTURNCODE)
    IF(ALLOCATED(FXCODE)) DEALLOCATE(FXCODE)
    IF(ALLOCATED(FLAST_DETID)) DEALLOCATE(FLAST_DETID)
    IF(ALLOCATED(FENTRY_LINK)) DEALLOCATE(FENTRY_LINK)
    IF(ALLOCATED(REMAINING_DIST)) DEALLOCATE(REMAINING_DIST)
    IF(ALLOCATED(FLC_TIMER)) DEALLOCATE(FLC_TIMER)
    IF(ALLOCATED(FLAG_TIMER)) DEALLOCATE(FLAG_TIMER)
    IF(ALLOCATED(FDESIREDSPEED)) DEALLOCATE(FDESIREDSPEED)
    IF(ALLOCATED(FSPEED)) DEALLOCATE(FSPEED)
    IF(ALLOCATED(FSPEED_ADJ)) DEALLOCATE(FSPEED_ADJ)
    IF(ALLOCATED(FACCELERATION)) DEALLOCATE(FACCELERATION)
    IF(ALLOCATED(FPREV_ACCEL)) DEALLOCATE(FPREV_ACCEL)
    IF(ALLOCATED(FLOCATION)) DEALLOCATE(FLOCATION)
    IF(ALLOCATED(FENTRYTIME)) DEALLOCATE(FENTRYTIME)
    IF(ALLOCATED(FDISCH_TIMER)) DEALLOCATE(FDISCH_TIMER)
    IF(ALLOCATED(FGO_THRU_SIGNAL)) DEALLOCATE(FGO_THRU_SIGNAL)
    IF(ALLOCATED(FWILL_COOP_LC)) DEALLOCATE(FWILL_COOP_LC)
    IF(ALLOCATED(FEV_WAIT_TIMER)) DEALLOCATE(FEV_WAIT_TIMER)
    IF(ALLOCATED(FEV_WATCH)) DEALLOCATE(FEV_WATCH)
    IF(ALLOCATED(FEV_RAND)) DEALLOCATE(FEV_RAND)
    IF(ALLOCATED(FEV_DIST)) DEALLOCATE(FEV_DIST)
    IF(ALLOCATED(FWILL_COOP_EV)) DEALLOCATE(FWILL_COOP_EV)
    IF(ALLOCATED(FWILL_MOVE)) DEALLOCATE(FWILL_MOVE)
    IF(ALLOCATED(FEV_OVRSPD)) DEALLOCATE(FEV_OVRSPD)
    IF(ALLOCATED(FEV_RANGE)) DEALLOCATE(FEV_RANGE)

    IF(ALLOCATED(SORTED_LIST)) DEALLOCATE(SORTED_LIST)
    IF(ALLOCATED(SORT_POSITION)) DEALLOCATE(SORT_POSITION)
    IF(ALLOCATED(CURRENT_LIST)) DEALLOCATE(CURRENT_LIST)
    IF(ALLOCATED(SAVE_NEXT_STOP)) DEALLOCATE(SAVE_NEXT_STOP)
    IF(ALLOCATED(ISEGMENT)) DEALLOCATE(ISEGMENT)
    IF(ALLOCATED(NEXT_OBJECT)) DEALLOCATE(NEXT_OBJECT)
    IF(ALLOCATED(DESTINATION)) DEALLOCATE(DESTINATION)
    IF(ALLOCATED(IMETER)) DEALLOCATE(IMETER)
    IF(ALLOCATED(INCIDENT_NUM)) DEALLOCATE(INCIDENT_NUM)
    IF(ALLOCATED(DISTANCE_TO_SEGMENT_END)) DEALLOCATE(DISTANCE_TO_SEGMENT_END)
    IF(ALLOCATED(MUST_MERGE)) DEALLOCATE(MUST_MERGE)
    IF(ALLOCATED(WARNED_EXIT)) DEALLOCATE(WARNED_EXIT)
    IF(ALLOCATED(HOV_VIOLATOR)) DEALLOCATE(HOV_VIOLATOR)
    IF(ALLOCATED(HOV_URGENT)) DEALLOCATE(HOV_URGENT)
    IF(ALLOCATED(FDIVERTED)) DEALLOCATE(FDIVERTED)
    IF(ALLOCATED(FCF_MODEL)) DEALLOCATE(FCF_MODEL)
    IF(ALLOCATED(FDECEL)) DEALLOCATE(FDECEL)
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE WRITE_FREEWAY_TRAJECTORIES
    USE SIMPARAMS
    USE TEXT
    INCLUDE 'IOFILES.INC'
    INTEGER :: N = 1, IV, TOTAL
! ----------------------------------------------------------------------
    IF(SIMTIME .EQ. 0) THEN
      OPEN(N, FILE = LINFNAME(1:IROOT)//'VTRAJ', ERR=10, IOMSG=ETEXT)
    ELSE
      OPEN(N, FILE = LINFNAME(1:IROOT)//'VTRAJ', ACCESS='APPEND', ERR=10, IOMSG=ETEXT)
    ENDIF
    TOTAL = 0
    DO CONCURRENT (IV = 1: HIGHEST_INDEX_F)
      IF(FID(IV) .NE. 0) TOTAL = TOTAL + 1
    ENDDO
    WRITE(N, *) SIMTIME, TOTAL
    IF(TOTAL .GT. 0) THEN
      DO IV = 1, HIGHEST_INDEX_F
        IF(FID(IV) .NE. 0) THEN
          WRITE(N, *) FID(IV)
          WRITE(N, *) FFLEET(IV)
          WRITE(N, *) FVTYPE(IV)
          WRITE(N, *) FLINK(IV)
          WRITE(N, *) FLANE(IV)
          WRITE(N, *) FLOCATION(IV)
          WRITE(N, *) FSPEED(IV)
          WRITE(N, *) FACCELERATION(IV)
          WRITE(N, *) FPREV_ACCEL(IV)
        ENDIF
      ENDDO
    ENDIF
    CLOSE(N)
10  CONTINUE 
    WRITE(MSGTEXT,'(A)') 'FILE OPEN ERROR: WRITE_FREEWAY_TRAJECTORIES'
    CALL SENDTEXTMSG(M_INFO)
    WRITE(MSGTEXT, '(A)') ETEXT
    CALL SENDTEXTMSG(M_ERROR)
    ERROR_FLAG = 1
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE SAVE_FREEWAY_VEHICLES(FILE)
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: IV, N
! ----------------------------------------------------------------------
    DO CONCURRENT (IV = 1: MAX_VEHICLES_F)
      IF(FID(IV) .NE. 0) THEN
        HIGHEST_INDEX_F = IV
      ENDIF
    ENDDO
    WRITE(FILE) HIGHEST_INDEX_F
    WRITE(FILE) SORTED_LIST_LENGTH
    WRITE(FILE) MAX_VEHICLES_F
    IF(HIGHEST_INDEX_F .GT. 0) THEN
      WRITE(FILE) SORTED_LIST
      DO IV = 1, HIGHEST_INDEX_F
        !IF(FID(IV) .NE. 0) THEN
          WRITE(FILE) IV
          WRITE(FILE) FID(IV)
          WRITE(FILE) FFLEET(IV)
          WRITE(FILE) FVTYPE(IV)
          WRITE(FILE) FLINK(IV)
          WRITE(FILE) FLANE(IV)
          WRITE(FILE) FLOCATION(IV)
          WRITE(FILE) FSPEED(IV)
          WRITE(FILE) FACCELERATION(IV)
          WRITE(FILE) FPREV_ACCEL(IV)
          WRITE(FILE) FVLENGTH(IV)        
          WRITE(FILE) FLEADER(IV)
          WRITE(FILE) FPSEUDO_LEADER(IV)
          WRITE(FILE) FFOLLOWER(IV)
          WRITE(FILE) FPREVLINK(IV)
          WRITE(FILE) FPREVLANE(IV)
          WRITE(FILE) FDRIVERTYPE(IV)
          WRITE(FILE) (FLANECODES(IV, N), N = 1, N_FREEWAY_LANES)
          WRITE(FILE) FPATHID(IV)
          WRITE(FILE) FPSAVE(IV)
          WRITE(FILE) FROUTEID(IV)
          WRITE(FILE) FPATHPOINT(IV)
          WRITE(FILE) FXCODE(IV)
          WRITE(FILE) FLAST_DETID(IV)
          WRITE(FILE) FENTRY_LINK(IV)
          WRITE(FILE) REMAINING_DIST(IV)
          WRITE(FILE) FLC_TIMER(IV)
          WRITE(FILE) FLAG_TIMER(IV)
          WRITE(FILE) FDESIREDSPEED(IV)
          WRITE(FILE) FSPEED_ADJ(IV)
          WRITE(FILE) FENTRYTIME(IV)
          WRITE(FILE) FDISCH_TIMER(IV)
          WRITE(FILE) FGO_THRU_SIGNAL(IV)
          WRITE(FILE) FWILL_COOP_LC(IV)
          WRITE(FILE) FEV_WAIT_TIMER(IV)
          WRITE(FILE) FEV_WATCH(IV)
          WRITE(FILE) FEV_RAND(IV)
          WRITE(FILE) FEV_DIST(IV)
          WRITE(FILE) FWILL_COOP_EV(IV)
          WRITE(FILE) FWILL_MOVE(IV)
          WRITE(FILE) FEV_OVRSPD(IV)
          WRITE(FILE) FEV_RANGE(IV)
          WRITE(FILE) SORT_POSITION(IV)
          WRITE(FILE) CURRENT_LIST(IV)
          WRITE(FILE) SAVE_NEXT_STOP(IV)
          WRITE(FILE) DISTANCE_TO_SEGMENT_END(IV)
          WRITE(FILE) ISEGMENT(IV)
          WRITE(FILE) NEXT_OBJECT(IV)
          WRITE(FILE) DESTINATION(IV)
          WRITE(FILE) IMETER(IV)
          WRITE(FILE) INCIDENT_NUM(IV)
          WRITE(FILE) MUST_MERGE(IV)
          WRITE(FILE) WARNED_EXIT(IV)
          WRITE(FILE) HOV_VIOLATOR(IV)
          WRITE(FILE) HOV_URGENT(IV)
          WRITE(FILE) FDIVERTED(IV)
          WRITE(FILE) FCF_MODEL(IV)
          WRITE(FILE) FDECEL(IV)
        !ENDIF
      ENDDO
    ENDIF
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE RESTORE_FREEWAY_VEHICLE(FILE)
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: IV, I, N
! ----------------------------------------------------------------------
    READ(FILE) HIGHEST_INDEX_F
    READ(FILE) SORTED_LIST_LENGTH
    READ(FILE) MAX_VEHICLES_F
    CALL ALLOCATE_FREEWAY_VEHICLE_ARRAYS
    IF(HIGHEST_INDEX_F .GT. 0) THEN
      READ(FILE) SORTED_LIST
      DO I = 1, HIGHEST_INDEX_F
        READ(FILE) IV
        READ(FILE) FID(IV)
        READ(FILE) FFLEET(IV)
        READ(FILE) FVTYPE(IV)
        READ(FILE) FLINK(IV)
        READ(FILE) FLANE(IV)
        READ(FILE) FLOCATION(IV)
        READ(FILE) FSPEED(IV)
        READ(FILE) FACCELERATION(IV)
        READ(FILE) FPREV_ACCEL(IV)
        READ(FILE) FVLENGTH(IV)        
        READ(FILE) FLEADER(IV)
        READ(FILE) FPSEUDO_LEADER(IV)
        READ(FILE) FFOLLOWER(IV)
        READ(FILE) FPREVLINK(IV)
        READ(FILE) FPREVLANE(IV)
        READ(FILE) FDRIVERTYPE(IV)
        READ(FILE) (FLANECODES(IV, N), N = 1, N_FREEWAY_LANES)
        READ(FILE) FPATHID(IV)
        READ(FILE) FPSAVE(IV)
        READ(FILE) FROUTEID(IV)
        READ(FILE) FPATHPOINT(IV)
        READ(FILE) FXCODE(IV)
        READ(FILE) FLAST_DETID(IV)
        READ(FILE) FENTRY_LINK(IV)
        READ(FILE) REMAINING_DIST(IV)
        READ(FILE) FLC_TIMER(IV)
        READ(FILE) FLAG_TIMER(IV)
        READ(FILE) FDESIREDSPEED(IV)
        READ(FILE) FSPEED_ADJ(IV)
        READ(FILE) FENTRYTIME(IV)
        READ(FILE) FDISCH_TIMER(IV)
        READ(FILE) FGO_THRU_SIGNAL(IV)
        READ(FILE) FWILL_COOP_LC(IV)
        READ(FILE) FEV_WAIT_TIMER(IV)
        READ(FILE) FEV_WATCH(IV)
        READ(FILE) FEV_RAND(IV)
        READ(FILE) FEV_DIST(IV)
        READ(FILE) FWILL_COOP_EV(IV)
        READ(FILE) FWILL_MOVE(IV)
        READ(FILE) FEV_OVRSPD(IV)
        READ(FILE) FEV_RANGE(IV)
        READ(FILE) SORT_POSITION(IV)
        READ(FILE) CURRENT_LIST(IV)
        READ(FILE) SAVE_NEXT_STOP(IV)
        READ(FILE) DISTANCE_TO_SEGMENT_END(IV)
        READ(FILE) ISEGMENT(IV)
        READ(FILE) NEXT_OBJECT(IV)
        READ(FILE) DESTINATION(IV)
        READ(FILE) IMETER(IV)
        READ(FILE) INCIDENT_NUM(IV)
        READ(FILE) MUST_MERGE(IV)
        READ(FILE) WARNED_EXIT(IV)
        READ(FILE) HOV_VIOLATOR(IV)
        READ(FILE) HOV_URGENT(IV)
        READ(FILE) FDIVERTED(IV)
        READ(FILE) FCF_MODEL(IV)
        READ(FILE) FDECEL(IV)
      ENDDO
    ENDIF
    END SUBROUTINE

  END MODULE 
      
  MODULE STREET_VEHICLES
    USE GLOBAL_DATA
    USE VEHICLE_PARAMETERS
    IMPLICIT NONE

! --- QSTATE codes

    INTEGER, PARAMETER :: QS_NOTINQ = 0
    INTEGER, PARAMETER :: QS_STOPPED = 1
    INTEGER, PARAMETER :: QS_MOVING = 2
    INTEGER, PARAMETER :: QS_BLOCKER = 3
    INTEGER, PARAMETER :: QS_DWELL = 4
    INTEGER, PARAMETER :: QS_CFSTOPPED = 5
    INTEGER, PARAMETER :: QS_CFMOVING = 6
        
    INTEGER :: HIGHEST_INDEX_S
    INTEGER :: MAX_VEHICLES_S
    INTEGER :: EXITING_VEHICLES

! --- Vehicle arrays

    REAL,    ALLOCATABLE :: SACCELERATION(:)
    INTEGER, ALLOCATABLE :: SCROSS1(:,:)
    INTEGER, ALLOCATABLE :: SCROSS2(:,:)
    REAL,    ALLOCATABLE :: SDECEL(:)
    REAL,    ALLOCATABLE :: SDESIREDSPEED(:)
    REAL,    ALLOCATABLE :: SDISCH_TIMER(:)
    INTEGER, ALLOCATABLE :: SDRIVERTYPE(:)    
    INTEGER, ALLOCATABLE :: DRIVER_TYPE(:)    
    INTEGER, ALLOCATABLE :: SENTRY_LINK(:)
    REAL,    ALLOCATABLE :: SENTRYTIME(:)
    INTEGER, ALLOCATABLE :: SEV_DIST(:)
    INTEGER, ALLOCATABLE :: SEV_OVRSPD(:)
    INTEGER, ALLOCATABLE :: SEV_RANGE(:)
    INTEGER, ALLOCATABLE :: SEV_RAND(:)
    REAL,    ALLOCATABLE :: SEV_WAIT_TIMER(:)
    INTEGER, ALLOCATABLE :: SEV_WATCH(:)
    INTEGER, ALLOCATABLE :: SFLEET(:)
    LOGICAL, ALLOCATABLE :: SGO_THRU_SIGNAL(:)
    LOGICAL, ALLOCATABLE :: FORCE_STOP(:)
    REAL,    ALLOCATABLE :: SLAG_TIMER(:)
    INTEGER, ALLOCATABLE :: SLANE(:)
    INTEGER, ALLOCATABLE :: SLANECODES(:,:)
    INTEGER, ALLOCATABLE :: SLINK(:)
    INTEGER, ALLOCATABLE :: SFOLLOWER(:)
    INTEGER, ALLOCATABLE :: SID(:)
    INTEGER, ALLOCATABLE :: SLAST_DETID(:)
    REAL,    ALLOCATABLE :: SLC_TIMER(:)
    INTEGER, ALLOCATABLE :: SLEADER(:)
    REAL,    ALLOCATABLE :: SLOCATION(:)
    INTEGER, ALLOCATABLE :: SPATHID(:)
    INTEGER, ALLOCATABLE :: SPATHPOINT(:)
    INTEGER, ALLOCATABLE :: SPSAVE(:)
    INTEGER, ALLOCATABLE :: SPSEUDO_LEADER(:)
    REAL,    ALLOCATABLE :: SPREV_ACCEL(:)
    INTEGER, ALLOCATABLE :: ARC_ENTRYLINK(:)
    INTEGER, ALLOCATABLE :: ARC_ENTRYLANE(:)
    INTEGER, ALLOCATABLE :: ARC_DIRECTION(:)
    REAL,    ALLOCATABLE :: ARC_LOCATION(:)
    REAL,    ALLOCATABLE :: ARC_LENGTH(:)
    REAL,    ALLOCATABLE :: LIMITED_SPEED_DIST(:)
    INTEGER, ALLOCATABLE :: SPREVLINK(:)
    INTEGER, ALLOCATABLE :: SPREVLANE(:)
    INTEGER, ALLOCATABLE :: SROUTEID(:)
    REAL,    ALLOCATABLE :: SSPEED(:)
    REAL,    ALLOCATABLE :: SSPEED_ADJ(:)
    REAL,    ALLOCATABLE :: SSTART_LAG(:)
    INTEGER, ALLOCATABLE :: STURNCODE(:)
    INTEGER, ALLOCATABLE :: SVLENGTH(:)        
    INTEGER, ALLOCATABLE :: SVTYPE(:)
    INTEGER, ALLOCATABLE :: SXCODE(:)
    LOGICAL, ALLOCATABLE :: SWILL_COOP_EV(:)
    LOGICAL, ALLOCATABLE :: SWILL_COOP_LC(:)
    LOGICAL, ALLOCATABLE :: SWILL_MOVE(:)
    LOGICAL, ALLOCATABLE :: SDIVERTED(:)
    INTEGER, ALLOCATABLE :: SCF_MODEL(:)
    
    REAL,    ALLOCATABLE :: DWELL_TIMER(:)
    REAL,    ALLOCATABLE :: WAIT_TIME(:)
    INTEGER, ALLOCATABLE :: GOAL_LANE(:)
    LOGICAL, ALLOCATABLE :: HAS_STOPPED(:)
    INTEGER, ALLOCATABLE :: SPDICD(:)
    INTEGER, ALLOCATABLE :: NEXT_STOP(:)
    INTEGER, ALLOCATABLE :: PREV_TURNCODE(:)
    REAL,    ALLOCATABLE :: PRVDIST(:)
    INTEGER, ALLOCATABLE :: ICD_LINK(:)
    INTEGER, ALLOCATABLE :: PRVLNKICD(:)
    INTEGER, ALLOCATABLE :: ICD_TURNCODE(:)
    INTEGER, ALLOCATABLE :: QSTATE(:)
    INTEGER, ALLOCATABLE :: TURN_CODE(:)
    INTEGER, ALLOCATABLE :: TURN_CODE2(:)
    INTEGER, ALLOCATABLE :: TURN_LINK(:)
    INTEGER, ALLOCATABLE :: TURN_LINK2(:)
    INTEGER, ALLOCATABLE :: VEHICD(:)
    INTEGER, ALLOCATABLE :: VEHICD0(:)
    LOGICAL, ALLOCATABLE :: WILL_JUMP(:)
    LOGICAL, ALLOCATABLE :: WILL_YIELD(:)
    LOGICAL, ALLOCATABLE :: RTOR_FLAG(:)
    LOGICAL, ALLOCATABLE :: REDRUNNER(:)
    LOGICAL, ALLOCATABLE :: INDZ(:)
    INTEGER, ALLOCATABLE :: DESIRED_LANE(:)
    INTEGER, ALLOCATABLE :: TURN_INDICATOR(:)
    INTEGER, ALLOCATABLE :: ROUNDABOUT_EXIT(:)
    LOGICAL, ALLOCATABLE :: FIRST_RIGHT(:)
    LOGICAL, ALLOCATABLE :: IN_TURNING_WAY(:)
!DEC$ATTRIBUTES DLLEXPORT::HIGHEST_INDEX_S
!DEC$ATTRIBUTES DLLEXPORT::SID
!DEC$ATTRIBUTES DLLEXPORT::SLOCATION
!DEC$ATTRIBUTES DLLEXPORT::SLINK
!DEC$ATTRIBUTES DLLEXPORT::SLANE
!DEC$ATTRIBUTES DLLEXPORT::SSPEED
!DEC$ATTRIBUTES DLLEXPORT::SDESIREDSPEED                

    CONTAINS
        
        
    SUBROUTINE STREET_RANDOM(ISEED, RNDNUM)
    USE SIMPARAMS
    IMPLICIT NONE
    INTEGER, INTENT(INOUT) :: ISEED
    REAL, INTENT(OUT) :: RNDNUM
    INTEGER A, P, B15, B16, XHI, XALO, LEFTLO, FHI, K
! ----------------------------------------------------------------------
!     Define the constant values.

    DATA A   /      16807 /
    DATA B15 /      32768 /
    DATA B16 /      65536 /
    DATA P   / 2147483647 /
! ----------------------------------------------------------------------
    IF(STOCHASTIC) THEN
      XHI    = ISEED / B16
      XALO   = (ISEED - XHI*B16) * A
      LEFTLO = XALO / B16
      FHI    = XHI * A + LEFTLO
      K      = FHI / B15
      ISEED  = ( ((XALO-LEFTLO*B16) - P) + (FHI - K*B15)*B16 ) + K
      IF( ISEED .LT. 0 ) ISEED = ISEED + P
      RNDNUM = (2 * (ISEED / 256) + 1) / 16777216.0
    ELSE
      RNDNUM = 0.5
    ENDIF

    END SUBROUTINE       

    SUBROUTINE ALLOCATE_STREET_INTERFACE_ARRAYS
    IF(ALLOCATED(SCROSS1)) RETURN
    ALLOCATE(SCROSS1(MAX_NODE_NUMBER, N_INTERFACE_LANES))
    ALLOCATE(SCROSS2(MAX_NODE_NUMBER, N_INTERFACE_LANES))
    SCROSS1 = 0
    SCROSS2 = 0
    END SUBROUTINE
    
    SUBROUTINE ALLOCATE_STREET_VEHICLE_ARRAYS
    IF(ALLOCATED(SID)) RETURN
    MAX_VEHICLES_S = 1000
    
    ALLOCATE(SID(MAX_VEHICLES_S))
    SID = 0
        
    ALLOCATE(SLEADER(MAX_VEHICLES_S))
    SLEADER = 0
        
    ALLOCATE(SPSEUDO_LEADER(MAX_VEHICLES_S))
    SPSEUDO_LEADER = 0
        
    ALLOCATE(SFOLLOWER(MAX_VEHICLES_S))
    SFOLLOWER = 0
        
    ALLOCATE(SLINK(MAX_VEHICLES_S))
    SLINK = 0
        
    ALLOCATE(SLANE(MAX_VEHICLES_S))
    SLANE = 0
        
    ALLOCATE(ARC_ENTRYLINK(MAX_VEHICLES_S))
    ARC_ENTRYLINK = 0
        
    ALLOCATE(ARC_ENTRYLANE(MAX_VEHICLES_S))
    ARC_ENTRYLANE = 0
        
    ALLOCATE(ARC_DIRECTION(MAX_VEHICLES_S))
    ARC_DIRECTION = 0
        
    ALLOCATE(ARC_LOCATION(MAX_VEHICLES_S))
    ARC_LOCATION = 0.
        
    ALLOCATE(ARC_LENGTH(MAX_VEHICLES_S))
    ARC_LENGTH = 0.
        
    ALLOCATE(LIMITED_SPEED_DIST(MAX_VEHICLES_S))
    LIMITED_SPEED_DIST = 0.
        
    ALLOCATE(SPREVLINK(MAX_VEHICLES_S))
    SPREVLINK = 0
        
    ALLOCATE(SPREVLANE(MAX_VEHICLES_S))
    SPREVLANE = 0
        
    ALLOCATE(SDRIVERTYPE(MAX_VEHICLES_S))
    SDRIVERTYPE = 0
        
    ALLOCATE(DRIVER_TYPE(MAX_VEHICLES_S))
    DRIVER_TYPE = 0
        
    ALLOCATE(SVLENGTH(MAX_VEHICLES_S))        
    SVLENGTH = 0
        
    ALLOCATE(SFLEET(MAX_VEHICLES_S))
    SFLEET = 0
        
    ALLOCATE(SVTYPE(MAX_VEHICLES_S))
    SVTYPE = 0
        
    ALLOCATE(SLANECODES(MAX_VEHICLES_S, N_STREET_LANES))
    SLANECODES = LC_NULL
        
    ALLOCATE(SPATHID(MAX_VEHICLES_S))
    SPATHID = 0
        
    ALLOCATE(SPSAVE(MAX_VEHICLES_S))
    SPSAVE = 0
        
    ALLOCATE(SROUTEID(MAX_VEHICLES_S))
    SROUTEID = 0
        
    ALLOCATE(SPATHPOINT(MAX_VEHICLES_S))
    SPATHPOINT = 0
        
    ALLOCATE(STURNCODE(MAX_VEHICLES_S))
    STURNCODE = TC_THRU
        
    ALLOCATE(SXCODE(MAX_VEHICLES_S))
    SXCODE = 0
        
    ALLOCATE(SLAST_DETID(MAX_VEHICLES_S))
    SLAST_DETID = 0
        
    ALLOCATE(SENTRY_LINK(MAX_VEHICLES_S))
    SENTRY_LINK = 0
        
    ALLOCATE(SLC_TIMER(MAX_VEHICLES_S))
    SLC_TIMER = 0
        
    ALLOCATE(SLAG_TIMER(MAX_VEHICLES_S))
    SLAG_TIMER = 0
        
    ALLOCATE(SSTART_LAG(MAX_VEHICLES_S))
    SSTART_LAG = 0
        
    ALLOCATE(SDESIREDSPEED(MAX_VEHICLES_S))
    SDESIREDSPEED = 0
        
    ALLOCATE(SSPEED(MAX_VEHICLES_S))
    SSPEED = 0
        
    ALLOCATE(SSPEED_ADJ(MAX_VEHICLES_S))
    SSPEED_ADJ = 0
        
    ALLOCATE(SACCELERATION(MAX_VEHICLES_S))
    SACCELERATION = 0.
        
    ALLOCATE(SPREV_ACCEL(MAX_VEHICLES_S))
    SPREV_ACCEL = 0
        
    ALLOCATE(SLOCATION(MAX_VEHICLES_S))
    SLOCATION = 0
        
    ALLOCATE(SENTRYTIME(MAX_VEHICLES_S))
    SENTRYTIME = 0
        
    ALLOCATE(SDISCH_TIMER(MAX_VEHICLES_S))
    SDISCH_TIMER = 0.

    ALLOCATE(SGO_THRU_SIGNAL(MAX_VEHICLES_S))
    SGO_THRU_SIGNAL = .FALSE.
        
    ALLOCATE(FORCE_STOP(MAX_VEHICLES_S))
    FORCE_STOP = .FALSE.
        
    ALLOCATE(SDECEL(MAX_VEHICLES_S))
    SDECEL = 20.

    ALLOCATE(SEV_WAIT_TIMER(MAX_VEHICLES_S))
    SEV_WAIT_TIMER = 0.

    ALLOCATE(SEV_WATCH(MAX_VEHICLES_S))
    SEV_WATCH = 0
        
    ALLOCATE(SEV_RAND(MAX_VEHICLES_S))
    SEV_RAND = -1
        
    ALLOCATE(SEV_DIST(MAX_VEHICLES_S))
    SEV_DIST = 0
        
    ALLOCATE(SWILL_COOP_EV(MAX_VEHICLES_S))
    SWILL_COOP_EV = .FALSE.

    ALLOCATE(SWILL_MOVE(MAX_VEHICLES_S))
    SWILL_MOVE = .FALSE.
        
    ALLOCATE(SDIVERTED(MAX_VEHICLES_S))
    SDIVERTED = .FALSE.
        
    ALLOCATE(SCF_MODEL(MAX_VEHICLES_S))
    SCF_MODEL = 0
        
    ALLOCATE(SEV_OVRSPD(MAX_VEHICLES_S))
    SEV_OVRSPD = 0
        
    ALLOCATE(SEV_RANGE(MAX_VEHICLES_S))
    SEV_RANGE = 0
        
        
    ALLOCATE(GOAL_LANE(MAX_VEHICLES_S))
    GOAL_LANE = 0
        
    ALLOCATE(TURN_LINK(MAX_VEHICLES_S))
    TURN_LINK = 0
        
    ALLOCATE(TURN_CODE(MAX_VEHICLES_S))
    TURN_CODE = TC_THRU
        
    ALLOCATE(DESIRED_LANE(MAX_VEHICLES_S))
    DESIRED_LANE = 0
        
    ALLOCATE(TURN_INDICATOR(MAX_VEHICLES_S))
    TURN_INDICATOR = 0
    
    ALLOCATE(ROUNDABOUT_EXIT(MAX_VEHICLES_S))
    ROUNDABOUT_EXIT = 0
        
    ALLOCATE(FIRST_RIGHT(MAX_VEHICLES_S))
    FIRST_RIGHT = .FALSE.
        
    ALLOCATE(IN_TURNING_WAY(MAX_VEHICLES_S))
    IN_TURNING_WAY = .FALSE.
        
    ALLOCATE(TURN_CODE2(MAX_VEHICLES_S))
    TURN_CODE2 = TC_NULL
        
    ALLOCATE(TURN_LINK2(MAX_VEHICLES_S))
    TURN_LINK2 = 0
        
    ALLOCATE(NEXT_STOP(MAX_VEHICLES_S))
    NEXT_STOP = 0
        
    ALLOCATE(QSTATE(MAX_VEHICLES_S))
    QSTATE = QS_NOTINQ
        
    ALLOCATE(PREV_TURNCODE(MAX_VEHICLES_S))
    PREV_TURNCODE = 0
        
    ALLOCATE(PRVDIST(MAX_VEHICLES_S))
    PRVDIST = 0
        
    ALLOCATE(PRVLNKICD(MAX_VEHICLES_S))
    PRVLNKICD = 0
        
    ALLOCATE(ICD_TURNCODE(MAX_VEHICLES_S))
    ICD_TURNCODE = 0
        
    ALLOCATE(ICD_LINK(MAX_VEHICLES_S))
    ICD_LINK = 0
        
    ALLOCATE(SPDICD(MAX_VEHICLES_S))
    SPDICD = 0
        
    ALLOCATE(VEHICD(MAX_VEHICLES_S))
    VEHICD = 0
        
    ALLOCATE(VEHICD0(MAX_VEHICLES_S))
    VEHICD0 = 0
        
    ALLOCATE(DWELL_TIMER(MAX_VEHICLES_S))
    DWELL_TIMER = 0.
        
    ALLOCATE(WAIT_TIME(MAX_VEHICLES_S))
    WAIT_TIME = 0.
        
    ALLOCATE(WILL_YIELD(MAX_VEHICLES_S))
    WILL_YIELD = .FALSE.
        
    ALLOCATE(RTOR_FLAG(MAX_VEHICLES_S))
    RTOR_FLAG = .FALSE.
        
    ALLOCATE(REDRUNNER(MAX_VEHICLES_S))
    REDRUNNER = .FALSE.
        
    ALLOCATE(INDZ(MAX_VEHICLES_S))
    INDZ = .FALSE.
        
    ALLOCATE(WILL_JUMP(MAX_VEHICLES_S))
    WILL_JUMP = .FALSE.
        
    ALLOCATE(SWILL_COOP_LC(MAX_VEHICLES_S))
    SWILL_COOP_LC = .FALSE.
        
    ALLOCATE(HAS_STOPPED(MAX_VEHICLES_S))
    HAS_STOPPED = .FALSE.
        
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE DELETE_STREET_VEHICLE(IV, XTRACT)
    USE GLOBAL_DATA
    INTEGER, INTENT(IN) :: IV
    LOGICAL, INTENT(IN) :: XTRACT
! ----------------------------------------------------------------------

! --- Remove an unused vehicle from the vehicle arrays.

    IF(.NOT. XTRACT) THEN
      IF(SLEADER(IV) .NE. 0) SFOLLOWER(SLEADER(IV)) = 0
      IF(SFOLLOWER(IV) .NE. 0) SLEADER(SFOLLOWER(IV)) = 0
    ENDIF
    SID(IV) = 0
    SLEADER(IV) = 0
    SPSEUDO_LEADER(IV) = 0
    SFOLLOWER(IV) = 0
    SLINK(IV) = 0
    SLANE(IV) = 0
    ARC_ENTRYLINK(IV) = 0
    ARC_ENTRYLANE(IV) = 0
    ARC_DIRECTION(IV) = 0
    ARC_LOCATION(IV) = 0.
    ARC_LENGTH(IV) = 0.
    ARC_LENGTH(IV) = 0.
    LIMITED_SPEED_DIST(IV) = 0.
    SPREVLINK(IV) = 0
    SPREVLANE(IV) = 0
    SDRIVERTYPE(IV) = 0
    DRIVER_TYPE(IV) = 0
    SVLENGTH(IV) = 0        
    SFLEET(IV) = 0
    SVTYPE(IV) = 0
    SLANECODES(IV, 1:7) = TC_THRU
    STURNCODE(IV) = TC_THRU
    SPATHID(IV) = 0
    SPSAVE(IV) = 0
    SROUTEID(IV) = 0
    SPATHPOINT(IV) = 0
    SXCODE(IV) = 0
    SLAST_DETID(IV) = 0
    SENTRY_LINK(IV) = 0
    SLC_TIMER(IV) = 0.
    SLAG_TIMER(IV) = 0.
    SSTART_LAG(IV) = 0.
    SDESIREDSPEED(IV) = 0.
    SSPEED(IV) = 0.
    SSPEED_ADJ(IV) = 0.
    SACCELERATION(IV) = 0.
    SPREV_ACCEL(IV) = 0.
    SLOCATION(IV) = 0.
    SENTRYTIME(IV) = 0.
    SDISCH_TIMER(IV) = 0.
    SGO_THRU_SIGNAL(IV) = .FALSE.
    FORCE_STOP(IV) = .FALSE.
    SWILL_COOP_LC(IV) = .FALSE.
    SDECEL(IV) = 20.
        
    SEV_WAIT_TIMER(IV) = 0.
    SEV_WATCH(IV) = 0
    SEV_RAND(IV) = -1
    SEV_DIST(IV) = 0
    SWILL_COOP_EV(IV) = .FALSE.
    SWILL_MOVE(IV) = .FALSE.
    SDIVERTED(IV) = .FALSE.
    SCF_MODEL(IV) = 0
    SEV_OVRSPD(IV) = 0
    SEV_RANGE(IV) = 0

    GOAL_LANE(IV) = 0
    QSTATE(IV) = QS_NOTINQ
    TURN_LINK(IV) = 0
    TURN_CODE(IV) = TC_THRU
    DESIRED_LANE(IV) = 0
    TURN_INDICATOR(IV) = 0
    ROUNDABOUT_EXIT(IV) = 0
    FIRST_RIGHT(IV) = .FALSE.
    IN_TURNING_WAY(IV) = .FALSE.
    TURN_CODE2(IV) = TC_NULL
    TURN_LINK2(IV) = 0
    NEXT_STOP(IV) = 0
    PREV_TURNCODE(IV) = 0
    PRVDIST(IV) = 0
    PRVLNKICD(IV) = 0
    ICD_TURNCODE(IV) = 0
    ICD_LINK(IV) = 0
    SPDICD(IV) = 0
    VEHICD(IV) = 0
    VEHICD0(IV) = 0
    DWELL_TIMER(IV) = 0.
    WAIT_TIME(IV) = 0.
    WILL_YIELD(IV) = .FALSE.
    RTOR_FLAG(IV) = .FALSE.
    REDRUNNER(IV) = .FALSE.
    INDZ(IV) = .FALSE.
    WILL_JUMP(IV) = .FALSE.
    HAS_STOPPED(IV) = .FALSE.
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE REALLOCATE_STREET_VEHICLE_ARRAYS
    USE ARRAY_FUNCTIONS
    INTEGER :: I1, I2
! ----------------------------------------------------------------------
    I1 = MAX_VEHICLES_S
    I2 = MAX_VEHICLES_S + 1000
    MAX_VEHICLES_S = I2
        
    CALL REALLOCATE_INTEGER(SID, I1, I2) 
    CALL REALLOCATE_INTEGER(SLEADER, I1, I2) 
    CALL REALLOCATE_INTEGER(SPSEUDO_LEADER, I1, I2) 
    CALL REALLOCATE_INTEGER(SFOLLOWER, I1, I2) 
    CALL REALLOCATE_INTEGER(SLINK, I1, I2) 
    CALL REALLOCATE_INTEGER(SLANE, I1, I2) 
    CALL REALLOCATE_INTEGER(ARC_ENTRYLINK, I1, I2) 
    CALL REALLOCATE_INTEGER(ARC_ENTRYLANE, I1, I2) 
    CALL REALLOCATE_INTEGER(ARC_DIRECTION, I1, I2) 
    CALL REALLOCATE_REAL(ARC_LOCATION, I1, I2) 
    CALL REALLOCATE_REAL(ARC_LENGTH, I1, I2) 
    CALL REALLOCATE_REAL(LIMITED_SPEED_DIST, I1, I2) 
    CALL REALLOCATE_INTEGER(SPREVLINK, I1, I2) 
    CALL REALLOCATE_INTEGER(SPREVLANE, I1, I2) 
    CALL REALLOCATE_INTEGER(SDRIVERTYPE, I1, I2) 
    CALL REALLOCATE_INTEGER(DRIVER_TYPE, I1, I2) 
    CALL REALLOCATE_INTEGER(SVLENGTH, I1, I2)         
    CALL REALLOCATE_INTEGER(SFLEET, I1, I2) 
    CALL REALLOCATE_INTEGER(SVTYPE, I1, I2) 
    CALL REALLOCATE_INTEGER_X(SLANECODES, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(STURNCODE, I1, I2) 
    CALL REALLOCATE_INTEGER(SPATHID, I1, I2) 
    CALL REALLOCATE_INTEGER(SPSAVE, I1, I2) 
    CALL REALLOCATE_INTEGER(SROUTEID, I1, I2) 
    CALL REALLOCATE_INTEGER(SPATHPOINT, I1, I2) 
    CALL REALLOCATE_INTEGER(SLAST_DETID, I1, I2)
    CALL REALLOCATE_INTEGER(SENTRY_LINK, I1, I2)
    CALL REALLOCATE_REAL(SLC_TIMER, I1, I2)
    CALL REALLOCATE_REAL(SLAG_TIMER, I1, I2)
    CALL REALLOCATE_REAL(SSTART_LAG, I1, I2)
    CALL REALLOCATE_REAL(SDESIREDSPEED, I1, I2) 
    CALL REALLOCATE_REAL(SSPEED, I1, I2) 
    CALL REALLOCATE_REAL(SSPEED_ADJ, I1, I2) 
    CALL REALLOCATE_REAL(SACCELERATION, I1, I2) 
    CALL REALLOCATE_REAL(SPREV_ACCEL, I1, I2) 
    CALL REALLOCATE_REAL(SLOCATION, I1, I2) 
    CALL REALLOCATE_REAL(SENTRYTIME, I1, I2)
    CALL REALLOCATE_REAL(SDISCH_TIMER, I1, I2)
    CALL REALLOCATE_LOGICAL(SGO_THRU_SIGNAL, I1, I2)
    CALL REALLOCATE_LOGICAL(FORCE_STOP, I1, I2)
    CALL REALLOCATE_LOGICAL(SWILL_COOP_LC, I1, I2)
    CALL REALLOCATE_REAL(SDECEL, I1, I2)
    CALL REALLOCATE_REAL(SEV_WAIT_TIMER, I1, I2)
    CALL REALLOCATE_INTEGER(SEV_WATCH, I1, I2)
    CALL REALLOCATE_INTEGER(SEV_RAND, I1, I2)
    CALL REALLOCATE_INTEGER(SEV_DIST, I1, I2)
    CALL REALLOCATE_LOGICAL(SWILL_COOP_EV, I1, I2)
    CALL REALLOCATE_LOGICAL(SWILL_MOVE, I1, I2)
    CALL REALLOCATE_LOGICAL(SDIVERTED, I1, I2)
    CALL REALLOCATE_INTEGER(SCF_MODEL, I1, I2)
    CALL REALLOCATE_INTEGER(SEV_OVRSPD, I1, I2)
    CALL REALLOCATE_INTEGER(SEV_RANGE, I1, I2)
        
    CALL REALLOCATE_INTEGER(GOAL_LANE, I1, I2) 
    CALL REALLOCATE_INTEGER(TURN_LINK, I1, I2) 
    CALL REALLOCATE_INTEGER(TURN_CODE, I1, I2) 
    CALL REALLOCATE_INTEGER(DESIRED_LANE, I1, I2) 
    CALL REALLOCATE_INTEGER(TURN_INDICATOR, I1, I2) 
    CALL REALLOCATE_INTEGER(ROUNDABOUT_EXIT, I1, I2) 
    CALL REALLOCATE_LOGICAL(FIRST_RIGHT, I1, I2) 
    CALL REALLOCATE_LOGICAL(IN_TURNING_WAY, I1, I2) 
    CALL REALLOCATE_INTEGER(TURN_CODE2, I1, I2) 
    CALL REALLOCATE_INTEGER(TURN_LINK2, I1, I2) 
    CALL REALLOCATE_INTEGER(NEXT_STOP, I1, I2) 
    CALL REALLOCATE_INTEGER(SXCODE, I1, I2)
    CALL REALLOCATE_INTEGER(QSTATE, I1, I2)
    CALL REALLOCATE_INTEGER(PREV_TURNCODE, I1, I2)
    CALL REALLOCATE_REAL(PRVDIST, I1, I2)
    CALL REALLOCATE_INTEGER(PRVLNKICD, I1, I2)
    CALL REALLOCATE_INTEGER(ICD_TURNCODE, I1, I2)
    CALL REALLOCATE_INTEGER(ICD_LINK, I1, I2)
    CALL REALLOCATE_INTEGER(SPDICD, I1, I2)
    CALL REALLOCATE_INTEGER(VEHICD, I1, I2)
    CALL REALLOCATE_INTEGER(VEHICD0, I1, I2)
    CALL REALLOCATE_REAL(DWELL_TIMER, I1, I2)
    CALL REALLOCATE_REAL(WAIT_TIME, I1, I2)
    CALL REALLOCATE_LOGICAL(WILL_YIELD, I1, I2)
    CALL REALLOCATE_LOGICAL(RTOR_FLAG, I1, I2)
    CALL REALLOCATE_LOGICAL(REDRUNNER, I1, I2)
    CALL REALLOCATE_LOGICAL(INDZ, I1, I2)
    CALL REALLOCATE_LOGICAL(WILL_JUMP, I1, I2)
    CALL REALLOCATE_LOGICAL(HAS_STOPPED, I1, I2)

    END SUBROUTINE
               
! ==================================================================================================
    SUBROUTINE DEALLOCATE_STREET_VEHICLE_ARRAYS
    IF(ALLOCATED(SID)) DEALLOCATE(SID)
    IF(ALLOCATED(SLEADER)) DEALLOCATE(SLEADER)
    IF(ALLOCATED(SPSEUDO_LEADER)) DEALLOCATE(SPSEUDO_LEADER)
    IF(ALLOCATED(SFOLLOWER)) DEALLOCATE(SFOLLOWER)
    IF(ALLOCATED(SLINK)) DEALLOCATE(SLINK)
    IF(ALLOCATED(SLANE)) DEALLOCATE(SLANE)
    IF(ALLOCATED(ARC_ENTRYLINK)) DEALLOCATE(ARC_ENTRYLINK)
    IF(ALLOCATED(ARC_ENTRYLANE)) DEALLOCATE(ARC_ENTRYLANE)
    IF(ALLOCATED(ARC_DIRECTION)) DEALLOCATE(ARC_DIRECTION)
    IF(ALLOCATED(ARC_LOCATION)) DEALLOCATE(ARC_LOCATION)
    IF(ALLOCATED(ARC_LENGTH)) DEALLOCATE(ARC_LENGTH)
    IF(ALLOCATED(LIMITED_SPEED_DIST)) DEALLOCATE(LIMITED_SPEED_DIST)
    IF(ALLOCATED(SPREVLINK)) DEALLOCATE(SPREVLINK)
    IF(ALLOCATED(SPREVLANE)) DEALLOCATE(SPREVLANE)
    IF(ALLOCATED(SDRIVERTYPE)) DEALLOCATE(SDRIVERTYPE)
    IF(ALLOCATED(DRIVER_TYPE)) DEALLOCATE(DRIVER_TYPE)
    IF(ALLOCATED(SVLENGTH)) DEALLOCATE(SVLENGTH)
    IF(ALLOCATED(SFLEET)) DEALLOCATE(SFLEET)
    IF(ALLOCATED(SVTYPE)) DEALLOCATE(SVTYPE)
    IF(ALLOCATED(SLANECODES)) DEALLOCATE(SLANECODES)
    IF(ALLOCATED(STURNCODE)) DEALLOCATE(STURNCODE)
    IF(ALLOCATED(SXCODE)) DEALLOCATE(SXCODE)
    IF(ALLOCATED(SPATHID)) DEALLOCATE(SPATHID)
    IF(ALLOCATED(SPSAVE)) DEALLOCATE(SPSAVE)
    IF(ALLOCATED(SROUTEID)) DEALLOCATE(SROUTEID)
    IF(ALLOCATED(SPATHPOINT)) DEALLOCATE(SPATHPOINT)
    IF(ALLOCATED(SLAST_DETID)) DEALLOCATE(SLAST_DETID)
    IF(ALLOCATED(SENTRY_LINK)) DEALLOCATE(SENTRY_LINK)
    IF(ALLOCATED(SLC_TIMER)) DEALLOCATE(SLC_TIMER)
    IF(ALLOCATED(SLAG_TIMER)) DEALLOCATE(SLAG_TIMER)
    IF(ALLOCATED(SSTART_LAG)) DEALLOCATE(SSTART_LAG)
    IF(ALLOCATED(SDESIREDSPEED)) DEALLOCATE(SDESIREDSPEED)
    IF(ALLOCATED(SSPEED)) DEALLOCATE(SSPEED)
    IF(ALLOCATED(SSPEED_ADJ)) DEALLOCATE(SSPEED_ADJ)
    IF(ALLOCATED(SACCELERATION)) DEALLOCATE(SACCELERATION)
    IF(ALLOCATED(SPREV_ACCEL)) DEALLOCATE(SPREV_ACCEL)
    IF(ALLOCATED(SLOCATION)) DEALLOCATE(SLOCATION)
    IF(ALLOCATED(SENTRYTIME)) DEALLOCATE(SENTRYTIME)
    IF(ALLOCATED(SDISCH_TIMER)) DEALLOCATE(SDISCH_TIMER)
    IF(ALLOCATED(SGO_THRU_SIGNAL)) DEALLOCATE(SGO_THRU_SIGNAL)
    IF(ALLOCATED(FORCE_STOP)) DEALLOCATE(FORCE_STOP)
    IF(ALLOCATED(SWILL_COOP_LC)) DEALLOCATE(SWILL_COOP_LC)
    IF(ALLOCATED(SDECEL)) DEALLOCATE(SDECEL)
    IF(ALLOCATED(SEV_WAIT_TIMER)) DEALLOCATE(SEV_WAIT_TIMER)
    IF(ALLOCATED(SEV_WATCH)) DEALLOCATE(SEV_WATCH)
    IF(ALLOCATED(SEV_RAND)) DEALLOCATE(SEV_RAND)
    IF(ALLOCATED(SEV_DIST)) DEALLOCATE(SEV_DIST)
    IF(ALLOCATED(SWILL_COOP_EV)) DEALLOCATE(SWILL_COOP_EV)
    IF(ALLOCATED(SWILL_MOVE)) DEALLOCATE(SWILL_MOVE)
    IF(ALLOCATED(SDIVERTED)) DEALLOCATE(SDIVERTED)
    IF(ALLOCATED(SCF_MODEL)) DEALLOCATE(SCF_MODEL)
    IF(ALLOCATED(SEV_OVRSPD)) DEALLOCATE(SEV_OVRSPD)
    IF(ALLOCATED(SEV_RANGE)) DEALLOCATE(SEV_RANGE)
        
    IF(ALLOCATED(GOAL_LANE)) DEALLOCATE(GOAL_LANE)
    IF(ALLOCATED(TURN_LINK)) DEALLOCATE(TURN_LINK)
    IF(ALLOCATED(TURN_CODE)) DEALLOCATE(TURN_CODE)
    IF(ALLOCATED(DESIRED_LANE)) DEALLOCATE(DESIRED_LANE)
    IF(ALLOCATED(TURN_INDICATOR)) DEALLOCATE(TURN_INDICATOR)
    IF(ALLOCATED(ROUNDABOUT_EXIT)) DEALLOCATE(ROUNDABOUT_EXIT)
    IF(ALLOCATED(FIRST_RIGHT)) DEALLOCATE(FIRST_RIGHT)
    IF(ALLOCATED(IN_TURNING_WAY)) DEALLOCATE(IN_TURNING_WAY)
    IF(ALLOCATED(TURN_CODE2)) DEALLOCATE(TURN_CODE2)
    IF(ALLOCATED(TURN_LINK2)) DEALLOCATE(TURN_LINK2)
    IF(ALLOCATED(NEXT_STOP)) DEALLOCATE(NEXT_STOP)
    IF(ALLOCATED(QSTATE)) DEALLOCATE(QSTATE)
    IF(ALLOCATED(PREV_TURNCODE)) DEALLOCATE(PREV_TURNCODE)
    IF(ALLOCATED(PRVDIST)) DEALLOCATE(PRVDIST)
    IF(ALLOCATED(PRVLNKICD)) DEALLOCATE(PRVLNKICD)
    IF(ALLOCATED(ICD_TURNCODE)) DEALLOCATE(ICD_TURNCODE)
    IF(ALLOCATED(ICD_LINK)) DEALLOCATE(ICD_LINK)
    IF(ALLOCATED(SPDICD)) DEALLOCATE(SPDICD)
    IF(ALLOCATED(VEHICD)) DEALLOCATE(VEHICD)
    IF(ALLOCATED(VEHICD0)) DEALLOCATE(VEHICD0)
    IF(ALLOCATED(DWELL_TIMER)) DEALLOCATE(DWELL_TIMER)
    IF(ALLOCATED(WAIT_TIME)) DEALLOCATE(WAIT_TIME)
    IF(ALLOCATED(WILL_YIELD)) DEALLOCATE(WILL_YIELD)
    IF(ALLOCATED(RTOR_FLAG)) DEALLOCATE(RTOR_FLAG)
    IF(ALLOCATED(REDRUNNER)) DEALLOCATE(REDRUNNER)
    IF(ALLOCATED(INDZ)) DEALLOCATE(INDZ)
    IF(ALLOCATED(WILL_JUMP)) DEALLOCATE(WILL_JUMP)
    IF(ALLOCATED(HAS_STOPPED)) DEALLOCATE(HAS_STOPPED)
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE WRITE_STREET_VEHICLE_TRAJECTORIES
    USE SIMPARAMS
    USE TEXT
    INCLUDE 'IOFILES.INC'
    INTEGER :: N = 1, IV, TOTAL
! ----------------------------------------------------------------------
    IF(SIMTIME .EQ. 0) THEN
      OPEN(N, FILE = LINFNAME(1:IROOT)//'VTRAJ', ERR=10, IOMSG=ETEXT)
    ELSE
      OPEN(N, FILE = LINFNAME(1:IROOT)//'VTRAJ', ACCESS='APPEND', ERR=10, IOMSG=ETEXT)
    ENDIF
    TOTAL = 0
    DO IV = 1, HIGHEST_INDEX_S
      IF(SID(IV) .NE. 0) TOTAL = TOTAL + 1
    ENDDO
    WRITE(N, *) SIMTIME, TOTAL
    IF(TOTAL .GT. 0) THEN
      DO IV = 1, HIGHEST_INDEX_S
        IF(SID(IV) .NE. 0) THEN
          WRITE(N, *) SID(IV)
          WRITE(N, *) SFLEET(IV)
          WRITE(N, *) SVTYPE(IV)
          WRITE(N, *) SLINK(IV)
          WRITE(N, *) SLANE(IV)
          WRITE(N, *) SLOCATION(IV)
          WRITE(N, *) SSPEED(IV)
          WRITE(N, *) SACCELERATION(IV)
          WRITE(N, *) SPREV_ACCEL(IV)
        ENDIF
      ENDDO
    ENDIF
    CLOSE(N)
10  CONTINUE 
    WRITE(MSGTEXT,'(A)') 'FILE OPEN ERROR: WRITE_STREET_VEHICLE_TRAJECTORIES'
    CALL SENDTEXTMSG(M_INFO)
    WRITE(MSGTEXT, '(A)') ETEXT
    CALL SENDTEXTMSG(M_ERROR)
    ERROR_FLAG = 1
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE SAVE_STREET_VEHICLES(FILE)
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: IV, TOTAL, N
! ----------------------------------------------------------------------
    WRITE(FILE) MAX_VEHICLES_S
    TOTAL = 0
    DO CONCURRENT (IV = 1: HIGHEST_INDEX_S)
      IF(SID(IV) .NE. 0) TOTAL = TOTAL + 1
    ENDDO
    WRITE(FILE) TOTAL
    IF(TOTAL .GT. 0) THEN
      DO IV = 1, HIGHEST_INDEX_S
        IF(SID(IV) .NE. 0) THEN
          WRITE(FILE) IV
          WRITE(FILE) SID(IV)
          WRITE(FILE) SFLEET(IV)
          WRITE(FILE) SVTYPE(IV)
          WRITE(FILE) SLINK(IV)
          WRITE(FILE) SLANE(IV)
          WRITE(FILE) SLOCATION(IV)
          WRITE(FILE) SSPEED(IV)
          WRITE(FILE) SACCELERATION(IV)
          WRITE(FILE) SPREV_ACCEL(IV)
          WRITE(FILE) SVLENGTH(IV)        
          WRITE(FILE) SLEADER(IV)
          WRITE(FILE) SPSEUDO_LEADER(IV)
          WRITE(FILE) SFOLLOWER(IV)
          WRITE(FILE) ARC_ENTRYLINK(IV)
          WRITE(FILE) ARC_ENTRYLANE(IV)
          WRITE(FILE) ARC_DIRECTION(IV)
          WRITE(FILE) ARC_LOCATION(IV)
          WRITE(FILE) ARC_LENGTH(IV)
          WRITE(FILE) ARC_LENGTH(IV)
          WRITE(FILE) LIMITED_SPEED_DIST(IV)
          WRITE(FILE) SPREVLINK(IV)
          WRITE(FILE) SPREVLANE(IV)
          WRITE(FILE) SDRIVERTYPE(IV)
          WRITE(FILE) DRIVER_TYPE(IV)
          WRITE(FILE) (SLANECODES(IV, N), N = 1, N_STREET_LANES)
          WRITE(FILE) STURNCODE(IV)
          WRITE(FILE) SPATHID(IV)
          WRITE(FILE) SPSAVE(IV)
          WRITE(FILE) SROUTEID(IV)
          WRITE(FILE) SPATHPOINT(IV)
          WRITE(FILE) SXCODE(IV)
          WRITE(FILE) SLAST_DETID(IV)
          WRITE(FILE) SENTRY_LINK(IV)
          WRITE(FILE) SLC_TIMER(IV)
          WRITE(FILE) SLAG_TIMER(IV)
          WRITE(FILE) SSTART_LAG(IV)
          WRITE(FILE) SDESIREDSPEED(IV)
          WRITE(FILE) SSPEED_ADJ(IV)
          WRITE(FILE) SENTRYTIME(IV)
          WRITE(FILE) SDISCH_TIMER(IV)
          WRITE(FILE) SGO_THRU_SIGNAL(IV)
          WRITE(FILE) FORCE_STOP(IV)
          WRITE(FILE) SWILL_COOP_LC(IV)
          WRITE(FILE) SDECEL(IV)
          WRITE(FILE) SEV_WATCH(IV)
          WRITE(FILE) SEV_RAND(IV)
          WRITE(FILE) SEV_WAIT_TIMER(IV)
          WRITE(FILE) SEV_DIST(IV)
          WRITE(FILE) SWILL_COOP_EV(IV)
          WRITE(FILE) SWILL_MOVE(IV)
          WRITE(FILE) SDIVERTED(IV)
          WRITE(FILE) SCF_MODEL(IV)
          WRITE(FILE) SEV_OVRSPD(IV)
          WRITE(FILE) SEV_RANGE(IV)

          WRITE(FILE) GOAL_LANE(IV)
          WRITE(FILE) TURN_LINK(IV)
          WRITE(FILE) TURN_CODE(IV)
          WRITE(FILE) DESIRED_LANE(IV)
          WRITE(FILE) TURN_INDICATOR(IV)
          WRITE(FILE) ROUNDABOUT_EXIT(IV)
          WRITE(FILE) FIRST_RIGHT(IV)
          WRITE(FILE) IN_TURNING_WAY(IV)
          WRITE(FILE) TURN_CODE2(IV)
          WRITE(FILE) TURN_LINK2(IV)
          WRITE(FILE) NEXT_STOP(IV)
          WRITE(FILE) QSTATE(IV)
          WRITE(FILE) PREV_TURNCODE(IV)
          WRITE(FILE) PRVDIST(IV)
          WRITE(FILE) PRVLNKICD(IV)
          WRITE(FILE) ICD_TURNCODE(IV)
          WRITE(FILE) ICD_LINK(IV)
          WRITE(FILE) SPDICD(IV)
          WRITE(FILE) VEHICD(IV)
          WRITE(FILE) VEHICD0(IV)
          WRITE(FILE) DWELL_TIMER(IV)
          WRITE(FILE) WAIT_TIME(IV)
          WRITE(FILE) WILL_YIELD(IV)
          WRITE(FILE) RTOR_FLAG(IV)
          WRITE(FILE) REDRUNNER(IV)
          WRITE(FILE) INDZ(IV)
          WRITE(FILE) WILL_JUMP(IV)
          WRITE(FILE) HAS_STOPPED(IV)
        ENDIF
      ENDDO
    ENDIF
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE RESTORE_STREET_VEHICLE(FILE)
    INTEGER, INTENT(IN) :: FILE
    INTEGER :: IV, TOTAL, I, N
! ----------------------------------------------------------------------
    READ(FILE) MAX_VEHICLES_S
    READ(FILE) TOTAL
    CALL ALLOCATE_STREET_VEHICLE_ARRAYS
    IF(TOTAL .GT. 0) THEN
      DO I = 1, TOTAL
        READ(FILE) IV
        READ(FILE) SID(IV)
        READ(FILE) SFLEET(IV)
        READ(FILE) SVTYPE(IV)
        READ(FILE) SLINK(IV)
        READ(FILE) SLANE(IV)
        READ(FILE) SLOCATION(IV)
        READ(FILE) SSPEED(IV)
        READ(FILE) SACCELERATION(IV)
        READ(FILE) SPREV_ACCEL(IV)
        READ(FILE) SVLENGTH(IV)        
        READ(FILE) SLEADER(IV)
        READ(FILE) SPSEUDO_LEADER(IV)
        READ(FILE) SFOLLOWER(IV)
        READ(FILE) ARC_ENTRYLINK(IV)
        READ(FILE) ARC_ENTRYLANE(IV)
        READ(FILE) ARC_DIRECTION(IV)
        READ(FILE) ARC_LOCATION(IV)
        READ(FILE) ARC_LENGTH(IV)
        READ(FILE) LIMITED_SPEED_DIST(IV)
        READ(FILE) SPREVLINK(IV)
        READ(FILE) SPREVLANE(IV)
        READ(FILE) SDRIVERTYPE(IV)
        READ(FILE) DRIVER_TYPE(IV)
        READ(FILE) (SLANECODES(IV, N), N = 1, N_STREET_LANES)
        READ(FILE) STURNCODE(IV)
        READ(FILE) SPATHID(IV)
        READ(FILE) SPSAVE(IV)
        READ(FILE) SROUTEID(IV)
        READ(FILE) SPATHPOINT(IV)
        READ(FILE) SXCODE(IV)
        READ(FILE) SLAST_DETID(IV)
        READ(FILE) SENTRY_LINK(IV)
        READ(FILE) SLC_TIMER(IV)
        READ(FILE) SLAG_TIMER(IV)
        READ(FILE) SSTART_LAG(IV)
        READ(FILE) SDESIREDSPEED(IV)
        READ(FILE) SSPEED_ADJ(IV)
        READ(FILE) SENTRYTIME(IV)
        READ(FILE) SDISCH_TIMER(IV)
        READ(FILE) SGO_THRU_SIGNAL(IV)
        READ(FILE) FORCE_STOP(IV)
        READ(FILE) SWILL_COOP_LC(IV)
        READ(FILE) SDECEL(IV)
        READ(FILE) SEV_WATCH(IV)
        READ(FILE) SEV_RAND(IV)
        READ(FILE) SEV_WAIT_TIMER(IV)
        READ(FILE) SEV_DIST(IV)
        READ(FILE) SWILL_COOP_EV(IV)
        READ(FILE) SWILL_MOVE(IV)
        READ(FILE) SDIVERTED(IV)
        READ(FILE) SCF_MODEL(IV)
        READ(FILE) SEV_OVRSPD(IV)
        READ(FILE) SEV_RANGE(IV)

        READ(FILE) GOAL_LANE(IV)
        READ(FILE) TURN_LINK(IV)
        READ(FILE) TURN_CODE(IV)
        READ(FILE) DESIRED_LANE(IV)
        READ(FILE) TURN_INDICATOR(IV)
        READ(FILE) ROUNDABOUT_EXIT(IV)
        READ(FILE) FIRST_RIGHT(IV)
        READ(FILE) IN_TURNING_WAY(IV)
        READ(FILE) TURN_CODE2(IV)
        READ(FILE) TURN_LINK2(IV)
        READ(FILE) NEXT_STOP(IV)
        READ(FILE) QSTATE(IV)
        READ(FILE) PREV_TURNCODE(IV)
        READ(FILE) PRVDIST(IV)
        READ(FILE) PRVLNKICD(IV)
        READ(FILE) ICD_TURNCODE(IV)
        READ(FILE) ICD_LINK(IV)
        READ(FILE) SPDICD(IV)
        READ(FILE) VEHICD(IV)
        READ(FILE) VEHICD0(IV)
        READ(FILE) DWELL_TIMER(IV)
        READ(FILE) WAIT_TIME(IV)
        READ(FILE) WILL_YIELD(IV)
        READ(FILE) RTOR_FLAG(IV)
        READ(FILE) REDRUNNER(IV)
        READ(FILE) INDZ(IV)
        READ(FILE) WILL_JUMP(IV)
        READ(FILE) HAS_STOPPED(IV)
      ENDDO
    ENDIF
    RETURN
    END SUBROUTINE

    END MODULE 







