! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

MODULE API_DATA
  USE GLOBAL_DATA
  INTEGER, PARAMETER :: NVTYPES = 36
  INTEGER, ALLOCATABLE :: FLOW_RATE(:,:)
  INTEGER, ALLOCATABLE :: FTHRU_PCT(:,:)
  INTEGER, ALLOCATABLE :: LEFT_PCT(:,:)
  INTEGER, ALLOCATABLE :: STHRU_PCT(:,:)
  INTEGER, ALLOCATABLE :: RIGHT_PCT(:,:)
  INTEGER, ALLOCATABLE :: LDIAG_PCT(:,:)
  INTEGER, ALLOCATABLE :: RDIAG_PCT(:,:)
  
  REAL,    ALLOCATABLE :: METER_HEADWAY1(:,:)
  INTEGER, ALLOCATABLE :: METER_ONSET(:,:)
  LOGICAL, ALLOCATABLE :: METER_TWOPERGREEN(:,:)
 
  INTEGER, ALLOCATABLE :: DURATIONS(:,:,:)
  INTEGER, ALLOCATABLE :: SIGCODES(:,:,:,:)
                        
  TYPE NODE_LOCATION_DATA
    INTEGER :: X
    INTEGER :: Y
    REAL    :: LATITUDE
    REAL    :: LONGITUDE
    INTEGER :: ELEVATION
    LOGICAL :: IS_USED
    LOGICAL :: IS_DEFINED
  END TYPE
  
  TYPE API_DETECTOR_DATA
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: ASSOCIATED_PHASE
    INTEGER :: STATION_ID
    REAL    :: LOCATION
    INTEGER :: LANE1
    INTEGER :: LANE2
    INTEGER :: ZONE_LENGTH
    REAL    :: DELAY_TIME
    REAL    :: CARRYOVER_TIME
    INTEGER :: NEXT_DET
    INTEGER :: TYPE_CODE
    INTEGER :: OPERATION_CODE
    INTEGER :: COUNT
    INTEGER :: CURRENT_STATE
    REAL    :: ON_TIME
    REAL    :: SPEED_TOTAL
    INTEGER :: HDWY_COUNT
    REAL    :: HDWY_TOTAL
  END TYPE
    
  TYPE FREEWAY_LINK
    INTEGER :: ID
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: USN_TYPE
    INTEGER :: DSN_TYPE
    INTEGER :: LINKTYPE
    INTEGER :: THRUNODE
    INTEGER :: EXITNODE
    INTEGER :: LENGTH
    INTEGER :: MAINLINE_SENDING_LANE
    INTEGER :: MAINLINE_RECEIVING_LANE
    INTEGER :: OFFRAMP_SENDING_LANE
    INTEGER :: OFFRAMP_RECEIVING_LANE
    INTEGER :: FULLLANES
    INTEGER :: ADDDROP_CODE(3)                  
    INTEGER :: ADDDROP_LANE(3)                  
    INTEGER :: ADDDROP_DIST(3)                  
    INTEGER :: ADDDROP_WARN(3)                  
    INTEGER :: AUXLANEID(N_AUXLANES)
    INTEGER :: AUXLANECODE(N_AUXLANES)
    INTEGER :: AUXLANELENGTH(N_AUXLANES)
    INTEGER :: FREEFLOWSPEED
    INTEGER :: THRUPCT
    INTEGER :: OFFRAMP_WARN_DISTANCE
    INTEGER :: ANTICIP_WARNING_DISTANCE
    INTEGER :: ANTICIP_WARNING_SPEED
    INTEGER :: NHOV_LANES
    INTEGER :: HOV_BEGIN
    INTEGER :: HOV_END
    INTEGER :: HOV_CODE
    INTEGER :: HOV_OFFRAMP_WARN_DISTANCE
    INTEGER :: HOV_SIDE
    INTEGER :: HOV_TYPE
    INTEGER :: HOV_WARN
    REAL    :: HOV_PCT
    REAL    :: CFMULT
    INTEGER :: FIRST_DETECTOR
    REAL    :: GRADE
    REAL    :: TILT
    REAL    :: CURVE
    INTEGER :: PAVEMENT
    REAL    :: SHOULDER_WIDTH
    REAL    :: LANE_WIDTH(N_FREEWAY_LANES)
    INTEGER :: BARRIER(2)
    INTEGER :: DATASTATION_ID
    INTEGER :: DATASTATION_LOCATION
    INTEGER :: TRUCK_CODE
    INTEGER :: TRUCK_DIR
    INTEGER :: TRUCK_LANE
    INTEGER :: ETL_WARN
    INTEGER :: EXCLUDE_TYPE(N_FREEWAY_LANES, NVTYPES)
    REAL    :: MULTIPLIER_EXIT(NVTYPES)
    REAL    :: STARTUP_TIME
    INTEGER :: MERGE_DIVERGE_CODE
  END TYPE
    
  TYPE STREET_LINK
    INTEGER :: ID
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: USN_TYPE
    INTEGER :: DSN_TYPE
    INTEGER :: THRUNODE
    INTEGER :: LEFTNODE
    INTEGER :: RIGHTNODE
    INTEGER :: LDIAGNODE
    INTEGER :: RDIAGNODE
    INTEGER :: OPPOSENODE
    INTEGER :: LENGTH
    INTEGER :: FULLLANES
    INTEGER :: LEFTTURNBAYS
    INTEGER :: RIGHTTURNBAYS
    INTEGER :: FREEFLOWSPEED
    INTEGER :: CHANNELIZATION(N_STREET_LANES)
    REAL    :: LANE_LENGTH(N_STREET_LANES)
    INTEGER :: LEFTPCT
    INTEGER :: THRUPCT
    INTEGER :: RIGHTPCT
    INTEGER :: LDIAGPCT
    INTEGER :: RDIAGPCT
    REAL    :: GRADE
    INTEGER :: DISTRIBUTION_CODE
    REAL    :: STARTUP_DELAY
    REAL    :: DISCHARGE_HDWY
    INTEGER :: RTOR
    INTEGER :: PED_CODE
    INTEGER :: LANE1
    INTEGER :: LANE2
    REAL    :: CFMULT
    INTEGER :: SIGHT_DIST
    INTEGER :: FIRST_DETECTOR
    REAL    :: SHOULDER_WIDTH
    REAL    :: LANE_WIDTH(N_STREET_LANES)
    INTEGER :: STE_FREQ
    INTEGER :: STE_DURATION
    INTEGER :: SIGNAL_RANGE
    INTEGER :: CENTROID
    INTEGER :: CENTROID_LABEL
    INTEGER :: EXCLUDE_TYPE(N_STREET_LANES, NVTYPES)
    REAL    :: MULTIPLIER_LEFT(NVTYPES)
    REAL    :: MULTIPLIER_THRU(NVTYPES)
    REAL    :: MULTIPLIER_RIGHT(NVTYPES)
    REAL    :: MULTIPLIER_LDIAG(NVTYPES)
    REAL    :: MULTIPLIER_RDIAG(NVTYPES)
    INTEGER :: LT_SPEED
    INTEGER :: RT_SPEED
    REAL    :: LT_LIMITED_SPEED_DIST
    REAL    :: RT_LIMITED_SPEED_DIST
  END TYPE
  
  TYPE INTERSECTION_DIMENSIONS
    REAL :: UP_INT_WIDTH
    REAL :: LANE_CENTER(N_STREET_LANES)
    REAL :: LT_ARC_LENGTH(N_STREET_LANES, N_STREET_LANES)
    REAL :: THRU_ARC_LENGTH(N_STREET_LANES, N_STREET_LANES)
    REAL :: RT_ARC_LENGTH(N_STREET_LANES, N_STREET_LANES)
    REAL :: LD_ARC_LENGTH(N_STREET_LANES, N_STREET_LANES)
    REAL :: RD_ARC_LENGTH(N_STREET_LANES, N_STREET_LANES)
  END TYPE
  
  TYPE ANIMATION_DATA
    INTEGER :: ID
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: SIGNALIZED
    INTEGER :: FIRST_VEHICLE(N_STREET_LANES)
    INTEGER :: FIRST_ON_SHOULDER
    INTEGER :: SIGNAL_CODE
    INTEGER :: PREV_SIGNAL_CODE
    INTEGER :: SIGNAL_LEFT
    INTEGER :: SIGNAL_THRU
    INTEGER :: SIGNAL_RIGHT
    INTEGER :: SIGNAL_DIAG
    INTEGER :: AMBER_LEFT
    INTEGER :: AMBER_THRU
    INTEGER :: AMBER_RIGHT
    INTEGER :: AMBER_DIAG
  END TYPE
  
  TYPE COORDINATION_INPUTS
    INTEGER :: NODE
    REAL    :: CYCLE_LENGTH
    REAL    :: OFFSET
   END TYPE    
  
  TYPE API_ACTUATED_DATA
    INTEGER :: NODE
    INTEGER :: CFAILS
    INTEGER :: ADJ
    INTEGER :: ACTUATED_MODE(8)
    LOGICAL :: LEFTARROW(8, 10)
    LOGICAL :: THRUARROW(8, 10)
    LOGICAL :: RIGHTARROW(8, 10)
    LOGICAL :: DIAGARROW(8, 10)
    REAL    :: MIN_GREEN_TIME(8)
    REAL    :: MAX_GREEN_TIME(8)
    REAL    :: DEFAULT_EXTENSION_TIME(8)
    REAL    :: GAP_TIME(8)
    REAL    :: TIME_BEFORE_REDUCTION(8)
    REAL    :: TIME_TO_REDUCE(8)
    REAL    :: MIN_GAP_TIME(8)
    REAL    :: YC(8)
    REAL    :: RC(8)
    INTEGER :: N_DIRECT_APPROACHES
    INTEGER :: DIRECT_APPROACH_USN(20)
    INTEGER :: N_INDIRECT_APPROACHES
    INTEGER :: INDIRECT_APPROACH_USN(5)
    INTEGER :: INDIRECT_APPROACH_DSN(5)
    REAL    :: CYCLE_LENGTH
    REAL    :: OFFSET
    INTEGER :: RING_PHASE(8)
    INTEGER :: DETECTOR_COUNT
    INTEGER :: DETECTOR_LIST(64)
    INTEGER :: TRANSITION_METHOD
    REAL    :: MAX_ADD
    REAL    :: MAX_SUBTRACT
    REAL    :: FORCE_OFF_TIMES(8)
    REAL    :: SPLITS(8)
    LOGICAL :: PED_OMIT(8)
    INTEGER :: PED_INTENSITY(8)
    INTEGER :: PED_HEADWAY(8)
    INTEGER :: PED_START_TIME(8)
    INTEGER :: PED_RECALL_CODE(8)
    REAL    :: WALK_TIME(8)
    REAL    :: WALK_CLEARANCE_TIME(8)
  END TYPE
    
  TYPE ENTRY_NODE_DATA
    INTEGER :: NODE_ID
    !INTEGER :: NODE_ID_LEFT
    !INTEGER :: NODE_ID_THRU
    !INTEGER :: NODE_ID_RIGHT
    !INTEGER :: NODE_ID_LDIAG
    !INTEGER :: NODE_ID_RDIAG
    INTEGER :: FLOWRATE
    REAL    :: CARPOOL_PCT
    REAL    :: TRUCK_PCT
    INTEGER :: HOV_VIOLATORS_PER10000
    INTEGER :: LANE_PCT(10)
  END TYPE
    
  TYPE SOURCE_SINK_DATA
    INTEGER :: SS_USN
    INTEGER :: SS_DSN
    INTEGER :: CENTROID_LABEL
    REAL    :: CARPOOL_PCT
    REAL    :: TRUCK_PCT
    INTEGER :: FLOWRATE
    INTEGER :: HOV_VIOLATORS_PER10000
  END TYPE
    
  TYPE FV_STRUCT
    REAL    :: ACCELERATION
    REAL    :: DECEL
    REAL    :: DESIREDSPEED
    REAL    :: DISCH_TIMER
    INTEGER :: DRIVERTYPE    
    INTEGER :: ENTRY_LINK
    REAL    :: ENTRYTIME
    INTEGER :: EV_DIST
    INTEGER :: EV_OVRSPD
    INTEGER :: EV_RANGE
    INTEGER :: EV_RAND
    REAL    :: EV_WAIT_TIMER
    INTEGER :: EV_WATCH
    INTEGER :: FLEET
    LOGICAL :: GO_THRU_SIGNAL
    REAL    :: LAG_TIMER
    INTEGER :: LANE
    INTEGER :: LANECODES(N_FREEWAY_LANES)
    INTEGER :: LINK
    INTEGER :: FOLLOWER
    INTEGER :: ID
    INTEGER :: LAST_DETID
    REAL    :: LC_TIMER
    INTEGER :: LEADER
    REAL    :: LOCATION
    INTEGER :: PATHID
    INTEGER :: PATHPOINT
    INTEGER :: PSAVE
    INTEGER :: PSEUDO_LEADER
    REAL    :: PREV_ACCEL
    INTEGER :: PREVLINK
    INTEGER :: PREVLANE
    INTEGER :: ROUTEID
    REAL    :: SPEED
    REAL    :: SPEED_ADJ
    INTEGER :: TURNCODE
    INTEGER :: VLENGTH        
    INTEGER :: VTYPE
    INTEGER :: XCODE
    LOGICAL :: WILL_COOP_EV
    LOGICAL :: WILL_COOP_LC
    LOGICAL :: WILL_MOVE
    INTEGER :: DESTINATION
    REAL    :: DISTANCE_TO_SEGMENT_END
    LOGICAL :: DIVERTED
    LOGICAL :: HOV_VIOLATOR
    INTEGER :: IMETER
    INTEGER :: INCIDENT_NUM
    INTEGER :: ISEGMENT
    LOGICAL :: MUST_MERGE
    INTEGER :: NEXT_OBJECT
    REAL    :: REMAINING_DIST
    INTEGER :: SORTED_LIST
    INTEGER :: SORT_POSITION
    INTEGER :: CF_MODEL
  END TYPE
    
  TYPE SV_STRUCT
    REAL    :: ACCELERATION
    REAL    :: DECEL
    REAL    :: DESIREDSPEED
    REAL    :: DISCH_TIMER
    INTEGER :: DRIVERTYPE    
    INTEGER :: ENTRY_LINK
    REAL    :: ENTRYTIME
    INTEGER :: EV_DIST
    INTEGER :: EV_OVRSPD
    INTEGER :: EV_RANGE
    INTEGER :: EV_RAND
    REAL    :: EV_WAIT_TIMER
    INTEGER :: EV_WATCH
    INTEGER :: FLEET
    LOGICAL :: GO_THRU_SIGNAL
    REAL    :: LAG_TIMER
    INTEGER :: LANE
    INTEGER :: LANECODES(N_STREET_LANES)
    INTEGER :: LINK
    INTEGER :: FOLLOWER
    INTEGER :: ID
    INTEGER :: LAST_DETID
    REAL    :: LC_TIMER
    INTEGER :: LEADER
    REAL    :: LOCATION
    INTEGER :: PATHID
    INTEGER :: PATHPOINT
    INTEGER :: PSAVE
    INTEGER :: PSEUDO_LEADER
    REAL    :: PREV_ACCEL
    INTEGER :: PREVLINK
    INTEGER :: PREVLANE
    INTEGER :: ROUTEID
    REAL    :: SPEED
    REAL    :: SPEED_ADJ
    REAL    :: START_LAG
    INTEGER :: TURNCODE
    INTEGER :: VLENGTH        
    INTEGER :: VTYPE
    INTEGER :: XCODE
    LOGICAL :: WILL_COOP_EV
    LOGICAL :: WILL_COOP_LC
    LOGICAL :: WILL_MOVE
    LOGICAL :: DIVERTED
    REAL    :: DWELL_TIMER
    INTEGER :: GOAL_LANE
    LOGICAL :: HAS_STOPPED
    INTEGER :: SPDICD
    INTEGER :: NEXT_STOP
    INTEGER :: PRVDIST
    INTEGER :: ICD_LINK
    INTEGER :: PRVLNKICD
    INTEGER :: QSTATE
    INTEGER :: TURN_CODE
    INTEGER :: TURN_CODE2
    INTEGER :: TURN_LINK
    INTEGER :: TURN_LINK2
    INTEGER :: VEHICD
    INTEGER :: VEHICD0
    LOGICAL :: WILL_JUMP
    LOGICAL :: WILL_YIELD
    INTEGER :: CF_MODEL
    REAL    :: ARC_LOCATION
    INTEGER :: ARC_ENTRYLINK
    INTEGER :: ARC_ENTRYLANE
  END TYPE
    
  TYPE NETWORK_INPUTS
    INTEGER :: RUN_INIT
    INTEGER :: INITIALIZATION_END
    INTEGER :: TIME_PERIOD_DURATION(19)
    INTEGER :: TIME_INTERVAL
    REAL    :: TIMESTEP
    INTEGER :: TYPE_OF_RUN
    INTEGER :: SIM_START_TIME
    INTEGER :: MAX_NODE_NUMBER
    REAL    :: DLC_MULT
    REAL    :: DLC_THRESHOLD
  END TYPE
  
  TYPE API_CAR_FOLLOWING
    REAL :: ACC_TG
    REAL :: ACC_AMAX
    REAL :: ACC_DMAX
    REAL :: ACC_K1
    REAL :: ACC_K2
    REAL :: CACC_TG
    REAL :: CACC_AMAX
    REAL :: CACC_DMAX
    REAL :: CACC_K1
    REAL :: CACC_K2
  END TYPE
  
  TYPE FREEWAY_NETWORK_INPUTS
    REAL    :: CFRICT(4)
    REAL    :: DEFAULT_HOV_PCT
    REAL    :: LAG_ACCEL
    REAL    :: LAG_DECEL
    REAL    :: FFSPEED_ADJ(10)
    REAL    :: ZFOLL_PITT(10)
    REAL    :: ZFOLL_IDM(10)
    INTEGER :: PITT_SEP
    INTEGER :: IDM_SEP
    REAL    :: FREEWAY_PCT_COOP
    REAL    :: LC_TIME
  END TYPE
  
  TYPE STREET_NETWORK_INPUTS
    REAL    :: ADDITIONAL_GAP(10)
    INTEGER :: AMBER_DECEL(10)
    INTEGER :: PDELAY_WEAK(10)
    INTEGER :: PDELAY_STRONG(10)
    INTEGER :: PED_DURATION(3)
    REAL    :: ACCEPTABLE_GAP(10)
    REAL    :: ACCEPTABLE_LTG(10)     
    REAL    :: ACCEPTABLE_RTG(10)
    REAL    :: DWELL_MULTIPLIER(6, 10)
    REAL    :: FFSPEED_ADJ(10)
    REAL    :: ZFOLL_PITT(10)
    REAL    :: ZFOLL_IDM(10)
    INTEGER :: PITT_SEP
    INTEGER :: IDM_SEP
    REAL    :: LC_TIME
    REAL    :: LT_JUMPER_PROB(N_STREET_LANES)
    REAL    :: LT_LAGGER_PROB(3)
    REAL    :: SPILLBACK_PROB(4)
    REAL    :: STOP_SPD
    REAL    :: STREET_PCT_COOP
    REAL    :: YIELD_SPD
    REAL    :: DRIVER_FAMPCT
    REAL    :: QFACTOR(5)
    REAL    :: STE_MULT(10)
    REAL    :: TURNSIGNAL_PROB(10)
    REAL    :: TURNSIGNAL_DIST
  END TYPE
    
  TYPE BUSR
    INTEGER :: NUMBER
    INTEGER :: HDWY
    INTEGER :: OFFSET
    INTEGER :: NNODES
    INTEGER :: ROUTE_NODES(200)
    INTEGER :: STATIONLIST(100) 
    INTEGER :: PERSONTRIPS
    INTEGER :: TIMER
    INTEGER :: TRAVELTIME
    INTEGER :: TRIPS
  END TYPE

  TYPE BUSSTATION_DATA
    INTEGER :: STATION_NUMBER
    INTEGER :: BLOCK_CODE
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: CAPACITY 
    INTEGER :: TYPE_CODE
    INTEGER :: LOCATION
    INTEGER :: DWELL
    REAL    :: BYPASS_PCT
    INTEGER :: NEXT_STATION
    INTEGER :: POCKET_LANE
    INTEGER :: FRONT
    INTEGER :: COUNT
    REAL    :: DWELL_TIME
    REAL    :: EMPTY_TIME
    REAL    :: OVERFLOW_TIME
  END TYPE

  TYPE DETECTOR_INPUTS
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: SIGNAL_NODE
    REAL    :: CARRYOVER_TIME
    REAL    :: DELAY_TIME
    INTEGER :: LINK
    INTEGER :: LANE1
    INTEGER :: LANE2
    REAL    :: LOCATION
    INTEGER :: OPERATION_CODE
    INTEGER :: TYPE_CODE
    INTEGER :: STATION_ID
    REAL    :: ZONE_LENGTH
    INTEGER :: ASSOCIATED_PHASE
    INTEGER :: DETECTION_ZONE
    INTEGER :: NEXT_DET
  END TYPE

  TYPE DETECTOR_OUTPUTS
    INTEGER :: COUNT
    INTEGER :: CURRENT_STATE
    INTEGER :: PREVIOUS_STATE
    INTEGER :: HDWY_COUNT
    REAL    :: HDWY_TOTAL
    REAL    :: ON_TIME
    REAL    :: SPEED_TOTAL
    INTEGER :: LENGTH_TOTAL
    REAL    :: LAST_ACTUATION_TIME
    REAL    :: LAST_SPEED
    INTEGER :: LAST_LENGTH
    INTEGER :: CURRENT_STATE_TEMP(10)
    INTEGER :: PREVIOUS_STATE_TEMP(10)
  END TYPE
    
  TYPE EVENT_DATA
   INTEGER :: USN
   INTEGER :: DSN
   INTEGER :: LANE
   INTEGER :: BEGIN_TIME
   INTEGER :: END_TIME
   INTEGER :: LOCATION
   INTEGER :: SPEED_REDUCTION  
   INTEGER :: LENGTH 
   INTEGER :: CODE
  END TYPE

  TYPE PARKING_DATA
   INTEGER :: USN
   INTEGER :: DSN
   INTEGER :: DURATION
   INTEGER :: FREQ
   INTEGER :: LEFT_START
   INTEGER :: LEFT_LEN
   INTEGER :: RIGHT_START
   INTEGER :: RIGHT_LEN
  END TYPE

  TYPE INCIDENT_DATA
   INTEGER :: USN
   INTEGER :: DSN
   INTEGER :: BEGIN_POINT
   INTEGER :: BEGIN_TIME
   INTEGER :: END_POINT
   INTEGER :: END_TIME
   INTEGER :: RBNF
   INTEGER :: WARN_POINT
   INTEGER :: CODE(N_FREEWAY_LANES)
  END TYPE

  TYPE DIVERSION_DATA
   INTEGER :: USN
   INTEGER :: DSN
   INTEGER :: BEGIN_TIME
   INTEGER :: END_TIME
   INTEGER :: LOCATION
   INTEGER :: PATHID
   INTEGER :: PERCENTAGE
   INTEGER :: SPEED
  END TYPE

  TYPE VEHICLE_TYPE_DATA
    INTEGER :: LENGTH
    REAL    :: HEADWAY_FACTOR
    REAL    :: AVERAGE_OCCUPANCY
    REAL    :: NON_EMERGENCY_DECEL
    INTEGER :: FLEET_FREEWAY_AUTO
    INTEGER :: FLEET_FREEWAY_TRUCK
    INTEGER :: FLEET_FREEWAY_CARPOOL
    INTEGER :: FLEET_FREEWAY_BUS
    INTEGER :: FLEET_FREEWAY_EV
    INTEGER :: FLEET_STREET_AUTO
    INTEGER :: FLEET_STREET_TRUCK
    INTEGER :: FLEET_STREET_CARPOOL
    INTEGER :: FLEET_STREET_BUS
    INTEGER :: FLEET_STREET_EV
    INTEGER :: FLEET_STREET_BIKE 
    REAL    :: PCT_PITT 
    REAL    :: PCT_IDM  
    REAL    :: PCT_ACC  
    REAL    :: PCT_CACC 
  END TYPE
  
  TYPE COND_TURNPCTS
    INTEGER :: USN
    INTEGER :: DSN
    INTEGER :: LEFTPCT(4)
    INTEGER :: THRUPCT(4)
    INTEGER :: RIGHTPCT(4)
    INTEGER :: LDIAGPCT(4)
    INTEGER :: RDIAGPCT(4)
  END TYPE
  
  TYPE RAMPMETER_DATA
    INTEGER :: DSN            !dsn of the link containing the meter
    INTEGER :: LINK           !link ID returned by ETFOMM
    INTEGER :: CONTROL        !type of control, 0=external,1=clock,2=demand/capacity,3=speed control
    INTEGER :: ONSET          !time that metering begins
    INTEGER :: STATE          !current meter state, returned by ETFOMM,0=inactive,-1=green,1=red
    INTEGER :: DETECTOR(10)   !detectors used by the meter
    INTEGER :: CAPACITY       !link capacity used for demand/capacity metering
    INTEGER :: SPEED(6)       !speed thresholds used for speed control
    REAL    :: HEADWAY(6)     !headway thresholds used for speed control
    LOGICAL :: TWOPERGREEN    !two vehicles allowed per green,TRUE=yes
  END TYPE
  
  TYPE RABT_API_DATA
    INTEGER :: APPROACHES = 0
    INTEGER :: APPROACH_USN(5) = 0
    INTEGER :: APPROACH_DSN(5) = 0
    INTEGER :: DEPARTING_USN(5) = 0
    INTEGER :: DEPARTING_DSN(5) = 0
    REAL    :: EXIT_PCTS(5, 5) = 0
    INTEGER :: RADIUS = 0
  END TYPE
  
  TYPE INTCH_API_DATA
    INTEGER :: ID = 0
    INTEGER :: NLINKS = 0
    INTEGER :: NORIGINS = 0
    INTEGER :: NDESTS = 0
    INTEGER :: LINKS(100) = 0
    INTEGER :: ORIGIN_LINKS(20) = 0
    INTEGER :: DESTINATION_LINKS(20) = 0
    INTEGER :: EXIT_TURN_CODE(20, 20)
    REAL    :: EXIT_PCT(20, 20, 5)
  END TYPE
  
  CONTAINS
  
  SUBROUTINE ALLOCATE_API_DATA(N_STREET_LINKS, N_PERIODS)
  ALLOCATE(LEFT_PCT(N_STREET_LINKS, N_PERIODS))
  ALLOCATE(STHRU_PCT(N_STREET_LINKS, N_PERIODS))
  ALLOCATE(RIGHT_PCT(N_STREET_LINKS, N_PERIODS))
  ALLOCATE(LDIAG_PCT(N_STREET_LINKS, N_PERIODS))
  ALLOCATE(RDIAG_PCT(N_STREET_LINKS, N_PERIODS))
  LEFT_PCT = 0
  STHRU_PCT = 0
  RIGHT_PCT = 0
  LDIAG_PCT = 0
  RDIAG_PCT = 0
  END SUBROUTINE

  SUBROUTINE DEALLOCATE_API_DATA
  IF(ALLOCATED(FLOW_RATE)) DEALLOCATE(FLOW_RATE)
  IF(ALLOCATED(FTHRU_PCT)) DEALLOCATE(FTHRU_PCT)
  IF(ALLOCATED(LEFT_PCT)) DEALLOCATE(LEFT_PCT)
  IF(ALLOCATED(STHRU_PCT)) DEALLOCATE(STHRU_PCT)
  IF(ALLOCATED(RIGHT_PCT)) DEALLOCATE(RIGHT_PCT)
  IF(ALLOCATED(LDIAG_PCT)) DEALLOCATE(LDIAG_PCT)
  IF(ALLOCATED(RDIAG_PCT)) DEALLOCATE(RDIAG_PCT)
  IF(ALLOCATED(METER_HEADWAY1)) DEALLOCATE(METER_HEADWAY1)
  IF(ALLOCATED(METER_ONSET)) DEALLOCATE(METER_ONSET)
  IF(ALLOCATED(METER_TWOPERGREEN)) DEALLOCATE(METER_TWOPERGREEN)
  IF(ALLOCATED(DURATIONS)) DEALLOCATE(DURATIONS)
  IF(ALLOCATED(SIGCODES)) DEALLOCATE(SIGCODES)
  END SUBROUTINE

END MODULE
