! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

  MODULE CORSIM_NODES
    INTEGER, ALLOCATABLE :: UPNODE(:)
    INTEGER, ALLOCATABLE :: DWNODE(:)
!DEC$ATTRIBUTES DLLEXPORT::UPNODE
!DEC$ATTRIBUTES DLLEXPORT::DWNODE
    INTEGER, ALLOCATABLE :: UPNOD(:)
    INTEGER, ALLOCATABLE :: DWNOD(:)
!DEC$ATTRIBUTES DLLEXPORT::UPNOD
!DEC$ATTRIBUTES DLLEXPORT::DWNOD
  END MODULE
      
  MODULE DISTRIBUTIONS
    REAL :: STARTUP_MULT(40)  &
          = (/ 2.18, 1.40, 1.25, 1.18, 1.02, .86, .78, .63, .47, .23,   &
               2.58, 1.90, 1.43, 1.14, .95, .76, .57, .38, .29, 0.,     &
                       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,          &
                       0., 0., 0., 0., 0., 0., 0., 0., 0., 0. /)        
    REAL :: HDWY_MULTIPLIER(40)  &
                  = (/ 1.7, 1.2, 1.2, 1.1, 1.0, 1.0, .9, .7, .7, .5,    &
                       1.8, 1.4, 1.2, 1.1, 1.0, .9, .8, .7, .6, .5,     &
                       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,          &
                       0., 0., 0., 0., 0., 0., 0., 0., 0., 0. /)        
    REAL :: QFACTOR(5) = (/0.4, 0.3, 0.2, 0.1, 0.0/)
    CONTAINS
      
! ==================================================================================================
    SUBROUTINE SAVE_DISTRIBUTIONS(FILE)
    INTEGER, INTENT(IN) :: FILE
! ----------------------------------------------------------------------

! --- Save static data.

    WRITE(FILE) STARTUP_MULT
    WRITE(FILE) HDWY_MULTIPLIER
    RETURN
    END SUBROUTINE
      
! ==================================================================================================
    SUBROUTINE RESTORE_DISTRIBUTIONS(FILE)
    INTEGER, INTENT(IN) :: FILE
! ----------------------------------------------------------------------

! --- Save static data.

    READ(FILE) STARTUP_MULT
    READ(FILE) HDWY_MULTIPLIER
    RETURN
    END SUBROUTINE
      
  END MODULE
      

  MODULE PEDS
    IMPLICIT NONE
    INTEGER :: PDELAY_WEAK(10) = (/0, 0, 0, 0, 0, 0, 0, 1, 2, 6/)
    INTEGER :: PDELAY_STRONG(10) = (/0, 0, 0, 1, 2, 3, 4, 5, 8, 15/)
    INTEGER :: PED_DURATION(3) = (/0, 10, 25/)
        
    CONTAINS
      
! ==================================================================================================
    SUBROUTINE SAVE_PEDS(FILE1)
    INTEGER, INTENT(IN) :: FILE1
! ----------------------------------------------------------------------

! --- Save static data.

    WRITE(FILE1) PDELAY_WEAK
    WRITE(FILE1) PDELAY_STRONG
    WRITE(FILE1) PED_DURATION
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE RESTORE_PEDS(FILE1)
    INTEGER, INTENT(IN) :: FILE1
! ----------------------------------------------------------------------

! --- Restore data.

    READ(FILE1) PDELAY_WEAK
    READ(FILE1) PDELAY_STRONG
    READ(FILE1) PED_DURATION
    RETURN
    END SUBROUTINE
        
  END MODULE
  
  MODULE FREEWAY_LINKS
    USE GLOBAL_DATA
    USE VEHICLE_TYPES
    IMPLICIT NONE
    
    LOGICAL :: FREEWAY_LANE_CLOSED = .FALSE.

    INTEGER, PARAMETER :: AUX_ACCEL = 1
    INTEGER, PARAMETER :: AUX_DECEL = 2   
    INTEGER, PARAMETER :: AUX_FULL = 3

    INTEGER, PARAMETER :: I_ADD = 1
    INTEGER, PARAMETER :: I_DROP = -1
        
    INTEGER, PARAMETER :: TRK_NULL = 0
    INTEGER, PARAMETER :: TRK_BIASED = 1
    INTEGER, PARAMETER :: TRK_RESTRICTED = 2
    INTEGER, PARAMETER :: TRK_RESTRICTED_EXCL = 3
    INTEGER, PARAMETER :: TRK_BIASED_EXCL = 4
    INTEGER, PARAMETER :: DIR_RIGHT = 0
    INTEGER, PARAMETER :: DIR_LEFT = 1
        
    INTEGER :: N_FREEWAY_LINKS

    REAL,    ALLOCATABLE :: FAREA(:)
    REAL,    ALLOCATABLE :: FCFMULT(:)
    REAL,    ALLOCATABLE :: FCO_TOTAL(:)
    INTEGER, ALLOCATABLE :: FDISCHARGED(:)
    INTEGER, ALLOCATABLE :: FDISCHARGED_BUSES(:)
    INTEGER, ALLOCATABLE :: FDISCHARGED_LANE(:,:)
    INTEGER, ALLOCATABLE :: DISCHARGED_RAMP(:)
    INTEGER, ALLOCATABLE :: FDISCHARGED_TYPE(:,:)
    INTEGER, ALLOCATABLE :: FDSN(:)
    INTEGER, ALLOCATABLE :: FENTERING(:)
    LOGICAL, ALLOCATABLE :: FEV_ONLINK(:)
    INTEGER, ALLOCATABLE :: FFIRST_DETECTOR(:)
    INTEGER, ALLOCATABLE :: FFIRST_ON_SHOULDER(:)
    REAL,    ALLOCATABLE :: FFREEFLOWSPEED(:)
    REAL,    ALLOCATABLE :: FFUEL_TOTAL(:)
    REAL,    ALLOCATABLE :: FHC_TOTAL(:)
    REAL,    ALLOCATABLE :: FGRADE(:)
    INTEGER, ALLOCATABLE :: FLANE_CHANGES(:)
    REAL,    ALLOCATABLE :: FLANE_WIDTH(:,:)
    INTEGER, ALLOCATABLE :: FLAST_VEHICLE(:,:)
    INTEGER, ALLOCATABLE :: FLAST_VEHICLE_OUT(:,:)
    INTEGER, ALLOCATABLE :: FLAST_VEHICLE_OUT_ID(:,:)
    INTEGER, ALLOCATABLE :: FLENGTH(:)
    REAL,    ALLOCATABLE :: FNOX_TOTAL(:)
    INTEGER, ALLOCATABLE :: FNUMLANES(:)
    REAL,    ALLOCATABLE :: FPERSON_TRIPS(:)
    INTEGER, ALLOCATABLE :: FSHOULDER_WIDTH(:)
    REAL,    ALLOCATABLE :: FSTARTUP_TIME(:)                   
    INTEGER, ALLOCATABLE :: FTHRU_LINK(:)
    REAL,    ALLOCATABLE :: FTHRU_PERCENT(:)
    INTEGER, ALLOCATABLE :: FUSN(:)
    LOGICAL, ALLOCATABLE :: FXCLUDE_TYPE(:,:,:)
    REAL,    ALLOCATABLE :: FZDELAY_LANE(:,:)
    REAL,    ALLOCATABLE :: FZDIST(:)
    REAL,    ALLOCATABLE :: FZDIST_LANE(:,:)
    REAL,    ALLOCATABLE :: FZDIST_TYPE(:,:)
    REAL,    ALLOCATABLE :: FZOCCS(:,:)
    REAL,    ALLOCATABLE :: FZTIME(:)
    REAL,    ALLOCATABLE :: FZTIME_BUS(:)
    REAL,    ALLOCATABLE :: FZTIME_LANE(:,:)
    REAL,    ALLOCATABLE :: FZTIME_TYPE(:,:)
    LOGICAL, ALLOCATABLE :: FLANE_CLOSED(:,:)
    LOGICAL, ALLOCATABLE :: MAIN_MERGE_LINK(:)
    LOGICAL, ALLOCATABLE :: RAMP_MERGE_LINK(:)
    INTEGER, ALLOCATABLE :: MERGING_LANE(:)
    LOGICAL, ALLOCATABLE :: DIVERGE_LINK(:)
        
    INTEGER, ALLOCATABLE :: ADDDROP_CODE(:,:)                  
    INTEGER, ALLOCATABLE :: ADDDROP_LANE(:,:)                  
    INTEGER, ALLOCATABLE :: ADDDROP_DIST(:,:)                  
    INTEGER, ALLOCATABLE :: ADDDROP_WARN(:,:)                  
    INTEGER, ALLOCATABLE :: ANTICIP_WARNING_DISTANCE(:)
    INTEGER, ALLOCATABLE :: ANTICIP_WARNING_SPEED(:)
    INTEGER, ALLOCATABLE :: AUX_LANE_ID(:,:)                   
    INTEGER, ALLOCATABLE :: AUX_LANE_CODE(:,:)                 
    INTEGER, ALLOCATABLE :: AUX_LANE_LENGTH(:,:)               
    INTEGER, ALLOCATABLE :: AVERAGE_SPEED(:)
    INTEGER, ALLOCATABLE :: BARRIER(:,:)
    REAL,    ALLOCATABLE :: CURVE(:)
    INTEGER, ALLOCATABLE :: DATASTATION_ID(:)
    INTEGER, ALLOCATABLE :: DATASTATION_LOCATION(:)
    INTEGER, ALLOCATABLE :: ETL_WARN(:)
    INTEGER, ALLOCATABLE :: EXIT_LANE(:,:)                    
    INTEGER, ALLOCATABLE :: HOV_BEGIN(:)
    INTEGER, ALLOCATABLE :: HOV_END(:)
    INTEGER, ALLOCATABLE :: HOV_CODE(:)
    INTEGER, ALLOCATABLE :: HOV_LANES(:,:)
    INTEGER, ALLOCATABLE :: HOV_OFFRAMP_WARN_DISTANCE(:)
    REAL,    ALLOCATABLE :: HOV_PCT(:)
    INTEGER, ALLOCATABLE :: HOV_SIDE(:)
    INTEGER, ALLOCATABLE :: HOV_TYPE(:)
    INTEGER, ALLOCATABLE :: HOV_WARN(:)
    INTEGER, ALLOCATABLE :: LINKTYPE(:)                        
    REAL   , ALLOCATABLE :: MULTIPLIER_EXIT(:,:)
    INTEGER, ALLOCATABLE :: NHOV_LANES(:)
    INTEGER, ALLOCATABLE :: OFFRAMP_LINK(:)                    
    INTEGER, ALLOCATABLE :: OFFRAMP_WARN_DISTANCE(:)
    INTEGER, ALLOCATABLE :: PAVEMENT(:)
    INTEGER, ALLOCATABLE :: RAMPMETER(:)
    INTEGER, ALLOCATABLE :: RECEIVING_LANE(:,:)                
    INTEGER, ALLOCATABLE :: SEGMENT(:)           
    REAL,    ALLOCATABLE :: TILT(:)     
    INTEGER, ALLOCATABLE :: TRUCK_CODE(:)
    INTEGER, ALLOCATABLE :: TRUCK_DIR(:)
    INTEGER, ALLOCATABLE :: TRUCK_LANE(:)
    REAL,    ALLOCATABLE :: USN_TO_SEG_END(:)
    INTEGER, ALLOCATABLE :: VEHICLES_DIVERTED(:)
    INTEGER, ALLOCATABLE :: SAVE_WARN1(:)
    INTEGER, ALLOCATABLE :: SAVE_WARN2(:)

    INTEGER, ALLOCATABLE :: MAINLINE_SENDING_LANE(:)
    INTEGER, ALLOCATABLE :: MAINLINE_RECEIVING_LANE(:)
    INTEGER, ALLOCATABLE :: OFFRAMP_SENDING_LANE(:)
    INTEGER, ALLOCATABLE :: OFFRAMP_RECEIVING_LANE(:)
    
    LOGICAL, ALLOCATABLE :: WRITE25(:,:)
    LOGICAL, ALLOCATABLE :: WRITE33(:,:)
    INTEGER, ALLOCATABLE :: VFIRST(:)
    INTEGER, ALLOCATABLE :: VLAST(:)
    INTEGER, ALLOCATABLE :: NVEH(:)

  CONTAINS

! ==================================================================================================
    SUBROUTINE ALLOCATE_FREEWAY_LINK_ARRAYS
    USE GLOBAL_DATA
    IF(ALLOCATED(FUSN)) RETURN
    IF(N_FREEWAY_LINKS .GT. 0) THEN
      ALLOCATE(FUSN(N_FREEWAY_LINKS))
      FUSN = 0
      ALLOCATE(FDSN(N_FREEWAY_LINKS))
      FDSN = 0
      ALLOCATE(FLENGTH(N_FREEWAY_LINKS))
      FLENGTH = 0
      ALLOCATE(FTHRU_LINK(N_FREEWAY_LINKS))
      FTHRU_LINK = 0
      ALLOCATE(FFREEFLOWSPEED(N_FREEWAY_LINKS))
      FFREEFLOWSPEED = 0
      ALLOCATE(FLANE_WIDTH(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FLANE_WIDTH = STD_WIDTH
      ALLOCATE(MAINLINE_RECEIVING_LANE(N_FREEWAY_LINKS))
      MAINLINE_RECEIVING_LANE = 0
      ALLOCATE(FSTARTUP_TIME(N_FREEWAY_LINKS))
      FSTARTUP_TIME = 1.0
      ALLOCATE(FNUMLANES(N_FREEWAY_LINKS))
      FNUMLANES = 0
      ALLOCATE(FCFMULT(N_FREEWAY_LINKS))
      FCFMULT = 1.0
      ALLOCATE(FLAST_VEHICLE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FLAST_VEHICLE = 0
      ALLOCATE(FLAST_VEHICLE_OUT(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FLAST_VEHICLE_OUT = 0
      ALLOCATE(FLAST_VEHICLE_OUT_ID(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FLAST_VEHICLE_OUT_ID = 0
      ALLOCATE(FTHRU_PERCENT(N_FREEWAY_LINKS))
      FTHRU_PERCENT = 100
      ALLOCATE(FENTERING(N_FREEWAY_LINKS))
      FENTERING = 0
      ALLOCATE(FLANE_CHANGES(N_FREEWAY_LINKS))
      FLANE_CHANGES = 0
      ALLOCATE(FDISCHARGED(N_FREEWAY_LINKS))
      FDISCHARGED = 0
      ALLOCATE(FDISCHARGED_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FDISCHARGED_LANE = 0
      ALLOCATE(DISCHARGED_RAMP(N_FREEWAY_LINKS))
      DISCHARGED_RAMP = 0
      ALLOCATE(FDISCHARGED_BUSES(N_FREEWAY_LINKS))
      FDISCHARGED_BUSES = 0
      ALLOCATE(FDISCHARGED_TYPE(N_FREEWAY_LINKS, NTYPES))
      FDISCHARGED_TYPE = 0
      ALLOCATE(FAREA(N_FREEWAY_LINKS))
      FAREA = 0
      ALLOCATE(FZDIST(N_FREEWAY_LINKS))
      FZDIST = 0
      ALLOCATE(FZDIST_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FZDIST_LANE = 0
      ALLOCATE(FZDIST_TYPE(N_FREEWAY_LINKS, NTYPES))
      FZDIST_TYPE = 0
      ALLOCATE(FZDELAY_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FZDELAY_LANE = 0
      ALLOCATE(FZOCCS(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FZOCCS = 0
      ALLOCATE(FPERSON_TRIPS(N_FREEWAY_LINKS))
      FPERSON_TRIPS = 0
      ALLOCATE(FZTIME(N_FREEWAY_LINKS))
      FZTIME = 0
      ALLOCATE(FZTIME_TYPE(N_FREEWAY_LINKS, NTYPES))
      FZTIME_TYPE = 0
      ALLOCATE(FZTIME_BUS(N_FREEWAY_LINKS))
      FZTIME_BUS = 0
      ALLOCATE(FZTIME_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FZTIME_LANE = 0
      ALLOCATE(FXCLUDE_TYPE(N_FREEWAY_LINKS, N_FREEWAY_LANES, NTYPES))
      FXCLUDE_TYPE = .FALSE.
      ALLOCATE(FFIRST_DETECTOR(N_FREEWAY_LINKS))
      FFIRST_DETECTOR = 0
      ALLOCATE(FGRADE(N_FREEWAY_LINKS))
      FGRADE = 0
      ALLOCATE(FSHOULDER_WIDTH(N_FREEWAY_LINKS))
      FSHOULDER_WIDTH = 6
      ALLOCATE(FEV_ONLINK(N_FREEWAY_LINKS))
      FEV_ONLINK = .FALSE.
      ALLOCATE(FFIRST_ON_SHOULDER(N_FREEWAY_LINKS))
      FFIRST_ON_SHOULDER = 0
      ALLOCATE(FCO_TOTAL(N_FREEWAY_LINKS))
      FCO_TOTAL = 0.0
      ALLOCATE(FHC_TOTAL(N_FREEWAY_LINKS))
      FHC_TOTAL = 0.0
      ALLOCATE(FNOX_TOTAL(N_FREEWAY_LINKS))
      FNOX_TOTAL = 0.0
      ALLOCATE(FFUEL_TOTAL(N_FREEWAY_LINKS))
      FFUEL_TOTAL = 0.0
      ALLOCATE(FLANE_CLOSED(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      FLANE_CLOSED = .FALSE.
      ALLOCATE(MAIN_MERGE_LINK(N_FREEWAY_LINKS))
      MAIN_MERGE_LINK = .FALSE.
      ALLOCATE(RAMP_MERGE_LINK(N_FREEWAY_LINKS))
      RAMP_MERGE_LINK = .FALSE.
      ALLOCATE(MERGING_LANE(N_FREEWAY_LINKS))
      MERGING_LANE = .FALSE.
      ALLOCATE(DIVERGE_LINK(N_FREEWAY_LINKS))
      DIVERGE_LINK = .FALSE.
      ALLOCATE(BARRIER(N_FREEWAY_LINKS, 2))
      BARRIER = 0
      ALLOCATE(OFFRAMP_LINK(N_FREEWAY_LINKS))
      OFFRAMP_LINK = 0
      ALLOCATE(OFFRAMP_SENDING_LANE(N_FREEWAY_LINKS))
      OFFRAMP_SENDING_LANE = 0
      ALLOCATE(LINKTYPE(N_FREEWAY_LINKS))
      LINKTYPE = 0
      ALLOCATE(RECEIVING_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      RECEIVING_LANE = 0
      ALLOCATE(EXIT_LANE(N_FREEWAY_LINKS, N_FREEWAY_LANES))
      EXIT_LANE = 0
      ALLOCATE(AUX_LANE_ID(N_FREEWAY_LINKS, N_AUXLANES))
      AUX_LANE_ID = 0
      ALLOCATE(AUX_LANE_CODE(N_FREEWAY_LINKS, N_AUXLANES))
      AUX_LANE_CODE = 0
      ALLOCATE(AUX_LANE_LENGTH(N_FREEWAY_LINKS, N_AUXLANES))
      AUX_LANE_LENGTH = 0
      ALLOCATE(ADDDROP_CODE(N_FREEWAY_LINKS, 3))
      ADDDROP_CODE = 0
      ALLOCATE(ADDDROP_LANE(N_FREEWAY_LINKS, 3))
      ADDDROP_LANE = 0
      ALLOCATE(ADDDROP_DIST(N_FREEWAY_LINKS, 3))
      ADDDROP_DIST = 0
      ALLOCATE(ADDDROP_WARN(N_FREEWAY_LINKS, 3))
      ADDDROP_WARN = 1500
      ALLOCATE(USN_TO_SEG_END(N_FREEWAY_LINKS))
      USN_TO_SEG_END = 0
      ALLOCATE(SEGMENT(N_FREEWAY_LINKS))           
      SEGMENT = 0
      ALLOCATE(DATASTATION_ID(N_FREEWAY_LINKS))
      DATASTATION_ID = 0
      ALLOCATE(DATASTATION_LOCATION(N_FREEWAY_LINKS))
      DATASTATION_LOCATION = 0
      ALLOCATE(OFFRAMP_WARN_DISTANCE(N_FREEWAY_LINKS))
      OFFRAMP_WARN_DISTANCE = 0
      ALLOCATE(HOV_OFFRAMP_WARN_DISTANCE(N_FREEWAY_LINKS))
      HOV_OFFRAMP_WARN_DISTANCE = 0
      ALLOCATE(ANTICIP_WARNING_DISTANCE(N_FREEWAY_LINKS))
      ANTICIP_WARNING_DISTANCE = 1500
      ALLOCATE(ANTICIP_WARNING_SPEED(N_FREEWAY_LINKS))
      ANTICIP_WARNING_SPEED = 0
      ALLOCATE(AVERAGE_SPEED(N_FREEWAY_LINKS))
      AVERAGE_SPEED = 100
      ALLOCATE(RAMPMETER(N_FREEWAY_LINKS))
      RAMPMETER = 0
          
      ALLOCATE(NHOV_LANES(N_FREEWAY_LINKS))
      NHOV_LANES = 0
      ALLOCATE(HOV_LANES(N_FREEWAY_LINKS, 3))
      HOV_LANES = 0
      ALLOCATE(HOV_SIDE(N_FREEWAY_LINKS))
      HOV_SIDE = 0
      ALLOCATE(HOV_TYPE(N_FREEWAY_LINKS))
      HOV_TYPE = 0
      ALLOCATE(HOV_CODE(N_FREEWAY_LINKS))
      HOV_CODE = 0
      ALLOCATE(HOV_BEGIN(N_FREEWAY_LINKS))
      HOV_BEGIN = 0
      ALLOCATE(HOV_END(N_FREEWAY_LINKS))
      HOV_END = 0
      ALLOCATE(HOV_WARN(N_FREEWAY_LINKS))
      HOV_WARN = 0
      ALLOCATE(HOV_PCT(N_FREEWAY_LINKS))
      HOV_PCT = 0
          
      ALLOCATE(TILT(N_FREEWAY_LINKS))
      TILT = 0
      ALLOCATE(CURVE(N_FREEWAY_LINKS))
      CURVE = 0
      ALLOCATE(PAVEMENT(N_FREEWAY_LINKS))
      PAVEMENT = 1
          
      ALLOCATE(TRUCK_CODE(N_FREEWAY_LINKS))
      TRUCK_CODE = 0
      ALLOCATE(TRUCK_LANE(N_FREEWAY_LINKS))
      TRUCK_LANE = 0
      ALLOCATE(TRUCK_DIR(N_FREEWAY_LINKS))
      TRUCK_DIR = 0
      ALLOCATE(ETL_WARN(N_FREEWAY_LINKS))
      ETL_WARN = 0
      ALLOCATE(VEHICLES_DIVERTED(N_FREEWAY_LINKS))
      VEHICLES_DIVERTED = 0

      ALLOCATE(MULTIPLIER_EXIT(N_FREEWAY_LINKS, NTYPES))
      MULTIPLIER_EXIT = 1.0
          
      ALLOCATE(SAVE_WARN1(N_FREEWAY_LINKS))
      SAVE_WARN1 = 0
      ALLOCATE(SAVE_WARN2(N_FREEWAY_LINKS))
      SAVE_WARN2 = 0
      ALLOCATE(OFFRAMP_RECEIVING_LANE(N_FREEWAY_LINKS))
      OFFRAMP_RECEIVING_LANE = 0
      ALLOCATE(MAINLINE_SENDING_LANE(N_FREEWAY_LINKS))
      MAINLINE_SENDING_LANE = 0
      
      ALLOCATE(WRITE25(N_FREEWAY_LINKS, 19))
      WRITE25 = .FALSE.
      
      ALLOCATE(WRITE33(N_FREEWAY_LINKS, 19))
      WRITE33 = .FALSE.
      
      ALLOCATE(VFIRST(N_FREEWAY_LINKS))
      ALLOCATE(VLAST(N_FREEWAY_LINKS))
      ALLOCATE(NVEH(N_FREEWAY_LINKS))
    ENDIF
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE REALLOCATE_FREEWAY_LINK_ARRAYS(N)
    USE ARRAY_FUNCTIONS
    INTEGER :: N, I1, I2
! ----------------------------------------------------------------------
    I1 = N_FREEWAY_LINKS
    I2 = N_FREEWAY_LINKS + N
    N_FREEWAY_LINKS = I2
    CALL REALLOCATE_INTEGER(FUSN, I1, I2)
    CALL REALLOCATE_INTEGER(FDSN, I1, I2)
    CALL REALLOCATE_INTEGER(FLENGTH, I1, I2)
    CALL REALLOCATE_INTEGER(FTHRU_LINK, I1, I2)
    CALL REALLOCATE_REAL(FFREEFLOWSPEED, I1, I2)
    CALL REALLOCATE_REAL_X(FLANE_WIDTH, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER(MAINLINE_RECEIVING_LANE, I1, I2)
    CALL REALLOCATE_REAL(FSTARTUP_TIME, I1, I2)
    CALL REALLOCATE_INTEGER(FNUMLANES, I1, I2)
    CALL REALLOCATE_REAL(FCFMULT, I1, I2)
    CALL REALLOCATE_INTEGER_X(FLAST_VEHICLE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER_X(FLAST_VEHICLE_OUT, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER_X(FLAST_VEHICLE_OUT_ID, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_REAL(FTHRU_PERCENT, I1, I2)
    CALL REALLOCATE_INTEGER(FENTERING, I1, I2)
    CALL REALLOCATE_INTEGER(FLANE_CHANGES, I1, I2)
    CALL REALLOCATE_INTEGER(FDISCHARGED, I1, I2)
    CALL REALLOCATE_INTEGER_X(FDISCHARGED_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER(DISCHARGED_RAMP, I1, I2)
    CALL REALLOCATE_INTEGER(FDISCHARGED_BUSES, I1, I2)
    CALL REALLOCATE_INTEGER_X(FDISCHARGED_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_REAL(FAREA, I1, I2)
    CALL REALLOCATE_REAL(FZDIST, I1, I2)
    CALL REALLOCATE_REAL_X(FZDIST_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_REAL_X(FZDIST_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(FZDELAY_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_REAL_X(FZOCCS, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_REAL(FPERSON_TRIPS, I1, I2)
    CALL REALLOCATE_REAL(FZTIME, I1, I2)
    CALL REALLOCATE_REAL_X(FZTIME_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_REAL(FZTIME_BUS, I1, I2)
    CALL REALLOCATE_REAL_X(FZTIME_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_LOGICAL_XY(FXCLUDE_TYPE, I1, I2, N_FREEWAY_LANES, NTYPES)
    CALL REALLOCATE_INTEGER(FFIRST_DETECTOR, I1, I2)
    CALL REALLOCATE_REAL(FGRADE, I1, I2)
    CALL REALLOCATE_INTEGER(FSHOULDER_WIDTH, I1, I2)
    CALL REALLOCATE_LOGICAL(FEV_ONLINK, I1, I2)
    CALL REALLOCATE_INTEGER(FFIRST_ON_SHOULDER, I1, I2)
    CALL REALLOCATE_REAL(FCO_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(FHC_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(FNOX_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(FFUEL_TOTAL, I1, I2)
    CALL REALLOCATE_INTEGER_X(BARRIER, I1, I2, 2)
    CALL REALLOCATE_INTEGER(OFFRAMP_LINK, I1, I2)
    CALL REALLOCATE_INTEGER(OFFRAMP_SENDING_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(LINKTYPE, I1, I2)
    CALL REALLOCATE_INTEGER_X(RECEIVING_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER_X(EXIT_LANE, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_INTEGER_X(AUX_LANE_ID, I1, I2, N_AUXLANES)
    CALL REALLOCATE_INTEGER_X(AUX_LANE_CODE, I1, I2, N_AUXLANES)
    CALL REALLOCATE_INTEGER_X(AUX_LANE_LENGTH, I1, I2, N_AUXLANES)
    CALL REALLOCATE_INTEGER_X(ADDDROP_CODE, I1, I2, 3)
    CALL REALLOCATE_INTEGER_X(ADDDROP_LANE, I1, I2, 3)
    CALL REALLOCATE_INTEGER_X(ADDDROP_DIST, I1, I2, 3)
    CALL REALLOCATE_INTEGER_X(ADDDROP_WARN, I1, I2, 3)
    CALL REALLOCATE_REAL(USN_TO_SEG_END, I1, I2)
    CALL REALLOCATE_INTEGER(SEGMENT, I1, I2)           
    CALL REALLOCATE_INTEGER(DATASTATION_ID, I1, I2)
    CALL REALLOCATE_INTEGER(DATASTATION_LOCATION, I1, I2)
    CALL REALLOCATE_INTEGER(OFFRAMP_WARN_DISTANCE, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_OFFRAMP_WARN_DISTANCE, I1, I2)
    CALL REALLOCATE_INTEGER(ANTICIP_WARNING_DISTANCE, I1, I2)
    CALL REALLOCATE_INTEGER(ANTICIP_WARNING_SPEED, I1, I2)
    CALL REALLOCATE_INTEGER(AVERAGE_SPEED, I1, I2)
    CALL REALLOCATE_INTEGER(RAMPMETER, I1, I2)
    CALL REALLOCATE_INTEGER(NHOV_LANES, I1, I2)
    CALL REALLOCATE_INTEGER_X(HOV_LANES, I1, I2, 3)
    CALL REALLOCATE_INTEGER(HOV_SIDE, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_TYPE, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_CODE, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_BEGIN, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_END, I1, I2)
    CALL REALLOCATE_INTEGER(HOV_WARN, I1, I2)
    CALL REALLOCATE_REAL(HOV_PCT, I1, I2)
    CALL REALLOCATE_REAL(TILT, I1, I2)
    CALL REALLOCATE_REAL(CURVE, I1, I2)
    CALL REALLOCATE_INTEGER(PAVEMENT, I1, I2)
    CALL REALLOCATE_INTEGER(TRUCK_CODE, I1, I2)
    CALL REALLOCATE_INTEGER(TRUCK_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(TRUCK_DIR, I1, I2)
    CALL REALLOCATE_INTEGER(ETL_WARN, I1, I2)
    CALL REALLOCATE_INTEGER(VEHICLES_DIVERTED, I1, I2)
    CALL REALLOCATE_REAL_X(MULTIPLIER_EXIT, I1, I2, NTYPES)
    CALL REALLOCATE_INTEGER(SAVE_WARN1, I1, I2)
    CALL REALLOCATE_INTEGER(SAVE_WARN2, I1, I2)
    CALL REALLOCATE_INTEGER(OFFRAMP_RECEIVING_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(MAINLINE_SENDING_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(VFIRST, I1, I2)
    CALL REALLOCATE_INTEGER(VLAST, I1, I2)
    CALL REALLOCATE_LOGICAL_X(WRITE25, I1, I2, 19)
    CALL REALLOCATE_LOGICAL_X(WRITE33, I1, I2, 19)
    CALL REALLOCATE_INTEGER(VFIRST, I1, I2)
    CALL REALLOCATE_INTEGER(VLAST, I1, I2)
    CALL REALLOCATE_INTEGER(NVEH, I1, I2)
    CALL REALLOCATE_LOGICAL_X(FLANE_CLOSED, I1, I2, N_FREEWAY_LANES)
    CALL REALLOCATE_LOGICAL(MAIN_MERGE_LINK, I1, I2)
    CALL REALLOCATE_LOGICAL(RAMP_MERGE_LINK, I1, I2)
    CALL REALLOCATE_INTEGER(MERGING_LANE, I1, I2)
    CALL REALLOCATE_LOGICAL(DIVERGE_LINK, I1, I2)
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE DEALLOCATE_FREEWAY_LINK_ARRAYS
    USE SIMPARAMS
    IF(ALLOCATED(FUSN)) THEN
      DEALLOCATE(FUSN)
      DEALLOCATE(FDSN)
      DEALLOCATE(FLENGTH)
      DEALLOCATE(FTHRU_LINK)
      DEALLOCATE(FFREEFLOWSPEED)
      DEALLOCATE(FLANE_WIDTH)
      DEALLOCATE(MAINLINE_RECEIVING_LANE)
      DEALLOCATE(FSTARTUP_TIME)
      DEALLOCATE(FNUMLANES)
      DEALLOCATE(FCFMULT)
      DEALLOCATE(FLAST_VEHICLE_OUT)
      DEALLOCATE(FLAST_VEHICLE_OUT_ID)
      DEALLOCATE(FTHRU_PERCENT)
      DEALLOCATE(FENTERING)
      DEALLOCATE(FLANE_CHANGES)
      DEALLOCATE(FDISCHARGED)
      DEALLOCATE(FDISCHARGED_LANE)
      DEALLOCATE(DISCHARGED_RAMP)
      DEALLOCATE(FDISCHARGED_BUSES)
      DEALLOCATE(FDISCHARGED_TYPE)
      DEALLOCATE(FAREA)
      DEALLOCATE(FZDIST)
      DEALLOCATE(FZDIST_LANE)
      DEALLOCATE(FZDIST_TYPE)
      DEALLOCATE(FZDELAY_LANE)
      DEALLOCATE(FZOCCS)
      DEALLOCATE(FPERSON_TRIPS)
      DEALLOCATE(FZTIME)
      DEALLOCATE(FZTIME_TYPE)
      DEALLOCATE(FZTIME_BUS)
      DEALLOCATE(FZTIME_LANE)
      DEALLOCATE(FXCLUDE_TYPE)
      DEALLOCATE(FFIRST_DETECTOR)
      DEALLOCATE(FGRADE)
      DEALLOCATE(FSHOULDER_WIDTH)
      DEALLOCATE(FEV_ONLINK)
      DEALLOCATE(FFIRST_ON_SHOULDER)
      DEALLOCATE(FCO_TOTAL)
      DEALLOCATE(FHC_TOTAL)
      DEALLOCATE(FNOX_TOTAL)
      DEALLOCATE(FFUEL_TOTAL)
      DEALLOCATE(FLANE_CLOSED)
      DEALLOCATE(MAIN_MERGE_LINK)
      DEALLOCATE(RAMP_MERGE_LINK)
      DEALLOCATE(MERGING_LANE)
      DEALLOCATE(DIVERGE_LINK)
                      
      DEALLOCATE(BARRIER)
      DEALLOCATE(OFFRAMP_LINK)
      DEALLOCATE(OFFRAMP_SENDING_LANE)
      DEALLOCATE(LINKTYPE)
      DEALLOCATE(RECEIVING_LANE)
      DEALLOCATE(EXIT_LANE)
      DEALLOCATE(AUX_LANE_ID)
      DEALLOCATE(AUX_LANE_CODE)
      DEALLOCATE(AUX_LANE_LENGTH)
      DEALLOCATE(ADDDROP_CODE)
      DEALLOCATE(ADDDROP_LANE)
      DEALLOCATE(ADDDROP_DIST)
      DEALLOCATE(ADDDROP_WARN)
      DEALLOCATE(USN_TO_SEG_END)
      DEALLOCATE(SEGMENT)           
      DEALLOCATE(DATASTATION_ID)
      DEALLOCATE(DATASTATION_LOCATION)
      DEALLOCATE(OFFRAMP_WARN_DISTANCE)
      DEALLOCATE(HOV_OFFRAMP_WARN_DISTANCE)
      DEALLOCATE(ANTICIP_WARNING_DISTANCE)
      DEALLOCATE(ANTICIP_WARNING_SPEED)
      DEALLOCATE(AVERAGE_SPEED)
      DEALLOCATE(RAMPMETER)

      DEALLOCATE(NHOV_LANES)
      DEALLOCATE(HOV_LANES)
      DEALLOCATE(HOV_SIDE)
      DEALLOCATE(HOV_TYPE)
      DEALLOCATE(HOV_CODE)
      DEALLOCATE(HOV_BEGIN)
      DEALLOCATE(HOV_END)
      DEALLOCATE(HOV_WARN)
      DEALLOCATE(HOV_PCT)

      DEALLOCATE(TILT)
      DEALLOCATE(CURVE)
      DEALLOCATE(PAVEMENT)
            
      DEALLOCATE(TRUCK_CODE)
      DEALLOCATE(TRUCK_LANE)
      DEALLOCATE(TRUCK_DIR)
      DEALLOCATE(ETL_WARN)
      DEALLOCATE(VEHICLES_DIVERTED)

      DEALLOCATE(MULTIPLIER_EXIT)

      DEALLOCATE(FLAST_VEHICLE)
      DEALLOCATE(SAVE_WARN1)
      DEALLOCATE(SAVE_WARN2)
      DEALLOCATE(OFFRAMP_RECEIVING_LANE)
      DEALLOCATE(MAINLINE_SENDING_LANE)
          
#ifndef TSIS_COMPATIBLE
      DEALLOCATE(WRITE25)
      DEALLOCATE(WRITE33)
#endif      
      DEALLOCATE(VFIRST)
      DEALLOCATE(VLAST)
      DEALLOCATE(NVEH)
    ENDIF
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE FIND_FREEWAY_LINK(I1, I2, IL)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: I1
    INTEGER, INTENT(IN) :: I2
    INTEGER, INTENT(OUT) :: IL
    INTEGER :: I
! ----------------------------------------------------------------------
    IL = 0
    DO I = 1, N_FREEWAY_LINKS
      IF(FUSN(I) .EQ. I1 .AND. FDSN(I) .EQ. I2) THEN
        IL = I
        EXIT
      ENDIF
    ENDDO
    RETURN
    END SUBROUTINE

! ==================================================================================================
    INTEGER FUNCTION FREEWAY_LANE_TO_RIGHT(LANE)
    INTEGER, INTENT(IN) :: LANE
! ----------------------------------------------------------------------
    IF(LANE .EQ. 1) THEN
      FREEWAY_LANE_TO_RIGHT = 16
    ELSEIF(LANE .EQ. 20) THEN
      FREEWAY_LANE_TO_RIGHT = 0
    ELSEIF(LANE .GT. 15) THEN
      FREEWAY_LANE_TO_RIGHT = LANE + 1
    ELSE
      FREEWAY_LANE_TO_RIGHT = LANE - 1
    ENDIF
    END FUNCTION

! ==================================================================================================
    INTEGER FUNCTION FREEWAY_LANE_TO_LEFT(LANE)
    INTEGER, INTENT(IN) :: LANE
! ----------------------------------------------------------------------
    IF(LANE .EQ. 16) THEN
      FREEWAY_LANE_TO_LEFT = 1
    ELSEIF(LANE .GT. 16) THEN
      FREEWAY_LANE_TO_LEFT = LANE - 1
    ELSEIF(LANE .EQ. 15) THEN
      FREEWAY_LANE_TO_LEFT = 0
    ELSE
      FREEWAY_LANE_TO_LEFT = LANE + 1
    ENDIF
    END FUNCTION
        
! ==================================================================================================
    SUBROUTINE SAVE_FREEWAY_LINKS(FILE1, FILE2, FIRST)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1, FILE2
    LOGICAL, INTENT(IN) :: FIRST
! ----------------------------------------------------------------------
! --- Save static data.
    
    IF(FIRST) THEN
      WRITE(FILE1) FUSN
      WRITE(FILE1) FDSN
      WRITE(FILE1) FLENGTH
      WRITE(FILE1) FTHRU_LINK
      WRITE(FILE1) FFREEFLOWSPEED
      WRITE(FILE1) FLANE_WIDTH
      WRITE(FILE1) MAINLINE_RECEIVING_LANE
      WRITE(FILE1) FSTARTUP_TIME
      WRITE(FILE1) FNUMLANES
      WRITE(FILE1) FCFMULT
      WRITE(FILE1) FTHRU_PERCENT
      WRITE(FILE1) FAREA
      WRITE(FILE1) FXCLUDE_TYPE
      WRITE(FILE1) FGRADE
      WRITE(FILE1) FSHOULDER_WIDTH
      WRITE(FILE1) BARRIER
      WRITE(FILE1) OFFRAMP_LINK
      WRITE(FILE1) OFFRAMP_SENDING_LANE
      WRITE(FILE1) LINKTYPE
      WRITE(FILE1) RECEIVING_LANE
      WRITE(FILE1) EXIT_LANE
      WRITE(FILE1) AUX_LANE_ID
      WRITE(FILE1) AUX_LANE_CODE
      WRITE(FILE1) AUX_LANE_LENGTH
      WRITE(FILE1) ADDDROP_CODE
      WRITE(FILE1) ADDDROP_LANE
      WRITE(FILE1) ADDDROP_DIST
      WRITE(FILE1) ADDDROP_WARN
      WRITE(FILE1) USN_TO_SEG_END
      WRITE(FILE1) SEGMENT
      WRITE(FILE1) DATASTATION_ID
      WRITE(FILE1) DATASTATION_LOCATION
      WRITE(FILE1) OFFRAMP_WARN_DISTANCE
      WRITE(FILE1) HOV_OFFRAMP_WARN_DISTANCE
      WRITE(FILE1) ANTICIP_WARNING_DISTANCE
      WRITE(FILE1) ANTICIP_WARNING_SPEED
      WRITE(FILE1) RAMPMETER
      WRITE(FILE1) NHOV_LANES
      WRITE(FILE1) HOV_LANES
      WRITE(FILE1) HOV_SIDE
      WRITE(FILE1) HOV_TYPE
      WRITE(FILE1) HOV_CODE
      WRITE(FILE1) HOV_BEGIN
      WRITE(FILE1) HOV_END
      WRITE(FILE1) HOV_WARN
      WRITE(FILE1) HOV_PCT
      WRITE(FILE1) TILT
      WRITE(FILE1) CURVE
      WRITE(FILE1) PAVEMENT
      WRITE(FILE1) TRUCK_CODE
      WRITE(FILE1) TRUCK_LANE
      WRITE(FILE1) TRUCK_DIR
      WRITE(FILE1) ETL_WARN
      WRITE(FILE1) VEHICLES_DIVERTED
      WRITE(FILE1) MULTIPLIER_EXIT
    ENDIF
    
! --- Save dynamic data.
    
    WRITE(FILE2) AVERAGE_SPEED
    WRITE(FILE2) FLAST_VEHICLE_OUT
    WRITE(FILE2) FLAST_VEHICLE_OUT_ID
    WRITE(FILE2) FENTERING
    WRITE(FILE2) FLANE_CHANGES
    WRITE(FILE2) FDISCHARGED
    WRITE(FILE2) FDISCHARGED_LANE
    WRITE(FILE2) DISCHARGED_RAMP
    WRITE(FILE2) FDISCHARGED_BUSES
    WRITE(FILE2) FDISCHARGED_TYPE
    WRITE(FILE2) FZDIST
    WRITE(FILE2) FZDIST_LANE
    WRITE(FILE2) FZDIST_TYPE
    WRITE(FILE2) FZDELAY_LANE
    WRITE(FILE2) FZOCCS
    WRITE(FILE2) FPERSON_TRIPS
    WRITE(FILE2) FZTIME
    WRITE(FILE2) FZTIME_TYPE
    WRITE(FILE2) FZTIME_BUS
    WRITE(FILE2) FZTIME_LANE
    WRITE(FILE2) FLAST_VEHICLE
    WRITE(FILE2) FEV_ONLINK
    WRITE(FILE2) FFIRST_ON_SHOULDER
    WRITE(FILE2) FCO_TOTAL
    WRITE(FILE2) FHC_TOTAL
    WRITE(FILE2) FNOX_TOTAL
    WRITE(FILE2) FFUEL_TOTAL
    WRITE(FILE2) FLANE_CLOSED
    WRITE(FILE2) MAIN_MERGE_LINK
    WRITE(FILE2) RAMP_MERGE_LINK
    WRITE(FILE2) MERGING_LANE
    WRITE(FILE2) DIVERGE_LINK
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE RESTORE_FREEWAY_LINKS(FILE1, FILE2)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1, FILE2
! ----------------------------------------------------------------------

! --- Restore static data.
    
    READ(FILE1) FUSN
    READ(FILE1) FDSN
    READ(FILE1) FLENGTH
    READ(FILE1) FTHRU_LINK
    READ(FILE1) FFREEFLOWSPEED
    READ(FILE1) FLANE_WIDTH
    READ(FILE1) MAINLINE_RECEIVING_LANE
    READ(FILE1) FSTARTUP_TIME
    READ(FILE1) FNUMLANES
    READ(FILE1) FCFMULT
    READ(FILE1) FTHRU_PERCENT
    READ(FILE1) FAREA
    READ(FILE1) FXCLUDE_TYPE
    READ(FILE1) FGRADE
    READ(FILE1) FSHOULDER_WIDTH
    READ(FILE1) BARRIER
    READ(FILE1) OFFRAMP_LINK
    READ(FILE1) OFFRAMP_SENDING_LANE
    READ(FILE1) LINKTYPE
    READ(FILE1) RECEIVING_LANE
    READ(FILE1) EXIT_LANE
    READ(FILE1) AUX_LANE_ID
    READ(FILE1) AUX_LANE_CODE
    READ(FILE1) AUX_LANE_LENGTH
    READ(FILE1) ADDDROP_CODE
    READ(FILE1) ADDDROP_LANE
    READ(FILE1) ADDDROP_DIST
    READ(FILE1) ADDDROP_WARN
    READ(FILE1) USN_TO_SEG_END
    READ(FILE1) SEGMENT
    READ(FILE1) DATASTATION_ID
    READ(FILE1) DATASTATION_LOCATION
    READ(FILE1) OFFRAMP_WARN_DISTANCE
    READ(FILE1) HOV_OFFRAMP_WARN_DISTANCE
    READ(FILE1) ANTICIP_WARNING_DISTANCE
    READ(FILE1) ANTICIP_WARNING_SPEED
    READ(FILE1) RAMPMETER
    READ(FILE1) NHOV_LANES
    READ(FILE1) HOV_LANES
    READ(FILE1) HOV_SIDE
    READ(FILE1) HOV_TYPE
    READ(FILE1) HOV_CODE
    READ(FILE1) HOV_BEGIN
    READ(FILE1) HOV_END
    READ(FILE1) HOV_WARN
    READ(FILE1) HOV_PCT
    READ(FILE1) TILT
    READ(FILE1) CURVE
    READ(FILE1) PAVEMENT
    READ(FILE1) TRUCK_CODE
    READ(FILE1) TRUCK_LANE
    READ(FILE1) TRUCK_DIR
    READ(FILE1) ETL_WARN
    READ(FILE1) VEHICLES_DIVERTED
    READ(FILE1) MULTIPLIER_EXIT

! --- Restore dynamic data.

    READ(FILE2) AVERAGE_SPEED
    READ(FILE2) FLAST_VEHICLE_OUT
    READ(FILE2) FLAST_VEHICLE_OUT_ID
    READ(FILE2) FENTERING
    READ(FILE2) FLANE_CHANGES
    READ(FILE2) FDISCHARGED
    READ(FILE2) FDISCHARGED_LANE
    READ(FILE2) DISCHARGED_RAMP
    READ(FILE2) FDISCHARGED_BUSES
    READ(FILE2) FDISCHARGED_TYPE
    READ(FILE2) FZDIST
    READ(FILE2) FZDIST_LANE
    READ(FILE2) FZDIST_TYPE
    READ(FILE2) FZDELAY_LANE
    READ(FILE2) FZOCCS
    READ(FILE2) FPERSON_TRIPS
    READ(FILE2) FZTIME
    READ(FILE2) FZTIME_TYPE
    READ(FILE2) FZTIME_BUS
    READ(FILE2) FZTIME_LANE
    READ(FILE2) FLAST_VEHICLE
    READ(FILE2) FEV_ONLINK
    READ(FILE2) FFIRST_ON_SHOULDER
    READ(FILE2) FCO_TOTAL
    READ(FILE2) FHC_TOTAL
    READ(FILE2) FNOX_TOTAL
    READ(FILE2) FFUEL_TOTAL
    READ(FILE2) FLANE_CLOSED
    READ(FILE2) MAIN_MERGE_LINK
    READ(FILE2) RAMP_MERGE_LINK
    READ(FILE2) MERGING_LANE
    READ(FILE2) DIVERGE_LINK

    RETURN
    END SUBROUTINE

  END MODULE

  MODULE STREET_LINKS
    USE GLOBAL_DATA
    USE VEHICLE_TYPES
    IMPLICIT NONE

    LOGICAL :: STREET_LANE_CLOSED = .FALSE.

! --- The signal codes have the same values as the signal codes
! --- used in the TSD file.

    INTEGER, PARAMETER :: S_RED    =  0
    INTEGER, PARAMETER :: S_AMBER  =  1
    INTEGER, PARAMETER :: S_GREEN  =  2
    INTEGER, PARAMETER :: S_PERGRN =  3
    INTEGER, PARAMETER :: S_NONE   =  4
    INTEGER, PARAMETER :: S_PERAMB =  5
    INTEGER, PARAMETER :: S_STOP   = 30
    INTEGER, PARAMETER :: S_YIELD  = 31

    INTEGER :: N_STREET_LINKS

    REAL,    ALLOCATABLE :: SAREA(:)
    REAL,    ALLOCATABLE :: SCFMULT(:)
    REAL,    ALLOCATABLE :: SCO_TOTAL(:)
    INTEGER, ALLOCATABLE :: SDISCHARGED(:)
    INTEGER, ALLOCATABLE :: SDISCHARGED_BUSES(:)
    INTEGER, ALLOCATABLE :: SDISCHARGED_LANE(:,:)
    INTEGER, ALLOCATABLE :: SDISCHARGED_TYPE(:,:)
    INTEGER, ALLOCATABLE :: SDSN(:)
    INTEGER, ALLOCATABLE :: SENTERING(:)
    LOGICAL, ALLOCATABLE :: SEV_ONLINK(:)
    INTEGER, ALLOCATABLE :: SFIRST_DETECTOR(:)
    INTEGER, ALLOCATABLE :: SFIRST_ON_SHOULDER(:)
    REAL,    ALLOCATABLE :: SFREEFLOWSPEED(:)
    REAL,    ALLOCATABLE :: SFUEL_TOTAL(:)
    REAL,    ALLOCATABLE :: SHC_TOTAL(:)
    REAL,    ALLOCATABLE :: SGRADE(:)
    INTEGER, ALLOCATABLE :: SLANE_CHANGES(:)
    REAL,    ALLOCATABLE :: SLANE_WIDTH(:,:)
    INTEGER, ALLOCATABLE :: SLAST_VEHICLE_OUT(:,:)
    INTEGER, ALLOCATABLE :: SLAST_VEHICLE_OUT_ID(:,:)
    INTEGER, ALLOCATABLE :: SLENGTH(:)
    REAL,    ALLOCATABLE :: SNOX_TOTAL(:)
    INTEGER, ALLOCATABLE :: SNUMLANES(:)
    INTEGER, ALLOCATABLE :: TOTAL_LANES(:)
    REAL,    ALLOCATABLE :: SPERSON_TRIPS(:)
    INTEGER, ALLOCATABLE :: SSHOULDER_WIDTH(:)
    REAL,    ALLOCATABLE :: SSTARTUP_TIME(:)                   
    INTEGER, ALLOCATABLE :: SALIGNMENT_LANE(:)
    INTEGER, ALLOCATABLE :: DIAG_NODE(:)
    INTEGER, ALLOCATABLE :: STHRU_ALIGNMENT_LANE(:)
    INTEGER, ALLOCATABLE :: STHRU_LINK(:)
    REAL   , ALLOCATABLE :: STHRU_PERCENT(:)
    INTEGER, ALLOCATABLE :: SUSN(:)
    LOGICAL, ALLOCATABLE :: SXCLUDE_TYPE(:,:,:)
    REAL,    ALLOCATABLE :: SZDELAY_LANE(:,:)
    REAL,    ALLOCATABLE :: SZDIST(:)
    REAL,    ALLOCATABLE :: SZDIST_LANE(:,:)
    REAL,    ALLOCATABLE :: SZDIST_TYPE(:,:)
    REAL,    ALLOCATABLE :: SZOCCS(:,:)
    REAL,    ALLOCATABLE :: SZTIME(:)
    REAL,    ALLOCATABLE :: SZTIME_BUS(:)
    REAL,    ALLOCATABLE :: SZTIME_LANE(:,:)
    REAL,    ALLOCATABLE :: SZTIME_TYPE(:,:)  
    LOGICAL, ALLOCATABLE :: SLANE_CLOSED(:,:)
    LOGICAL, ALLOCATABLE :: LANE_GOES_LEFT(:,:)
    LOGICAL, ALLOCATABLE :: LANE_GOES_RIGHT(:,:)
    
    INTEGER, ALLOCATABLE :: AC_SIGNAL_ID(:)
    LOGICAL, ALLOCATABLE :: AMBER_LEFT(:)
    LOGICAL, ALLOCATABLE :: AMBER_THRU(:)
    LOGICAL, ALLOCATABLE :: AMBER_RIGHT(:)
    LOGICAL, ALLOCATABLE :: AMBER_DIAG(:)
    INTEGER, ALLOCATABLE :: APPROACH_NUM(:)
    INTEGER, ALLOCATABLE :: BLOCKAGE(:,:)
    INTEGER, ALLOCATABLE :: CENTROID(:)
    INTEGER, ALLOCATABLE :: CENTROID_NV(:)
    INTEGER, ALLOCATABLE :: CENTROID_LABEL(:)
    INTEGER, ALLOCATABLE :: CHANNELIZATION(:,:)
    LOGICAL, ALLOCATABLE :: COND_LDIAG(:)
    LOGICAL, ALLOCATABLE :: COND_RDIAG(:)
    INTEGER, ALLOCATABLE :: COND_LDIAGPCT(:,:)
    INTEGER, ALLOCATABLE :: COND_RDIAGPCT(:,:)
    LOGICAL, ALLOCATABLE :: COND_LEFT(:)
    INTEGER, ALLOCATABLE :: COND_LEFTPCT(:,:)
    LOGICAL, ALLOCATABLE :: COND_THRU(:)
    INTEGER, ALLOCATABLE :: COND_THRUPCT(:,:)
    LOGICAL, ALLOCATABLE :: COND_RIGHT(:)
    INTEGER, ALLOCATABLE :: COND_RIGHTPCT(:,:)
    INTEGER, ALLOCATABLE :: CYCLE_FAILURES(:)
    INTEGER, ALLOCATABLE :: LEFT_DIAG_LINK(:)                   
    INTEGER, ALLOCATABLE :: RIGHT_DIAG_LINK(:)                   
    REAL   , ALLOCATABLE :: RTW_EXIT_POINT(:)                   
    REAL   , ALLOCATABLE :: RTW_ENTRY_POINT(:)                   
    INTEGER, ALLOCATABLE :: RTW_RECEIVING_LINK(:)                   
    REAL   , ALLOCATABLE :: RTW_LENGTH(:)                   
    REAL   , ALLOCATABLE :: RTW_FFSPEED(:)                   
    INTEGER, ALLOCATABLE :: RTW_CONTROL_CODE(:)                   
    INTEGER, ALLOCATABLE :: RTW_LANES(:)                   
    REAL   , ALLOCATABLE :: LDIAG_PERCENT(:)                    
    REAL   , ALLOCATABLE :: RDIAG_PERCENT(:)                    
    INTEGER, ALLOCATABLE :: DISCHARGED_LEFT(:)
    INTEGER, ALLOCATABLE :: DISCHARGED_RIGHT(:)
    INTEGER, ALLOCATABLE :: DISCHARGED_DIAG(:)
    INTEGER, ALLOCATABLE :: FAR_CROSSLINK(:)
    INTEGER, ALLOCATABLE :: FIRST_BUS_STATION(:)
    INTEGER, ALLOCATABLE :: FIRST_VEHICLE(:,:)
    INTEGER, ALLOCATABLE :: FTC_SIGNAL_ID(:)
    INTEGER, ALLOCATABLE :: ROUNDABOUT_ID(:)
    INTEGER, ALLOCATABLE :: ROUNDABOUT_APPROACH_NUM(:)
    INTEGER, ALLOCATABLE :: ROUNDABOUT_EXIT_NUM(:)
    REAL,    ALLOCATABLE :: QDISCHARGE_HDWY(:)                  
    REAL,    ALLOCATABLE :: LAGGER_TIMER(:)
    INTEGER, ALLOCATABLE :: SLAST_VEHICLE(:,:)
    INTEGER, ALLOCATABLE :: LEFT_LINK(:)                   
    REAL   , ALLOCATABLE :: LEFT_PERCENT(:)                    
    REAL   , ALLOCATABLE :: LANE_LENGTH(:,:)              
    INTEGER, ALLOCATABLE :: LINKTYPE_CODE(:)
    REAL   , ALLOCATABLE :: LANE_CENTER(:,:)
    REAL   , ALLOCATABLE :: LT_ARC_LENGTH(:,:,:)
    REAL   , ALLOCATABLE :: THRU_ARC_LENGTH(:,:,:)
    REAL   , ALLOCATABLE :: RT_ARC_LENGTH(:,:,:)
    REAL   , ALLOCATABLE :: LD_ARC_LENGTH(:,:,:)
    REAL   , ALLOCATABLE :: RD_ARC_LENGTH(:,:,:)
    REAL   , ALLOCATABLE :: LT_LIMITED_SPEED_DIST(:)
    REAL   , ALLOCATABLE :: RT_LIMITED_SPEED_DIST(:)
    REAL,    ALLOCATABLE :: MULTIPLIER_LDIAG(:,:)
    REAL,    ALLOCATABLE :: MULTIPLIER_RDIAG(:,:)
    REAL,    ALLOCATABLE :: MULTIPLIER_LEFT(:,:)
    REAL,    ALLOCATABLE :: MULTIPLIER_THRU(:,:)
    REAL,    ALLOCATABLE :: MULTIPLIER_RIGHT(:,:)
    INTEGER, ALLOCATABLE :: NEAR_CROSSLINK(:)
    INTEGER, ALLOCATABLE :: NEAR_UPPER_CROSSLINK(:,:)
    INTEGER, ALLOCATABLE :: NUMBER_LEFTPOCKETS(:)              
    INTEGER, ALLOCATABLE :: NUMBER_RIGHTPOCKETS(:)             
    INTEGER, ALLOCATABLE :: NUMBER_TURNINGWAYS(:)             
    INTEGER, ALLOCATABLE :: OPPOSE_LINK(:)                   
    INTEGER, ALLOCATABLE :: PED_CODE(:)                  
    REAL,    ALLOCATABLE :: QUEUE_DELAY(:)
    REAL,    ALLOCATABLE :: QUEUE_DELAY_DIAG(:)
    REAL,    ALLOCATABLE :: QUEUE_DELAY_LEFT(:)
    REAL,    ALLOCATABLE :: QUEUE_DELAY_RIGHT(:)
    INTEGER, ALLOCATABLE :: QUEUE_MAX(:,:)
    INTEGER, ALLOCATABLE :: QUEUE_TOTAL(:,:)
    REAL,    ALLOCATABLE :: RICDELAY(:)
    REAL,    ALLOCATABLE :: RICDELD(:)
    REAL,    ALLOCATABLE :: RICDELL(:)
    REAL,    ALLOCATABLE :: RICDELR(:)
    INTEGER, ALLOCATABLE :: RIGHT_LINK(:)                  
    REAL   , ALLOCATABLE :: RIGHT_PERCENT(:)                   
    LOGICAL, ALLOCATABLE :: RTOR(:)
    INTEGER, ALLOCATABLE :: SIGHT_DIST(:)
    REAL,    ALLOCATABLE :: TIME_IN_AMBER_LEFT(:)
    REAL,    ALLOCATABLE :: TIME_IN_AMBER_THRU(:)
    REAL,    ALLOCATABLE :: TIME_IN_AMBER_RIGHT(:)
    REAL,    ALLOCATABLE :: TIME_IN_AMBER_DIAG(:)
    REAL,    ALLOCATABLE :: TIME_IN_RED_LEFT(:)
    REAL,    ALLOCATABLE :: TIME_IN_RED_THRU(:)
    REAL,    ALLOCATABLE :: TIME_IN_RED_RIGHT(:)
    REAL,    ALLOCATABLE :: TIME_IN_RED_DIAG(:)
    INTEGER, ALLOCATABLE :: PREV_SIGNAL_CODE(:)
    INTEGER, ALLOCATABLE :: PREV_SIGNAL_LEFT(:)
    INTEGER, ALLOCATABLE :: SIGNAL_CODE(:)
    LOGICAL, ALLOCATABLE :: SIGNAL_LEFT(:)
    LOGICAL, ALLOCATABLE :: SIGNAL_THRU(:)
    LOGICAL, ALLOCATABLE :: SIGNAL_RIGHT(:)
    LOGICAL, ALLOCATABLE :: SIGNAL_DIAG(:)
    INTEGER, ALLOCATABLE :: PHASE_LEFT(:)
    INTEGER, ALLOCATABLE :: PHASE_THRU(:)
    INTEGER, ALLOCATABLE :: PHASE_RIGHT(:)
    INTEGER, ALLOCATABLE :: PHASE_DIAG(:)
    INTEGER, ALLOCATABLE :: SIGNAL_RANGE(:)
    LOGICAL, ALLOCATABLE :: SIGNALIZED(:)
    INTEGER, ALLOCATABLE :: SOURCE_SINK(:)
    INTEGER, ALLOCATABLE :: STE_DURATION(:)
    INTEGER, ALLOCATABLE :: STE_FREQ(:)
    REAL,    ALLOCATABLE :: STOP_DELAY(:)
    REAL,    ALLOCATABLE :: STOP_DELAY_DIAG(:)
    REAL,    ALLOCATABLE :: STOP_DELAY_LEFT(:)
    REAL,    ALLOCATABLE :: STOP_DELAY_RIGHT(:)
    INTEGER, ALLOCATABLE :: STOPPED_VEHICLES(:)
    REAL,    ALLOCATABLE :: UP_INT_WIDTH(:)
    REAL,    ALLOCATABLE :: ZDIST_DIAG(:)
    REAL,    ALLOCATABLE :: ZDIST_LEFT(:)
    REAL,    ALLOCATABLE :: ZDIST_RIGHT(:)
    REAL,    ALLOCATABLE :: ZTIME_DIAG(:)
    REAL,    ALLOCATABLE :: ZTIME_LEFT(:)
    REAL,    ALLOCATABLE :: ZTIME_RIGHT(:)
    INTEGER, ALLOCATABLE :: ZSTOP(:)
    INTEGER, ALLOCATABLE :: RED_LIGHT_RUNNERS(:)
    INTEGER, ALLOCATABLE :: VEHICLES_INDZ(:)
    
    LOGICAL, ALLOCATABLE :: WRITE12(:)
    LOGICAL, ALLOCATABLE :: WRITE13(:)
    LOGICAL, ALLOCATABLE :: WRITE21(:,:)
    LOGICAL, ALLOCATABLE :: WRITE51(:,:)
    LOGICAL, ALLOCATABLE :: WRITE82(:)
    LOGICAL, ALLOCATABLE :: WRITE83(:)
    INTEGER, ALLOCATABLE :: LANE_NUMBERS(:,:)
    INTEGER, ALLOCATABLE :: FIRST_FULL_LANE(:)
    INTEGER, ALLOCATABLE :: LAST_FULL_LANE(:)
    LOGICAL, ALLOCATABLE :: ALWAYS_GREEN(:,:)
    INTEGER, ALLOCATABLE :: CHECK_MERGE(:)
    
    INTEGER, ALLOCATABLE :: LT_SPEED(:)
    INTEGER, ALLOCATABLE :: RT_SPEED(:) 
      
  CONTAINS

! ==================================================================================================
    SUBROUTINE ALLOCATE_STREET_LINK_ARRAYS
    USE GLOBAL_DATA
    IF(ALLOCATED(SUSN)) RETURN
    IF(N_STREET_LINKS .GT. 0) THEN
      ALLOCATE(SUSN(N_STREET_LINKS))
      SUSN = 0
      ALLOCATE(SDSN(N_STREET_LINKS))
      SDSN = 0
      ALLOCATE(SLENGTH(N_STREET_LINKS))
      SLENGTH = 0
      ALLOCATE(STHRU_LINK(N_STREET_LINKS))
      STHRU_LINK = 0
      ALLOCATE(SFREEFLOWSPEED(N_STREET_LINKS))
      SFREEFLOWSPEED = 0
      ALLOCATE(SLANE_WIDTH(N_STREET_LINKS, N_STREET_LANES))
      SLANE_WIDTH = STD_WIDTH
      ALLOCATE(STHRU_ALIGNMENT_LANE(N_STREET_LINKS))
      STHRU_ALIGNMENT_LANE = 0
      ALLOCATE(SSTARTUP_TIME(N_STREET_LINKS)) 
      SSTARTUP_TIME = 2.0         
      ALLOCATE(SNUMLANES(N_STREET_LINKS))
      SNUMLANES = 0
      ALLOCATE(TOTAL_LANES(N_STREET_LINKS))
      TOTAL_LANES = 0
      ALLOCATE(SCFMULT(N_STREET_LINKS))
      SCFMULT = 1.0
      ALLOCATE(SLAST_VEHICLE_OUT(N_STREET_LINKS, N_STREET_LANES))
      SLAST_VEHICLE_OUT = 0
      ALLOCATE(SLAST_VEHICLE_OUT_ID(N_STREET_LINKS, N_STREET_LANES))
      SLAST_VEHICLE_OUT_ID = 0
      ALLOCATE(STHRU_PERCENT(N_STREET_LINKS))
      STHRU_PERCENT = 0
      ALLOCATE(SENTERING(N_STREET_LINKS))
      SENTERING = 0
      ALLOCATE(SLANE_CHANGES(N_STREET_LINKS))
      SLANE_CHANGES = 0
      ALLOCATE(SDISCHARGED(N_STREET_LINKS))
      SDISCHARGED = 0
      ALLOCATE(SDISCHARGED_LANE(N_STREET_LINKS, N_STREET_LANES))
      SDISCHARGED_LANE = 0
      ALLOCATE(DISCHARGED_LEFT(N_STREET_LINKS))
      DISCHARGED_LEFT = 0
      ALLOCATE(DISCHARGED_RIGHT(N_STREET_LINKS))
      DISCHARGED_RIGHT = 0
      ALLOCATE(DISCHARGED_DIAG(N_STREET_LINKS))
      DISCHARGED_DIAG = 0
      ALLOCATE(SDISCHARGED_BUSES(N_STREET_LINKS))
      SDISCHARGED_BUSES = 0
      ALLOCATE(SDISCHARGED_TYPE(N_STREET_LINKS, NTYPES))
      SDISCHARGED_TYPE = 0
      ALLOCATE(SAREA(N_STREET_LINKS))
      SAREA = 0
      ALLOCATE(SZDIST_LANE(N_STREET_LINKS, N_STREET_LANES))
      SZDIST_LANE = 0
      ALLOCATE(SZDIST_TYPE(N_STREET_LINKS, NTYPES))
      SZDIST_TYPE = 0
      ALLOCATE(SZTIME_TYPE(N_STREET_LINKS, NTYPES))
      SZTIME_TYPE = 0
      ALLOCATE(SLANE_CLOSED(N_STREET_LINKS, N_STREET_LANES))
      SLANE_CLOSED = 0
      ALLOCATE(LANE_GOES_LEFT(N_STREET_LINKS, N_STREET_LANES))
      LANE_GOES_LEFT = .FALSE.
      ALLOCATE(LANE_GOES_RIGHT(N_STREET_LINKS, N_STREET_LANES))
      LANE_GOES_RIGHT = .FALSE.
      ALLOCATE(SZDIST(N_STREET_LINKS))
      SZDIST = 0
      ALLOCATE(ZDIST_DIAG(N_STREET_LINKS))
      ZDIST_DIAG = 0
      ALLOCATE(ZDIST_LEFT(N_STREET_LINKS))
      ZDIST_LEFT = 0
      ALLOCATE(ZDIST_RIGHT(N_STREET_LINKS))
      ZDIST_RIGHT = 0
      ALLOCATE(SZDELAY_LANE(N_STREET_LINKS, N_STREET_LANES))
      SZDELAY_LANE = 0
      ALLOCATE(SZOCCS(N_STREET_LINKS, N_STREET_LANES))
      SZOCCS = 0
      ALLOCATE(SPERSON_TRIPS(N_STREET_LINKS))
      SPERSON_TRIPS = 0
      ALLOCATE(ZSTOP(N_STREET_LINKS))
      ZSTOP = 0
      ALLOCATE(RED_LIGHT_RUNNERS(N_STREET_LINKS))
      RED_LIGHT_RUNNERS = 0
      ALLOCATE(VEHICLES_INDZ(N_STREET_LINKS))
      VEHICLES_INDZ = 0
      ALLOCATE(SZTIME(N_STREET_LINKS))
      SZTIME = 0
      ALLOCATE(ZTIME_DIAG(N_STREET_LINKS))
      ZTIME_DIAG = 0
      ALLOCATE(ZTIME_LEFT(N_STREET_LINKS))
      ZTIME_LEFT = 0
      ALLOCATE(ZTIME_RIGHT(N_STREET_LINKS))
      ZTIME_RIGHT = 0
      ALLOCATE(SZTIME_BUS(N_STREET_LINKS))
      SZTIME_BUS = 0
      ALLOCATE(SZTIME_LANE(N_STREET_LINKS, N_STREET_LANES))
      SZTIME_LANE = 0
      ALLOCATE(SXCLUDE_TYPE(N_STREET_LINKS, N_STREET_LANES, NTYPES))
      SXCLUDE_TYPE = .FALSE.
      ALLOCATE(SFIRST_DETECTOR(N_STREET_LINKS))
      SFIRST_DETECTOR = 0
      ALLOCATE(SGRADE(N_STREET_LINKS))
      SGRADE = 0
      ALLOCATE(SSHOULDER_WIDTH(N_STREET_LINKS))
      SSHOULDER_WIDTH = 0
      ALLOCATE(SEV_ONLINK(N_STREET_LINKS))
      SEV_ONLINK = .FALSE.
      ALLOCATE(SFIRST_ON_SHOULDER(N_STREET_LINKS))
      SFIRST_ON_SHOULDER = 0
      ALLOCATE(SCO_TOTAL(N_STREET_LINKS))
      SCO_TOTAL = 0
      ALLOCATE(SHC_TOTAL(N_STREET_LINKS))
      SHC_TOTAL = 0
      ALLOCATE(SNOX_TOTAL(N_STREET_LINKS))
      SNOX_TOTAL = 0
      ALLOCATE(SFUEL_TOTAL(N_STREET_LINKS))
      SFUEL_TOTAL = 0

      ALLOCATE(SALIGNMENT_LANE(N_STREET_LINKS))
      SALIGNMENT_LANE = 0
      ALLOCATE(DIAG_NODE(N_STREET_LINKS))
      DIAG_NODE = 0
      ALLOCATE(PED_CODE(N_STREET_LINKS))         
      PED_CODE = 0
      ALLOCATE(QDISCHARGE_HDWY(N_STREET_LINKS))         
      QDISCHARGE_HDWY = 1.8
      ALLOCATE(SIGHT_DIST(N_STREET_LINKS))         
      SIGHT_DIST = 1000
      ALLOCATE(TIME_IN_AMBER_LEFT(N_STREET_LINKS))         
      TIME_IN_AMBER_LEFT = 0.0
      ALLOCATE(TIME_IN_AMBER_THRU(N_STREET_LINKS))         
      TIME_IN_AMBER_THRU = 0.0
      ALLOCATE(TIME_IN_AMBER_RIGHT(N_STREET_LINKS))         
      TIME_IN_AMBER_RIGHT = 0.0
      ALLOCATE(TIME_IN_AMBER_DIAG(N_STREET_LINKS))         
      TIME_IN_AMBER_DIAG = 0.0
      ALLOCATE(TIME_IN_RED_LEFT(N_STREET_LINKS))         
      TIME_IN_RED_LEFT = 0.0
      ALLOCATE(TIME_IN_RED_THRU(N_STREET_LINKS))         
      TIME_IN_RED_THRU = 0.0
      ALLOCATE(TIME_IN_RED_RIGHT(N_STREET_LINKS))         
      TIME_IN_RED_RIGHT = 0.0
      ALLOCATE(TIME_IN_RED_DIAG(N_STREET_LINKS))         
      TIME_IN_RED_DIAG = 0.0
      ALLOCATE(NUMBER_LEFTPOCKETS(N_STREET_LINKS))     
      NUMBER_LEFTPOCKETS = 0
      ALLOCATE(NUMBER_RIGHTPOCKETS(N_STREET_LINKS))    
      NUMBER_RIGHTPOCKETS = 0
      ALLOCATE(NUMBER_TURNINGWAYS(N_STREET_LINKS))    
      NUMBER_TURNINGWAYS = 0
      ALLOCATE(LANE_LENGTH(N_STREET_LINKS, N_STREET_LANES))     
      LANE_LENGTH = 0
      ALLOCATE(FIRST_BUS_STATION(N_STREET_LINKS))
      FIRST_BUS_STATION = 0
      ALLOCATE(LEFT_LINK(N_STREET_LINKS))              
      LEFT_LINK = 0
      ALLOCATE(RIGHT_LINK(N_STREET_LINKS))             
      RIGHT_LINK = 0
      ALLOCATE(LEFT_DIAG_LINK(N_STREET_LINKS))              
      LEFT_DIAG_LINK = 0
      ALLOCATE(RIGHT_DIAG_LINK(N_STREET_LINKS))              
      RIGHT_DIAG_LINK = 0
      ALLOCATE(RTW_EXIT_POINT(N_STREET_LINKS))              
      RTW_EXIT_POINT = 0
      ALLOCATE(RTW_ENTRY_POINT(N_STREET_LINKS))              
      RTW_ENTRY_POINT = 0
      ALLOCATE(RTW_RECEIVING_LINK(N_STREET_LINKS))              
      RTW_RECEIVING_LINK = 0
      ALLOCATE(RTW_LENGTH(N_STREET_LINKS))              
      RTW_LENGTH = 0.
      ALLOCATE(RTW_FFSPEED(N_STREET_LINKS))              
      RTW_FFSPEED = 0.
      ALLOCATE(RTW_CONTROL_CODE(N_STREET_LINKS))              
      RTW_CONTROL_CODE = 0
      ALLOCATE(RTW_LANES(N_STREET_LINKS))              
      RTW_LANES = 0
      ALLOCATE(OPPOSE_LINK(N_STREET_LINKS))            
      OPPOSE_LINK = 0
      ALLOCATE(LEFT_PERCENT(N_STREET_LINKS))           
      LEFT_PERCENT = 0
      ALLOCATE(RIGHT_PERCENT(N_STREET_LINKS))          
      RIGHT_PERCENT = 0
      ALLOCATE(LDIAG_PERCENT(N_STREET_LINKS))           
      LDIAG_PERCENT = 0
      ALLOCATE(RDIAG_PERCENT(N_STREET_LINKS))           
      RDIAG_PERCENT = 0
      ALLOCATE(CHANNELIZATION(N_STREET_LINKS, N_STREET_LANES))
      CHANNELIZATION = -1
      ALLOCATE(FIRST_VEHICLE(N_STREET_LINKS, N_STREET_LANES))
      FIRST_VEHICLE = 0
      ALLOCATE(SLAST_VEHICLE(N_STREET_LINKS, N_STREET_LANES))
      SLAST_VEHICLE = 0
      ALLOCATE(FTC_SIGNAL_ID(N_STREET_LINKS))
      FTC_SIGNAL_ID = 0
      ALLOCATE(ROUNDABOUT_ID(N_STREET_LINKS))
      ROUNDABOUT_ID = 0
      ALLOCATE(ROUNDABOUT_APPROACH_NUM(N_STREET_LINKS))
      ROUNDABOUT_APPROACH_NUM = 0
      ALLOCATE(ROUNDABOUT_EXIT_NUM(N_STREET_LINKS))
      ROUNDABOUT_EXIT_NUM = 0
      ALLOCATE(AC_SIGNAL_ID(N_STREET_LINKS))
      AC_SIGNAL_ID = 0
      ALLOCATE(PREV_SIGNAL_CODE(N_STREET_LINKS))
      PREV_SIGNAL_CODE = 0
      ALLOCATE(PREV_SIGNAL_LEFT(N_STREET_LINKS))
      PREV_SIGNAL_LEFT = .FALSE.
      ALLOCATE(SIGNAL_CODE(N_STREET_LINKS))
      SIGNAL_CODE = 0
      ALLOCATE(SIGNAL_LEFT(N_STREET_LINKS))
      SIGNAL_LEFT = .FALSE.
      ALLOCATE(SIGNAL_THRU(N_STREET_LINKS))
      SIGNAL_THRU = .FALSE.
      ALLOCATE(SIGNAL_RIGHT(N_STREET_LINKS))
      SIGNAL_RIGHT = .FALSE.
      ALLOCATE(SIGNAL_DIAG(N_STREET_LINKS))
      SIGNAL_DIAG = .FALSE.
      ALLOCATE(PHASE_LEFT(N_STREET_LINKS))
      PHASE_LEFT = 0
      ALLOCATE(PHASE_THRU(N_STREET_LINKS))
      PHASE_THRU = 0
      ALLOCATE(PHASE_RIGHT(N_STREET_LINKS))
      PHASE_RIGHT = 0
      ALLOCATE(PHASE_DIAG(N_STREET_LINKS))
      PHASE_DIAG = 0
      ALLOCATE(AMBER_LEFT(N_STREET_LINKS))
      AMBER_LEFT = .FALSE.
      ALLOCATE(AMBER_THRU(N_STREET_LINKS))
      AMBER_THRU = .FALSE.
      ALLOCATE(AMBER_RIGHT(N_STREET_LINKS))
      AMBER_RIGHT = .FALSE.
      ALLOCATE(AMBER_DIAG(N_STREET_LINKS))
      AMBER_DIAG = .FALSE.
      ALLOCATE(NEAR_CROSSLINK(N_STREET_LINKS))
      NEAR_CROSSLINK = 0
      ALLOCATE(NEAR_UPPER_CROSSLINK(N_STREET_LINKS, 5))
      NEAR_UPPER_CROSSLINK = 0
      ALLOCATE(FAR_CROSSLINK(N_STREET_LINKS))
      FAR_CROSSLINK = 0
      ALLOCATE(UP_INT_WIDTH(N_STREET_LINKS))
      UP_INT_WIDTH = 0
      ALLOCATE(LANE_CENTER(N_STREET_LINKS, N_STREET_LANES))
      LANE_CENTER = 0
      ALLOCATE(LT_ARC_LENGTH(N_STREET_LINKS, N_STREET_LANES, N_STREET_LANES))
      LT_ARC_LENGTH = 0
      ALLOCATE(THRU_ARC_LENGTH(N_STREET_LINKS, N_STREET_LANES, N_STREET_LANES))
      THRU_ARC_LENGTH = 0
      ALLOCATE(RT_ARC_LENGTH(N_STREET_LINKS, N_STREET_LANES, N_STREET_LANES))
      RT_ARC_LENGTH = 0
      ALLOCATE(LD_ARC_LENGTH(N_STREET_LINKS, N_STREET_LANES, N_STREET_LANES))
      LD_ARC_LENGTH = 0
      ALLOCATE(RD_ARC_LENGTH(N_STREET_LINKS, N_STREET_LANES, N_STREET_LANES))
      RD_ARC_LENGTH = 0
      ALLOCATE(LT_LIMITED_SPEED_DIST(N_STREET_LINKS))
      LT_LIMITED_SPEED_DIST = 0
      ALLOCATE(RT_LIMITED_SPEED_DIST(N_STREET_LINKS))
      RT_LIMITED_SPEED_DIST = 0
      ALLOCATE(APPROACH_NUM(N_STREET_LINKS))
      APPROACH_NUM = 0
      ALLOCATE(BLOCKAGE(N_STREET_LINKS, N_STREET_LANES))
      BLOCKAGE = 0
      ALLOCATE(STE_FREQ(N_STREET_LINKS))
      STE_FREQ = 0
      ALLOCATE(STE_DURATION(N_STREET_LINKS))
      STE_DURATION = 0
      ALLOCATE(SOURCE_SINK(N_STREET_LINKS))
      SOURCE_SINK = 0
      ALLOCATE(CYCLE_FAILURES(N_STREET_LINKS))
      CYCLE_FAILURES = 0
      ALLOCATE(QUEUE_TOTAL(N_STREET_LINKS, N_STREET_LANES))
      QUEUE_TOTAL = 0
      ALLOCATE(QUEUE_MAX(N_STREET_LINKS, N_STREET_LANES))
      QUEUE_MAX = 0
      ALLOCATE(RICDELAY(N_STREET_LINKS))
      RICDELAY = 0
      ALLOCATE(RICDELD(N_STREET_LINKS))
      RICDELD = 0
      ALLOCATE(RICDELL(N_STREET_LINKS))
      RICDELL = 0
      ALLOCATE(RICDELR(N_STREET_LINKS))
      RICDELR = 0
      ALLOCATE(RTOR(N_STREET_LINKS))
      RTOR = .TRUE.
      ALLOCATE(LINKTYPE_CODE(N_STREET_LINKS))
      LINKTYPE_CODE = 0
      ALLOCATE(LAGGER_TIMER(N_STREET_LINKS))
      LAGGER_TIMER = -5.0
      ALLOCATE(COND_LEFT(N_STREET_LINKS))
      COND_LEFT = .FALSE.
      ALLOCATE(COND_THRU(N_STREET_LINKS))
      COND_THRU = .FALSE.
      ALLOCATE(COND_RIGHT(N_STREET_LINKS))
      COND_RIGHT = .FALSE.
      ALLOCATE(COND_LDIAG(N_STREET_LINKS))
      COND_LDIAG = .FALSE.
      ALLOCATE(COND_RDIAG(N_STREET_LINKS))
      COND_RDIAG = .FALSE.
      ALLOCATE(COND_LEFTPCT(N_STREET_LINKS, 5))
      COND_LEFTPCT = 0
      ALLOCATE(COND_THRUPCT(N_STREET_LINKS, 5))
      COND_THRUPCT = 0
      ALLOCATE(COND_RIGHTPCT(N_STREET_LINKS, 5))
      COND_RIGHTPCT = 0
      ALLOCATE(COND_LDIAGPCT(N_STREET_LINKS, 5))
      COND_LDIAGPCT = 0
      ALLOCATE(COND_RDIAGPCT(N_STREET_LINKS, 5))
      COND_RDIAGPCT = 0
      ALLOCATE(STOP_DELAY(N_STREET_LINKS))
      STOP_DELAY = 0
      ALLOCATE(STOP_DELAY_DIAG(N_STREET_LINKS))
      STOP_DELAY_DIAG = 0
      ALLOCATE(STOP_DELAY_LEFT(N_STREET_LINKS))
      STOP_DELAY_LEFT = 0
      ALLOCATE(STOP_DELAY_RIGHT(N_STREET_LINKS))
      STOP_DELAY_RIGHT = 0
      ALLOCATE(QUEUE_DELAY(N_STREET_LINKS))
      QUEUE_DELAY = 0
      ALLOCATE(QUEUE_DELAY_DIAG(N_STREET_LINKS))
      QUEUE_DELAY_DIAG = 0
      ALLOCATE(QUEUE_DELAY_LEFT(N_STREET_LINKS))
      QUEUE_DELAY_LEFT = 0
      ALLOCATE(QUEUE_DELAY_RIGHT(N_STREET_LINKS))
      QUEUE_DELAY_RIGHT = 0
      ALLOCATE(CENTROID(N_STREET_LINKS))
      CENTROID = 0
      ALLOCATE(CENTROID_NV(N_STREET_LINKS))
      CENTROID_NV = 0
      ALLOCATE(CENTROID_LABEL(N_STREET_LINKS))
      CENTROID_LABEL = 0
      ALLOCATE(MULTIPLIER_LEFT(N_STREET_LINKS, NTYPES))
      MULTIPLIER_LEFT = 1.0
      ALLOCATE(MULTIPLIER_THRU(N_STREET_LINKS, NTYPES))
      MULTIPLIER_THRU = 1.0
      ALLOCATE(MULTIPLIER_RIGHT(N_STREET_LINKS, NTYPES))
      MULTIPLIER_RIGHT = 1.0
      ALLOCATE(MULTIPLIER_LDIAG(N_STREET_LINKS, NTYPES))
      MULTIPLIER_LDIAG = 1.0
      ALLOCATE(MULTIPLIER_RDIAG(N_STREET_LINKS, NTYPES))
      MULTIPLIER_RDIAG = 1.0
      ALLOCATE(STOPPED_VEHICLES(N_STREET_LINKS))
      STOPPED_VEHICLES = 0
      ALLOCATE(SIGNAL_RANGE(N_STREET_LINKS))
      SIGNAL_RANGE = 0
      ALLOCATE(SIGNALIZED(N_STREET_LINKS))
      SIGNALIZED = .FALSE.
      
      ALLOCATE(WRITE12(N_STREET_LINKS))
      WRITE12 = .FALSE.
      ALLOCATE(WRITE13(N_STREET_LINKS))
      WRITE13 = .FALSE.
      ALLOCATE(WRITE21(N_STREET_LINKS, 19))
      WRITE21 = .FALSE.
      ALLOCATE(WRITE51(N_STREET_LINKS, 19))
      WRITE51 = .FALSE.
      ALLOCATE(WRITE82(N_STREET_LINKS))
      WRITE82 = .FALSE.
      ALLOCATE(WRITE83(N_STREET_LINKS))
      WRITE83 = .FALSE.
      ALLOCATE(LANE_NUMBERS(N_STREET_LINKS, N_STREET_LANES))
      LANE_NUMBERS = 0
      ALLOCATE(FIRST_FULL_LANE(N_STREET_LINKS))
      FIRST_FULL_LANE = 0
      ALLOCATE(LAST_FULL_LANE(N_STREET_LINKS))
      LAST_FULL_LANE = 0
      ALLOCATE(ALWAYS_GREEN(N_STREET_LINKS, 5))
      ALWAYS_GREEN = .FALSE.
      ALLOCATE(CHECK_MERGE(N_STREET_LINKS))
      CHECK_MERGE = 0
      ALLOCATE(LT_SPEED(N_STREET_LINKS))
      LT_SPEED = 22
      ALLOCATE(RT_SPEED(N_STREET_LINKS))
      RT_SPEED = 13
      
    ENDIF
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE REALLOCATE_STREET_LINK_ARRAYS(N)
    USE ARRAY_FUNCTIONS
    INTEGER :: N, I1, I2
! ----------------------------------------------------------------------
    I1 = N_STREET_LINKS
    I2 = N_STREET_LINKS + N
    N_STREET_LINKS = I2
    CALL REALLOCATE_INTEGER(SUSN, I1, I2)
    CALL REALLOCATE_INTEGER(SDSN, I1, I2)
    CALL REALLOCATE_INTEGER(SLENGTH, I1, I2)
    CALL REALLOCATE_INTEGER(STHRU_LINK, I1, I2)
    CALL REALLOCATE_REAL(SFREEFLOWSPEED, I1, I2)
    CALL REALLOCATE_REAL_X(SLANE_WIDTH, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(STHRU_ALIGNMENT_LANE, I1, I2)
    CALL REALLOCATE_REAL(SSTARTUP_TIME, I1, I2) 
    CALL REALLOCATE_INTEGER(SNUMLANES, I1, I2)
    CALL REALLOCATE_INTEGER(TOTAL_LANES, I1, I2)
    CALL REALLOCATE_REAL(SCFMULT, I1, I2)
    CALL REALLOCATE_INTEGER_X(SLAST_VEHICLE_OUT, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER_X(SLAST_VEHICLE_OUT_ID, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL(STHRU_PERCENT, I1, I2)
    CALL REALLOCATE_INTEGER(SENTERING, I1, I2)
    CALL REALLOCATE_INTEGER(SLANE_CHANGES, I1, I2)
    CALL REALLOCATE_INTEGER(SDISCHARGED, I1, I2)
    CALL REALLOCATE_INTEGER_X(SDISCHARGED_LANE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(DISCHARGED_LEFT, I1, I2)
    CALL REALLOCATE_INTEGER(DISCHARGED_RIGHT, I1, I2)
    CALL REALLOCATE_INTEGER(DISCHARGED_DIAG, I1, I2)
    CALL REALLOCATE_INTEGER(SDISCHARGED_BUSES, I1, I2)
    CALL REALLOCATE_INTEGER_X(SDISCHARGED_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_REAL(SAREA, I1, I2)
    CALL REALLOCATE_REAL_X(SZDIST_LANE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL_X(SZDIST_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(SZTIME_TYPE, I1, I2, NTYPES)
    CALL REALLOCATE_LOGICAL_X(SLANE_CLOSED, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_LOGICAL_X(LANE_GOES_LEFT, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_LOGICAL_X(LANE_GOES_RIGHT, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL(SZDIST, I1, I2)
    CALL REALLOCATE_REAL(ZDIST_DIAG, I1, I2)
    CALL REALLOCATE_REAL(ZDIST_LEFT, I1, I2)
    CALL REALLOCATE_REAL(ZDIST_RIGHT, I1, I2)
    CALL REALLOCATE_REAL_X(SZDELAY_LANE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL_X(SZOCCS, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL(SPERSON_TRIPS, I1, I2)
    CALL REALLOCATE_INTEGER(ZSTOP, I1, I2)
    CALL REALLOCATE_INTEGER(RED_LIGHT_RUNNERS, I1, I2)
    CALL REALLOCATE_INTEGER(VEHICLES_INDZ, I1, I2)
    CALL REALLOCATE_REAL(SZTIME, I1, I2)
    CALL REALLOCATE_REAL(ZTIME_DIAG, I1, I2)
    CALL REALLOCATE_REAL(ZTIME_LEFT, I1, I2)
    CALL REALLOCATE_REAL(ZTIME_RIGHT, I1, I2)
    CALL REALLOCATE_REAL(SZTIME_BUS, I1, I2)
    CALL REALLOCATE_REAL_X(SZTIME_LANE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_LOGICAL_XY(SXCLUDE_TYPE, I1, I2, N_STREET_LANES, NTYPES)
    CALL REALLOCATE_INTEGER(SFIRST_DETECTOR, I1, I2)
    CALL REALLOCATE_REAL(SGRADE, I1, I2)
    CALL REALLOCATE_INTEGER(SSHOULDER_WIDTH, I1, I2)
    CALL REALLOCATE_LOGICAL(SEV_ONLINK, I1, I2)
    CALL REALLOCATE_INTEGER(SFIRST_ON_SHOULDER, I1, I2)
    CALL REALLOCATE_REAL(SCO_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(SHC_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(SNOX_TOTAL, I1, I2)
    CALL REALLOCATE_REAL(SFUEL_TOTAL, I1, I2)
    CALL REALLOCATE_INTEGER(SALIGNMENT_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(DIAG_NODE, I1, I2)
    CALL REALLOCATE_INTEGER(PED_CODE, I1, I2)         
    CALL REALLOCATE_REAL(QDISCHARGE_HDWY, I1, I2)         
    CALL REALLOCATE_INTEGER(SIGHT_DIST, I1, I2)         
    CALL REALLOCATE_REAL(TIME_IN_AMBER_LEFT, I1, I2)         
    CALL REALLOCATE_REAL(TIME_IN_AMBER_THRU, I1, I2)         
    CALL REALLOCATE_REAL(TIME_IN_AMBER_RIGHT, I1, I2)         
    CALL REALLOCATE_REAL(TIME_IN_AMBER_DIAG, I1, I2)         
    CALL REALLOCATE_REAL(TIME_IN_RED_LEFT, I1, I2)
    CALL REALLOCATE_REAL(TIME_IN_RED_THRU, I1, I2)
    CALL REALLOCATE_REAL(TIME_IN_RED_RIGHT, I1, I2)
    CALL REALLOCATE_REAL(TIME_IN_RED_DIAG, I1, I2)
    CALL REALLOCATE_INTEGER(NUMBER_LEFTPOCKETS, I1, I2)     
    CALL REALLOCATE_INTEGER(NUMBER_RIGHTPOCKETS, I1, I2)    
    CALL REALLOCATE_INTEGER(NUMBER_TURNINGWAYS, I1, I2)    
    CALL REALLOCATE_REAL_X(LANE_LENGTH, I1, I2, N_STREET_LANES)     
    CALL REALLOCATE_INTEGER(FIRST_BUS_STATION, I1, I2)
    CALL REALLOCATE_INTEGER(LEFT_LINK, I1, I2)              
    CALL REALLOCATE_INTEGER(RIGHT_LINK, I1, I2)             
    CALL REALLOCATE_INTEGER(LEFT_DIAG_LINK, I1, I2)              
    CALL REALLOCATE_INTEGER(RIGHT_DIAG_LINK, I1, I2)              
    CALL REALLOCATE_REAL(RTW_EXIT_POINT, I1, I2)
    CALL REALLOCATE_REAL(RTW_ENTRY_POINT, I1, I2)
    CALL REALLOCATE_INTEGER(RTW_RECEIVING_LINK, I1, I2)
    CALL REALLOCATE_REAL(RTW_LENGTH, I1, I2)              
    CALL REALLOCATE_REAL(RTW_FFSPEED, I1, I2)              
    CALL REALLOCATE_INTEGER(RTW_CONTROL_CODE, I1, I2)              
    CALL REALLOCATE_INTEGER(RTW_LANES, I1, I2)              
    CALL REALLOCATE_INTEGER(OPPOSE_LINK, I1, I2)            
    CALL REALLOCATE_REAL(LEFT_PERCENT, I1, I2)           
    CALL REALLOCATE_REAL(RIGHT_PERCENT, I1, I2)          
    CALL REALLOCATE_REAL(LDIAG_PERCENT, I1, I2)           
    CALL REALLOCATE_REAL(RDIAG_PERCENT, I1, I2)           
    CALL REALLOCATE_INTEGER_X(CHANNELIZATION, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER_X(FIRST_VEHICLE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER_X(SLAST_VEHICLE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(FTC_SIGNAL_ID, I1, I2)
    CALL REALLOCATE_INTEGER(ROUNDABOUT_ID, I1, I2)
    CALL REALLOCATE_INTEGER(ROUNDABOUT_APPROACH_NUM, I1, I2)
    CALL REALLOCATE_INTEGER(ROUNDABOUT_EXIT_NUM, I1, I2)
    CALL REALLOCATE_INTEGER(AC_SIGNAL_ID, I1, I2)
    CALL REALLOCATE_INTEGER(PREV_SIGNAL_CODE, I1, I2)
    CALL REALLOCATE_INTEGER(PREV_SIGNAL_LEFT, I1, I2)
    CALL REALLOCATE_INTEGER(SIGNAL_CODE, I1, I2)
    CALL REALLOCATE_LOGICAL(SIGNAL_LEFT, I1, I2)
    CALL REALLOCATE_LOGICAL(SIGNAL_THRU, I1, I2)
    CALL REALLOCATE_LOGICAL(SIGNAL_RIGHT, I1, I2)
    CALL REALLOCATE_LOGICAL(SIGNAL_DIAG, I1, I2)
    CALL REALLOCATE_INTEGER(PHASE_LEFT, I1, I2)
    CALL REALLOCATE_INTEGER(PHASE_THRU, I1, I2)
    CALL REALLOCATE_INTEGER(PHASE_RIGHT, I1, I2)
    CALL REALLOCATE_INTEGER(PHASE_DIAG, I1, I2)
    CALL REALLOCATE_LOGICAL(AMBER_LEFT, I1, I2)
    CALL REALLOCATE_LOGICAL(AMBER_THRU, I1, I2)
    CALL REALLOCATE_LOGICAL(AMBER_RIGHT, I1, I2)
    CALL REALLOCATE_LOGICAL(AMBER_DIAG, I1, I2)
    CALL REALLOCATE_INTEGER(NEAR_CROSSLINK, I1, I2)
    CALL REALLOCATE_INTEGER_X(NEAR_UPPER_CROSSLINK, I1, I2, 5)
    CALL REALLOCATE_INTEGER(FAR_CROSSLINK, I1, I2)
    CALL REALLOCATE_REAL(UP_INT_WIDTH, I1, I2)
    CALL REALLOCATE_REAL_X(LANE_CENTER, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL_XY(LT_ARC_LENGTH, I1, I2, N_STREET_LANES, N_STREET_LANES)
    CALL REALLOCATE_REAL_XY(THRU_ARC_LENGTH, I1, I2, N_STREET_LANES, N_STREET_LANES)
    CALL REALLOCATE_REAL_XY(RT_ARC_LENGTH, I1, I2, N_STREET_LANES, N_STREET_LANES)
    CALL REALLOCATE_REAL_XY(LD_ARC_LENGTH, I1, I2, N_STREET_LANES, N_STREET_LANES)
    CALL REALLOCATE_REAL_XY(RD_ARC_LENGTH, I1, I2, N_STREET_LANES, N_STREET_LANES)
    CALL REALLOCATE_REAL(LT_LIMITED_SPEED_DIST, I1, I2)
    CALL REALLOCATE_REAL(RT_LIMITED_SPEED_DIST, I1, I2)
    CALL REALLOCATE_INTEGER(APPROACH_NUM, I1, I2)
    CALL REALLOCATE_INTEGER_X(BLOCKAGE, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(STE_FREQ, I1, I2)
    CALL REALLOCATE_INTEGER(STE_DURATION, I1, I2)
    CALL REALLOCATE_INTEGER(SOURCE_SINK, I1, I2)
    CALL REALLOCATE_INTEGER(CYCLE_FAILURES, I1, I2)
    CALL REALLOCATE_INTEGER_X(QUEUE_TOTAL, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER_X(QUEUE_MAX, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_REAL(RICDELAY, I1, I2)
    CALL REALLOCATE_REAL(RICDELD, I1, I2)
    CALL REALLOCATE_REAL(RICDELL, I1, I2)
    CALL REALLOCATE_REAL(RICDELR, I1, I2)
    CALL REALLOCATE_LOGICAL(RTOR, I1, I2)
    CALL REALLOCATE_INTEGER(LINKTYPE_CODE, I1, I2)
    CALL REALLOCATE_REAL(LAGGER_TIMER, I1, I2)
    CALL REALLOCATE_LOGICAL(COND_LEFT, I1, I2)
    CALL REALLOCATE_LOGICAL(COND_THRU, I1, I2)
    CALL REALLOCATE_LOGICAL(COND_RIGHT, I1, I2)
    CALL REALLOCATE_LOGICAL(COND_LDIAG, I1, I2)
    CALL REALLOCATE_LOGICAL(COND_RDIAG, I1, I2)
    CALL REALLOCATE_INTEGER_X(COND_LEFTPCT, I1, I2, 5)
    CALL REALLOCATE_INTEGER_X(COND_THRUPCT, I1, I2, 5)
    CALL REALLOCATE_INTEGER_X(COND_RIGHTPCT, I1, I2, 5)
    CALL REALLOCATE_INTEGER_X(COND_LDIAGPCT, I1, I2, 5)
    CALL REALLOCATE_INTEGER_X(COND_RDIAGPCT, I1, I2, 5)
    CALL REALLOCATE_REAL(STOP_DELAY, I1, I2)
    CALL REALLOCATE_REAL(STOP_DELAY_DIAG, I1, I2)
    CALL REALLOCATE_REAL(STOP_DELAY_LEFT, I1, I2)
    CALL REALLOCATE_REAL(STOP_DELAY_RIGHT, I1, I2)
    CALL REALLOCATE_REAL(QUEUE_DELAY, I1, I2)
    CALL REALLOCATE_REAL(QUEUE_DELAY_DIAG, I1, I2)
    CALL REALLOCATE_REAL(QUEUE_DELAY_LEFT, I1, I2)
    CALL REALLOCATE_REAL(QUEUE_DELAY_RIGHT, I1, I2)
    CALL REALLOCATE_INTEGER(CENTROID, I1, I2)
    CALL REALLOCATE_INTEGER(CENTROID_NV, I1, I2)
    CALL REALLOCATE_INTEGER(CENTROID_LABEL, I1, I2)
    CALL REALLOCATE_REAL_X(MULTIPLIER_LEFT, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(MULTIPLIER_THRU, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(MULTIPLIER_RIGHT, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(MULTIPLIER_LDIAG, I1, I2, NTYPES)
    CALL REALLOCATE_REAL_X(MULTIPLIER_RDIAG, I1, I2, NTYPES)
    CALL REALLOCATE_INTEGER(STOPPED_VEHICLES, I1, I2)
    CALL REALLOCATE_INTEGER(SIGNAL_RANGE, I1, I2)
    CALL REALLOCATE_LOGICAL(SIGNALIZED, I1, I2)
    CALL REALLOCATE_LOGICAL(WRITE12, I1, I2)
    CALL REALLOCATE_LOGICAL(WRITE13, I1, I2)
    CALL REALLOCATE_LOGICAL_X(WRITE21, I1, I2, 19)
    CALL REALLOCATE_LOGICAL_X(WRITE51, I1, I2, 19)
    CALL REALLOCATE_LOGICAL(WRITE82, I1, I2)
    CALL REALLOCATE_LOGICAL(WRITE83, I1, I2)
    CALL REALLOCATE_INTEGER_X(LANE_NUMBERS, I1, I2, N_STREET_LANES)
    CALL REALLOCATE_INTEGER(FIRST_FULL_LANE, I1, I2)
    CALL REALLOCATE_INTEGER(LAST_FULL_LANE, I1, I2)
    CALL REALLOCATE_LOGICAL_X(ALWAYS_GREEN, I1, I2, 5)
    CALL REALLOCATE_INTEGER(CHECK_MERGE, I1, I2)
    CALL REALLOCATE_INTEGER(LT_SPEED, I1, I2)
    CALL REALLOCATE_INTEGER(RT_SPEED, I1, I2)
    RETURN
    END SUBROUTINE
   
  ! ==================================================================================================
    SUBROUTINE DEALLOCATE_STREET_LINK_ARRAYS
    USE SIMPARAMS
    IF(ALLOCATED(SUSN)) THEN
      DEALLOCATE(SUSN)
      DEALLOCATE(SDSN)
      DEALLOCATE(SLENGTH)
      DEALLOCATE(STHRU_LINK)
      DEALLOCATE(SFREEFLOWSPEED)
      DEALLOCATE(SLANE_WIDTH)
      DEALLOCATE(STHRU_ALIGNMENT_LANE)
      DEALLOCATE(SSTARTUP_TIME)          
      DEALLOCATE(SNUMLANES)
      DEALLOCATE(TOTAL_LANES)
      DEALLOCATE(SCFMULT)
      DEALLOCATE(SLAST_VEHICLE_OUT)
      DEALLOCATE(SLAST_VEHICLE_OUT_ID)
      DEALLOCATE(STHRU_PERCENT)
      DEALLOCATE(SENTERING)
      DEALLOCATE(SLANE_CHANGES)
      DEALLOCATE(SDISCHARGED)
      DEALLOCATE(SDISCHARGED_LANE)
      DEALLOCATE(DISCHARGED_LEFT)
      DEALLOCATE(DISCHARGED_RIGHT)
      DEALLOCATE(DISCHARGED_DIAG)
      DEALLOCATE(SDISCHARGED_BUSES)
      DEALLOCATE(SDISCHARGED_TYPE)
      DEALLOCATE(SAREA)
      DEALLOCATE(SZDIST_LANE)
      DEALLOCATE(SZDIST_TYPE)
      DEALLOCATE(SZTIME_TYPE)
      DEALLOCATE(SZDIST)
      DEALLOCATE(ZDIST_DIAG)
      DEALLOCATE(ZDIST_LEFT)
      DEALLOCATE(ZDIST_RIGHT)
      DEALLOCATE(SZDELAY_LANE)
      DEALLOCATE(SZOCCS)
      DEALLOCATE(SPERSON_TRIPS)
      DEALLOCATE(ZSTOP)
      DEALLOCATE(RED_LIGHT_RUNNERS)
      DEALLOCATE(VEHICLES_INDZ)
      DEALLOCATE(SZTIME)
      DEALLOCATE(ZTIME_DIAG)
      DEALLOCATE(ZTIME_LEFT)
      DEALLOCATE(ZTIME_RIGHT)
      DEALLOCATE(SZTIME_BUS)
      DEALLOCATE(SZTIME_LANE)
      DEALLOCATE(SXCLUDE_TYPE)
      DEALLOCATE(SFIRST_DETECTOR)
      DEALLOCATE(SGRADE)
      DEALLOCATE(SSHOULDER_WIDTH)
      DEALLOCATE(SEV_ONLINK)
      DEALLOCATE(SFIRST_ON_SHOULDER)
      DEALLOCATE(SCO_TOTAL)
      DEALLOCATE(SHC_TOTAL)
      DEALLOCATE(SNOX_TOTAL)
      DEALLOCATE(SFUEL_TOTAL)
      DEALLOCATE(SLANE_CLOSED)
      DEALLOCATE(LANE_GOES_LEFT)
      DEALLOCATE(LANE_GOES_RIGHT)

      DEALLOCATE(SALIGNMENT_LANE)
      DEALLOCATE(DIAG_NODE)
      DEALLOCATE(PED_CODE)         
      DEALLOCATE(QDISCHARGE_HDWY)         
      DEALLOCATE(SIGHT_DIST)         
      DEALLOCATE(TIME_IN_AMBER_LEFT)         
      DEALLOCATE(TIME_IN_AMBER_THRU)         
      DEALLOCATE(TIME_IN_AMBER_RIGHT)         
      DEALLOCATE(TIME_IN_AMBER_DIAG)         
      DEALLOCATE(TIME_IN_RED_LEFT)         
      DEALLOCATE(TIME_IN_RED_THRU)         
      DEALLOCATE(TIME_IN_RED_RIGHT)         
      DEALLOCATE(TIME_IN_RED_DIAG)         
      DEALLOCATE(NUMBER_LEFTPOCKETS)     
      DEALLOCATE(NUMBER_RIGHTPOCKETS)    
      DEALLOCATE(NUMBER_TURNINGWAYS)    
      DEALLOCATE(LANE_LENGTH)     
      DEALLOCATE(FIRST_BUS_STATION)
      DEALLOCATE(LEFT_LINK)              
      DEALLOCATE(RIGHT_LINK)             
      DEALLOCATE(LEFT_DIAG_LINK)              
      DEALLOCATE(RIGHT_DIAG_LINK)              
      DEALLOCATE(RTW_EXIT_POINT)              
      DEALLOCATE(RTW_ENTRY_POINT)              
      DEALLOCATE(RTW_RECEIVING_LINK)              
      DEALLOCATE(RTW_LENGTH)              
      DEALLOCATE(RTW_FFSPEED)              
      DEALLOCATE(RTW_CONTROL_CODE)              
      DEALLOCATE(RTW_LANES)              
      DEALLOCATE(OPPOSE_LINK)            
      DEALLOCATE(LEFT_PERCENT)           
      DEALLOCATE(RIGHT_PERCENT)          
      DEALLOCATE(LDIAG_PERCENT)           
      DEALLOCATE(RDIAG_PERCENT)           
      DEALLOCATE(CHANNELIZATION)
      DEALLOCATE(FIRST_VEHICLE)
      DEALLOCATE(SLAST_VEHICLE)
      DEALLOCATE(FTC_SIGNAL_ID)
      DEALLOCATE(ROUNDABOUT_ID)
      DEALLOCATE(ROUNDABOUT_APPROACH_NUM)
      DEALLOCATE(ROUNDABOUT_EXIT_NUM)
      DEALLOCATE(AC_SIGNAL_ID)
      DEALLOCATE(PREV_SIGNAL_CODE)
      DEALLOCATE(PREV_SIGNAL_LEFT)
      DEALLOCATE(SIGNAL_CODE)
      DEALLOCATE(SIGNAL_LEFT)
      DEALLOCATE(SIGNAL_THRU)
      DEALLOCATE(SIGNAL_RIGHT)
      DEALLOCATE(SIGNAL_DIAG)
      DEALLOCATE(PHASE_LEFT)
      DEALLOCATE(PHASE_THRU)
      DEALLOCATE(PHASE_RIGHT)
      DEALLOCATE(PHASE_DIAG)
      DEALLOCATE(AMBER_LEFT)
      DEALLOCATE(AMBER_THRU)
      DEALLOCATE(AMBER_RIGHT)
      DEALLOCATE(AMBER_DIAG)
      DEALLOCATE(NEAR_CROSSLINK)
      DEALLOCATE(NEAR_UPPER_CROSSLINK)
      DEALLOCATE(FAR_CROSSLINK)
      DEALLOCATE(UP_INT_WIDTH)
      DEALLOCATE(LANE_CENTER)
      DEALLOCATE(LT_ARC_LENGTH)
      DEALLOCATE(THRU_ARC_LENGTH)
      DEALLOCATE(RT_ARC_LENGTH)
      DEALLOCATE(LD_ARC_LENGTH)
      DEALLOCATE(RD_ARC_LENGTH)
      DEALLOCATE(LT_LIMITED_SPEED_DIST)
      DEALLOCATE(RT_LIMITED_SPEED_DIST)
      DEALLOCATE(APPROACH_NUM)
      DEALLOCATE(BLOCKAGE)
      DEALLOCATE(STE_FREQ)
      DEALLOCATE(STE_DURATION)
      DEALLOCATE(SOURCE_SINK)
      DEALLOCATE(CYCLE_FAILURES)
      DEALLOCATE(QUEUE_TOTAL)
      DEALLOCATE(QUEUE_MAX)
      DEALLOCATE(RICDELAY)
      DEALLOCATE(RICDELD)
      DEALLOCATE(RICDELL)
      DEALLOCATE(RICDELR)
      DEALLOCATE(RTOR)
      DEALLOCATE(LINKTYPE_CODE)
      DEALLOCATE(LAGGER_TIMER)
      DEALLOCATE(COND_LEFT)
      DEALLOCATE(COND_THRU)
      DEALLOCATE(COND_RIGHT)
      DEALLOCATE(COND_LDIAG)
      DEALLOCATE(COND_RDIAG)
      DEALLOCATE(COND_LEFTPCT)
      DEALLOCATE(COND_THRUPCT)
      DEALLOCATE(COND_RIGHTPCT)
      DEALLOCATE(COND_LDIAGPCT)
      DEALLOCATE(COND_RDIAGPCT)
      DEALLOCATE(STOP_DELAY)
      DEALLOCATE(STOP_DELAY_DIAG)
      DEALLOCATE(STOP_DELAY_LEFT)
      DEALLOCATE(STOP_DELAY_RIGHT)
      DEALLOCATE(QUEUE_DELAY)
      DEALLOCATE(QUEUE_DELAY_DIAG)
      DEALLOCATE(QUEUE_DELAY_LEFT)
      DEALLOCATE(QUEUE_DELAY_RIGHT)
      DEALLOCATE(CENTROID)
      DEALLOCATE(CENTROID_NV)
      DEALLOCATE(CENTROID_LABEL)
      DEALLOCATE(MULTIPLIER_LEFT)
      DEALLOCATE(MULTIPLIER_THRU)
      DEALLOCATE(MULTIPLIER_RIGHT)
      DEALLOCATE(MULTIPLIER_LDIAG)
      DEALLOCATE(MULTIPLIER_RDIAG)
      DEALLOCATE(STOPPED_VEHICLES)
      DEALLOCATE(SIGNAL_RANGE)
      DEALLOCATE(SIGNALIZED)
      DEALLOCATE(WRITE12)
      DEALLOCATE(WRITE13)
#ifndef TSIS_COMPATIBLE
      DEALLOCATE(WRITE21)
      DEALLOCATE(WRITE51)
      DEALLOCATE(WRITE82)
      DEALLOCATE(WRITE83)
#endif
      DEALLOCATE(LANE_NUMBERS)
      DEALLOCATE(FIRST_FULL_LANE)
      DEALLOCATE(LAST_FULL_LANE)
      DEALLOCATE(ALWAYS_GREEN)
      DEALLOCATE(CHECK_MERGE)
      DEALLOCATE(LT_SPEED)
      DEALLOCATE(RT_SPEED)
    ENDIF
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE FIND_STREET_LINK(I1, I2, IL)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: I1
    INTEGER, INTENT(IN) :: I2
    INTEGER, INTENT(OUT) :: IL
    INTEGER :: I
! ----------------------------------------------------------------------
    IL = 0
    DO I = 1, N_STREET_LINKS
      IF(SUSN(I) .EQ. I1 .AND. SDSN(I) .EQ. I2) THEN
        IL = I
        EXIT
      ENDIF
    ENDDO
    RETURN
    END SUBROUTINE

! ==================================================================================================
    SUBROUTINE SAVE_STREET_LINKS(FILE1, FILE2, FIRST)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1, FILE2
    LOGICAL, INTENT(IN) :: FIRST
! ----------------------------------------------------------------------

! --- Save static data.
    
    IF(FIRST) THEN
      WRITE(FILE1) SUSN
      WRITE(FILE1) SDSN
      WRITE(FILE1) SLENGTH
      WRITE(FILE1) STHRU_LINK
      WRITE(FILE1) SFREEFLOWSPEED
      WRITE(FILE1) SLANE_WIDTH
      WRITE(FILE1) STHRU_ALIGNMENT_LANE
      WRITE(FILE1) SSTARTUP_TIME          
      WRITE(FILE1) SNUMLANES
      WRITE(FILE1) TOTAL_LANES
      WRITE(FILE1) SCFMULT
      WRITE(FILE1) STHRU_PERCENT
      WRITE(FILE1) SDISCHARGED_TYPE
      WRITE(FILE1) SAREA
      WRITE(FILE1) SXCLUDE_TYPE
      WRITE(FILE1) SFIRST_DETECTOR
      WRITE(FILE1) SGRADE
      WRITE(FILE1) SSHOULDER_WIDTH
      WRITE(FILE1) SALIGNMENT_LANE
      WRITE(FILE1) DIAG_NODE
      WRITE(FILE1) PED_CODE         
      WRITE(FILE1) QDISCHARGE_HDWY         
      WRITE(FILE1) SIGHT_DIST         
      WRITE(FILE1) TIME_IN_AMBER_LEFT         
      WRITE(FILE1) TIME_IN_AMBER_THRU         
      WRITE(FILE1) TIME_IN_AMBER_RIGHT         
      WRITE(FILE1) TIME_IN_AMBER_DIAG         
      WRITE(FILE1) TIME_IN_RED_LEFT         
      WRITE(FILE1) TIME_IN_RED_THRU         
      WRITE(FILE1) TIME_IN_RED_RIGHT         
      WRITE(FILE1) TIME_IN_RED_DIAG
      WRITE(FILE1) NUMBER_LEFTPOCKETS     
      WRITE(FILE1) NUMBER_RIGHTPOCKETS    
      WRITE(FILE1) NUMBER_TURNINGWAYS    
      WRITE(FILE1) LANE_LENGTH     
      WRITE(FILE1) FIRST_BUS_STATION
      WRITE(FILE1) LEFT_LINK              
      WRITE(FILE1) RIGHT_LINK             
      WRITE(FILE1) LEFT_DIAG_LINK              
      WRITE(FILE1) RIGHT_DIAG_LINK              
      WRITE(FILE1) RTW_EXIT_POINT              
      WRITE(FILE1) RTW_ENTRY_POINT              
      WRITE(FILE1) RTW_RECEIVING_LINK              
      WRITE(FILE1) RTW_LENGTH              
      WRITE(FILE1) RTW_FFSPEED              
      WRITE(FILE1) RTW_CONTROL_CODE              
      WRITE(FILE1) RTW_LANES              
      WRITE(FILE1) OPPOSE_LINK            
      WRITE(FILE1) LEFT_PERCENT           
      WRITE(FILE1) RIGHT_PERCENT          
      WRITE(FILE1) LDIAG_PERCENT           
      WRITE(FILE1) RDIAG_PERCENT           
      WRITE(FILE1) CHANNELIZATION
      WRITE(FILE1) FTC_SIGNAL_ID
      WRITE(FILE1) ROUNDABOUT_ID
      WRITE(FILE1) ROUNDABOUT_APPROACH_NUM
      WRITE(FILE1) ROUNDABOUT_EXIT_NUM
      WRITE(FILE1) AC_SIGNAL_ID
      WRITE(FILE1) NEAR_CROSSLINK
      WRITE(FILE1) NEAR_UPPER_CROSSLINK
      WRITE(FILE1) FAR_CROSSLINK
      WRITE(FILE1) UP_INT_WIDTH
      WRITE(FILE1) LANE_CENTER
      WRITE(FILE1) LT_ARC_LENGTH
      WRITE(FILE1) THRU_ARC_LENGTH
      WRITE(FILE1) RT_ARC_LENGTH
      WRITE(FILE1) LD_ARC_LENGTH
      WRITE(FILE1) LT_LIMITED_SPEED_DIST
      WRITE(FILE1) RT_LIMITED_SPEED_DIST
      WRITE(FILE1) RD_ARC_LENGTH
      WRITE(FILE1) LT_LIMITED_SPEED_DIST
      WRITE(FILE1) RT_LIMITED_SPEED_DIST
      WRITE(FILE1) APPROACH_NUM
      WRITE(FILE1) STE_FREQ
      WRITE(FILE1) STE_DURATION
      WRITE(FILE1) RTOR
      WRITE(FILE1) LINKTYPE_CODE
      WRITE(FILE1) COND_LEFT
      WRITE(FILE1) COND_THRU
      WRITE(FILE1) COND_RIGHT
      WRITE(FILE1) COND_LDIAG
      WRITE(FILE1) COND_RDIAG
      WRITE(FILE1) COND_LEFTPCT
      WRITE(FILE1) COND_THRUPCT
      WRITE(FILE1) COND_RIGHTPCT
      WRITE(FILE1) COND_LDIAGPCT
      WRITE(FILE1) COND_RDIAGPCT
      WRITE(FILE1) CENTROID
      WRITE(FILE1) CENTROID_LABEL
      WRITE(FILE1) MULTIPLIER_LEFT
      WRITE(FILE1) MULTIPLIER_THRU
      WRITE(FILE1) MULTIPLIER_RIGHT
      WRITE(FILE1) MULTIPLIER_LDIAG
      WRITE(FILE1) MULTIPLIER_RDIAG
      WRITE(FILE1) SIGNAL_RANGE
      WRITE(FILE1) SIGNALIZED
      WRITE(FILE1) WRITE12
      WRITE(FILE1) WRITE13
      WRITE(FILE1) WRITE21
      WRITE(FILE1) WRITE51
      WRITE(FILE1) WRITE82
      WRITE(FILE1) WRITE83
      WRITE(FILE1) LANE_NUMBERS
      WRITE(FILE1) FIRST_FULL_LANE
      WRITE(FILE1) LAST_FULL_LANE
      WRITE(FILE1) ALWAYS_GREEN
      WRITE(FILE1) CHECK_MERGE
      WRITE(FILE1) LT_SPEED
      WRITE(FILE1) RT_SPEED
    ENDIF

! --- Save dynamic data.

    WRITE(FILE2) SLAST_VEHICLE_OUT
    WRITE(FILE2) SLAST_VEHICLE_OUT_ID
    WRITE(FILE2) FIRST_VEHICLE
    WRITE(FILE2) SLAST_VEHICLE
    WRITE(FILE2) PREV_SIGNAL_CODE
    WRITE(FILE2) PREV_SIGNAL_LEFT
    WRITE(FILE2) SIGNAL_CODE
    WRITE(FILE2) SIGNAL_LEFT
    WRITE(FILE2) SIGNAL_THRU
    WRITE(FILE2) SIGNAL_RIGHT
    WRITE(FILE2) SIGNAL_DIAG
    WRITE(FILE2) PHASE_LEFT
    WRITE(FILE2) PHASE_THRU
    WRITE(FILE2) PHASE_RIGHT
    WRITE(FILE2) PHASE_DIAG
    WRITE(FILE2) AMBER_LEFT
    WRITE(FILE2) AMBER_THRU
    WRITE(FILE2) AMBER_RIGHT
    WRITE(FILE2) AMBER_DIAG
    WRITE(FILE2) BLOCKAGE
    WRITE(FILE2) SOURCE_SINK
    WRITE(FILE2) SENTERING
    WRITE(FILE2) SLANE_CHANGES
    WRITE(FILE2) SDISCHARGED
    WRITE(FILE2) SDISCHARGED_LANE
    WRITE(FILE2) DISCHARGED_LEFT
    WRITE(FILE2) DISCHARGED_RIGHT
    WRITE(FILE2) DISCHARGED_DIAG
    WRITE(FILE2) SDISCHARGED_BUSES
    WRITE(FILE2) SZDIST_LANE
    WRITE(FILE2) SZDIST_TYPE
    WRITE(FILE2) SZTIME_TYPE
    WRITE(FILE2) SZDIST
    WRITE(FILE2) ZDIST_DIAG
    WRITE(FILE2) ZDIST_LEFT
    WRITE(FILE2) ZDIST_RIGHT
    WRITE(FILE2) SZDELAY_LANE
    WRITE(FILE2) SZOCCS
    WRITE(FILE2) SPERSON_TRIPS
    WRITE(FILE2) ZSTOP
    WRITE(FILE2) RED_LIGHT_RUNNERS
    WRITE(FILE2) VEHICLES_INDZ
    WRITE(FILE2) SZTIME
    WRITE(FILE2) ZTIME_DIAG
    WRITE(FILE2) ZTIME_LEFT
    WRITE(FILE2) ZTIME_RIGHT
    WRITE(FILE2) SZTIME_BUS
    WRITE(FILE2) SZTIME_LANE
    WRITE(FILE2) SEV_ONLINK
    WRITE(FILE2) SFIRST_ON_SHOULDER
    WRITE(FILE2) SCO_TOTAL
    WRITE(FILE2) SHC_TOTAL
    WRITE(FILE2) SNOX_TOTAL
    WRITE(FILE2) SFUEL_TOTAL
    WRITE(FILE2) SLANE_CLOSED
    WRITE(FILE2) LANE_GOES_LEFT
    WRITE(FILE2) LANE_GOES_RIGHT
    WRITE(FILE2) CYCLE_FAILURES
    WRITE(FILE2) QUEUE_TOTAL
    WRITE(FILE2) QUEUE_MAX
    WRITE(FILE2) RICDELAY
    WRITE(FILE2) RICDELD
    WRITE(FILE2) RICDELL
    WRITE(FILE2) RICDELR
    WRITE(FILE2) LAGGER_TIMER
    WRITE(FILE2) STOPPED_VEHICLES
    WRITE(FILE2) STOP_DELAY
    WRITE(FILE2) STOP_DELAY_DIAG
    WRITE(FILE2) STOP_DELAY_LEFT
    WRITE(FILE2) STOP_DELAY_RIGHT
    WRITE(FILE2) QUEUE_DELAY
    WRITE(FILE2) QUEUE_DELAY_DIAG
    WRITE(FILE2) QUEUE_DELAY_LEFT
    WRITE(FILE2) QUEUE_DELAY_RIGHT
    WRITE(FILE2) CENTROID_NV
    RETURN
    END SUBROUTINE
        
! ==================================================================================================
    SUBROUTINE RESTORE_STREET_LINKS(FILE1, FILE2)
    USE SIMPARAMS
    INTEGER, INTENT(IN) :: FILE1, FILE2
! ----------------------------------------------------------------------
! --- Restore static data.

    READ(FILE1) SUSN
    READ(FILE1) SDSN
    READ(FILE1) SLENGTH
    READ(FILE1) STHRU_LINK
    READ(FILE1) SFREEFLOWSPEED
    READ(FILE1) SLANE_WIDTH
    READ(FILE1) STHRU_ALIGNMENT_LANE
    READ(FILE1) SSTARTUP_TIME          
    READ(FILE1) SNUMLANES
    READ(FILE1) TOTAL_LANES
    READ(FILE1) SCFMULT
    READ(FILE1) STHRU_PERCENT
    READ(FILE1) SDISCHARGED_TYPE
    READ(FILE1) SAREA
    READ(FILE1) SXCLUDE_TYPE
    READ(FILE1) SFIRST_DETECTOR
    READ(FILE1) SGRADE
    READ(FILE1) SSHOULDER_WIDTH
    READ(FILE1) SALIGNMENT_LANE
    READ(FILE1) DIAG_NODE
    READ(FILE1) PED_CODE         
    READ(FILE1) QDISCHARGE_HDWY         
    READ(FILE1) SIGHT_DIST         
    READ(FILE1) TIME_IN_AMBER_LEFT         
    READ(FILE1) TIME_IN_AMBER_THRU         
    READ(FILE1) TIME_IN_AMBER_RIGHT         
    READ(FILE1) TIME_IN_AMBER_DIAG         
    READ(FILE1) TIME_IN_RED_LEFT         
    READ(FILE1) TIME_IN_RED_THRU         
    READ(FILE1) TIME_IN_RED_RIGHT         
    READ(FILE1) TIME_IN_RED_DIAG
    READ(FILE1) NUMBER_LEFTPOCKETS     
    READ(FILE1) NUMBER_RIGHTPOCKETS    
    READ(FILE1) NUMBER_TURNINGWAYS    
    READ(FILE1) LANE_LENGTH     
    READ(FILE1) FIRST_BUS_STATION
    READ(FILE1) LEFT_LINK              
    READ(FILE1) RIGHT_LINK             
    READ(FILE1) LEFT_DIAG_LINK              
    READ(FILE1) RIGHT_DIAG_LINK              
    READ(FILE1) RTW_EXIT_POINT              
    READ(FILE1) RTW_ENTRY_POINT              
    READ(FILE1) RTW_RECEIVING_LINK              
    READ(FILE1) RTW_LENGTH              
    READ(FILE1) RTW_FFSPEED              
    READ(FILE1) RTW_CONTROL_CODE              
    READ(FILE1) RTW_LANES              
    READ(FILE1) OPPOSE_LINK            
    READ(FILE1) LEFT_PERCENT           
    READ(FILE1) RIGHT_PERCENT          
    READ(FILE1) LDIAG_PERCENT           
    READ(FILE1) RDIAG_PERCENT           
    READ(FILE1) CHANNELIZATION
    READ(FILE1) FTC_SIGNAL_ID
    READ(FILE1) ROUNDABOUT_ID
    READ(FILE1) ROUNDABOUT_APPROACH_NUM
    READ(FILE1) ROUNDABOUT_EXIT_NUM
    READ(FILE1) AC_SIGNAL_ID
    READ(FILE1) NEAR_CROSSLINK
    READ(FILE1) NEAR_UPPER_CROSSLINK
    READ(FILE1) FAR_CROSSLINK
    READ(FILE1) UP_INT_WIDTH
    READ(FILE1) LANE_CENTER
    READ(FILE1) LT_ARC_LENGTH
    READ(FILE1) THRU_ARC_LENGTH
    READ(FILE1) RT_ARC_LENGTH
    READ(FILE1) LD_ARC_LENGTH
    READ(FILE1) LT_LIMITED_SPEED_DIST
    READ(FILE1) RT_LIMITED_SPEED_DIST
    READ(FILE1) RD_ARC_LENGTH
    READ(FILE1) LT_LIMITED_SPEED_DIST
    READ(FILE1) RT_LIMITED_SPEED_DIST
    READ(FILE1) APPROACH_NUM
    READ(FILE1) STE_FREQ
    READ(FILE1) STE_DURATION
    READ(FILE1) RTOR
    READ(FILE1) LINKTYPE_CODE
    READ(FILE1) COND_LEFT
    READ(FILE1) COND_THRU
    READ(FILE1) COND_RIGHT
    READ(FILE1) COND_LDIAG
    READ(FILE1) COND_RDIAG
    READ(FILE1) COND_LEFTPCT
    READ(FILE1) COND_THRUPCT
    READ(FILE1) COND_RIGHTPCT
    READ(FILE1) COND_LDIAGPCT
    READ(FILE1) COND_RDIAGPCT
    READ(FILE1) CENTROID
    READ(FILE1) CENTROID_LABEL
    READ(FILE1) MULTIPLIER_LEFT
    READ(FILE1) MULTIPLIER_THRU
    READ(FILE1) MULTIPLIER_RIGHT
    READ(FILE1) MULTIPLIER_LDIAG
    READ(FILE1) MULTIPLIER_RDIAG
    READ(FILE1) SIGNAL_RANGE
    READ(FILE1) SIGNALIZED
    READ(FILE1) WRITE12
    READ(FILE1) WRITE13
    READ(FILE1) WRITE21
    READ(FILE1) WRITE51
    READ(FILE1) WRITE82
    READ(FILE1) WRITE83
    READ(FILE1) LANE_NUMBERS
    READ(FILE1) FIRST_FULL_LANE
    READ(FILE1) LAST_FULL_LANE
    READ(FILE1) ALWAYS_GREEN
    READ(FILE1) CHECK_MERGE
    READ(FILE1) LT_SPEED
    READ(FILE1) RT_SPEED

! --- Restore dynamic data.

    READ(FILE2) SLAST_VEHICLE_OUT
    READ(FILE2) SLAST_VEHICLE_OUT_ID
    READ(FILE2) FIRST_VEHICLE
    READ(FILE2) SLAST_VEHICLE
    READ(FILE2) PREV_SIGNAL_CODE
    READ(FILE2) PREV_SIGNAL_LEFT
    READ(FILE2) SIGNAL_CODE
    READ(FILE2) SIGNAL_LEFT
    READ(FILE2) SIGNAL_THRU
    READ(FILE2) SIGNAL_RIGHT
    READ(FILE2) SIGNAL_DIAG
    READ(FILE2) PHASE_LEFT
    READ(FILE2) PHASE_THRU
    READ(FILE2) PHASE_RIGHT
    READ(FILE2) PHASE_DIAG
    READ(FILE2) AMBER_LEFT
    READ(FILE2) AMBER_THRU
    READ(FILE2) AMBER_RIGHT
    READ(FILE2) AMBER_DIAG
    READ(FILE2) BLOCKAGE
    READ(FILE2) SOURCE_SINK
    READ(FILE2) SENTERING
    READ(FILE2) SLANE_CHANGES
    READ(FILE2) SDISCHARGED
    READ(FILE2) SDISCHARGED_LANE
    READ(FILE2) DISCHARGED_LEFT
    READ(FILE2) DISCHARGED_RIGHT
    READ(FILE2) DISCHARGED_DIAG
    READ(FILE2) SDISCHARGED_BUSES
    READ(FILE2) SZDIST_LANE
    READ(FILE2) SZDIST_TYPE
    READ(FILE2) SZTIME_TYPE
    READ(FILE2) SZDIST
    READ(FILE2) ZDIST_DIAG
    READ(FILE2) ZDIST_LEFT
    READ(FILE2) ZDIST_RIGHT
    READ(FILE2) SZDELAY_LANE
    READ(FILE2) SZOCCS
    READ(FILE2) SPERSON_TRIPS
    READ(FILE2) ZSTOP
    READ(FILE2) RED_LIGHT_RUNNERS
    READ(FILE2) VEHICLES_INDZ
    READ(FILE2) SZTIME
    READ(FILE2) ZTIME_DIAG
    READ(FILE2) ZTIME_LEFT
    READ(FILE2) ZTIME_RIGHT
    READ(FILE2) SZTIME_BUS
    READ(FILE2) SZTIME_LANE
    READ(FILE2) SEV_ONLINK
    READ(FILE2) SFIRST_ON_SHOULDER
    READ(FILE2) SCO_TOTAL
    READ(FILE2) SHC_TOTAL
    READ(FILE2) SNOX_TOTAL
    READ(FILE2) SFUEL_TOTAL
    READ(FILE2) SLANE_CLOSED
    READ(FILE2) LANE_GOES_LEFT
    READ(FILE2) LANE_GOES_RIGHT
    READ(FILE2) CYCLE_FAILURES
    READ(FILE2) QUEUE_TOTAL
    READ(FILE2) QUEUE_MAX
    READ(FILE2) RICDELAY
    READ(FILE2) RICDELD
    READ(FILE2) RICDELL
    READ(FILE2) RICDELR
    READ(FILE2) LAGGER_TIMER
    READ(FILE2) STOPPED_VEHICLES
    READ(FILE2) STOP_DELAY
    READ(FILE2) STOP_DELAY_DIAG
    READ(FILE2) STOP_DELAY_LEFT
    READ(FILE2) STOP_DELAY_RIGHT
    READ(FILE2) QUEUE_DELAY
    READ(FILE2) QUEUE_DELAY_DIAG
    READ(FILE2) QUEUE_DELAY_LEFT
    READ(FILE2) QUEUE_DELAY_RIGHT
    READ(FILE2) CENTROID_NV
    RETURN
    END SUBROUTINE
  END MODULE

