! Copyright © 2014
! New Global Systems for Intelligent Transportation Management Corp.
  
! This file is part of ETFOMM.
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU Affero General Public License as
! published by the Free Software Foundation, either version 3 of the
! License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU Affero General Public License for more details.
!
! You should have received a copy of the GNU Affero General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.

  SUBROUTINE WRITE_NETWORK_TEXT
  USE NODE_TABLE
  USE FREEWAY_LINKS
  USE STREET_LINKS
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER :: I, N = 1, ILEFT, ITHRU, IRIGHT, ILDIAG, IRDIAG, IOFF, J, K
  INCLUDE 'IOFILES.INC'
  CHARACTER*200 STRING
! ----------------------------------------------------------------------
  OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_NETWORK_NODES.TXT', ERR=10, IOMSG=ETEXT)
  DO I = 1, MAX_NODE_NUMBER + 1000
    IF(IS_USED(I)) THEN
      WRITE(N, 1, ERR=20, IOMSG=ETEXT) I, X195(I), Y195(I), NETCODE(I), 0, NODE_LAT(I), NODE_LON(I), NODE_ELEV(I)
    ENDIF
  ENDDO
  CLOSE(N)
  
  OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_NETWORK_LINKS.TXT', ERR=10, IOMSG=ETEXT)
  WRITE(N, 2, ERR=20, IOMSG=ETEXT) N_FREEWAY_LINKS, ' FREEWAY LINKS'
  DO I = 1, N_FREEWAY_LINKS
    IOFF = 0
    ITHRU = 0
    IF(NODE_TYPE(FDSN(I)) .NE. NT_EXTERN .AND. FTHRU_LINK(I) .NE. 0) ITHRU = FDSN(FTHRU_LINK(I))
    IF(OFFRAMP_LINK(I) .NE. 0) IOFF = FDSN(OFFRAMP_LINK(I))
    WRITE(N, 3, ERR=20, IOMSG=ETEXT) FUSN(I), FDSN(I), FLENGTH(I), FNUMLANES(I),         &
    ITHRU, IOFF, LINKTYPE(I),                                       &
    MAINLINE_RECEIVING_LANE(I), OFFRAMP_SENDING_LANE(I),             &
    MAINLINE_SENDING_LANE(I), OFFRAMP_RECEIVING_LANE(I),                   &
    AUX_LANE_ID(I, 1), AUX_LANE_CODE(I, 1), AUX_LANE_LENGTH(I, 1),  &
    AUX_LANE_ID(I, 2), AUX_LANE_CODE(I, 2), AUX_LANE_LENGTH(I, 2),  &
    AUX_LANE_ID(I, 3), AUX_LANE_CODE(I, 3), AUX_LANE_LENGTH(I, 3),  &
    AUX_LANE_ID(I, 4), AUX_LANE_CODE(I, 4), AUX_LANE_LENGTH(I, 4),  &
    AUX_LANE_ID(I, 5), AUX_LANE_CODE(I, 5), AUX_LANE_LENGTH(I, 5),  &
    AUX_LANE_ID(I, 6), AUX_LANE_CODE(I, 6), AUX_LANE_LENGTH(I, 6),  &
    ADDDROP_CODE(I, 1), ADDDROP_LANE(I, 1), ADDDROP_DIST(I, 1),     &
    ADDDROP_CODE(I, 2), ADDDROP_LANE(I, 2), ADDDROP_DIST(I, 2),     &
    ADDDROP_CODE(I, 3), ADDDROP_LANE(I, 3), ADDDROP_DIST(I, 3)
  ENDDO
  
  
  WRITE(N, 2, ERR=20, IOMSG=ETEXT) N_STREET_LINKS, ' STREET LINKS'
  DO I = 1, N_STREET_LINKS
    ILEFT = 0
    ITHRU = 0
    IRIGHT = 0
    ILDIAG = 0
    IRDIAG = 0
    IF(LEFT_LINK(I) .NE. 0) ILEFT = SDSN(LEFT_LINK(I))
    IF(STHRU_LINK(I) .NE. 0) ITHRU = SDSN(STHRU_LINK(I))
    IF(RIGHT_LINK(I) .NE. 0) IRIGHT = SDSN(RIGHT_LINK(I))
    IF(LEFT_DIAG_LINK(I) .NE. 0) ILDIAG = SDSN(LEFT_DIAG_LINK(I))
    IF(RIGHT_DIAG_LINK(I) .NE. 0) IRDIAG = SDSN(RIGHT_DIAG_LINK(I))

    STRING = ''
    WRITE(STRING(1:64), 4, ERR=20, IOMSG=ETEXT) SUSN(I), SDSN(I), SNUMLANES(I), &
    SALIGNMENT_LANE(I), STHRU_ALIGNMENT_LANE(I),                          &
    NUMBER_LEFTPOCKETS(I), NUMBER_RIGHTPOCKETS(I),                        &
    ILEFT, ITHRU, IRIGHT, ILDIAG, IRDIAG, TOTAL_LANES(I)
    K = 56
    DO J = 1, TOTAL_LANES(I) 
      K = K + 9
      WRITE(STRING(K:K+8), '(A,F8.1)') ',', LANE_LENGTH(I, J)
    ENDDO
    WRITE(N, '(A)', ERR=20, IOMSG=ETEXT) STRING(1:K+9)
  ENDDO
  
1 FORMAT(I4,',',I8,',',I8,',',I2,',',I2,',',F12.7,',',F12.7,',',I8)  
2 FORMAT(I4, A)
3 FORMAT(35(I4,','),I4)  
4 FORMAT(12(I4,','),I4)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_NETWORK_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_NETWORK_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END
  
  SUBROUTINE WRITE_LINK_TEXT(THELINKDATA)
  USE SIMPARAMS
  USE ANIMATION_DATA
  USE TEXT
  IMPLICIT NONE
  TYPE(LINKDATA) :: THELINKDATA
  INTEGER :: N = 2, W(12), T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_LINK_DATA.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 2
  IF(THELINKDATA%USN .GT. 999) THEN
    W(2) = 4
  ELSEIF(THELINKDATA%USN .GT. 99) THEN
    W(2) = 3
  ELSEIF(THELINKDATA%USN .GT. 9) THEN
    W(2) = 2
  ENDIF
  IF(THELINKDATA%DSN .GT. 999) THEN
    W(3) = 4
  ELSEIF(THELINKDATA%DSN .GT. 99) THEN
    W(3) = 3
  ELSEIF(THELINKDATA%DSN .GT. 9) THEN
    W(3) = 2
  ENDIF
  IF(THELINKDATA%NUMVEHICLES .GT. 999) THEN
    W(4) = 4
  ELSEIF(THELINKDATA%NUMVEHICLES .GT. 99) THEN
    W(4) = 3
  ELSEIF(THELINKDATA%NUMVEHICLES .GT. 9) THEN
    W(4) = 2
  ENDIF
  IF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, THELINKDATA
1 FORMAT(F<T+D+1>.<D>,',',I<W(1)>,',',I<W(2)>,',',I<W(3)>,',',I<W(4)>,',',I<W(5)>,',',I<W(6)>,',',I<W(7)>,',',I<W(8)>,',',I<W(9)>,',', &
  I<W(10)>,',',I<W(11)>,',',I<W(12)>, I1)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_LINK_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_LINK_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END

  
  SUBROUTINE WRITE_RAMPMETER_TEXT(THELINKDATA)
  USE ANIMATION_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  TYPE(LINKDATA) :: THELINKDATA
  INTEGER :: N = 3, W(12), T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_RAMPMETER_DATA.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(THELINKDATA%USN .GT. 999) THEN
    W(2) = 4
  ELSEIF(THELINKDATA%USN .GT. 99) THEN
    W(2) = 3
  ELSEIF(THELINKDATA%USN .GT. 9) THEN
    W(2) = 2
  ENDIF
  IF(THELINKDATA%DSN .GT. 999) THEN
    W(3) = 4
  ELSEIF(THELINKDATA%DSN .GT. 99) THEN
    W(3) = 3
  ELSEIF(THELINKDATA%DSN .GT. 9) THEN
    W(3) = 2
  ENDIF
  IF(THELINKDATA%NUMVEHICLES .GT. 999) THEN
    W(4) = 4
  ELSEIF(THELINKDATA%NUMVEHICLES .GT. 99) THEN
    W(4) = 3
  ELSEIF(THELINKDATA%NUMVEHICLES .GT. 9) THEN
    W(4) = 2
  ENDIF
  IF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, THELINKDATA
1 FORMAT(F<T+D+1>.<D>,',',I<W(1)>,',',I<W(2)>,',',I<W(3)>,',',I<W(4)>,',',I<W(5)>,',',I<W(6)>,',',I<W(7)>,',',I<W(8)>,',',I<W(9)>,',', &
  I<W(10)>,',',I<W(11)>,',',I<W(12)>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_RAMPMETER_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_RAMPMETER_TEX'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END
  
  SUBROUTINE WRITE_VEHICLE_LIST(THIS_VEHICLE, NODE, VLEN)
  USE VEHICLE_MOD
  USE VEHICLE_TYPES
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  TYPE(VEHICLE), INTENT(IN) :: THIS_VEHICLE
  INTEGER, INTENT(IN) :: NODE, VLEN
  INTEGER :: N = 4, W(6)
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_LIST.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(THIS_VEHICLE%GLOBALID .GT. 999999999) THEN
    W(1) = 10
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 99999999) THEN
    W(1) = 9
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 9999999) THEN
    W(1) = 8
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 999999) THEN
    W(1) = 7
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 99999) THEN
    W(1) = 6
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 9999) THEN
    W(1) = 5
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 999) THEN
    W(1) = 4
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 99) THEN
    W(1) = 3
  ELSEIF(THIS_VEHICLE%GLOBALID .GT. 9) THEN
    W(1) = 2
  ENDIF
  IF(NODE .GT. 999) THEN
    W(2) = 4
  ELSEIF(NODE .GT. 99) THEN
    W(2) = 3
  ELSEIF(NODE .GT. 9) THEN
    W(2) = 2
  ENDIF
  IF(THIS_VEHICLE%VTYPE .GT. 9) THEN
    W(4) = 2
  ENDIF
  W(5) = 2
  IF(THIS_VEHICLE%DRIVER .GT. 9) THEN
    W(6) = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) THIS_VEHICLE%GLOBALID, NODE, THIS_VEHICLE%FLEET, THIS_VEHICLE%VTYPE, VLEN, THIS_VEHICLE%DRIVER
1 FORMAT(I<W(1)>,',',I<W(2)>,',',I<W(3)>,',',I<W(4)>,',',I<W(5)>,',',I<W(6)>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_LIST'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_LIST'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END
  
  SUBROUTINE WRITE_VEHICLE_TEXT(USN, DSN, THEVEHDATA)
  USE ANIMATION_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  TYPE(VEHICLEDATA) :: THEVEHDATA
  INTEGER*2, INTENT(IN) :: USN, DSN
  INTEGER :: N = 5, W(14), T, D, US, DS
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_DATA.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(THEVEHDATA%VEHICLEGLOBALID .GT. 999999999) THEN
    W(1) = 10
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 99999999) THEN
    W(1) = 9
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 9999999) THEN
    W(1) = 8
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 999999) THEN
    W(1) = 7
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 99999) THEN
    W(1) = 6
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 9999) THEN
    W(1) = 5
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 999) THEN
    W(1) = 4
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 99) THEN
    W(1) = 3
  ELSEIF(THEVEHDATA%VEHICLEGLOBALID .GT. 9) THEN
    W(1) = 2
  ENDIF
  IF(THEVEHDATA%LANENUMBER .GT. 9) THEN
    W(2) = 2
  ENDIF
  IF(THEVEHDATA%DISTANCEFROMUSN .GT. 99999) THEN
    W(3) = 6
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .GT. 9999) THEN
    W(3) = 5
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .GT. 999) THEN
    W(3) = 4
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .GT. 99) THEN
    W(3) = 3
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .GT. 9) THEN
    W(3) = 2
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .GT. 0) THEN
    W(3) = 1
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .LT. -999) THEN
    W(3) = 5
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .LT. -99) THEN
    W(3) = 4
  ELSEIF(THEVEHDATA%DISTANCEFROMUSN .LT. -9) THEN
    W(3) = 3
  ELSE
    W(3) = 2
  ENDIF
  IF(THEVEHDATA%USNPREVLINK .GT. 999) THEN
    W(4) = 4
  ELSEIF(THEVEHDATA%USNPREVLINK .GT. 99) THEN
    W(4) = 3
  ELSEIF(THEVEHDATA%USNPREVLINK .GT. 9) THEN
    W(4) = 2
  ENDIF
  IF(THEVEHDATA%ACCELERATION .GT. 999) THEN
    W(7) = 4
  ELSEIF(THEVEHDATA%ACCELERATION .GT. 99) THEN
    W(7) = 3
  ELSEIF(THEVEHDATA%ACCELERATION .GT. 9) THEN
    W(7) = 2
  ELSEIF(THEVEHDATA%ACCELERATION .LT. -99) THEN
    W(7) = 4
  ELSEIF(THEVEHDATA%ACCELERATION .LT. -9) THEN
    W(7) = 3
  ELSEIF(THEVEHDATA%ACCELERATION .LT. 0) THEN
    W(7) = 2
  ENDIF
  IF(THEVEHDATA%VELOCITY .GT. 99) THEN
    W(8) = 3
  ELSEIF(THEVEHDATA%VELOCITY  .GT. 9) THEN
    W(8) = 2
  ENDIF
  IF(THEVEHDATA%TARGETLANE .GT. 9) THEN
    W(10) = 2
  ENDIF
  IF(THEVEHDATA%DESTINATION .GT. 999) THEN
    W(11) = 4
  ELSEIF(THEVEHDATA%DESTINATION .GT. 99) THEN
    W(11) = 3
  ELSEIF(THEVEHDATA%DESTINATION .GT. 9) THEN
    W(11) = 2
  ENDIF
  IF(THEVEHDATA%LEADVEHICLEID .GT. 999999999) THEN
    W(12) = 10
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 99999999) THEN
    W(12) = 9
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 9999999) THEN
    W(12) = 8
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 999999) THEN
    W(12) = 7
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 99999) THEN
    W(12) = 6
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 9999) THEN
    W(12) = 5
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 999) THEN
    W(12) = 4
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 99) THEN
    W(12) = 3
  ELSEIF(THEVEHDATA%LEADVEHICLEID .GT. 9) THEN
    W(12) = 2
  ENDIF
  IF(THEVEHDATA%FOLLOWVEHICLEID .GT. 999999999) THEN
    W(13) = 10
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 99999999) THEN
    W(13) = 9
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 9999999) THEN
    W(13) = 8
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 999999) THEN
    W(13) = 7
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 99999) THEN
    W(13) = 6
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 9999) THEN
    W(13) = 5
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 999) THEN
    W(13) = 4
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 99) THEN
    W(13) = 3
  ELSEIF(THEVEHDATA%FOLLOWVEHICLEID .GT. 9) THEN
    W(13) = 2
  ENDIF
  IF(THEVEHDATA%PREVLANE .GT. 9) THEN
    W(14) = 2
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  IF(USN .GT. 999) THEN
    US = 4
  ELSEIF(USN .GT. 99) THEN
    US = 3
  ELSEIF(USN .GT. 9) THEN
    US = 2
  ELSE
    US = 1
  ENDIF
  IF(DSN .GT. 999) THEN
    DS = 4
  ELSEIF(DSN .GT. 99) THEN
    DS = 3
  ELSEIF(DSN .GT. 9) THEN
    DS = 2
  ELSE
    DS = 1
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, USN, DSN, THEVEHDATA%VEHICLEGLOBALID, THEVEHDATA%LANENUMBER, THEVEHDATA%DISTANCEFROMUSN, THEVEHDATA%USNPREVLINK, &
  THEVEHDATA%TURNCODE, THEVEHDATA%QUEUECODE, THEVEHDATA%ACCELERATION, THEVEHDATA%VELOCITY, THEVEHDATA%LANECHANGESTATUS, &
  THEVEHDATA%TARGETLANE, THEVEHDATA%DESTINATION, THEVEHDATA%LEADVEHICLEID, THEVEHDATA%FOLLOWVEHICLEID, THEVEHDATA%PREVLANE
1 FORMAT(F<T+D+1>.<D>,',',I<US>',',I<DS>',',I<W(1)>,',',I<W(2)>,',' ,I<W(3)>,',',I<W(4)>,',', I<W(5)>,',',I<W(6)>,',',I<W(7)>,',', &
  I<W(8)>,',',I<W(9)>,',',I<W(10)>,',',I<W(11)>,',',I<W(12)>,',',I<W(13)>',',I<W(14)>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(I8)') THEVEHDATA%DISTANCEFROMUSN
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
  END  
  
  SUBROUTINE WRITE_VEHICLE_TEXT_ARC(IV)
  USE STREET_VEHICLES
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: IV
  INTEGER :: IL, N = 6, W(4), T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
#ifdef DebugVersion
  integer :: temp
  temp = sid(iv)
#endif
  IL = SLINK(IV)
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_DATA_ARC.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(SID(IV) .GT. 999999999) THEN
    W(1) = 10
  ELSEIF(SID(IV) .GT. 99999999) THEN
    W(1) = 9
  ELSEIF(SID(IV) .GT. 9999999) THEN
    W(1) = 8
  ELSEIF(SID(IV) .GT. 999999) THEN
    W(1) = 7
  ELSEIF(SID(IV) .GT. 99999) THEN
    W(1) = 6
  ELSEIF(SID(IV) .GT. 9999) THEN
    W(1) = 5
  ELSEIF(SID(IV) .GT. 999) THEN
    W(1) = 4
  ELSEIF(SID(IV) .GT. 99) THEN
    W(1) = 3
  ELSEIF(SID(IV) .GT. 9) THEN
    W(1) = 2
  ENDIF
  IF(ARC_LOCATION(IV) .GT. 9999) THEN
    W(2) = 5
  ELSEIF(ARC_LOCATION(IV) .GT. 999) THEN
    W(2) = 4
  ELSEIF(ARC_LOCATION(IV) .GT. 99) THEN
    W(2) = 3
  ELSEIF(ARC_LOCATION(IV) .GT. 9) THEN
    W(2) = 2
  ELSEIF(ARC_LOCATION(IV) .GT. 0) THEN
    W(2) = 1
  ELSEIF(ARC_LOCATION(IV) .LT. -999) THEN
    W(2) = 5
  ELSEIF(ARC_LOCATION(IV) .LT. -99) THEN
    W(2) = 4
  ELSEIF(ARC_LOCATION(IV) .LT. -9) THEN
    W(2) = 3
  ELSE
    W(2) = 2
  ENDIF
  IF(ARC_ENTRYLINK(IV) .GT. 999) THEN
    W(3) = 4
  ELSEIF(ARC_ENTRYLINK(IV) .GT. 99) THEN
    W(3) = 3
  ELSEIF(ARC_ENTRYLINK(IV) .GT. 9) THEN
    W(3) = 2
  ELSEIF(ARC_ENTRYLINK(IV) .GT. 0) THEN
    W(3) = 1
  ELSEIF(ARC_ENTRYLINK(IV) .LT. -999) THEN
    W(3) = 5
  ELSEIF(ARC_ENTRYLINK(IV) .LT. -99) THEN
    W(3) = 4
  ELSEIF(ARC_ENTRYLINK(IV) .LT. -9) THEN
    W(3) = 3
  ELSE
    W(3) = 2
  ENDIF
  IF(IL .GT. 999) THEN
    W(4) = 4
  ELSEIF(IL .GT. 99) THEN
    W(4) = 3
  ELSEIF(IL .GT. 9) THEN
    W(4) = 2
  ELSEIF(IL .GT. 0) THEN
    W(4) = 1
  ELSEIF(IL .LT. -999) THEN
    W(4) = 5
  ELSEIF(IL .LT. -99) THEN
    W(4) = 4
  ELSEIF(IL .LT. -9) THEN
    W(4) = 3
  ELSE
    W(4) = 2
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
    
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, SID(IV), ARC_LOCATION(IV), ARC_ENTRYLINK(IV), ARC_ENTRYLANE(IV), IL, SLANE(IV)
1 FORMAT(F<T+D+1>.<D>,','I<W(1)>,',',F<3+W(2)>.2, ',', I<W(3)>,','I1,','I<W(4)>,','I2)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_TEXT_ARC'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_TEXT_ARC'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(I4, F10.2)') SID(IV), ARC_LOCATION(IV)
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
  END
  
  SUBROUTINE WRITE_VEHICLE_TEXT_RTW(IV)
  USE STREET_VEHICLES
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: IV
  INTEGER :: IL, N = 7, W(3), T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
#ifdef DebugVersion
  integer :: temp
  temp = sid(iv)
#endif
  IL = SLINK(IV)
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_DATA_RTW.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(SID(IV) .GT. 999999999) THEN
    W(1) = 10
  ELSEIF(SID(IV) .GT. 99999999) THEN
    W(1) = 9
  ELSEIF(SID(IV) .GT. 9999999) THEN
    W(1) = 8
  ELSEIF(SID(IV) .GT. 999999) THEN
    W(1) = 7
  ELSEIF(SID(IV) .GT. 99999) THEN
    W(1) = 6
  ELSEIF(SID(IV) .GT. 9999) THEN
    W(1) = 5
  ELSEIF(SID(IV) .GT. 999) THEN
    W(1) = 4
  ELSEIF(SID(IV) .GT. 99) THEN
    W(1) = 3
  ELSEIF(SID(IV) .GT. 9) THEN
    W(1) = 2
  ENDIF
  IF(ARC_LOCATION(IV) .GT. 9999) THEN
    W(2) = 5
  ELSEIF(ARC_LOCATION(IV) .GT. 999) THEN
    W(2) = 4
  ELSEIF(ARC_LOCATION(IV) .GT. 99) THEN
    W(2) = 3
  ELSEIF(ARC_LOCATION(IV) .GT. 9) THEN
    W(2) = 2
  ELSEIF(ARC_LOCATION(IV) .GT. 0) THEN
    W(2) = 1
  ELSEIF(ARC_LOCATION(IV) .LT. -999) THEN
    W(2) = 5
  ELSEIF(ARC_LOCATION(IV) .LT. -99) THEN
    W(2) = 4
  ELSEIF(ARC_LOCATION(IV) .LT. -9) THEN
    W(2) = 3
  ELSE
    W(2) = 2
  ENDIF
  IF(IL .GT. 9999) THEN
    W(3) = 5
  ELSEIF(IL .GT. 999) THEN
    W(3) = 4
  ELSEIF(IL .GT. 99) THEN
    W(3) = 3
  ELSEIF(IL .GT. 9) THEN
    W(3) = 2
  ELSE
    W(3) = 1
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
    
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, SID(IV), ARC_LOCATION(IV), IL
1 FORMAT(F<T+D+1>.<D>,','I<W(1)>,',',F<3+W(2)>.2, ',', I<W(3)>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_TEXT_RTW'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_TEXT_RTW'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(I4, F10.2)') SID(IV), ARC_LOCATION(IV)
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
  END
  
  SUBROUTINE WRITE_VEHICLE_TEXT_STOPPED(IV)
  USE STREET_VEHICLES
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: IV
  INTEGER :: IL, N = 9, W(3), T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IL = SLINK(IV)
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_DATA_STOPPED.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(IV .GT. 999999999) THEN
    W(1) = 10
  ELSEIF(IV .GT. 99999999) THEN
    W(1) = 9
  ELSEIF(IV .GT. 9999999) THEN
    W(1) = 8
  ELSEIF(IV .GT. 999999) THEN
    W(1) = 7
  ELSEIF(IV .GT. 99999) THEN
    W(1) = 6
  ELSEIF(IV .GT. 9999) THEN
    W(1) = 5
  ELSEIF(IV .GT. 999) THEN
    W(1) = 4
  ELSEIF(IV .GT. 99) THEN
    W(1) = 3
  ELSEIF(IV .GT. 9) THEN
    W(1) = 2
  ENDIF

  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
    
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, IV
1 FORMAT(F<T+D+1>.<D>,','I<W(1)>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_TEXT_STOPPED'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_TEXT_STOPPED'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(I4, F10.2)') SID(IV), ARC_LOCATION(IV)
  CALL SENDTEXTMSG(M_ERROR)
  EXITFLG = 1
  RETURN
  END

  SUBROUTINE WRITE_INCIDENT_TEXT(THELKINCDATA)
  USE ANIMATION_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  TYPE(LKINCDATA) :: THELKINCDATA
  INTEGER :: N = 8, T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_INCIDENT_DATA.TXT', ERR=10, IOMSG=ETEXT)
  ENDIF
  IF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) SIMTIME, THELKINCDATA
1 FORMAT(F<T+D+1>.<D>,',',I8,',',I8,',',I2,',',F10.1,',',F10.1,',',I8,',',I8,',',F10.1,',',F10.1,',',I4,',',I4,',',I4,',',11(I4,','),10(I4','),I4)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_INCIDENT_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_INCIDENT_TEXT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END

  SUBROUTINE WRITE_VEHICLE_ENTRY_TEXT(ID, USN)
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER*2, INTENT(IN) :: ID, USN
  INTEGER :: N = 9, W, T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_ENTRY.TXT', ERR=10, IOMSG=ETEXT)
  ELSE
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_ENTRY.TXT', ACCESS='APPEND', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(ID .GT. 999999999) THEN
    W = 10
  ELSEIF(ID .GT. 99999999) THEN
    W = 9
  ELSEIF(ID .GT. 9999999) THEN
    W = 8
  ELSEIF(ID .GT. 999999) THEN
    W = 7
  ELSEIF(ID .GT. 99999) THEN
    W = 6
  ELSEIF(ID .GT. 9999) THEN
    W = 5
  ELSEIF(ID .GT. 999) THEN
    W = 4
  ELSEIF(ID .GT. 99) THEN
    W = 3
  ELSEIF(ID .GT. 9) THEN
    W = 2
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) ID, SIMTIME, USN
  CLOSE(N)
1 FORMAT(I<W>,',',F<T+D+1>.<D>,',',I4)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_ENTRY'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_ENTRY'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END

  SUBROUTINE WRITE_VEHICLE_EXIT_TEXT(ID, DSN)
  USE ANIMATION_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER*2, INTENT(IN) :: ID, DSN
  INTEGER :: N = 10, W, T, D
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_EXIT.TXT', ERR=10, IOMSG=ETEXT)
  ELSE
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_VEHICLE_EXIT.TXT', ACCESS='APPEND', ERR=10, IOMSG=ETEXT)
  ENDIF
  W = 1
  IF(ID .GT. 999999999) THEN
    W = 10
  ELSEIF(ID .GT. 99999999) THEN
    W = 9
  ELSEIF(ID .GT. 9999999) THEN
    W = 8
  ELSEIF(ID .GT. 999999) THEN
    W = 7
  ELSEIF(ID .GT. 99999) THEN
    W = 6
  ELSEIF(ID .GT. 9999) THEN
    W = 5
  ELSEIF(ID .GT. 999) THEN
    W = 4
  ELSEIF(ID .GT. 99) THEN
    W = 3
  ELSEIF(ID .GT. 9) THEN
    W = 2
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) ID, SIMTIME, DSN
  CLOSE(N)
1 FORMAT(I<W>,',',F<T+D+1>.<D>,',',I4)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_VEHICLE_EXIT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_VEHICLE_EXIT'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END

  SUBROUTINE WRITE_DETECTOR_TEXT(IDET, ID)
  USE ANIMATION_DATA
  USE SIMPARAMS
  USE TEXT
  IMPLICIT NONE
  INTEGER*2, INTENT(IN) :: IDET, ID
  INTEGER :: N = 11, W, T, D, DT
  LOGICAL :: FIRST = .TRUE.
  INCLUDE 'IOFILES.INC'
! ----------------------------------------------------------------------
  IF(FIRST) THEN
    FIRST = .FALSE.
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_DETECTOR.TXT', ERR=10, IOMSG=ETEXT)
  ELSE
    OPEN(N, FILE = LINFNAME(1:IROOT-1)//'_DETECTOR.TXT', ACCESS='APPEND', ERR=10, IOMSG=ETEXT)
  ENDIF
  IF(IDET .GT. 999) THEN
    DT = 4
  ELSEIF(IDET .GT. 99) THEN
    DT = 3
  ELSEIF(IDET .GT. 9) THEN
    DT = 2
  ELSE
    DT = 1
  ENDIF
  IF(ID .GT. 999999999) THEN
    W = 10
  ELSEIF(ID .GT. 99999999) THEN
    W = 9
  ELSEIF(ID .GT. 9999999) THEN
    W = 8
  ELSEIF(ID .GT. 999999) THEN
    W = 7
  ELSEIF(ID .GT. 99999) THEN
    W = 6
  ELSEIF(ID .GT. 9999) THEN
    W = 5
  ELSEIF(ID .GT. 999) THEN
    W = 4
  ELSEIF(ID .GT. 99) THEN
    W = 3
  ELSEIF(ID .GT. 9) THEN
    W = 2
  ELSE
    W = 1
  ENDIF
  IF(SIMTIME .GT. 99999) THEN
    T = 6
  ELSEIF(SIMTIME .GT. 9999) THEN
    T = 5
  ELSEIF(SIMTIME .GT. 999) THEN
    T = 4
  ELSEIF(SIMTIME .GT. 99) THEN
    T = 3
  ELSEIF(SIMTIME .GT. 9) THEN
    T = 2
  ELSE
    T = 1
  ENDIF
  IF(TIMESTEP .EQ. 1.0) THEN
    D = 0
  ELSEIF(TIMESTEP .EQ. 0.1) THEN
    D = 1
  ELSE
    D = 2
  ENDIF
  WRITE(N, 1, ERR=20, IOMSG=ETEXT) IDET, SIMTIME, ID
  CLOSE(N)
1 FORMAT(I<DT>,',',F<T+D+1>.<D>,',',I<W>)
  RETURN
10 WRITE(MSGTEXT, '(A)') 'FILE OPEN ERROR : WRITE_DETECTOR'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
20 WRITE(MSGTEXT, '(A)') 'FILE WRITE ERROR : WRITE_DETECTOR'
  CALL SENDTEXTMSG(M_ERROR)
  WRITE(MSGTEXT, '(A)') ETEXT
  CALL SENDTEXTMSG(M_ERROR)
  RETURN
  END

